# frozen_string_literal: true

module Cadenya
  module Models
    class ContextWindowCompacted < Cadenya::Internal::Type::BaseModel
      # @!attribute messages_compacted
      #   Number of messages that were compacted
      #
      #   @return [Integer]
      required :messages_compacted, Integer, api_name: :messagesCompacted

      # @!attribute new_context_window
      #   The new context window created by this compaction
      #
      #   @return [Cadenya::Models::ObjectiveContextWindowData]
      required :new_context_window, -> { Cadenya::ObjectiveContextWindowData }, api_name: :newContextWindow

      # @!attribute strategies
      #   The strategies that were applied during this compaction
      #
      #   @return [Array<String>]
      required :strategies, Cadenya::Internal::Type::ArrayOf[String]

      # @!attribute summary
      #   The summary generated by the summarization strategy, if used.
      #
      #   @return [String, nil]
      optional :summary, String

      # @!method initialize(messages_compacted:, new_context_window:, strategies:, summary: nil)
      #   @param messages_compacted [Integer] Number of messages that were compacted
      #
      #   @param new_context_window [Cadenya::Models::ObjectiveContextWindowData] The new context window created by this compaction
      #
      #   @param strategies [Array<String>] The strategies that were applied during this compaction
      #
      #   @param summary [String] The summary generated by the summarization strategy, if used.
    end
  end
end
