module Cadenya
  module Resources
    class Agents
      class Feedback
        def list: (
          String agent_id,
          workspace_id: String,
          ?agent_variation_id: String,
          ?created_after: Time,
          ?created_before: Time,
          ?cursor: String,
          ?include_info: bool,
          ?labels: String,
          ?limit: Integer,
          ?query: String,
          ?sentiment: Cadenya::Models::Agents::FeedbackListParams::sentiment,
          ?request_options: Cadenya::request_opts
        ) -> Cadenya::Internal::CursorPagination[Cadenya::Objectives::ObjectiveFeedback]

        def initialize: (client: Cadenya::Client) -> void
      end
    end
  end
end
