module Cadenya
  module Resources
    class Agents
      class Schedules
        def create: (
          String agent_id,
          metadata: Cadenya::CreateResourceMetadata,
          spec: Cadenya::Agents::AgentScheduleSpec,
          ?workspace_id: String,
          ?request_options: Cadenya::request_opts
        ) -> Cadenya::Agents::AgentSchedule

        def retrieve: (
          String agent_id,
          String id,
          ?workspace_id: String,
          ?request_options: Cadenya::request_opts
        ) -> Cadenya::Agents::AgentSchedule

        def update: (
          String agent_id,
          String id,
          ?workspace_id: String,
          ?metadata: Cadenya::UpdateResourceMetadata,
          ?spec: Cadenya::Agents::AgentScheduleSpec,
          ?update_mask: String,
          ?request_options: Cadenya::request_opts
        ) -> Cadenya::Agents::AgentSchedule

        def list: (
          String agent_id,
          ?workspace_id: String,
          ?cursor: String,
          ?include_info: bool,
          ?labels: String,
          ?limit: Integer,
          ?prefix: String,
          ?query: String,
          ?sort_order: String,
          ?request_options: Cadenya::request_opts
        ) -> Cadenya::Internal::CursorPagination[Cadenya::Agents::AgentSchedule]

        def delete: (
          String agent_id,
          String id,
          ?workspace_id: String,
          ?request_options: Cadenya::request_opts
        ) -> nil

        def archive: (
          String agent_id,
          String id,
          ?workspace_id: String,
          ?request_options: Cadenya::request_opts
        ) -> Cadenya::Agents::AgentSchedule

        def pause: (
          String agent_id,
          String id,
          ?workspace_id: String,
          ?request_options: Cadenya::request_opts
        ) -> Cadenya::Agents::AgentSchedule

        def resume: (
          String agent_id,
          String id,
          ?workspace_id: String,
          ?request_options: Cadenya::request_opts
        ) -> Cadenya::Agents::AgentSchedule

        def initialize: (client: Cadenya::Client) -> void
      end
    end
  end
end
