module Cadenya
  module Resources
    class Agents
      class Variations
        def create: (
          String agent_id,
          metadata: Cadenya::CreateResourceMetadata,
          spec: Cadenya::Agents::AgentVariationSpec,
          ?workspace_id: String,
          ?request_options: Cadenya::request_opts
        ) -> Cadenya::Agents::AgentVariation

        def retrieve: (
          String agent_id,
          String id,
          ?workspace_id: String,
          ?request_options: Cadenya::request_opts
        ) -> Cadenya::Agents::AgentVariation

        def update: (
          String agent_id,
          String id,
          ?workspace_id: String,
          ?metadata: Cadenya::UpdateResourceMetadata,
          ?spec: Cadenya::Agents::AgentVariationSpec,
          ?update_mask: String,
          ?request_options: Cadenya::request_opts
        ) -> Cadenya::Agents::AgentVariation

        def list: (
          String agent_id,
          ?workspace_id: String,
          ?cursor: String,
          ?include_info: bool,
          ?labels: String,
          ?limit: Integer,
          ?sort_order: String,
          ?request_options: Cadenya::request_opts
        ) -> Cadenya::Internal::CursorPagination[Cadenya::Agents::AgentVariation]

        def delete: (
          String agent_id,
          String id,
          ?workspace_id: String,
          ?request_options: Cadenya::request_opts
        ) -> nil

        def add_assignment: (
          String agent_id,
          String variation_id,
          ?workspace_id: String,
          ?sub_agent_id: String,
          ?tool_id: String,
          ?tool_set_id: String,
          ?type: String,
          ?request_options: Cadenya::request_opts
        ) -> Cadenya::Agents::VariationAssignment

        def add_memory_layer: (
          String agent_id,
          String variation_id,
          memory_layer_id: String,
          ?workspace_id: String,
          ?position: Integer,
          ?request_options: Cadenya::request_opts
        ) -> Cadenya::Agents::VariationMemoryLayerAssignment

        def remove_assignment: (
          String agent_id,
          String variation_id,
          String id,
          ?workspace_id: String,
          ?request_options: Cadenya::request_opts
        ) -> nil

        def remove_memory_layer: (
          String agent_id,
          String variation_id,
          String id,
          ?workspace_id: String,
          ?request_options: Cadenya::request_opts
        ) -> nil

        def update_memory_layer: (
          String agent_id,
          String variation_id,
          String id,
          ?workspace_id: String,
          ?position: Integer,
          ?request_options: Cadenya::request_opts
        ) -> Cadenya::Agents::VariationMemoryLayerAssignment

        def initialize: (client: Cadenya::Client) -> void
      end
    end
  end
end
