# typed: strong

module Cadenya
  module Models
    class ContextWindowCompacted < Cadenya::Internal::Type::BaseModel
      OrHash =
        T.type_alias do
          T.any(Cadenya::ContextWindowCompacted, Cadenya::Internal::AnyHash)
        end

      # Number of messages that were compacted
      sig { returns(T.nilable(Integer)) }
      attr_reader :messages_compacted

      sig { params(messages_compacted: Integer).void }
      attr_writer :messages_compacted

      # The new context window created by this compaction
      sig { returns(T.nilable(Cadenya::ObjectiveContextWindowData)) }
      attr_reader :new_context_window

      sig do
        params(
          new_context_window: Cadenya::ObjectiveContextWindowData::OrHash
        ).void
      end
      attr_writer :new_context_window

      # The strategies that were applied during this compaction
      sig { returns(T.nilable(T::Array[String])) }
      attr_reader :strategies

      sig { params(strategies: T::Array[String]).void }
      attr_writer :strategies

      # The summary generated by the summarization strategy, if used.
      sig { returns(T.nilable(String)) }
      attr_reader :summary

      sig { params(summary: String).void }
      attr_writer :summary

      sig do
        params(
          messages_compacted: Integer,
          new_context_window: Cadenya::ObjectiveContextWindowData::OrHash,
          strategies: T::Array[String],
          summary: String
        ).returns(T.attached_class)
      end
      def self.new(
        # Number of messages that were compacted
        messages_compacted: nil,
        # The new context window created by this compaction
        new_context_window: nil,
        # The strategies that were applied during this compaction
        strategies: nil,
        # The summary generated by the summarization strategy, if used.
        summary: nil
      )
      end

      sig do
        override.returns(
          {
            messages_compacted: Integer,
            new_context_window: Cadenya::ObjectiveContextWindowData,
            strategies: T::Array[String],
            summary: String
          }
        )
      end
      def to_hash
      end
    end
  end
end
