module Cadenya
  module Models
    module Objectives
      type feedback_list_params =
        {
          workspace_id: String,
          objective_id: String,
          cursor: String,
          labels: String,
          limit: Integer
        }
        & Cadenya::Internal::Type::request_parameters

      class FeedbackListParams < Cadenya::Internal::Type::BaseModel
        extend Cadenya::Internal::Type::RequestParameters::Converter
        include Cadenya::Internal::Type::RequestParameters

        attr_accessor workspace_id: String

        attr_accessor objective_id: String

        attr_reader cursor: String?

        def cursor=: (String) -> String

        attr_reader labels: String?

        def labels=: (String) -> String

        attr_reader limit: Integer?

        def limit=: (Integer) -> Integer

        def initialize: (
          workspace_id: String,
          objective_id: String,
          ?cursor: String,
          ?labels: String,
          ?limit: Integer,
          ?request_options: Cadenya::request_opts
        ) -> void

        def to_hash: -> {
          workspace_id: String,
          objective_id: String,
          cursor: String,
          labels: String,
          limit: Integer,
          request_options: Cadenya::RequestOptions
        }
      end
    end
  end
end
