module Cadenya
  module Models
    class ObjectiveToolCallInfo = Objectives::ObjectiveToolCallInfo

    module Objectives
      type objective_tool_call_info =
        {
          created_by: Cadenya::Profile,
          objective: Cadenya::OperationMetadata,
          tool: Cadenya::BareMetadata,
          tool_set: Cadenya::BareMetadata
        }

      class ObjectiveToolCallInfo < Cadenya::Internal::Type::BaseModel
        attr_reader created_by: Cadenya::Profile?

        def created_by=: (Cadenya::Profile) -> Cadenya::Profile

        attr_accessor objective: Cadenya::OperationMetadata

        attr_reader tool: Cadenya::BareMetadata?

        def tool=: (Cadenya::BareMetadata) -> Cadenya::BareMetadata

        attr_reader tool_set: Cadenya::BareMetadata?

        def tool_set=: (Cadenya::BareMetadata) -> Cadenya::BareMetadata

        def initialize: (
          objective: Cadenya::OperationMetadata,
          ?created_by: Cadenya::Profile,
          ?tool: Cadenya::BareMetadata,
          ?tool_set: Cadenya::BareMetadata
        ) -> void

        def to_hash: -> {
          created_by: Cadenya::Profile,
          objective: Cadenya::OperationMetadata,
          tool: Cadenya::BareMetadata,
          tool_set: Cadenya::BareMetadata
        }
      end
    end
  end
end
