module Cadenya
  module Models
    class ObjectiveTaskData = Objectives::ObjectiveTaskData

    module Objectives
      type objective_task_data =
        { completed: bool, number: Integer, task: String, completed_at: Time }

      class ObjectiveTaskData < Cadenya::Internal::Type::BaseModel
        attr_accessor completed: bool

        attr_accessor task: String

        attr_accessor number: Integer

        attr_reader completed_at: Time?

        def completed_at=: (Time) -> Time

        def initialize: (
          completed: bool,
          number: Integer,
          task: String,
          ?completed_at: Time
        ) -> void

        def to_hash: -> {
          completed: bool,
          number: Integer,
          task: String,
          completed_at: Time
        }
      end
    end
  end
end
