module Cadenya
  module Models
    class ObjectiveToolCall = Objectives::ObjectiveToolCall

    module Objectives
      type objective_tool_call =
        {
          data: Cadenya::Objectives::ObjectiveToolCallData,
          execution_status: Cadenya::Models::Objectives::ObjectiveToolCall::execution_status,
          metadata: Cadenya::OperationMetadata,
          status: Cadenya::Models::Objectives::ObjectiveToolCall::status,
          info: Cadenya::Objectives::ObjectiveToolCallInfo
        }

      class ObjectiveToolCall < Cadenya::Internal::Type::BaseModel
        attr_accessor data: Cadenya::Objectives::ObjectiveToolCallData

        attr_accessor metadata: Cadenya::OperationMetadata

        attr_accessor status: Cadenya::Models::Objectives::ObjectiveToolCall::status

        attr_reader info: Cadenya::Objectives::ObjectiveToolCallInfo?

        def info=: (
          Cadenya::Objectives::ObjectiveToolCallInfo
        ) -> Cadenya::Objectives::ObjectiveToolCallInfo

        attr_accessor execution_status: Cadenya::Models::Objectives::ObjectiveToolCall::execution_status

        def initialize: (
          data: Cadenya::Objectives::ObjectiveToolCallData,
          execution_status: Cadenya::Models::Objectives::ObjectiveToolCall::execution_status,
          metadata: Cadenya::OperationMetadata,
          status: Cadenya::Models::Objectives::ObjectiveToolCall::status,
          ?info: Cadenya::Objectives::ObjectiveToolCallInfo
        ) -> void

        def to_hash: -> {
          data: Cadenya::Objectives::ObjectiveToolCallData,
          execution_status: Cadenya::Models::Objectives::ObjectiveToolCall::execution_status,
          metadata: Cadenya::OperationMetadata,
          status: Cadenya::Models::Objectives::ObjectiveToolCall::status,
          info: Cadenya::Objectives::ObjectiveToolCallInfo
        }

        type execution_status =
          :TOOL_CALL_EXECUTION_STATUS_UNSPECIFIED
          | :TOOL_CALL_EXECUTION_STATUS_PENDING
          | :TOOL_CALL_EXECUTION_STATUS_RUNNING
          | :TOOL_CALL_EXECUTION_STATUS_COMPLETED
          | :TOOL_CALL_EXECUTION_STATUS_ERRORED

        module ExecutionStatus
          extend Cadenya::Internal::Type::Enum

          TOOL_CALL_EXECUTION_STATUS_UNSPECIFIED: :TOOL_CALL_EXECUTION_STATUS_UNSPECIFIED
          TOOL_CALL_EXECUTION_STATUS_PENDING: :TOOL_CALL_EXECUTION_STATUS_PENDING
          TOOL_CALL_EXECUTION_STATUS_RUNNING: :TOOL_CALL_EXECUTION_STATUS_RUNNING
          TOOL_CALL_EXECUTION_STATUS_COMPLETED: :TOOL_CALL_EXECUTION_STATUS_COMPLETED
          TOOL_CALL_EXECUTION_STATUS_ERRORED: :TOOL_CALL_EXECUTION_STATUS_ERRORED

          def self?.values: -> ::Array[Cadenya::Models::Objectives::ObjectiveToolCall::execution_status]
        end

        type status =
          :TOOL_CALL_STATUS_UNSPECIFIED
          | :TOOL_CALL_STATUS_AUTO_APPROVED
          | :TOOL_CALL_STATUS_WAITING_FOR_APPROVAL
          | :TOOL_CALL_STATUS_APPROVED
          | :TOOL_CALL_STATUS_DENIED

        module Status
          extend Cadenya::Internal::Type::Enum

          TOOL_CALL_STATUS_UNSPECIFIED: :TOOL_CALL_STATUS_UNSPECIFIED
          TOOL_CALL_STATUS_AUTO_APPROVED: :TOOL_CALL_STATUS_AUTO_APPROVED
          TOOL_CALL_STATUS_WAITING_FOR_APPROVAL: :TOOL_CALL_STATUS_WAITING_FOR_APPROVAL
          TOOL_CALL_STATUS_APPROVED: :TOOL_CALL_STATUS_APPROVED
          TOOL_CALL_STATUS_DENIED: :TOOL_CALL_STATUS_DENIED

          def self?.values: -> ::Array[Cadenya::Models::Objectives::ObjectiveToolCall::status]
        end
      end
    end
  end
end
