module Cadenya
  module Models
    class ObjectiveToolCallData = Objectives::ObjectiveToolCallData

    module Objectives
      type objective_tool_call_data =
        {
          callable: Cadenya::Models::callable_tool,
          arguments: ::Hash[Symbol, top],
          memo: String,
          resolved_secrets: ::Array[Cadenya::Objectives::ResolvedSecret],
          status_changed_by: Cadenya::Profile
        }

      class ObjectiveToolCallData < Cadenya::Internal::Type::BaseModel
        attr_accessor callable: Cadenya::Models::callable_tool

        attr_accessor arguments: ::Hash[Symbol, top]

        attr_reader memo: String?

        def memo=: (String) -> String

        attr_accessor resolved_secrets: ::Array[Cadenya::Objectives::ResolvedSecret]

        attr_reader status_changed_by: Cadenya::Profile?

        def status_changed_by=: (Cadenya::Profile) -> Cadenya::Profile

        def initialize: (
          callable: Cadenya::Models::callable_tool,
          arguments: ::Hash[Symbol, top],
          resolved_secrets: ::Array[Cadenya::Objectives::ResolvedSecret],
          ?memo: String,
          ?status_changed_by: Cadenya::Profile
        ) -> void

        def to_hash: -> {
          callable: Cadenya::Models::callable_tool,
          arguments: ::Hash[Symbol, top],
          memo: String,
          resolved_secrets: ::Array[Cadenya::Objectives::ResolvedSecret],
          status_changed_by: Cadenya::Profile
        }
      end
    end
  end
end
