module Cadenya
  module Models
    class ObjectiveTool = Objectives::ObjectiveTool

    module Objectives
      type objective_tool =
        { metadata: Cadenya::BareMetadata, snapshot: Cadenya::ToolSets::Tool }

      class ObjectiveTool < Cadenya::Internal::Type::BaseModel
        attr_accessor metadata: Cadenya::BareMetadata

        attr_reader snapshot: Cadenya::ToolSets::Tool?

        def snapshot=: (Cadenya::ToolSets::Tool) -> Cadenya::ToolSets::Tool

        def initialize: (
          metadata: Cadenya::BareMetadata,
          ?snapshot: Cadenya::ToolSets::Tool
        ) -> void

        def to_hash: -> {
          metadata: Cadenya::BareMetadata,
          snapshot: Cadenya::ToolSets::Tool
        }
      end
    end
  end
end
