module Cadenya
  module Models
    class ObjectiveFeedback = Objectives::ObjectiveFeedback

    module Objectives
      type objective_feedback =
        {
          data: Cadenya::Objectives::ObjectiveFeedbackData,
          metadata: Cadenya::OperationMetadata,
          info: Cadenya::Objectives::ObjectiveFeedbackInfo
        }

      class ObjectiveFeedback < Cadenya::Internal::Type::BaseModel
        attr_accessor data: Cadenya::Objectives::ObjectiveFeedbackData

        attr_accessor metadata: Cadenya::OperationMetadata

        attr_accessor info: Cadenya::Objectives::ObjectiveFeedbackInfo

        def initialize: (
          data: Cadenya::Objectives::ObjectiveFeedbackData,
          metadata: Cadenya::OperationMetadata,
          info: Cadenya::Objectives::ObjectiveFeedbackInfo
        ) -> void

        def to_hash: -> {
          data: Cadenya::Objectives::ObjectiveFeedbackData,
          metadata: Cadenya::OperationMetadata,
          info: Cadenya::Objectives::ObjectiveFeedbackInfo
        }
      end
    end
  end
end
