module Cadenya
  module Models
    class ObjectiveTask = Objectives::ObjectiveTask

    module Objectives
      type objective_task =
        {
          data: Cadenya::Objectives::ObjectiveTaskData,
          metadata: Cadenya::BareMetadata
        }

      class ObjectiveTask < Cadenya::Internal::Type::BaseModel
        attr_accessor data: Cadenya::Objectives::ObjectiveTaskData

        attr_accessor metadata: Cadenya::BareMetadata

        def initialize: (
          data: Cadenya::Objectives::ObjectiveTaskData,
          metadata: Cadenya::BareMetadata
        ) -> void

        def to_hash: -> {
          data: Cadenya::Objectives::ObjectiveTaskData,
          metadata: Cadenya::BareMetadata
        }
      end
    end
  end
end
