module Cadenya
  module Models
    module Objectives
      type resolved_secret =
        {
          key: String,
          source: Cadenya::Models::Objectives::ResolvedSecret::source
        }

      class ResolvedSecret < Cadenya::Internal::Type::BaseModel
        attr_reader key: String?

        def key=: (String) -> String

        attr_reader source: Cadenya::Models::Objectives::ResolvedSecret::source?

        def source=: (
          Cadenya::Models::Objectives::ResolvedSecret::source
        ) -> Cadenya::Models::Objectives::ResolvedSecret::source

        def initialize: (
          ?key: String,
          ?source: Cadenya::Models::Objectives::ResolvedSecret::source
        ) -> void

        def to_hash: -> {
          key: String,
          source: Cadenya::Models::Objectives::ResolvedSecret::source
        }

        type source =
          :RESOLVED_SECRET_SOURCE_UNSPECIFIED
          | :RESOLVED_SECRET_SOURCE_WORKSPACE
          | :RESOLVED_SECRET_SOURCE_TOOLSET
          | :RESOLVED_SECRET_SOURCE_OBJECTIVE

        module Source
          extend Cadenya::Internal::Type::Enum

          RESOLVED_SECRET_SOURCE_UNSPECIFIED: :RESOLVED_SECRET_SOURCE_UNSPECIFIED
          RESOLVED_SECRET_SOURCE_WORKSPACE: :RESOLVED_SECRET_SOURCE_WORKSPACE
          RESOLVED_SECRET_SOURCE_TOOLSET: :RESOLVED_SECRET_SOURCE_TOOLSET
          RESOLVED_SECRET_SOURCE_OBJECTIVE: :RESOLVED_SECRET_SOURCE_OBJECTIVE

          def self?.values: -> ::Array[Cadenya::Models::Objectives::ResolvedSecret::source]
        end
      end
    end
  end
end
