module Cadenya
  module Models
    module Objectives
      type set_tool_call_content_request_content_block =
        {
          audio: Cadenya::Objectives::SetToolCallContentRequestAudioBlock,
          image: Cadenya::Objectives::SetToolCallContentRequestImageBlock,
          text: Cadenya::Objectives::SetToolCallContentRequestTextBlock,
          type: String
        }

      class SetToolCallContentRequestContentBlock < Cadenya::Internal::Type::BaseModel
        attr_reader audio: Cadenya::Objectives::SetToolCallContentRequestAudioBlock?

        def audio=: (
          Cadenya::Objectives::SetToolCallContentRequestAudioBlock
        ) -> Cadenya::Objectives::SetToolCallContentRequestAudioBlock

        attr_reader image: Cadenya::Objectives::SetToolCallContentRequestImageBlock?

        def image=: (
          Cadenya::Objectives::SetToolCallContentRequestImageBlock
        ) -> Cadenya::Objectives::SetToolCallContentRequestImageBlock

        attr_reader text: Cadenya::Objectives::SetToolCallContentRequestTextBlock?

        def text=: (
          Cadenya::Objectives::SetToolCallContentRequestTextBlock
        ) -> Cadenya::Objectives::SetToolCallContentRequestTextBlock

        attr_reader type: String?

        def type=: (String) -> String

        def initialize: (
          ?audio: Cadenya::Objectives::SetToolCallContentRequestAudioBlock,
          ?image: Cadenya::Objectives::SetToolCallContentRequestImageBlock,
          ?text: Cadenya::Objectives::SetToolCallContentRequestTextBlock,
          ?type: String
        ) -> void

        def to_hash: -> {
          audio: Cadenya::Objectives::SetToolCallContentRequestAudioBlock,
          image: Cadenya::Objectives::SetToolCallContentRequestImageBlock,
          text: Cadenya::Objectives::SetToolCallContentRequestTextBlock,
          type: String
        }
      end
    end
  end
end
