module Cadenya
  module Models
    module Objectives
      type tool_call_list_params =
        {
          workspace_id: String,
          objective_id: String,
          cursor: String,
          execution_status: Cadenya::Models::Objectives::ToolCallListParams::execution_status,
          include_info: bool,
          labels: String,
          limit: Integer,
          status: Cadenya::Models::Objectives::ToolCallListParams::status
        }
        & Cadenya::Internal::Type::request_parameters

      class ToolCallListParams < Cadenya::Internal::Type::BaseModel
        extend Cadenya::Internal::Type::RequestParameters::Converter
        include Cadenya::Internal::Type::RequestParameters

        attr_reader workspace_id: String?

        def workspace_id=: (String) -> String

        attr_accessor objective_id: String

        attr_reader cursor: String?

        def cursor=: (String) -> String

        attr_reader execution_status: Cadenya::Models::Objectives::ToolCallListParams::execution_status?

        def execution_status=: (
          Cadenya::Models::Objectives::ToolCallListParams::execution_status
        ) -> Cadenya::Models::Objectives::ToolCallListParams::execution_status

        attr_reader include_info: bool?

        def include_info=: (bool) -> bool

        attr_reader labels: String?

        def labels=: (String) -> String

        attr_reader limit: Integer?

        def limit=: (Integer) -> Integer

        attr_reader status: Cadenya::Models::Objectives::ToolCallListParams::status?

        def status=: (
          Cadenya::Models::Objectives::ToolCallListParams::status
        ) -> Cadenya::Models::Objectives::ToolCallListParams::status

        def initialize: (
          objective_id: String,
          ?workspace_id: String,
          ?cursor: String,
          ?execution_status: Cadenya::Models::Objectives::ToolCallListParams::execution_status,
          ?include_info: bool,
          ?labels: String,
          ?limit: Integer,
          ?status: Cadenya::Models::Objectives::ToolCallListParams::status,
          ?request_options: Cadenya::request_opts
        ) -> void

        def to_hash: -> {
          workspace_id: String,
          objective_id: String,
          cursor: String,
          execution_status: Cadenya::Models::Objectives::ToolCallListParams::execution_status,
          include_info: bool,
          labels: String,
          limit: Integer,
          status: Cadenya::Models::Objectives::ToolCallListParams::status,
          request_options: Cadenya::RequestOptions
        }

        type execution_status =
          :TOOL_CALL_EXECUTION_STATUS_UNSPECIFIED
          | :TOOL_CALL_EXECUTION_STATUS_PENDING
          | :TOOL_CALL_EXECUTION_STATUS_RUNNING
          | :TOOL_CALL_EXECUTION_STATUS_COMPLETED
          | :TOOL_CALL_EXECUTION_STATUS_ERRORED
          | :TOOL_CALL_EXECUTION_STATUS_WAITING_FOR_CONTENT

        module ExecutionStatus
          extend Cadenya::Internal::Type::Enum

          TOOL_CALL_EXECUTION_STATUS_UNSPECIFIED: :TOOL_CALL_EXECUTION_STATUS_UNSPECIFIED
          TOOL_CALL_EXECUTION_STATUS_PENDING: :TOOL_CALL_EXECUTION_STATUS_PENDING
          TOOL_CALL_EXECUTION_STATUS_RUNNING: :TOOL_CALL_EXECUTION_STATUS_RUNNING
          TOOL_CALL_EXECUTION_STATUS_COMPLETED: :TOOL_CALL_EXECUTION_STATUS_COMPLETED
          TOOL_CALL_EXECUTION_STATUS_ERRORED: :TOOL_CALL_EXECUTION_STATUS_ERRORED
          TOOL_CALL_EXECUTION_STATUS_WAITING_FOR_CONTENT: :TOOL_CALL_EXECUTION_STATUS_WAITING_FOR_CONTENT

          def self?.values: -> ::Array[Cadenya::Models::Objectives::ToolCallListParams::execution_status]
        end

        type status =
          :TOOL_CALL_STATUS_UNSPECIFIED
          | :TOOL_CALL_STATUS_AUTO_APPROVED
          | :TOOL_CALL_STATUS_WAITING_FOR_APPROVAL
          | :TOOL_CALL_STATUS_APPROVED
          | :TOOL_CALL_STATUS_DENIED

        module Status
          extend Cadenya::Internal::Type::Enum

          TOOL_CALL_STATUS_UNSPECIFIED: :TOOL_CALL_STATUS_UNSPECIFIED
          TOOL_CALL_STATUS_AUTO_APPROVED: :TOOL_CALL_STATUS_AUTO_APPROVED
          TOOL_CALL_STATUS_WAITING_FOR_APPROVAL: :TOOL_CALL_STATUS_WAITING_FOR_APPROVAL
          TOOL_CALL_STATUS_APPROVED: :TOOL_CALL_STATUS_APPROVED
          TOOL_CALL_STATUS_DENIED: :TOOL_CALL_STATUS_DENIED

          def self?.values: -> ::Array[Cadenya::Models::Objectives::ToolCallListParams::status]
        end
      end
    end
  end
end
