# frozen_string_literal: true

# Code generated by redwood. DO NOT EDIT.
# Conformance driver: calls every operation against the mock at MOCK_URL.
# Loads the gem from the ambient load path/GEM_HOME — run with `-Ilib` for
# a source-tree run, or under an installed gem home for the packaging gate.
require "cadenya"
warn "cadenya loaded from: #{$LOADED_FEATURES.grep(%r{cadenya/client}).first}"

$failures = 0

def run(op_id)
  yield
  puts "PASS #{op_id}"
rescue StandardError => e
  $failures += 1
  puts "FAIL #{op_id}: #{e.message.to_s[0, 160]}"
end

def check_page(page)
  # Auto-iterate: the mock serves two pages and rejects the second when any
  # non-cursor query param drifts from the first request.
  total = page.count
  raise "expected 2 items across pages, got #{total}" unless total == 2
end

def check_stream(stream)
  count = stream.count
  raise "expected 2 events, got #{count}" unless count == 2
end

client = Cadenya::Client.new(api_key: "conformance-key", base_url: ENV.fetch("MOCK_URL"))

run("AccountService_GetAccount") { client.accounts.retrieve() }
run("AccountService_RotateChallengeToken") { client.accounts.rotate_challenge_token() }
run("AccountService_RotateWebhookSigningKey") { client.accounts.rotate_webhook_signing_key() }
run("GlobalAPIKeyService_GetGlobalAPIKey") { client.api_keys.retrieve_global() }
run("GlobalAPIKeyService_DisableGlobalAPIKey") { client.api_keys.disable_global() }
run("GlobalAPIKeyService_EnableGlobalAPIKey") { client.api_keys.enable_global() }
run("GlobalAPIKeyService_RotateGlobalAPIKey") { client.api_keys.rotate_global() }
run("APIKeyService_ListAPIKeys") { check_page(client.api_keys.list(workspace_id: "sample", limit: 1, cursor: "sample", prefix: "sample", query: "sample", labels: "sample", sort_order: "sample", include_info: true)) }
run("APIKeyService_CreateAPIKey") { client.api_keys.create(workspace_id: "sample", metadata: {"name" => "sample"}, spec: {}) }
run("APIKeyService_GetAPIKey") { client.api_keys.retrieve("sample", workspace_id: "sample") }
run("APIKeyService_DeleteAPIKey") { client.api_keys.delete("sample", workspace_id: "sample") }
run("APIKeyService_UpdateAPIKey") { client.api_keys.update("sample", workspace_id: "sample", metadata: {"name" => "sample"}, spec: {}, update_mask: "sample") }
run("APIKeyService_DisableAPIKey") { client.api_keys.disable("sample", workspace_id: "sample") }
run("APIKeyService_EnableAPIKey") { client.api_keys.enable("sample", workspace_id: "sample") }
run("APIKeyService_RotateAPIKey") { client.api_keys.rotate("sample", workspace_id: "sample") }
run("WorkspaceAdminService_ListProfiles") { check_page(client.workspace_admin.list_profiles(limit: 1, cursor: "sample", query: "sample", labels: "sample")) }
run("WorkspaceAdminService_ListAccountWorkspaces") { check_page(client.workspace_admin.list_account(limit: 1, cursor: "sample", include_archived: true, labels: "sample")) }
run("WorkspaceAdminService_CreateWorkspace") { client.workspace_admin.create(metadata: {"name" => "sample"}, spec: {}) }
run("WorkspaceAdminService_GetWorkspace") { client.workspace_admin.retrieve(workspace_id: "sample") }
run("WorkspaceAdminService_ArchiveWorkspace") { client.workspace_admin.archive(workspace_id: "sample") }
run("WorkspaceAdminService_UpdateWorkspace") { client.workspace_admin.update(workspace_id: "sample", metadata: {"name" => "sample"}, spec: {}, update_mask: "sample") }
run("WorkspaceAdminService_ListWorkspaceMembers") { check_page(client.workspace_admin.list_members(workspace_id: "sample", limit: 1, cursor: "sample")) }
run("WorkspaceAdminService_AddWorkspaceMember") { client.workspace_admin.add_member(workspace_id: "sample", profile_id: "sample", email: "sample") }
run("WorkspaceAdminService_RemoveWorkspaceMember") { client.workspace_admin.remove_member("sample", workspace_id: "sample") }
run("ProfilesService_Whoami") { client.profiles.whoami() }
run("WorkspaceService_ListWorkspaces") { check_page(client.workspaces.list(limit: 1, cursor: "sample", sort_order: "sample", include_info: true, labels: "sample")) }
run("AgentService_ListAgents") { check_page(client.agents.list(workspace_id: "sample", limit: 1, cursor: "sample", prefix: "sample", query: "sample", state: "STATE_UNSPECIFIED", variation_selection_mode: "VARIATION_SELECTION_MODE_UNSPECIFIED", labels: "sample", sort_order: "sample", include_info: true)) }
run("AgentService_CreateAgent") { client.agents.create(workspace_id: "sample", metadata: {"name" => "sample"}, spec: {"variation_selection_mode" => "VARIATION_SELECTION_MODE_UNSPECIFIED"}, default_variation: {"metadata" => {"name" => "sample"}, "spec" => {}}) }
run("AgentService_ListAgentFeedback") { check_page(client.agents.list_feedback("sample", workspace_id: "sample", limit: 1, cursor: "sample", query: "sample", sentiment: "FEEDBACK_SENTIMENT_UNSPECIFIED", agent_variation_id: "sample", created_after: "2026-01-01T00:00:00Z", created_before: "2026-01-01T00:00:00Z", labels: "sample", include_info: true)) }
run("AgentService_ListAgentWebhookDeliveries") { check_page(client.agents.list_webhook_deliveries("sample", workspace_id: "sample", cursor: "sample", limit: 1, objective_id: "sample", event_type: "OBJECTIVE_EVENT_TYPE_UNSPECIFIED", labels: "sample")) }
run("AgentService_GetAgent") { client.agents.retrieve("sample", workspace_id: "sample") }
run("AgentService_DeleteAgent") { client.agents.delete("sample", workspace_id: "sample") }
run("AgentService_UpdateAgent") { client.agents.update("sample", workspace_id: "sample", metadata: {"name" => "sample"}, spec: {"variation_selection_mode" => "VARIATION_SELECTION_MODE_UNSPECIFIED"}, update_mask: "sample") }
run("AgentService_ArchiveAgent") { client.agents.archive("sample", workspace_id: "sample") }
run("AgentService_PublishAgent") { client.agents.publish("sample", workspace_id: "sample") }
run("AgentService_UnarchiveAgent") { client.agents.unarchive("sample", workspace_id: "sample") }
run("AgentService_UnpublishAgent") { client.agents.unpublish("sample", workspace_id: "sample") }
run("AgentScheduleService_ListAgentSchedules") { check_page(client.agents.schedules.list("sample", workspace_id: "sample", limit: 1, cursor: "sample", prefix: "sample", query: "sample", labels: "sample", sort_order: "sample", include_info: true)) }
run("AgentScheduleService_CreateAgentSchedule") { client.agents.schedules.create("sample", workspace_id: "sample", metadata: {"name" => "sample"}, spec: {"schedule" => {}}) }
run("AgentScheduleService_GetAgentSchedule") { client.agents.schedules.retrieve("sample", "sample", workspace_id: "sample") }
run("AgentScheduleService_DeleteAgentSchedule") { client.agents.schedules.delete("sample", "sample", workspace_id: "sample") }
run("AgentScheduleService_UpdateAgentSchedule") { client.agents.schedules.update("sample", "sample", workspace_id: "sample", metadata: {"name" => "sample"}, spec: {"schedule" => {}}, update_mask: "sample") }
run("AgentScheduleService_ArchiveAgentSchedule") { client.agents.schedules.archive("sample", "sample", workspace_id: "sample") }
run("AgentScheduleService_PauseAgentSchedule") { client.agents.schedules.pause("sample", "sample", workspace_id: "sample") }
run("AgentScheduleService_ResumeAgentSchedule") { client.agents.schedules.resume("sample", "sample", workspace_id: "sample") }
run("AgentVariationService_ListAgentVariations") { check_page(client.agents.variations.list("sample", workspace_id: "sample", limit: 1, cursor: "sample", sort_order: "sample", include_info: true, labels: "sample")) }
run("AgentVariationService_CreateAgentVariation") { client.agents.variations.create("sample", workspace_id: "sample", metadata: {"name" => "sample"}, spec: {}) }
run("AgentVariationService_GetAgentVariation") { client.agents.variations.retrieve("sample", "sample", workspace_id: "sample") }
run("AgentVariationService_DeleteAgentVariation") { client.agents.variations.delete("sample", "sample", workspace_id: "sample") }
run("AgentVariationService_UpdateAgentVariation") { client.agents.variations.update("sample", "sample", workspace_id: "sample", metadata: {"name" => "sample"}, spec: {}, update_mask: "sample") }
run("AgentVariationService_AddAgentVariationAssignment") { client.agents.variations.add_assignment("sample", "sample", workspace_id: "sample", body: {"tool_id" => "sample", "type" => "toolId"}) }
run("AgentVariationService_RemoveAgentVariationAssignment") { client.agents.variations.remove_assignment("sample", "sample", "sample", workspace_id: "sample") }
run("AgentVariationService_AddAgentVariationMemoryLayer") { client.agents.variations.add_memory_layer("sample", "sample", workspace_id: "sample", memory_layer_id: "sample", position: 1) }
run("AgentVariationService_RemoveAgentVariationMemoryLayer") { client.agents.variations.remove_memory_layer("sample", "sample", "sample", workspace_id: "sample") }
run("AgentVariationService_UpdateAgentVariationMemoryLayer") { client.agents.variations.update_memory_layer("sample", "sample", "sample", workspace_id: "sample", position: 1) }
run("AIProviderKeyService_ListAIProviderKeys") { check_page(client.ai_provider_keys.list(workspace_id: "sample", limit: 1, cursor: "sample", prefix: "sample", query: "sample", promotional: true, labels: "sample", sort_order: "sample", include_info: true)) }
run("AIProviderKeyService_CreateAIProviderKey") { client.ai_provider_keys.create(workspace_id: "sample", metadata: {"name" => "sample"}, spec: {}) }
run("AIProviderKeyService_GetAIProviderKey") { client.ai_provider_keys.retrieve("sample", workspace_id: "sample") }
run("AIProviderKeyService_DeleteAIProviderKey") { client.ai_provider_keys.delete("sample", workspace_id: "sample") }
run("AIProviderKeyService_UpdateAIProviderKey") { client.ai_provider_keys.update("sample", workspace_id: "sample", metadata: {"name" => "sample"}, spec: {}, update_mask: "sample") }
run("MemoryService_ListMemoryLayers") { check_page(client.memory_layers.list(workspace_id: "sample", limit: 1, cursor: "sample", prefix: "sample", query: "sample", type: "MEMORY_LAYER_TYPE_UNSPECIFIED", agent_id: "sample", episodic_key_prefix: "sample", labels: "sample", sort_order: "sample", include_info: true)) }
run("MemoryService_CreateMemoryLayer") { client.memory_layers.create(workspace_id: "sample", metadata: {"name" => "sample"}, spec: {"type" => "MEMORY_LAYER_TYPE_UNSPECIFIED"}) }
run("MemoryService_GetMemoryLayer") { client.memory_layers.retrieve("sample", workspace_id: "sample") }
run("MemoryService_DeleteMemoryLayer") { client.memory_layers.delete("sample", workspace_id: "sample") }
run("MemoryService_UpdateMemoryLayer") { client.memory_layers.update("sample", workspace_id: "sample", metadata: {"name" => "sample"}, spec: {"type" => "MEMORY_LAYER_TYPE_UNSPECIFIED"}, update_mask: "sample") }
run("MemoryService_ListMemoryEntries") { check_page(client.memory_layers.entries.list("sample", workspace_id: "sample", limit: 1, cursor: "sample", prefix: "sample", query: "sample", labels: "sample", sort_order: "sample", include_info: true)) }
run("MemoryService_CreateMemoryEntry") { client.memory_layers.entries.create("sample", workspace_id: "sample", metadata: {"name" => "sample"}, spec: {"content" => "sample", "key" => "sample", "type" => "content"}) }
run("MemoryService_GetMemoryEntry") { client.memory_layers.entries.retrieve("sample", "sample", workspace_id: "sample") }
run("MemoryService_DeleteMemoryEntry") { client.memory_layers.entries.delete("sample", "sample", workspace_id: "sample") }
run("MemoryService_UpdateMemoryEntry") { client.memory_layers.entries.update("sample", "sample", workspace_id: "sample", metadata: {"name" => "sample"}, spec: {}, update_mask: "sample") }
run("ModelService_ListModels") { check_page(client.models.list(workspace_id: "sample", limit: 1, cursor: "sample", prefix: "sample", query: "sample", state: "STATE_UNSPECIFIED", ai_provider_key_id: "sample", is_assigned: true, labels: "sample", sort_order: "sample", include_info: true)) }
run("ModelService_GetModel") { client.models.retrieve("sample", workspace_id: "sample") }
run("ModelService_DisableModel") { client.models.disable("sample", workspace_id: "sample") }
run("ModelService_EnableModel") { client.models.enable("sample", workspace_id: "sample") }
run("ModelService_SwapModelOnVariations") { client.models.swap_on_variations(workspace_id: "sample", model_swaps: [{}]) }
run("ObjectiveService_ListObjectives") { check_page(client.objectives.list(workspace_id: "sample", limit: 1, cursor: "sample", agent_id: "sample", parent_objective_id: "sample", state: "STATE_UNSPECIFIED", profile_id: "sample", sort_order: "sample", include_info: true, agent_schedule_id: "sample", labels: "sample", tenant_id: "sample", subject_id: "sample", widget_id: "sample", widget_session_id: "sample")) }
run("ObjectiveService_CreateObjective") { client.objectives.create(workspace_id: "sample", agent_id: "sample", variation_id: "sample", metadata: {}, system_prompt_data: {}, first_user_message: "sample", secrets: [{}], memory_cascade: [{"memory_layer_id" => "sample"}], first_user_message_data: {}, episodic_memory: {"key" => "sample"}, tenant: {"id" => "sample"}, subject: {"id" => "sample"}, pinned_parameters: {}) }
run("ObjectiveService_GetObjective") { client.objectives.retrieve("sample", workspace_id: "sample") }
run("ObjectiveService_ListObjectiveContextWindows") { check_page(client.objectives.list_context_windows("sample", workspace_id: "sample", limit: 1, cursor: "sample", include_info: true, labels: "sample")) }
run("ObjectiveService_GetObjectiveDiagnostics") { client.objectives.retrieve_diagnostics("sample", workspace_id: "sample") }
run("ObjectiveService_ListObjectiveEvents") { check_page(client.objectives.list_events("sample", workspace_id: "sample", limit: 1, cursor: "sample", sort_order: "sample", include_info: true, window_id: "sample", since_event_id: "sample", labels: "sample")) }
run("ObjectiveEventStreamsService_StreamObjectiveEvents") { check_stream(client.objectives.stream_events("sample", workspace_id: "sample")) }
run("ObjectiveService_ListObjectiveFeedback") { check_page(client.objectives.list_feedback("sample", workspace_id: "sample", limit: 1, cursor: "sample", labels: "sample")) }
run("ObjectiveService_CreateObjectiveFeedback") { client.objectives.create_feedback("sample", workspace_id: "sample", metadata: {}, data: {}) }
run("ObjectiveService_ListObjectiveTasks") { check_page(client.objectives.list_tasks("sample", workspace_id: "sample", limit: 1, cursor: "sample", sort_order: "sample")) }
run("ObjectiveService_GetObjectiveTask") { client.objectives.retrieve_task("sample", "sample", workspace_id: "sample") }
run("ObjectiveService_ListObjectiveToolCalls") { check_page(client.objectives.list_tool_calls("sample", workspace_id: "sample", limit: 1, cursor: "sample", status: "TOOL_CALL_STATUS_UNSPECIFIED", include_info: true, execution_status: "TOOL_CALL_EXECUTION_STATUS_UNSPECIFIED", labels: "sample")) }
run("ObjectiveService_GetObjectiveToolCall") { client.objectives.retrieve_tool_call("sample", "sample", workspace_id: "sample") }
run("ObjectiveService_ApproveToolCall") { client.objectives.approve_tool_call("sample", "sample", workspace_id: "sample") }
run("ObjectiveService_DenyToolCall") { client.objectives.deny_tool_call("sample", "sample", workspace_id: "sample", memo: "sample") }
run("ObjectiveService_SetToolCallContent") { client.objectives.set_tool_call_content("sample", "sample", workspace_id: "sample", content: [{"text" => {"text" => "sample"}, "type" => "text"}]) }
run("ObjectiveService_ListObjectiveTools") { check_page(client.objectives.list_tools("sample", workspace_id: "sample", limit: 1, cursor: "sample")) }
run("ObjectiveService_CancelObjective") { client.objectives.cancel("sample", workspace_id: "sample", reason: "sample") }
run("ObjectiveService_CompactObjective") { client.objectives.compact("sample", workspace_id: "sample", compaction_config: {}) }
run("ObjectiveService_ContinueObjective") { client.objectives.continue("sample", workspace_id: "sample", message: "sample", enqueue: true) }
run("SearchService_SearchToolsOrToolSets") { client.tool_search.search_or_sets(workspace_id: "sample", query: "sample") }
run("TenantService_ListTenants") { check_page(client.tenants.list(workspace_id: "sample", limit: 1, cursor: "sample", query: "sample", labels: "sample", sort_order: "sample", include_info: true)) }
run("TenantService_GetTenant") { client.tenants.retrieve("sample", workspace_id: "sample", include_info: true) }
run("TenantService_DeleteTenant") { client.tenants.delete("sample", workspace_id: "sample") }
run("TenantService_ListTenantSubjects") { check_page(client.tenants.list_subjects("sample", workspace_id: "sample", limit: 1, cursor: "sample", query: "sample", sort_order: "sample", include_info: true)) }
run("ToolService_ListToolSets") { check_page(client.tool_sets.list(workspace_id: "sample", limit: 1, cursor: "sample", prefix: "sample", query: "sample", state: "STATE_UNSPECIFIED", labels: "sample", sort_order: "sample", include_info: true)) }
run("ToolService_CreateToolSet") { client.tool_sets.create(workspace_id: "sample", metadata: {"name" => "sample"}, spec: {"adapter" => {"mcp" => {}, "type" => "mcp"}}) }
run("ToolService_GetToolSet") { client.tool_sets.retrieve("sample", workspace_id: "sample") }
run("ToolService_DeleteToolSet") { client.tool_sets.delete("sample", workspace_id: "sample") }
run("ToolService_UpdateToolSet") { client.tool_sets.update("sample", workspace_id: "sample", metadata: {"name" => "sample"}, spec: {"adapter" => {"mcp" => {}, "type" => "mcp"}}, update_mask: "sample") }
run("ToolService_ArchiveToolSet") { client.tool_sets.archive("sample", workspace_id: "sample") }
run("ToolService_UnarchiveToolSet") { client.tool_sets.unarchive("sample", workspace_id: "sample") }
run("ToolService_ListToolSetEvents") { check_page(client.tool_sets.list_events("sample", workspace_id: "sample", limit: 1, cursor: "sample", sort_order: "sample", include_info: true, labels: "sample")) }
run("ToolService_GetToolSetOpenAPISpec") { client.tool_sets.retrieve_open_api_spec("sample", workspace_id: "sample") }
run("ToolService_ListToolSetUsage") { check_page(client.tool_sets.list_usage("sample", workspace_id: "sample", tool_id: "sample", limit: 1, cursor: "sample", sort_order: "sample")) }
run("ToolService_ListToolSetSecrets") { check_page(client.tool_sets.secrets.list("sample", workspace_id: "sample", limit: 1, cursor: "sample", prefix: "sample", query: "sample", sort_order: "sample", include_info: true)) }
run("ToolService_CreateToolSetSecret") { client.tool_sets.secrets.create("sample", workspace_id: "sample", metadata: {"name" => "sample"}, spec: {}) }
run("ToolService_GetToolSetSecret") { client.tool_sets.secrets.retrieve("sample", "sample", workspace_id: "sample") }
run("ToolService_DeleteToolSetSecret") { client.tool_sets.secrets.delete("sample", "sample", workspace_id: "sample") }
run("ToolService_UpdateToolSetSecret") { client.tool_sets.secrets.update("sample", "sample", workspace_id: "sample", metadata: {"name" => "sample"}, spec: {}, update_mask: "sample") }
run("ToolService_ListTools") { check_page(client.tool_sets.tools.list("sample", workspace_id: "sample", limit: 1, cursor: "sample", prefix: "sample", query: "sample", names: ["sample"], states: ["STATE_UNSPECIFIED"], requires_approval: true, labels: "sample", sort_order: "sample", include_info: true)) }
run("ToolService_CreateTool") { client.tool_sets.tools.create("sample", workspace_id: "sample", metadata: {"name" => "sample"}, spec: {"config" => {"http" => {"request_method" => "HTTP_METHOD_UNSPECIFIED"}, "type" => "http"}, "description" => "sample", "parameters" => {}, "requires_approval" => true}) }
run("ToolService_GetTool") { client.tool_sets.tools.retrieve("sample", "sample", workspace_id: "sample") }
run("ToolService_DeleteTool") { client.tool_sets.tools.delete("sample", "sample", workspace_id: "sample") }
run("ToolService_UpdateTool") { client.tool_sets.tools.update("sample", "sample", workspace_id: "sample", metadata: {"name" => "sample"}, spec: {"config" => {"http" => {"request_method" => "HTTP_METHOD_UNSPECIFIED"}, "type" => "http"}, "description" => "sample", "parameters" => {}, "requires_approval" => true}, update_mask: "sample") }
run("ToolService_OmitTool") { client.tool_sets.tools.omit("sample", "sample", workspace_id: "sample") }
run("ToolService_RestoreTool") { client.tool_sets.tools.restore("sample", "sample", workspace_id: "sample") }
run("UploadService_CreateUpload") { client.uploads.create(workspace_id: "sample", metadata: {"name" => "sample"}, spec: {"content_type" => "sample", "filename" => "sample", "size_bytes" => "sample"}) }
run("UploadService_GetUpload") { client.uploads.retrieve("sample", workspace_id: "sample") }
run("WidgetSessionService_ListWidgetSessions") { check_page(client.widget_sessions.list(workspace_id: "sample", limit: 1, cursor: "sample", widget_id: "sample", tenant_id: "sample", subject_id: "sample", state: "STATE_UNSPECIFIED", labels: "sample", sort_order: "sample", include_info: true)) }
run("WidgetSessionService_CreateWidgetSession") { client.widget_sessions.create(workspace_id: "sample", metadata: {}, spec: {"widget_id" => "sample"}, secrets: [{}]) }
run("WidgetSessionService_DeleteTenantWidgetSessions") { client.widget_sessions.delete_tenant(workspace_id: "sample", tenant_id: "sample") }
run("WidgetSessionService_GetWidgetSession") { client.widget_sessions.retrieve("sample", workspace_id: "sample") }
run("WidgetSessionService_DeleteWidgetSession") { client.widget_sessions.delete("sample", workspace_id: "sample") }
run("WidgetSessionService_RevokeWidgetSession") { client.widget_sessions.revoke("sample", workspace_id: "sample") }
run("WidgetService_ListWidgets") { check_page(client.widgets.list(workspace_id: "sample", limit: 1, cursor: "sample", agent_id: "sample", labels: "sample", sort_order: "sample", include_info: true)) }
run("WidgetService_CreateWidget") { client.widgets.create(workspace_id: "sample", metadata: {"name" => "sample"}, spec: {"agent_id" => "sample"}) }
run("WidgetService_GetWidget") { client.widgets.retrieve("sample", workspace_id: "sample") }
run("WidgetService_DeleteWidget") { client.widgets.delete("sample", workspace_id: "sample") }
run("WidgetService_UpdateWidget") { client.widgets.update("sample", workspace_id: "sample", metadata: {"name" => "sample"}, spec: {"agent_id" => "sample"}, update_mask: "sample") }
run("WidgetService_ArchiveWidget") { client.widgets.archive("sample", workspace_id: "sample") }
run("WidgetService_UnarchiveWidget") { client.widgets.unarchive("sample", workspace_id: "sample") }
run("WorkspaceSecretService_ListWorkspaceSecrets") { check_page(client.workspace_secrets.list(workspace_id: "sample", limit: 1, cursor: "sample", prefix: "sample", query: "sample", labels: "sample", sort_order: "sample", include_info: true)) }
run("WorkspaceSecretService_CreateWorkspaceSecret") { client.workspace_secrets.create(workspace_id: "sample", metadata: {"name" => "sample"}, spec: {}) }
run("WorkspaceSecretService_GetWorkspaceSecret") { client.workspace_secrets.retrieve("sample", workspace_id: "sample") }
run("WorkspaceSecretService_DeleteWorkspaceSecret") { client.workspace_secrets.delete("sample", workspace_id: "sample") }
run("WorkspaceSecretService_UpdateWorkspaceSecret") { client.workspace_secrets.update("sample", workspace_id: "sample", metadata: {"name" => "sample"}, spec: {}, update_mask: "sample") }

exit([$failures, 1].min)
