module Cadenya
  module Resources
    class ToolSets
      class Secrets
        def create: (
          String tool_set_id,
          workspace_id: String,
          metadata: Cadenya::CreateResourceMetadata,
          spec: Cadenya::ToolSets::ToolSetSecretSpec,
          ?request_options: Cadenya::request_opts
        ) -> Cadenya::ToolSets::ToolSetSecret

        def retrieve: (
          String id,
          workspace_id: String,
          tool_set_id: String,
          ?request_options: Cadenya::request_opts
        ) -> Cadenya::ToolSets::ToolSetSecret

        def update: (
          String id,
          workspace_id: String,
          tool_set_id: String,
          ?metadata: Cadenya::UpdateResourceMetadata,
          ?spec: Cadenya::ToolSets::ToolSetSecretSpec,
          ?update_mask: String,
          ?request_options: Cadenya::request_opts
        ) -> Cadenya::ToolSets::ToolSetSecret

        def list: (
          String tool_set_id,
          workspace_id: String,
          ?bundle_key: String,
          ?cursor: String,
          ?include_info: bool,
          ?limit: Integer,
          ?prefix: String,
          ?query: String,
          ?sort_order: String,
          ?request_options: Cadenya::request_opts
        ) -> Cadenya::Internal::CursorPagination[Cadenya::ToolSets::ToolSetSecret]

        def delete: (
          String id,
          workspace_id: String,
          tool_set_id: String,
          ?request_options: Cadenya::request_opts
        ) -> nil

        def initialize: (client: Cadenya::Client) -> void
      end
    end
  end
end
