module Cadenya
  module Resources
    class ToolSets
      class Tools
        def create: (
          String tool_set_id,
          workspace_id: String,
          metadata: Cadenya::CreateResourceMetadata,
          spec: Cadenya::ToolSets::ToolSpec,
          ?request_options: Cadenya::request_opts
        ) -> Cadenya::ToolSets::Tool

        def retrieve: (
          String id,
          workspace_id: String,
          tool_set_id: String,
          ?request_options: Cadenya::request_opts
        ) -> Cadenya::ToolSets::Tool

        def update: (
          String id,
          workspace_id: String,
          tool_set_id: String,
          ?metadata: Cadenya::UpdateResourceMetadata,
          ?spec: Cadenya::ToolSets::ToolSpec,
          ?update_mask: String,
          ?request_options: Cadenya::request_opts
        ) -> Cadenya::ToolSets::Tool

        def list: (
          String tool_set_id,
          workspace_id: String,
          ?bundle_key: String,
          ?cursor: String,
          ?include_info: bool,
          ?limit: Integer,
          ?names: ::Array[String],
          ?prefix: String,
          ?query: String,
          ?requires_approval: bool,
          ?sort_order: String,
          ?statuses: ::Array[Cadenya::Models::ToolSets::ToolListParams::status],
          ?request_options: Cadenya::request_opts
        ) -> Cadenya::Internal::CursorPagination[Cadenya::ToolSets::Tool]

        def delete: (
          String id,
          workspace_id: String,
          tool_set_id: String,
          ?request_options: Cadenya::request_opts
        ) -> nil

        def initialize: (client: Cadenya::Client) -> void
      end
    end
  end
end
