module Cadenya
  module Resources
    class Account
      def retrieve: (
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::AccountAPI

      def rotate_webhook_signing_key: (
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::RotateWebhookSigningKeyResponse

      def initialize: (client: Cadenya::Client) -> void
    end
  end
end
