module Cadenya
  module Resources
    class Agents
      attr_reader feedback: Cadenya::Resources::Agents::Feedback

      attr_reader webhook_deliveries: Cadenya::Resources::Agents::WebhookDeliveries

      attr_reader variations: Cadenya::Resources::Agents::Variations

      attr_reader schedules: Cadenya::Resources::Agents::Schedules

      def create: (
        metadata: Cadenya::CreateResourceMetadata,
        spec: Cadenya::AgentSpec,
        ?workspace_id: String,
        ?default_variation: Cadenya::AgentCreateParams::DefaultVariation,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::Agent

      def retrieve: (
        String id,
        ?workspace_id: String,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::Agent

      def update: (
        String id,
        ?workspace_id: String,
        ?metadata: Cadenya::UpdateResourceMetadata,
        ?spec: Cadenya::AgentSpec,
        ?update_mask: String,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::Agent

      def list: (
        ?workspace_id: String,
        ?cursor: String,
        ?include_info: bool,
        ?labels: String,
        ?limit: Integer,
        ?prefix: String,
        ?query: String,
        ?sort_order: String,
        ?state: Cadenya::Models::AgentListParams::state,
        ?variation_selection_mode: Cadenya::Models::AgentListParams::variation_selection_mode,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::Internal::CursorPagination[Cadenya::Agent]

      def delete: (
        String id,
        ?workspace_id: String,
        ?request_options: Cadenya::request_opts
      ) -> nil

      def archive: (
        String id,
        ?workspace_id: String,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::Agent

      def publish: (
        String id,
        ?workspace_id: String,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::Agent

      def unarchive: (
        String id,
        ?workspace_id: String,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::Agent

      def unpublish: (
        String id,
        ?workspace_id: String,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::Agent

      def initialize: (client: Cadenya::Client) -> void
    end
  end
end
