module Cadenya
  module Resources
    class BulkWorkspaceResources
      attr_reader results: Cadenya::Resources::BulkWorkspaceResources::Results

      def retrieve: (
        String id,
        workspace_id: String,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::BulkWorkspaceApply

      def list: (
        String workspace_id,
        ?bundle_key: String,
        ?cursor: String,
        ?limit: Integer,
        ?sort_order: String,
        ?state: Cadenya::Models::BulkWorkspaceResourceListParams::state,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::Internal::CursorPagination[Cadenya::BulkWorkspaceApply]

      def apply: (
        String workspace_id,
        data: Cadenya::BulkWorkspaceApplyData,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::BulkWorkspaceApply

      def initialize: (client: Cadenya::Client) -> void
    end
  end
end
