module Cadenya
  module Resources
    class MemoryLayers
      attr_reader entries: Cadenya::Resources::MemoryLayers::Entries

      def create: (
        String workspace_id,
        metadata: Cadenya::CreateResourceMetadata,
        spec: Cadenya::MemoryLayerSpec,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::MemoryLayer

      def retrieve: (
        String id,
        workspace_id: String,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::MemoryLayer

      def update: (
        String id,
        workspace_id: String,
        ?metadata: Cadenya::UpdateResourceMetadata,
        ?spec: Cadenya::MemoryLayerSpec,
        ?update_mask: String,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::MemoryLayer

      def list: (
        String workspace_id,
        ?bundle_key: String,
        ?cursor: String,
        ?include_info: bool,
        ?limit: Integer,
        ?prefix: String,
        ?query: String,
        ?sort_order: String,
        ?type: Cadenya::Models::MemoryLayerListParams::type_,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::Internal::CursorPagination[Cadenya::MemoryLayer]

      def delete: (
        String id,
        workspace_id: String,
        ?request_options: Cadenya::request_opts
      ) -> nil

      def initialize: (client: Cadenya::Client) -> void
    end
  end
end
