module Cadenya
  module Resources
    class Models
      def retrieve: (
        String id,
        workspace_id: String,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::Model

      def list: (
        String workspace_id,
        ?ai_provider_key_id: String,
        ?bundle_key: String,
        ?cursor: String,
        ?include_info: bool,
        ?limit: Integer,
        ?prefix: String,
        ?query: String,
        ?sort_order: String,
        ?state: Cadenya::Models::ModelListParams::state,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::Internal::CursorPagination[Cadenya::Model]

      def disable: (
        String id,
        workspace_id: String,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::Model

      def enable: (
        String id,
        workspace_id: String,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::Model

      def swap: (
        String workspace_id,
        ?model_swaps: ::Array[Cadenya::ModelSwapParams::ModelSwap],
        ?request_options: Cadenya::request_opts
      ) -> top

      def initialize: (client: Cadenya::Client) -> void
    end
  end
end
