module Cadenya
  module Resources
    class Profiles
      def list: (
        ?cursor: String,
        ?limit: Integer,
        ?query: String,
        ?type: Cadenya::Models::ProfileListParams::type_,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::Internal::CursorPagination[Cadenya::Profile]

      def initialize: (client: Cadenya::Client) -> void
    end
  end
end
