module Cadenya
  module Resources
    class Search
      def search_tools_or_tool_sets: (
        query: String,
        ?workspace_id: String,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::Models::SearchSearchToolsOrToolSetsResponse

      def initialize: (client: Cadenya::Client) -> void
    end
  end
end
