module Cadenya
  module Resources
    class Tenants
      attr_reader subjects: Cadenya::Resources::Tenants::Subjects

      def retrieve: (
        String id,
        ?workspace_id: String,
        ?include_info: bool,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::Tenant

      def list: (
        ?workspace_id: String,
        ?cursor: String,
        ?include_info: bool,
        ?labels: String,
        ?limit: Integer,
        ?query: String,
        ?sort_order: String,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::Internal::CursorPagination[Cadenya::Tenant]

      def delete: (
        String id,
        ?workspace_id: String,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::Tenant

      def initialize: (client: Cadenya::Client) -> void
    end
  end
end
