module Cadenya
  module Resources
    class ToolSets
      attr_reader tools: Cadenya::Resources::ToolSets::Tools

      attr_reader secrets: Cadenya::Resources::ToolSets::Secrets

      def create: (
        String workspace_id,
        metadata: Cadenya::CreateResourceMetadata,
        spec: Cadenya::ToolSetSpec,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::ToolSet

      def retrieve: (
        String id,
        workspace_id: String,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::ToolSet

      def update: (
        String id,
        workspace_id: String,
        ?metadata: Cadenya::UpdateResourceMetadata,
        ?spec: Cadenya::ToolSetSpec,
        ?update_mask: String,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::ToolSet

      def list: (
        String workspace_id,
        ?bundle_key: String,
        ?cursor: String,
        ?include_info: bool,
        ?limit: Integer,
        ?prefix: String,
        ?query: String,
        ?sort_order: String,
        ?state: Cadenya::Models::ToolSetListParams::state,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::Internal::CursorPagination[Cadenya::ToolSet]

      def delete: (
        String id,
        workspace_id: String,
        ?request_options: Cadenya::request_opts
      ) -> nil

      def archive: (
        String id,
        workspace_id: String,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::ToolSet

      def get_openapi_spec: (
        String tool_set_id,
        workspace_id: String,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::Models::ToolSetGetOpenAPISpecResponse

      def list_events: (
        String tool_set_id,
        workspace_id: String,
        ?cursor: String,
        ?include_info: bool,
        ?limit: Integer,
        ?sort_order: String,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::Internal::CursorPagination[Cadenya::ToolSetEvent]

      def unarchive: (
        String id,
        workspace_id: String,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::ToolSet

      def initialize: (client: Cadenya::Client) -> void
    end
  end
end
