module Cadenya
  module Resources
    class Uploads
      def create: (
        metadata: Cadenya::CreateResourceMetadata,
        spec: Cadenya::UploadSpec,
        ?workspace_id: String,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::Upload

      def retrieve: (
        String id,
        ?workspace_id: String,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::Upload

      def initialize: (client: Cadenya::Client) -> void
    end
  end
end
