module Cadenya
  module Resources
    class Webhooks
      def unsafe_unwrap: (String payload) -> Cadenya::UnsafeUnwrapWebhookEvent

      def unwrap: (
        String payload,
        headers: ::Hash[String, String],
        ?key: String?
      ) -> Cadenya::UnwrapWebhookEvent

      def initialize: (client: Cadenya::Client) -> void
    end
  end
end
