module Cadenya
  module Resources
    class WorkspaceSecrets
      def create: (
        metadata: Cadenya::CreateResourceMetadata,
        spec: Cadenya::WorkspaceSecretSpec,
        ?workspace_id: String,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::WorkspaceSecret

      def retrieve: (
        String id,
        ?workspace_id: String,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::WorkspaceSecret

      def update: (
        String id,
        ?workspace_id: String,
        ?metadata: Cadenya::UpdateResourceMetadata,
        ?spec: Cadenya::WorkspaceSecretSpec,
        ?update_mask: String,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::WorkspaceSecret

      def list: (
        ?workspace_id: String,
        ?cursor: String,
        ?include_info: bool,
        ?labels: String,
        ?limit: Integer,
        ?prefix: String,
        ?query: String,
        ?sort_order: String,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::Internal::CursorPagination[Cadenya::WorkspaceSecret]

      def delete: (
        String id,
        ?workspace_id: String,
        ?request_options: Cadenya::request_opts
      ) -> nil

      def initialize: (client: Cadenya::Client) -> void
    end
  end
end
