module Cadenya
  module Resources
    class Workspaces
      attr_reader members: Cadenya::Resources::Workspaces::Members

      def create: (
        metadata: Cadenya::WorkspaceCreateParams::Metadata,
        spec: Cadenya::WorkspaceSpec,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::Workspace

      def retrieve: (
        String id,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::Workspace

      def list: (
        ?cursor: String,
        ?include_info: bool,
        ?limit: Integer,
        ?sort_order: String,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::Internal::CursorPagination[Cadenya::Workspace]

      def delete: (String id, ?request_options: Cadenya::request_opts) -> nil

      def get_current: (
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::Workspace

      def initialize: (client: Cadenya::Client) -> void
    end
  end
end
