module Cadenya
  module Resources
    class Workspaces
      def list: (
        ?cursor: String,
        ?include_info: bool,
        ?labels: String,
        ?limit: Integer,
        ?sort_order: String,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::Internal::CursorPagination[Cadenya::Workspace]

      def initialize: (client: Cadenya::Client) -> void
    end
  end
end
