module Cadenya
  module Resources
    class WorkspaceAdmin
      attr_reader members: Cadenya::Resources::WorkspaceAdmin::Members

      attr_reader profiles: Cadenya::Resources::WorkspaceAdmin::Profiles

      def create: (
        metadata: Cadenya::WorkspaceAdminCreateParams::Metadata,
        spec: Cadenya::WorkspaceSpec,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::Workspace

      def retrieve: (
        ?workspace_id: String,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::Workspace

      def update: (
        ?workspace_id: String,
        ?metadata: Cadenya::WorkspaceAdminUpdateParams::Metadata,
        ?spec: Cadenya::WorkspaceSpec,
        ?update_mask: String,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::Workspace

      def list: (
        ?cursor: String,
        ?include_archived: bool,
        ?labels: String,
        ?limit: Integer,
        ?request_options: Cadenya::request_opts
      ) -> Cadenya::Internal::CursorPagination[Cadenya::Workspace]

      def archive: (
        ?workspace_id: String,
        ?request_options: Cadenya::request_opts
      ) -> nil

      def initialize: (client: Cadenya::Client) -> void
    end
  end
end
