module Cadenya
  module Models
    module ToolSets
      type config_http =
        {
          request_method: Cadenya::Models::ToolSets::ConfigHTTP::request_method,
          headers: ::Hash[Symbol, String],
          path: String,
          query: String,
          request_body_content_type: String,
          request_body_template: String,
          tool_name: String
        }

      class ConfigHTTP < Cadenya::Internal::Type::BaseModel
        attr_accessor request_method: Cadenya::Models::ToolSets::ConfigHTTP::request_method

        attr_reader headers: ::Hash[Symbol, String]?

        def headers=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

        attr_reader path: String?

        def path=: (String) -> String

        attr_reader query: String?

        def query=: (String) -> String

        attr_reader request_body_content_type: String?

        def request_body_content_type=: (String) -> String

        attr_reader request_body_template: String?

        def request_body_template=: (String) -> String

        attr_reader tool_name: String?

        def tool_name=: (String) -> String

        def initialize: (
          request_method: Cadenya::Models::ToolSets::ConfigHTTP::request_method,
          ?headers: ::Hash[Symbol, String],
          ?path: String,
          ?query: String,
          ?request_body_content_type: String,
          ?request_body_template: String,
          ?tool_name: String
        ) -> void

        def to_hash: -> {
          request_method: Cadenya::Models::ToolSets::ConfigHTTP::request_method,
          headers: ::Hash[Symbol, String],
          path: String,
          query: String,
          request_body_content_type: String,
          request_body_template: String,
          tool_name: String
        }

        type request_method =
          :HTTP_METHOD_UNSPECIFIED | :GET | :POST | :PUT | :PATCH | :DELETE

        module RequestMethod
          extend Cadenya::Internal::Type::Enum

          HTTP_METHOD_UNSPECIFIED: :HTTP_METHOD_UNSPECIFIED
          GET: :GET
          POST: :POST
          PUT: :PUT
          PATCH: :PATCH
          DELETE: :DELETE

          def self?.values: -> ::Array[Cadenya::Models::ToolSets::ConfigHTTP::request_method]
        end
      end
    end
  end
end
