module Cadenya
  module Models
    module ToolSets
      type config_openapi = { method_: String, path: String }

      class ConfigOpenAPI < Cadenya::Internal::Type::BaseModel
        attr_reader method_: String?

        def method_=: (String) -> String

        attr_reader path: String?

        def path=: (String) -> String

        def initialize: (?method_: String, ?path: String) -> void

        def to_hash: -> { method_: String, path: String }
      end
    end
  end
end
