module Cadenya
  module Models
    module ToolSets
      type config_mcp = { annotations: Cadenya::ToolSets::MCPAnnotations }

      class ConfigMCP < Cadenya::Internal::Type::BaseModel
        attr_reader annotations: Cadenya::ToolSets::MCPAnnotations?

        def annotations=: (
          Cadenya::ToolSets::MCPAnnotations
        ) -> Cadenya::ToolSets::MCPAnnotations

        def initialize: (
          ?annotations: Cadenya::ToolSets::MCPAnnotations
        ) -> void

        def to_hash: -> { annotations: Cadenya::ToolSets::MCPAnnotations }
      end
    end
  end
end
