module Cadenya
  module Models
    module ToolSets
      type mcp_annotations =
        {
          destructive_hint: bool,
          idempotent_hint: bool,
          open_world_hint: bool,
          read_only_hint: bool,
          title: String
        }

      class McpAnnotations < Cadenya::Internal::Type::BaseModel
        attr_reader destructive_hint: bool?

        def destructive_hint=: (bool) -> bool

        attr_reader idempotent_hint: bool?

        def idempotent_hint=: (bool) -> bool

        attr_reader open_world_hint: bool?

        def open_world_hint=: (bool) -> bool

        attr_reader read_only_hint: bool?

        def read_only_hint=: (bool) -> bool

        attr_reader title: String?

        def title=: (String) -> String

        def initialize: (
          ?destructive_hint: bool,
          ?idempotent_hint: bool,
          ?open_world_hint: bool,
          ?read_only_hint: bool,
          ?title: String
        ) -> void

        def to_hash: -> {
          destructive_hint: bool,
          idempotent_hint: bool,
          open_world_hint: bool,
          read_only_hint: bool,
          title: String
        }
      end
    end
  end
end
