module Cadenya
  module Models
    module ToolSets
      type tool_spec_config_bare =
        {
          bare: Cadenya::ToolSets::ConfigBare,
          type: Cadenya::Models::ToolSets::ToolSpecConfigBare::type_
        }

      class ToolSpecConfigBare < Cadenya::Internal::Type::BaseModel
        attr_accessor bare: Cadenya::ToolSets::ConfigBare

        attr_accessor type: Cadenya::Models::ToolSets::ToolSpecConfigBare::type_

        def initialize: (
          bare: Cadenya::ToolSets::ConfigBare,
          type: Cadenya::Models::ToolSets::ToolSpecConfigBare::type_
        ) -> void

        def to_hash: -> {
          bare: Cadenya::ToolSets::ConfigBare,
          type: Cadenya::Models::ToolSets::ToolSpecConfigBare::type_
        }

        type type_ = :bare

        module Type
          extend Cadenya::Internal::Type::Enum

          BARE: :bare

          def self?.values: -> ::Array[Cadenya::Models::ToolSets::ToolSpecConfigBare::type_]
        end
      end
    end
  end
end
