module Cadenya
  module Models
    module ToolSets
      type tool_spec_config_mcp =
        {
          mcp: Cadenya::ToolSets::ConfigMCP,
          type: Cadenya::Models::ToolSets::ToolSpecConfigMCP::type_
        }

      class ToolSpecConfigMCP < Cadenya::Internal::Type::BaseModel
        attr_accessor mcp: Cadenya::ToolSets::ConfigMCP

        attr_accessor type: Cadenya::Models::ToolSets::ToolSpecConfigMCP::type_

        def initialize: (
          mcp: Cadenya::ToolSets::ConfigMCP,
          type: Cadenya::Models::ToolSets::ToolSpecConfigMCP::type_
        ) -> void

        def to_hash: -> {
          mcp: Cadenya::ToolSets::ConfigMCP,
          type: Cadenya::Models::ToolSets::ToolSpecConfigMCP::type_
        }

        type type_ = :mcp

        module Type
          extend Cadenya::Internal::Type::Enum

          MCP: :mcp

          def self?.values: -> ::Array[Cadenya::Models::ToolSets::ToolSpecConfigMCP::type_]
        end
      end
    end
  end
end
