module Cadenya
  module Models
    module ToolSets
      type tool_spec_config =
        Cadenya::ToolSets::ToolSpecConfigHTTP
        | Cadenya::ToolSets::ToolSpecConfigMCP
        | Cadenya::ToolSets::ToolSpecConfigOpenAPI
        | Cadenya::ToolSets::ToolSpecConfigBare

      module ToolSpecConfig
        extend Cadenya::Internal::Type::Union

        def self?.variants: -> ::Array[Cadenya::Models::ToolSets::tool_spec_config]
      end
    end
  end
end
