module Cadenya
  module Models
    class ToolSetSecret = ToolSets::ToolSetSecret

    module ToolSets
      type tool_set_secret =
        {
          metadata: Cadenya::ResourceMetadata,
          spec: Cadenya::ToolSets::ToolSetSecretSpec,
          info: Cadenya::ToolSets::ToolSetSecretInfo
        }

      class ToolSetSecret < Cadenya::Internal::Type::BaseModel
        attr_accessor metadata: Cadenya::ResourceMetadata

        attr_accessor spec: Cadenya::ToolSets::ToolSetSecretSpec

        attr_reader info: Cadenya::ToolSets::ToolSetSecretInfo?

        def info=: (
          Cadenya::ToolSets::ToolSetSecretInfo
        ) -> Cadenya::ToolSets::ToolSetSecretInfo

        def initialize: (
          metadata: Cadenya::ResourceMetadata,
          spec: Cadenya::ToolSets::ToolSetSecretSpec,
          ?info: Cadenya::ToolSets::ToolSetSecretInfo
        ) -> void

        def to_hash: -> {
          metadata: Cadenya::ResourceMetadata,
          spec: Cadenya::ToolSets::ToolSetSecretSpec,
          info: Cadenya::ToolSets::ToolSetSecretInfo
        }
      end
    end
  end
end
