module Cadenya
  module Models
    module ToolSets
      type tool_create_params =
        {
          workspace_id: String,
          tool_set_id: String,
          metadata: Cadenya::CreateResourceMetadata,
          spec: Cadenya::ToolSets::ToolSpec
        }
        & Cadenya::Internal::Type::request_parameters

      class ToolCreateParams < Cadenya::Internal::Type::BaseModel
        extend Cadenya::Internal::Type::RequestParameters::Converter
        include Cadenya::Internal::Type::RequestParameters

        attr_reader workspace_id: String?

        def workspace_id=: (String) -> String

        attr_accessor tool_set_id: String

        attr_accessor metadata: Cadenya::CreateResourceMetadata

        attr_accessor spec: Cadenya::ToolSets::ToolSpec

        def initialize: (
          tool_set_id: String,
          metadata: Cadenya::CreateResourceMetadata,
          spec: Cadenya::ToolSets::ToolSpec,
          ?workspace_id: String,
          ?request_options: Cadenya::request_opts
        ) -> void

        def to_hash: -> {
          workspace_id: String,
          tool_set_id: String,
          metadata: Cadenya::CreateResourceMetadata,
          spec: Cadenya::ToolSets::ToolSpec,
          request_options: Cadenya::RequestOptions
        }
      end
    end
  end
end
