module Cadenya
  module Models
    class ToolSetSecretSpec = ToolSets::ToolSetSecretSpec

    module ToolSets
      type tool_set_secret_spec = { value: String }

      class ToolSetSecretSpec < Cadenya::Internal::Type::BaseModel
        attr_reader value: String?

        def value=: (String) -> String

        def initialize: (?value: String) -> void

        def to_hash: -> { value: String }
      end
    end
  end
end
