module Cadenya
  module Models
    module ToolSets
      type tool_spec =
        {
          config: Cadenya::Models::ToolSets::tool_spec_config,
          description: String,
          parameters: ::Hash[Symbol, top],
          requires_approval: bool,
          llm_tool_name: String
        }

      class ToolSpec < Cadenya::Internal::Type::BaseModel
        attr_accessor config: Cadenya::Models::ToolSets::tool_spec_config

        attr_accessor description: String

        attr_accessor parameters: ::Hash[Symbol, top]

        attr_accessor requires_approval: bool

        attr_reader llm_tool_name: String?

        def llm_tool_name=: (String) -> String

        def initialize: (
          config: Cadenya::Models::ToolSets::tool_spec_config,
          description: String,
          parameters: ::Hash[Symbol, top],
          requires_approval: bool,
          ?llm_tool_name: String
        ) -> void

        def to_hash: -> {
          config: Cadenya::Models::ToolSets::tool_spec_config,
          description: String,
          parameters: ::Hash[Symbol, top],
          requires_approval: bool,
          llm_tool_name: String
        }
      end
    end
  end
end
