module Cadenya
  module Models
    module ToolSets
      type tool_list_params =
        {
          workspace_id: String,
          tool_set_id: String,
          cursor: String,
          include_info: bool,
          labels: String,
          limit: Integer,
          names: ::Array[String],
          prefix: String,
          query: String,
          requires_approval: bool,
          sort_order: String,
          states: ::Array[Cadenya::Models::ToolSets::ToolListParams::state]
        }
        & Cadenya::Internal::Type::request_parameters

      class ToolListParams < Cadenya::Internal::Type::BaseModel
        extend Cadenya::Internal::Type::RequestParameters::Converter
        include Cadenya::Internal::Type::RequestParameters

        attr_reader workspace_id: String?

        def workspace_id=: (String) -> String

        attr_accessor tool_set_id: String

        attr_reader cursor: String?

        def cursor=: (String) -> String

        attr_reader include_info: bool?

        def include_info=: (bool) -> bool

        attr_reader labels: String?

        def labels=: (String) -> String

        attr_reader limit: Integer?

        def limit=: (Integer) -> Integer

        attr_reader names: ::Array[String]?

        def names=: (::Array[String]) -> ::Array[String]

        attr_reader prefix: String?

        def prefix=: (String) -> String

        attr_reader query: String?

        def query=: (String) -> String

        attr_reader requires_approval: bool?

        def requires_approval=: (bool) -> bool

        attr_reader sort_order: String?

        def sort_order=: (String) -> String

        attr_reader states: ::Array[Cadenya::Models::ToolSets::ToolListParams::state]?

        def states=: (
          ::Array[Cadenya::Models::ToolSets::ToolListParams::state]
        ) -> ::Array[Cadenya::Models::ToolSets::ToolListParams::state]

        def initialize: (
          tool_set_id: String,
          ?workspace_id: String,
          ?cursor: String,
          ?include_info: bool,
          ?labels: String,
          ?limit: Integer,
          ?names: ::Array[String],
          ?prefix: String,
          ?query: String,
          ?requires_approval: bool,
          ?sort_order: String,
          ?states: ::Array[Cadenya::Models::ToolSets::ToolListParams::state],
          ?request_options: Cadenya::request_opts
        ) -> void

        def to_hash: -> {
          workspace_id: String,
          tool_set_id: String,
          cursor: String,
          include_info: bool,
          labels: String,
          limit: Integer,
          names: ::Array[String],
          prefix: String,
          query: String,
          requires_approval: bool,
          sort_order: String,
          states: ::Array[Cadenya::Models::ToolSets::ToolListParams::state],
          request_options: Cadenya::RequestOptions
        }

        type state =
          :STATE_UNSPECIFIED
          | :STATE_AVAILABLE
          | :STATE_OMITTED
          | :STATE_ARCHIVED

        module State
          extend Cadenya::Internal::Type::Enum

          STATE_UNSPECIFIED: :STATE_UNSPECIFIED
          STATE_AVAILABLE: :STATE_AVAILABLE
          STATE_OMITTED: :STATE_OMITTED
          STATE_ARCHIVED: :STATE_ARCHIVED

          def self?.values: -> ::Array[Cadenya::Models::ToolSets::ToolListParams::state]
        end
      end
    end
  end
end
