module Cadenya
  module Models
    module ToolSets
      type tool =
        {
          metadata: Cadenya::ResourceMetadata,
          spec: Cadenya::ToolSets::ToolSpec,
          state: Cadenya::Models::ToolSets::Tool::state,
          info: Cadenya::ToolSets::ToolInfo
        }

      class Tool < Cadenya::Internal::Type::BaseModel
        attr_accessor metadata: Cadenya::ResourceMetadata

        attr_accessor spec: Cadenya::ToolSets::ToolSpec

        attr_reader info: Cadenya::ToolSets::ToolInfo?

        def info=: (Cadenya::ToolSets::ToolInfo) -> Cadenya::ToolSets::ToolInfo

        attr_accessor state: Cadenya::Models::ToolSets::Tool::state

        def initialize: (
          metadata: Cadenya::ResourceMetadata,
          spec: Cadenya::ToolSets::ToolSpec,
          state: Cadenya::Models::ToolSets::Tool::state,
          ?info: Cadenya::ToolSets::ToolInfo
        ) -> void

        def to_hash: -> {
          metadata: Cadenya::ResourceMetadata,
          spec: Cadenya::ToolSets::ToolSpec,
          state: Cadenya::Models::ToolSets::Tool::state,
          info: Cadenya::ToolSets::ToolInfo
        }

        type state =
          :STATE_UNSPECIFIED
          | :STATE_AVAILABLE
          | :STATE_OMITTED
          | :STATE_ARCHIVED

        module State
          extend Cadenya::Internal::Type::Enum

          STATE_UNSPECIFIED: :STATE_UNSPECIFIED
          STATE_AVAILABLE: :STATE_AVAILABLE
          STATE_OMITTED: :STATE_OMITTED
          STATE_ARCHIVED: :STATE_ARCHIVED

          def self?.values: -> ::Array[Cadenya::Models::ToolSets::Tool::state]
        end
      end
    end
  end
end
