module Cadenya
  module Models
    module ToolSets
      type tool_spec_config_http =
        {
          http: Cadenya::ToolSets::ConfigHTTP,
          type: Cadenya::Models::ToolSets::ToolSpecConfigHTTP::type_
        }

      class ToolSpecConfigHTTP < Cadenya::Internal::Type::BaseModel
        attr_accessor http: Cadenya::ToolSets::ConfigHTTP

        attr_accessor type: Cadenya::Models::ToolSets::ToolSpecConfigHTTP::type_

        def initialize: (
          http: Cadenya::ToolSets::ConfigHTTP,
          type: Cadenya::Models::ToolSets::ToolSpecConfigHTTP::type_
        ) -> void

        def to_hash: -> {
          http: Cadenya::ToolSets::ConfigHTTP,
          type: Cadenya::Models::ToolSets::ToolSpecConfigHTTP::type_
        }

        type type_ = :http

        module Type
          extend Cadenya::Internal::Type::Enum

          HTTP: :http

          def self?.values: -> ::Array[Cadenya::Models::ToolSets::ToolSpecConfigHTTP::type_]
        end
      end
    end
  end
end
