module Cadenya
  module Models
    module ToolSets
      type tool_spec =
        {
          config: Cadenya::ToolSets::ToolSpecConfig,
          description: String,
          parameters: ::Hash[Symbol, top],
          requires_approval: bool
        }

      class ToolSpec < Cadenya::Internal::Type::BaseModel
        attr_accessor config: Cadenya::ToolSets::ToolSpecConfig

        attr_accessor description: String

        attr_accessor parameters: ::Hash[Symbol, top]

        attr_accessor requires_approval: bool

        def initialize: (
          config: Cadenya::ToolSets::ToolSpecConfig,
          description: String,
          parameters: ::Hash[Symbol, top],
          requires_approval: bool
        ) -> void

        def to_hash: -> {
          config: Cadenya::ToolSets::ToolSpecConfig,
          description: String,
          parameters: ::Hash[Symbol, top],
          requires_approval: bool
        }
      end
    end
  end
end
