# frozen_string_literal: true

# Code generated by redwood. DO NOT EDIT.

module Cadenya
  module Resources
    class Accounts
      def initialize(core)
        @core = core
      end

      # Retrieves the current account for the token accessing the API
      def retrieve(request_options: nil)
        _path = "/v1/account"
        _data = @core.request(:get, _path, request_options: request_options)
        Types::Account.from_json(_data)
      end

      # Rotates the challenge token for the account
      def rotate_challenge_token(request_options: nil)
        _path = "/v1/account:rotateChallengeToken"
        _data = @core.request(:post, _path, request_options: request_options)
        Types::RotateChallengeTokenResponse.from_json(_data)
      end

      # Rotates the webhook signing key for the account
      def rotate_webhook_signing_key(request_options: nil)
        _path = "/v1/account:rotateWebhookSigningKey"
        _data = @core.request(:post, _path, request_options: request_options)
        Types::RotateWebhookEventsHmacSecretResponse.from_json(_data)
      end
    end
  end
end
