# frozen_string_literal: true

# Code generated by redwood. DO NOT EDIT.

module Cadenya
  module Resources
    class Agents
      attr_reader :schedules, :variations

      def initialize(core)
        @core = core
        @schedules = AgentSchedules.new(core)
        @variations = AgentVariations.new(core)
      end

      # List agents
      def list(workspace_id: nil, limit: nil, cursor: nil, prefix: nil, query: nil, state: nil, variation_selection_mode: nil, labels: nil, sort_order: nil, include_info: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/agents"
        _query = {
          "limit" => limit,
          "cursor" => cursor,
          "prefix" => prefix,
          "query" => query,
          "state" => state,
          "variationSelectionMode" => variation_selection_mode,
          "labels" => labels,
          "sortOrder" => sort_order,
          "includeInfo" => include_info,
        }
        _data = @core.request(:get, _path, query: _query, request_options: request_options) || {}
        _items = (_data["items"] || []).map { |item| Types::Agent.from_json(item) }
        _next_cursor = (((_data)["pagination"] || {}))["nextCursor"].to_s
        Page.new(_items, _next_cursor) do |_c|
          list(workspace_id: workspace_id, limit: limit, cursor: _c, prefix: prefix, query: query, state: state, variation_selection_mode: variation_selection_mode, labels: labels, sort_order: sort_order, include_info: include_info, request_options: request_options)
        end
      end

      # Create a new agent
      def create(metadata:, spec:, workspace_id: nil, default_variation: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/agents"
        _body = {
          "metadata" => metadata.nil? ? nil : (->(_v) { Types.encode_CreateResourceMetadata(_v) }).call(metadata),
          "spec" => spec.nil? ? nil : (->(_v) { Types.encode_AgentSpec(_v) }).call(spec),
          "defaultVariation" => default_variation.nil? ? nil : (->(_v) { Types.encode_CreateAgentVariationRequest(_v) }).call(default_variation),
        }.reject { |_k, v| v.nil? }
        _data = @core.request(:post, _path, body: _body, request_options: request_options)
        Types::Agent.from_json(_data)
      end

      # List feedback for an agent
      def list_feedback(agent_id, workspace_id: nil, limit: nil, cursor: nil, query: nil, sentiment: nil, agent_variation_id: nil, created_after: nil, created_before: nil, labels: nil, include_info: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/agents/#{Util.path_param('agentId', agent_id)}/feedback"
        _query = {
          "limit" => limit,
          "cursor" => cursor,
          "query" => query,
          "sentiment" => sentiment,
          "agentVariationId" => agent_variation_id,
          "createdAfter" => created_after,
          "createdBefore" => created_before,
          "labels" => labels,
          "includeInfo" => include_info,
        }
        _data = @core.request(:get, _path, query: _query, request_options: request_options) || {}
        _items = (_data["items"] || []).map { |item| Types::ObjectiveFeedback.from_json(item) }
        _next_cursor = (((_data)["pagination"] || {}))["nextCursor"].to_s
        Page.new(_items, _next_cursor) do |_c|
          list_feedback(agent_id, workspace_id: workspace_id, limit: limit, cursor: _c, query: query, sentiment: sentiment, agent_variation_id: agent_variation_id, created_after: created_after, created_before: created_before, labels: labels, include_info: include_info, request_options: request_options)
        end
      end

      # List webhook deliveries
      def list_webhook_deliveries(agent_id, workspace_id: nil, cursor: nil, limit: nil, objective_id: nil, event_type: nil, labels: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/agents/#{Util.path_param('agentId', agent_id)}/webhook_deliveries"
        _query = {
          "cursor" => cursor,
          "limit" => limit,
          "objectiveId" => objective_id,
          "eventType" => event_type,
          "labels" => labels,
        }
        _data = @core.request(:get, _path, query: _query, request_options: request_options) || {}
        _items = (_data["items"] || []).map { |item| Types::WebhookDelivery.from_json(item) }
        _next_cursor = (((_data)["pagination"] || {}))["nextCursor"].to_s
        Page.new(_items, _next_cursor) do |_c|
          list_webhook_deliveries(agent_id, workspace_id: workspace_id, cursor: _c, limit: limit, objective_id: objective_id, event_type: event_type, labels: labels, request_options: request_options)
        end
      end

      # Get an agent by ID
      def retrieve(id, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/agents/#{Util.path_param('id', id)}"
        _data = @core.request(:get, _path, request_options: request_options)
        Types::Agent.from_json(_data)
      end

      # Delete an agent
      def delete(id, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/agents/#{Util.path_param('id', id)}"
        @core.request(:delete, _path, expects_body: false, request_options: request_options)
        nil
      end

      # Update an agent
      def update(id, workspace_id: nil, metadata: nil, spec: nil, update_mask: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/agents/#{Util.path_param('id', id)}"
        _body = {
          "metadata" => metadata.nil? ? nil : (->(_v) { Types.encode_UpdateResourceMetadata(_v) }).call(metadata),
          "spec" => spec.nil? ? nil : (->(_v) { Types.encode_AgentSpec(_v) }).call(spec),
          "updateMask" => update_mask,
        }.reject { |_k, v| v.nil? }
        _data = @core.request(:patch, _path, body: _body, request_options: request_options)
        Types::Agent.from_json(_data)
      end

      # Archive an agent
      def archive(id, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/agents/#{Util.path_param('id', id)}:archive"
        _data = @core.request(:post, _path, request_options: request_options)
        Types::Agent.from_json(_data)
      end

      # Publish an agent
      def publish(id, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/agents/#{Util.path_param('id', id)}:publish"
        _data = @core.request(:post, _path, request_options: request_options)
        Types::Agent.from_json(_data)
      end

      # Unarchive an agent
      def unarchive(id, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/agents/#{Util.path_param('id', id)}:unarchive"
        _data = @core.request(:post, _path, request_options: request_options)
        Types::Agent.from_json(_data)
      end

      # Unpublish an agent
      def unpublish(id, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/agents/#{Util.path_param('id', id)}:unpublish"
        _data = @core.request(:post, _path, request_options: request_options)
        Types::Agent.from_json(_data)
      end
    end
  end
end
