# frozen_string_literal: true

# Code generated by redwood. DO NOT EDIT.

module Cadenya
  module Resources
    class AgentVariations
      def initialize(core)
        @core = core
      end

      # List variations
      def list(agent_id, workspace_id: nil, limit: nil, cursor: nil, sort_order: nil, include_info: nil, labels: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/agents/#{Util.path_param('agentId', agent_id)}/variations"
        _query = {
          "limit" => limit,
          "cursor" => cursor,
          "sortOrder" => sort_order,
          "includeInfo" => include_info,
          "labels" => labels,
        }
        _data = @core.request(:get, _path, query: _query, request_options: request_options) || {}
        _items = (_data["items"] || []).map { |item| Types::AgentVariation.from_json(item) }
        _next_cursor = (((_data)["pagination"] || {}))["nextCursor"].to_s
        Page.new(_items, _next_cursor) do |_c|
          list(agent_id, workspace_id: workspace_id, limit: limit, cursor: _c, sort_order: sort_order, include_info: include_info, labels: labels, request_options: request_options)
        end
      end

      # Create a new variation
      def create(agent_id, metadata:, spec:, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/agents/#{Util.path_param('agentId', agent_id)}/variations"
        _body = {
          "metadata" => metadata.nil? ? nil : (->(_v) { Types.encode_CreateResourceMetadata(_v) }).call(metadata),
          "spec" => spec.nil? ? nil : (->(_v) { Types.encode_AgentVariationSpec(_v) }).call(spec),
        }.reject { |_k, v| v.nil? }
        _data = @core.request(:post, _path, body: _body, request_options: request_options)
        Types::AgentVariation.from_json(_data)
      end

      # Get a variation by ID
      def retrieve(agent_id, id, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/agents/#{Util.path_param('agentId', agent_id)}/variations/#{Util.path_param('id', id)}"
        _data = @core.request(:get, _path, request_options: request_options)
        Types::AgentVariation.from_json(_data)
      end

      # Delete a variation
      def delete(agent_id, id, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/agents/#{Util.path_param('agentId', agent_id)}/variations/#{Util.path_param('id', id)}"
        @core.request(:delete, _path, expects_body: false, request_options: request_options)
        nil
      end

      # Update a variation
      def update(agent_id, id, workspace_id: nil, metadata: nil, spec: nil, update_mask: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/agents/#{Util.path_param('agentId', agent_id)}/variations/#{Util.path_param('id', id)}"
        _body = {
          "metadata" => metadata.nil? ? nil : (->(_v) { Types.encode_UpdateResourceMetadata(_v) }).call(metadata),
          "spec" => spec.nil? ? nil : (->(_v) { Types.encode_AgentVariationSpec(_v) }).call(spec),
          "updateMask" => update_mask,
        }.reject { |_k, v| v.nil? }
        _data = @core.request(:patch, _path, body: _body, request_options: request_options)
        Types::AgentVariation.from_json(_data)
      end

      # Add an assignment to a variation
      def add_assignment(agent_id, variation_id, body:, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/agents/#{Util.path_param('agentId', agent_id)}/variations/#{Util.path_param('variationId', variation_id)}/assignments"
        _data = @core.request(:post, _path, body: (->(_v) { Types.encode_AddAgentVariationAssignmentRequest(_v) }).call(body), request_options: request_options)
        Types.decode_VariationAssignment(_data)
      end

      # Remove an assignment from a variation
      def remove_assignment(agent_id, variation_id, id, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/agents/#{Util.path_param('agentId', agent_id)}/variations/#{Util.path_param('variationId', variation_id)}/assignments/#{Util.path_param('id', id)}"
        @core.request(:delete, _path, expects_body: false, request_options: request_options)
        nil
      end

      # Attach a memory layer to a variation
      def add_memory_layer(agent_id, variation_id, memory_layer_id:, workspace_id: nil, position: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/agents/#{Util.path_param('agentId', agent_id)}/variations/#{Util.path_param('variationId', variation_id)}/memory_layer_assignments"
        _body = {
          "memoryLayerId" => memory_layer_id,
          "position" => position,
        }.reject { |_k, v| v.nil? }
        _data = @core.request(:post, _path, body: _body, request_options: request_options)
        Types::VariationMemoryLayerAssignment.from_json(_data)
      end

      # Remove a memory layer assignment from a variation
      def remove_memory_layer(agent_id, variation_id, id, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/agents/#{Util.path_param('agentId', agent_id)}/variations/#{Util.path_param('variationId', variation_id)}/memory_layer_assignments/#{Util.path_param('id', id)}"
        @core.request(:delete, _path, expects_body: false, request_options: request_options)
        nil
      end

      # Update a variation's memory layer assignment
      def update_memory_layer(agent_id, variation_id, id, workspace_id: nil, position: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/agents/#{Util.path_param('agentId', agent_id)}/variations/#{Util.path_param('variationId', variation_id)}/memory_layer_assignments/#{Util.path_param('id', id)}"
        _body = {
          "position" => position,
        }.reject { |_k, v| v.nil? }
        _data = @core.request(:patch, _path, body: _body, request_options: request_options)
        Types::VariationMemoryLayerAssignment.from_json(_data)
      end
    end
  end
end
