# frozen_string_literal: true

# Code generated by redwood. DO NOT EDIT.

module Cadenya
  module Resources
    class ApiKeys
      def initialize(core)
        @core = core
      end

      # Get the global API key
      def retrieve_global(request_options: nil)
        _path = "/v1/account/global_api_key"
        _data = @core.request(:get, _path, request_options: request_options)
        Types::APIKey.from_json(_data)
      end

      # Disable the global API key
      def disable_global(request_options: nil)
        _path = "/v1/account/global_api_key:disable"
        _data = @core.request(:post, _path, request_options: request_options)
        Types::APIKey.from_json(_data)
      end

      # Enable the global API key
      def enable_global(request_options: nil)
        _path = "/v1/account/global_api_key:enable"
        _data = @core.request(:post, _path, request_options: request_options)
        Types::APIKey.from_json(_data)
      end

      # Rotate the global API key
      def rotate_global(request_options: nil)
        _path = "/v1/account/global_api_key:rotate"
        _data = @core.request(:post, _path, request_options: request_options)
        Types::APIKey.from_json(_data)
      end

      # List API keys
      def list(workspace_id: nil, limit: nil, cursor: nil, prefix: nil, query: nil, labels: nil, sort_order: nil, include_info: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/api_keys"
        _query = {
          "limit" => limit,
          "cursor" => cursor,
          "prefix" => prefix,
          "query" => query,
          "labels" => labels,
          "sortOrder" => sort_order,
          "includeInfo" => include_info,
        }
        _data = @core.request(:get, _path, query: _query, request_options: request_options) || {}
        _items = (_data["items"] || []).map { |item| Types::APIKey.from_json(item) }
        _next_cursor = (((_data)["pagination"] || {}))["nextCursor"].to_s
        Page.new(_items, _next_cursor) do |_c|
          list(workspace_id: workspace_id, limit: limit, cursor: _c, prefix: prefix, query: query, labels: labels, sort_order: sort_order, include_info: include_info, request_options: request_options)
        end
      end

      # Create a new API key
      def create(metadata:, spec:, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/api_keys"
        _body = {
          "metadata" => metadata.nil? ? nil : (->(_v) { Types.encode_CreateAccountResourceMetadata(_v) }).call(metadata),
          "spec" => spec.nil? ? nil : (->(_v) { Types.encode_APIKeySpec(_v) }).call(spec),
        }.reject { |_k, v| v.nil? }
        _data = @core.request(:post, _path, body: _body, request_options: request_options)
        Types::APIKey.from_json(_data)
      end

      # Get an API key by ID
      def retrieve(id, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/api_keys/#{Util.path_param('id', id)}"
        _data = @core.request(:get, _path, request_options: request_options)
        Types::APIKey.from_json(_data)
      end

      # Delete an API key
      def delete(id, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/api_keys/#{Util.path_param('id', id)}"
        @core.request(:delete, _path, expects_body: false, request_options: request_options)
        nil
      end

      # Update an API key
      def update(id, workspace_id: nil, metadata: nil, spec: nil, update_mask: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/api_keys/#{Util.path_param('id', id)}"
        _body = {
          "metadata" => metadata.nil? ? nil : (->(_v) { Types.encode_UpdateAccountResourceMetadata(_v) }).call(metadata),
          "spec" => spec.nil? ? nil : (->(_v) { Types.encode_APIKeySpec(_v) }).call(spec),
          "updateMask" => update_mask,
        }.reject { |_k, v| v.nil? }
        _data = @core.request(:patch, _path, body: _body, request_options: request_options)
        Types::APIKey.from_json(_data)
      end

      # Disable an API key
      def disable(id, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/api_keys/#{Util.path_param('id', id)}:disable"
        _data = @core.request(:post, _path, request_options: request_options)
        Types::APIKey.from_json(_data)
      end

      # Enable an API key
      def enable(id, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/api_keys/#{Util.path_param('id', id)}:enable"
        _data = @core.request(:post, _path, request_options: request_options)
        Types::APIKey.from_json(_data)
      end

      # Rotate an API key
      def rotate(id, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/api_keys/#{Util.path_param('id', id)}:rotate"
        _data = @core.request(:post, _path, request_options: request_options)
        Types::APIKey.from_json(_data)
      end
    end
  end
end
