# frozen_string_literal: true

# Code generated by redwood. DO NOT EDIT.

module Cadenya
  module Resources
    class Models
      def initialize(core)
        @core = core
      end

      # List models
      def list(workspace_id: nil, limit: nil, cursor: nil, prefix: nil, query: nil, state: nil, ai_provider_key_id: nil, is_assigned: nil, labels: nil, sort_order: nil, include_info: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/models"
        _query = {
          "limit" => limit,
          "cursor" => cursor,
          "prefix" => prefix,
          "query" => query,
          "state" => state,
          "aiProviderKeyId" => ai_provider_key_id,
          "isAssigned" => is_assigned,
          "labels" => labels,
          "sortOrder" => sort_order,
          "includeInfo" => include_info,
        }
        _data = @core.request(:get, _path, query: _query, request_options: request_options) || {}
        _items = (_data["items"] || []).map { |item| Types::Model.from_json(item) }
        _next_cursor = (((_data)["pagination"] || {}))["nextCursor"].to_s
        Page.new(_items, _next_cursor) do |_c|
          list(workspace_id: workspace_id, limit: limit, cursor: _c, prefix: prefix, query: query, state: state, ai_provider_key_id: ai_provider_key_id, is_assigned: is_assigned, labels: labels, sort_order: sort_order, include_info: include_info, request_options: request_options)
        end
      end

      # Get a model by ID
      def retrieve(id, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/models/#{Util.path_param('id', id)}"
        _data = @core.request(:get, _path, request_options: request_options)
        Types::Model.from_json(_data)
      end

      # Disable a model
      def disable(id, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/models/#{Util.path_param('id', id)}:disable"
        _data = @core.request(:post, _path, request_options: request_options)
        Types::Model.from_json(_data)
      end

      # Enable a model
      def enable(id, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/models/#{Util.path_param('id', id)}:enable"
        _data = @core.request(:post, _path, request_options: request_options)
        Types::Model.from_json(_data)
      end

      # Swap models on agent variations
      def swap_on_variations(workspace_id: nil, model_swaps: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/models:swapModelOnVariations"
        _body = {
          "modelSwaps" => model_swaps.nil? ? nil : (->(_v) { _v.is_a?(Array) ? _v.map { |_i| (->(_v) { Types.encode_SwapModelOnVariationsRequest_ModelSwap(_v) }).call(_i) } : _v }).call(model_swaps),
        }.reject { |_k, v| v.nil? }
        @core.request(:post, _path, body: _body, expects_body: false, request_options: request_options)
        nil
      end
    end
  end
end
