# frozen_string_literal: true

# Code generated by redwood. DO NOT EDIT.

module Cadenya
  module Resources
    class Objectives
      def initialize(core)
        @core = core
      end

      # List objectives
      def list(workspace_id: nil, limit: nil, cursor: nil, agent_id: nil, parent_objective_id: nil, state: nil, profile_id: nil, sort_order: nil, include_info: nil, agent_schedule_id: nil, labels: nil, tenant_id: nil, subject_id: nil, widget_id: nil, widget_session_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/objectives"
        _query = {
          "limit" => limit,
          "cursor" => cursor,
          "agentId" => agent_id,
          "parentObjectiveId" => parent_objective_id,
          "state" => state,
          "profileId" => profile_id,
          "sortOrder" => sort_order,
          "includeInfo" => include_info,
          "agentScheduleId" => agent_schedule_id,
          "labels" => labels,
          "tenantId" => tenant_id,
          "subjectId" => subject_id,
          "widgetId" => widget_id,
          "widgetSessionId" => widget_session_id,
        }
        _data = @core.request(:get, _path, query: _query, request_options: request_options) || {}
        _items = (_data["items"] || []).map { |item| Types::Objective.from_json(item) }
        _next_cursor = (((_data)["pagination"] || {}))["nextCursor"].to_s
        Page.new(_items, _next_cursor) do |_c|
          list(workspace_id: workspace_id, limit: limit, cursor: _c, agent_id: agent_id, parent_objective_id: parent_objective_id, state: state, profile_id: profile_id, sort_order: sort_order, include_info: include_info, agent_schedule_id: agent_schedule_id, labels: labels, tenant_id: tenant_id, subject_id: subject_id, widget_id: widget_id, widget_session_id: widget_session_id, request_options: request_options)
        end
      end

      # Create a new objective
      def create(agent_id:, system_prompt_data:, workspace_id: nil, variation_id: nil, metadata: nil, first_user_message: nil, secrets: nil, memory_cascade: nil, first_user_message_data: nil, episodic_memory: nil, tenant: nil, subject: nil, pinned_parameters: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/objectives"
        _body = {
          "agentId" => agent_id,
          "variationId" => variation_id,
          "metadata" => metadata.nil? ? nil : (->(_v) { Types.encode_CreateOperationMetadata(_v) }).call(metadata),
          "systemPromptData" => system_prompt_data,
          "firstUserMessage" => first_user_message,
          "secrets" => secrets.nil? ? nil : (->(_v) { _v.is_a?(Array) ? _v.map { |_i| (->(_v) { Types.encode_CreateObjectiveRequest_Secret(_v) }).call(_i) } : _v }).call(secrets),
          "memoryCascade" => memory_cascade.nil? ? nil : (->(_v) { _v.is_a?(Array) ? _v.map { |_i| (->(_v) { Types.encode_MemoryReference(_v) }).call(_i) } : _v }).call(memory_cascade),
          "firstUserMessageData" => first_user_message_data,
          "episodicMemory" => episodic_memory.nil? ? nil : (->(_v) { Types.encode_ObjectiveEpisodicConfig(_v) }).call(episodic_memory),
          "tenant" => tenant.nil? ? nil : (->(_v) { Types.encode_TenantAssertion(_v) }).call(tenant),
          "subject" => subject.nil? ? nil : (->(_v) { Types.encode_SubjectAssertion(_v) }).call(subject),
          "pinnedParameters" => pinned_parameters,
        }.reject { |_k, v| v.nil? }
        _data = @core.request(:post, _path, body: _body, request_options: request_options)
        Types::Objective.from_json(_data)
      end

      # Get an objective by ID
      def retrieve(id, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/objectives/#{Util.path_param('id', id)}"
        _data = @core.request(:get, _path, request_options: request_options)
        Types::Objective.from_json(_data)
      end

      # List objective context windows
      def list_context_windows(objective_id, workspace_id: nil, limit: nil, cursor: nil, include_info: nil, labels: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/objectives/#{Util.path_param('objectiveId', objective_id)}/context_windows"
        _query = {
          "limit" => limit,
          "cursor" => cursor,
          "includeInfo" => include_info,
          "labels" => labels,
        }
        _data = @core.request(:get, _path, query: _query, request_options: request_options) || {}
        _items = (_data["items"] || []).map { |item| Types::ObjectiveContextWindow.from_json(item) }
        _next_cursor = (((_data)["pagination"] || {}))["nextCursor"].to_s
        Page.new(_items, _next_cursor) do |_c|
          list_context_windows(objective_id, workspace_id: workspace_id, limit: limit, cursor: _c, include_info: include_info, labels: labels, request_options: request_options)
        end
      end

      # Get objective context diagnostics
      def retrieve_diagnostics(objective_id, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/objectives/#{Util.path_param('objectiveId', objective_id)}/diagnostics"
        _data = @core.request(:get, _path, request_options: request_options)
        Types::GetObjectiveDiagnosticsResponse.from_json(_data)
      end

      # List objective events
      def list_events(objective_id, workspace_id: nil, limit: nil, cursor: nil, sort_order: nil, include_info: nil, window_id: nil, since_event_id: nil, labels: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/objectives/#{Util.path_param('objectiveId', objective_id)}/events"
        _query = {
          "limit" => limit,
          "cursor" => cursor,
          "sortOrder" => sort_order,
          "includeInfo" => include_info,
          "windowId" => window_id,
          "sinceEventId" => since_event_id,
          "labels" => labels,
        }
        _data = @core.request(:get, _path, query: _query, request_options: request_options) || {}
        _items = (_data["items"] || []).map { |item| Types::ObjectiveEvent.from_json(item) }
        _next_cursor = (((_data)["pagination"] || {}))["nextCursor"].to_s
        Page.new(_items, _next_cursor) do |_c|
          list_events(objective_id, workspace_id: workspace_id, limit: limit, cursor: _c, sort_order: sort_order, include_info: include_info, window_id: window_id, since_event_id: since_event_id, labels: labels, request_options: request_options)
        end
      end

      # Stream objective events
      def stream_events(objective_id, workspace_id: nil, last_event_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/objectives/#{Util.path_param('objectiveId', objective_id)}/events:stream"
        _headers = last_event_id ? { "Last-Event-ID" => last_event_id } : nil
        _decoder = ->(event) { Types::ObjectiveEvent.from_json(event) }
        _auto_reconnect = !(request_options && request_options[:reconnect] == false)
        Stream.new(_decoder, last_event_id: last_event_id, skip_events: ["ping", "open"], auto_reconnect: _auto_reconnect) do |_cancel, _resume, &on_chunk|
          @core.stream_request(:get, _path, headers: (_resume ? { "Last-Event-ID" => _resume } : nil), request_options: request_options, cancel: _cancel, &on_chunk)
        end
      end

      # List feedback for an objective
      def list_feedback(objective_id, workspace_id: nil, limit: nil, cursor: nil, labels: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/objectives/#{Util.path_param('objectiveId', objective_id)}/feedback"
        _query = {
          "limit" => limit,
          "cursor" => cursor,
          "labels" => labels,
        }
        _data = @core.request(:get, _path, query: _query, request_options: request_options) || {}
        _items = (_data["items"] || []).map { |item| Types::ObjectiveFeedback.from_json(item) }
        _next_cursor = (((_data)["pagination"] || {}))["nextCursor"].to_s
        Page.new(_items, _next_cursor) do |_c|
          list_feedback(objective_id, workspace_id: workspace_id, limit: limit, cursor: _c, labels: labels, request_options: request_options)
        end
      end

      # Submit feedback for an objective
      def create_feedback(objective_id, metadata:, data:, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/objectives/#{Util.path_param('objectiveId', objective_id)}/feedback"
        _body = {
          "metadata" => metadata.nil? ? nil : (->(_v) { Types.encode_CreateOperationMetadata(_v) }).call(metadata),
          "data" => data.nil? ? nil : (->(_v) { Types.encode_ObjectiveFeedbackData(_v) }).call(data),
        }.reject { |_k, v| v.nil? }
        _data = @core.request(:post, _path, body: _body, request_options: request_options)
        Types::ObjectiveFeedback.from_json(_data)
      end

      # List objective tasks
      def list_tasks(objective_id, workspace_id: nil, limit: nil, cursor: nil, sort_order: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/objectives/#{Util.path_param('objectiveId', objective_id)}/tasks"
        _query = {
          "limit" => limit,
          "cursor" => cursor,
          "sortOrder" => sort_order,
        }
        _data = @core.request(:get, _path, query: _query, request_options: request_options) || {}
        _items = (_data["items"] || []).map { |item| Types::ObjectiveTask.from_json(item) }
        _next_cursor = (((_data)["pagination"] || {}))["nextCursor"].to_s
        Page.new(_items, _next_cursor) do |_c|
          list_tasks(objective_id, workspace_id: workspace_id, limit: limit, cursor: _c, sort_order: sort_order, request_options: request_options)
        end
      end

      # Get an objective task by ID
      def retrieve_task(objective_id, id, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/objectives/#{Util.path_param('objectiveId', objective_id)}/tasks/#{Util.path_param('id', id)}"
        _data = @core.request(:get, _path, request_options: request_options)
        Types::ObjectiveTask.from_json(_data)
      end

      # List objective tool calls
      def list_tool_calls(objective_id, workspace_id: nil, limit: nil, cursor: nil, status: nil, include_info: nil, execution_status: nil, labels: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/objectives/#{Util.path_param('objectiveId', objective_id)}/tool_calls"
        _query = {
          "limit" => limit,
          "cursor" => cursor,
          "status" => status,
          "includeInfo" => include_info,
          "executionStatus" => execution_status,
          "labels" => labels,
        }
        _data = @core.request(:get, _path, query: _query, request_options: request_options) || {}
        _items = (_data["items"] || []).map { |item| Types::ObjectiveToolCall.from_json(item) }
        _next_cursor = (((_data)["pagination"] || {}))["nextCursor"].to_s
        Page.new(_items, _next_cursor) do |_c|
          list_tool_calls(objective_id, workspace_id: workspace_id, limit: limit, cursor: _c, status: status, include_info: include_info, execution_status: execution_status, labels: labels, request_options: request_options)
        end
      end

      # Get an objective tool call by ID
      def retrieve_tool_call(objective_id, tool_call_id, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/objectives/#{Util.path_param('objectiveId', objective_id)}/tool_calls/#{Util.path_param('toolCallId', tool_call_id)}"
        _data = @core.request(:get, _path, request_options: request_options)
        Types::ObjectiveToolCallWithResult.from_json(_data)
      end

      # Approve a tool call
      def approve_tool_call(objective_id, tool_call_id, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/objectives/#{Util.path_param('objectiveId', objective_id)}/tool_calls/#{Util.path_param('toolCallId', tool_call_id)}:approve"
        _data = @core.request(:post, _path, request_options: request_options)
        Types::ObjectiveToolCall.from_json(_data)
      end

      # Deny a tool call
      def deny_tool_call(objective_id, tool_call_id, workspace_id: nil, memo: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/objectives/#{Util.path_param('objectiveId', objective_id)}/tool_calls/#{Util.path_param('toolCallId', tool_call_id)}:deny"
        _body = {
          "memo" => memo,
        }.reject { |_k, v| v.nil? }
        _data = @core.request(:post, _path, body: _body, request_options: request_options)
        Types::ObjectiveToolCall.from_json(_data)
      end

      # Set a bare tool call's content
      def set_tool_call_content(objective_id, tool_call_id, content:, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/objectives/#{Util.path_param('objectiveId', objective_id)}/tool_calls/#{Util.path_param('toolCallId', tool_call_id)}:setContent"
        _body = {
          "content" => content.nil? ? nil : (->(_v) { _v.is_a?(Array) ? _v.map { |_i| (->(_v) { Types.encode_SetToolCallContentRequest_ContentBlock(_v) }).call(_i) } : _v }).call(content),
        }.reject { |_k, v| v.nil? }
        _data = @core.request(:post, _path, body: _body, request_options: request_options)
        Types::ObjectiveToolCall.from_json(_data)
      end

      # List objective tools
      def list_tools(objective_id, workspace_id: nil, limit: nil, cursor: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/objectives/#{Util.path_param('objectiveId', objective_id)}/tools"
        _query = {
          "limit" => limit,
          "cursor" => cursor,
        }
        _data = @core.request(:get, _path, query: _query, request_options: request_options) || {}
        _items = (_data["items"] || []).map { |item| Types::ObjectiveTool.from_json(item) }
        _next_cursor = (((_data)["pagination"] || {}))["nextCursor"].to_s
        Page.new(_items, _next_cursor) do |_c|
          list_tools(objective_id, workspace_id: workspace_id, limit: limit, cursor: _c, request_options: request_options)
        end
      end

      # Cancel an objective
      def cancel(objective_id, workspace_id: nil, reason: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/objectives/#{Util.path_param('objectiveId', objective_id)}:cancel"
        _body = {
          "reason" => reason,
        }.reject { |_k, v| v.nil? }
        _data = @core.request(:post, _path, body: _body, request_options: request_options)
        Types::Objective.from_json(_data)
      end

      # Compact an objective
      def compact(objective_id, workspace_id: nil, compaction_config: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/objectives/#{Util.path_param('objectiveId', objective_id)}:compact"
        _body = {
          "compactionConfig" => compaction_config.nil? ? nil : (->(_v) { Types.encode_AgentVariationSpec_CompactionConfig(_v) }).call(compaction_config),
        }.reject { |_k, v| v.nil? }
        _data = @core.request(:post, _path, body: _body, request_options: request_options)
        Types::CompactObjectiveResponse.from_json(_data)
      end

      # Continue an objective
      def continue(objective_id, message:, workspace_id: nil, enqueue: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/objectives/#{Util.path_param('objectiveId', objective_id)}:continue"
        _body = {
          "message" => message,
          "enqueue" => enqueue,
        }.reject { |_k, v| v.nil? }
        _data = @core.request(:post, _path, body: _body, request_options: request_options)
        Types::ObjectiveEvent.from_json(_data)
      end
    end
  end
end
