# frozen_string_literal: true

# Code generated by redwood. DO NOT EDIT.

module Cadenya
  module Resources
    class Profiles
      def initialize(core)
        @core = core
      end

      # Retrieves the profile for the credentials accessing the API
      def whoami(request_options: nil)
        _path = "/v1/whoami"
        _data = @core.request(:get, _path, request_options: request_options)
        Types::Profile.from_json(_data)
      end
    end
  end
end
