# frozen_string_literal: true

# Code generated by redwood. DO NOT EDIT.

module Cadenya
  module Resources
    class Tenants
      def initialize(core)
        @core = core
      end

      # List tenants
      def list(workspace_id: nil, limit: nil, cursor: nil, query: nil, labels: nil, sort_order: nil, include_info: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/tenants"
        _query = {
          "limit" => limit,
          "cursor" => cursor,
          "query" => query,
          "labels" => labels,
          "sortOrder" => sort_order,
          "includeInfo" => include_info,
        }
        _data = @core.request(:get, _path, query: _query, request_options: request_options) || {}
        _items = (_data["items"] || []).map { |item| Types::Tenant.from_json(item) }
        _next_cursor = (((_data)["pagination"] || {}))["nextCursor"].to_s
        Page.new(_items, _next_cursor) do |_c|
          list(workspace_id: workspace_id, limit: limit, cursor: _c, query: query, labels: labels, sort_order: sort_order, include_info: include_info, request_options: request_options)
        end
      end

      # Get a tenant by ID
      def retrieve(id, workspace_id: nil, include_info: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/tenants/#{Util.path_param('id', id)}"
        _query = {
          "includeInfo" => include_info,
        }
        _data = @core.request(:get, _path, query: _query, request_options: request_options)
        Types::Tenant.from_json(_data)
      end

      # Erase a tenant
      def delete(id, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/tenants/#{Util.path_param('id', id)}"
        _data = @core.request(:delete, _path, request_options: request_options)
        Types::Tenant.from_json(_data)
      end

      # List a tenant's subjects
      def list_subjects(tenant_id, workspace_id: nil, limit: nil, cursor: nil, query: nil, sort_order: nil, include_info: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/tenants/#{Util.path_param('tenantId', tenant_id)}/subjects"
        _query = {
          "limit" => limit,
          "cursor" => cursor,
          "query" => query,
          "sortOrder" => sort_order,
          "includeInfo" => include_info,
        }
        _data = @core.request(:get, _path, query: _query, request_options: request_options) || {}
        _items = (_data["items"] || []).map { |item| Types::Subject.from_json(item) }
        _next_cursor = (((_data)["pagination"] || {}))["nextCursor"].to_s
        Page.new(_items, _next_cursor) do |_c|
          list_subjects(tenant_id, workspace_id: workspace_id, limit: limit, cursor: _c, query: query, sort_order: sort_order, include_info: include_info, request_options: request_options)
        end
      end
    end
  end
end
