# frozen_string_literal: true

# Code generated by redwood. DO NOT EDIT.

module Cadenya
  module Resources
    class ToolSearch
      def initialize(core)
        @core = core
      end

      # Search for tools or tool sets
      def search_or_sets(query:, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/search/tools_or_tool_sets"
        _query = {
          "query" => query,
        }
        _data = @core.request(:get, _path, query: _query, request_options: request_options)
        Types::SearchToolsOrToolSetsResponse.from_json(_data)
      end
    end
  end
end
