# frozen_string_literal: true

# Code generated by redwood. DO NOT EDIT.

module Cadenya
  module Resources
    class Tools
      def initialize(core)
        @core = core
      end

      # List tools
      def list(tool_set_id, workspace_id: nil, limit: nil, cursor: nil, prefix: nil, query: nil, names: nil, states: nil, requires_approval: nil, overlays: nil, labels: nil, sort_order: nil, include_info: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/tool_sets/#{Util.path_param('toolSetId', tool_set_id)}/tools"
        names = names.dup if names.is_a?(Array)
        states = states.dup if states.is_a?(Array)
        overlays = overlays.dup if overlays.is_a?(Array)
        _query = {
          "limit" => limit,
          "cursor" => cursor,
          "prefix" => prefix,
          "query" => query,
          "names" => names,
          "states" => states,
          "requiresApproval" => requires_approval,
          "overlays" => overlays,
          "labels" => labels,
          "sortOrder" => sort_order,
          "includeInfo" => include_info,
        }
        _data = @core.request(:get, _path, query: _query, request_options: request_options) || {}
        _items = (_data["items"] || []).map { |item| Types::Tool.from_json(item) }
        _next_cursor = (((_data)["pagination"] || {}))["nextCursor"].to_s
        Page.new(_items, _next_cursor) do |_c|
          list(tool_set_id, workspace_id: workspace_id, limit: limit, cursor: _c, prefix: prefix, query: query, names: names, states: states, requires_approval: requires_approval, overlays: overlays, labels: labels, sort_order: sort_order, include_info: include_info, request_options: request_options)
        end
      end

      # Create a new tool
      def create(tool_set_id, metadata:, spec:, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/tool_sets/#{Util.path_param('toolSetId', tool_set_id)}/tools"
        _body = {
          "metadata" => metadata.nil? ? nil : (->(_v) { Types.encode_CreateResourceMetadata(_v) }).call(metadata),
          "spec" => spec.nil? ? nil : (->(_v) { Types.encode_ToolSpec(_v) }).call(spec),
        }.reject { |_k, v| v.nil? }
        _data = @core.request(:post, _path, body: _body, request_options: request_options)
        Types::Tool.from_json(_data)
      end

      # Get a tool by ID
      def retrieve(tool_set_id, id, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/tool_sets/#{Util.path_param('toolSetId', tool_set_id)}/tools/#{Util.path_param('id', id)}"
        _data = @core.request(:get, _path, request_options: request_options)
        Types::Tool.from_json(_data)
      end

      # Delete a tool
      def delete(tool_set_id, id, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/tool_sets/#{Util.path_param('toolSetId', tool_set_id)}/tools/#{Util.path_param('id', id)}"
        @core.request(:delete, _path, expects_body: false, request_options: request_options)
        nil
      end

      # Update a tool
      def update(tool_set_id, id, workspace_id: nil, metadata: nil, spec: nil, update_mask: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/tool_sets/#{Util.path_param('toolSetId', tool_set_id)}/tools/#{Util.path_param('id', id)}"
        _body = {
          "metadata" => metadata.nil? ? nil : (->(_v) { Types.encode_UpdateResourceMetadata(_v) }).call(metadata),
          "spec" => spec.nil? ? nil : (->(_v) { Types.encode_ToolSpec(_v) }).call(spec),
          "updateMask" => update_mask,
        }.reject { |_k, v| v.nil? }
        _data = @core.request(:patch, _path, body: _body, request_options: request_options)
        Types::Tool.from_json(_data)
      end

      # Omit a tool
      def omit(tool_set_id, id, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/tool_sets/#{Util.path_param('toolSetId', tool_set_id)}/tools/#{Util.path_param('id', id)}:omit"
        _data = @core.request(:post, _path, request_options: request_options)
        Types::Tool.from_json(_data)
      end

      # Restore a tool
      def restore(tool_set_id, id, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/tool_sets/#{Util.path_param('toolSetId', tool_set_id)}/tools/#{Util.path_param('id', id)}:restore"
        _data = @core.request(:post, _path, request_options: request_options)
        Types::Tool.from_json(_data)
      end
    end
  end
end
