# frozen_string_literal: true

# Code generated by redwood. DO NOT EDIT.

module Cadenya
  module Resources
    class WidgetSessions
      def initialize(core)
        @core = core
      end

      # List widget sessions
      def list(workspace_id: nil, limit: nil, cursor: nil, widget_id: nil, tenant_id: nil, subject_id: nil, state: nil, labels: nil, sort_order: nil, include_info: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/widget_sessions"
        _query = {
          "limit" => limit,
          "cursor" => cursor,
          "widgetId" => widget_id,
          "tenantId" => tenant_id,
          "subjectId" => subject_id,
          "state" => state,
          "labels" => labels,
          "sortOrder" => sort_order,
          "includeInfo" => include_info,
        }
        _data = @core.request(:get, _path, query: _query, request_options: request_options) || {}
        _items = (_data["items"] || []).map { |item| Types::WidgetSession.from_json(item) }
        _next_cursor = (((_data)["pagination"] || {}))["nextCursor"].to_s
        Page.new(_items, _next_cursor) do |_c|
          list(workspace_id: workspace_id, limit: limit, cursor: _c, widget_id: widget_id, tenant_id: tenant_id, subject_id: subject_id, state: state, labels: labels, sort_order: sort_order, include_info: include_info, request_options: request_options)
        end
      end

      # Create a widget session
      def create(spec:, workspace_id: nil, metadata: nil, secrets: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/widget_sessions"
        _body = {
          "metadata" => metadata.nil? ? nil : (->(_v) { Types.encode_CreateOperationMetadata(_v) }).call(metadata),
          "spec" => spec.nil? ? nil : (->(_v) { Types.encode_WidgetSessionSpec(_v) }).call(spec),
          "secrets" => secrets.nil? ? nil : (->(_v) { _v.is_a?(Array) ? _v.map { |_i| (->(_v) { Types.encode_CreateWidgetSessionRequest_Secret(_v) }).call(_i) } : _v }).call(secrets),
        }.reject { |_k, v| v.nil? }
        _data = @core.request(:post, _path, body: _body, request_options: request_options)
        Types::WidgetSession.from_json(_data)
      end

      # Delete all of a tenant's widget sessions
      def delete_tenant(workspace_id: nil, tenant_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/widget_sessions"
        _query = {
          "tenantId" => tenant_id,
        }
        _data = @core.request(:delete, _path, query: _query, request_options: request_options)
        Types::DeleteTenantWidgetSessionsResponse.from_json(_data)
      end

      # Get a widget session by ID
      def retrieve(id, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/widget_sessions/#{Util.path_param('id', id)}"
        _data = @core.request(:get, _path, request_options: request_options)
        Types::WidgetSession.from_json(_data)
      end

      # Delete a widget session
      def delete(id, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/widget_sessions/#{Util.path_param('id', id)}"
        @core.request(:delete, _path, expects_body: false, request_options: request_options)
        nil
      end

      # Revoke a widget session
      def revoke(id, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/widget_sessions/#{Util.path_param('id', id)}:revoke"
        _data = @core.request(:post, _path, request_options: request_options)
        Types::WidgetSession.from_json(_data)
      end
    end
  end
end
