# frozen_string_literal: true

module Cadenya
  module Resources
    # Manage embeddable chat widgets. A widget binds an agent to a globally unique
    # hostname with a per-widget origin allowlist; browsers reach it with session
    # tokens minted via WidgetSessionService.
    class Widgets
      # Some parameter documentations has been truncated, see
      # {Cadenya::Models::WidgetCreateParams} for more details.
      #
      # Creates a widget bound to an agent. The widget's DNS label and hostname are
      # generated by the server and returned in `info`. The hostname may take up to a
      # minute to become reachable while the edge propagates.
      #
      # @overload create(metadata:, spec:, workspace_id: nil, request_options: {})
      #
      # @param metadata [Cadenya::Models::CreateResourceMetadata] Body param: CreateResourceMetadata contains the user-provided fields for creatin
      #
      # @param spec [Cadenya::Models::WidgetSpec] Body param: WidgetSpec is the user-provided configuration for a widget.
      #
      # @param workspace_id [String] Path param: Workspace ID.
      #
      # @param request_options [Cadenya::RequestOptions, Hash{Symbol=>Object}, nil]
      #
      # @return [Cadenya::Models::Widget]
      #
      # @see Cadenya::Models::WidgetCreateParams
      def create(params)
        parsed, options = Cadenya::WidgetCreateParams.dump_request(params)
        workspace_id =
          parsed.delete(:workspace_id) do
            @client.workspace_id
          end
        @client.request(
          method: :post,
          path: ["v1/workspaces/%1$s/widgets", workspace_id],
          body: parsed,
          model: Cadenya::Widget,
          options: options
        )
      end

      # Some parameter documentations has been truncated, see
      # {Cadenya::Models::WidgetRetrieveParams} for more details.
      #
      # Retrieves a widget by ID
      #
      # @overload retrieve(id, workspace_id: nil, request_options: {})
      #
      # @param id [String] Widget ID. Accepts the canonical `wgt_…` form or the `external_id:<value>` form.
      #
      # @param workspace_id [String] Workspace ID.
      #
      # @param request_options [Cadenya::RequestOptions, Hash{Symbol=>Object}, nil]
      #
      # @return [Cadenya::Models::Widget]
      #
      # @see Cadenya::Models::WidgetRetrieveParams
      def retrieve(id, params = {})
        parsed, options = Cadenya::WidgetRetrieveParams.dump_request(params)
        workspace_id =
          parsed.delete(:workspace_id) do
            @client.workspace_id
          end
        @client.request(
          method: :get,
          path: ["v1/workspaces/%1$s/widgets/%2$s", workspace_id, id],
          model: Cadenya::Widget,
          options: options
        )
      end

      # Some parameter documentations has been truncated, see
      # {Cadenya::Models::WidgetUpdateParams} for more details.
      #
      # Updates a widget's metadata or spec. The DNS label is immutable and cannot be
      # updated. Re-pointing the agent affects new sessions only; in-flight
      # conversations finish against the agent they started with.
      #
      # @overload update(id, workspace_id: nil, metadata: nil, spec: nil, update_mask: nil, request_options: {})
      #
      # @param id [String] Path param: Widget ID. Accepts the canonical `wgt_…` form or the `external_id:<v
      #
      # @param workspace_id [String] Path param: Workspace ID.
      #
      # @param metadata [Cadenya::Models::UpdateResourceMetadata] Body param: UpdateResourceMetadata contains the user-provided fields for updatin
      #
      # @param spec [Cadenya::Models::WidgetSpec] Body param: WidgetSpec is the user-provided configuration for a widget.
      #
      # @param update_mask [String] Body param: Fields to update.
      #
      # @param request_options [Cadenya::RequestOptions, Hash{Symbol=>Object}, nil]
      #
      # @return [Cadenya::Models::Widget]
      #
      # @see Cadenya::Models::WidgetUpdateParams
      def update(id, params = {})
        parsed, options = Cadenya::WidgetUpdateParams.dump_request(params)
        workspace_id =
          parsed.delete(:workspace_id) do
            @client.workspace_id
          end
        @client.request(
          method: :patch,
          path: ["v1/workspaces/%1$s/widgets/%2$s", workspace_id, id],
          body: parsed,
          model: Cadenya::Widget,
          options: options
        )
      end

      # Some parameter documentations has been truncated, see
      # {Cadenya::Models::WidgetListParams} for more details.
      #
      # Lists all widgets in a workspace
      #
      # @overload list(workspace_id: nil, agent_id: nil, cursor: nil, include_info: nil, labels: nil, limit: nil, sort_order: nil, request_options: {})
      #
      # @param workspace_id [String] Path param: Workspace ID.
      #
      # @param agent_id [String] Query param: Filter to widgets bound to a specific agent. Accepts the canonical
      #
      # @param cursor [String] Query param: Pagination cursor from previous response.
      #
      # @param include_info [Boolean] Query param: When true, the `info` field on each returned widget is populated.
      #
      # @param labels [String] Query param: Filters by metadata labels. Comma-separated key=value pairs,
      #
      # @param limit [Integer] Query param: Maximum number of results to return.
      #
      # @param sort_order [String] Query param: Sort order for results (asc or desc by creation time).
      #
      # @param request_options [Cadenya::RequestOptions, Hash{Symbol=>Object}, nil]
      #
      # @return [Cadenya::Internal::CursorPagination<Cadenya::Models::Widget>]
      #
      # @see Cadenya::Models::WidgetListParams
      def list(params = {})
        parsed, options = Cadenya::WidgetListParams.dump_request(params)
        query = Cadenya::Internal::Util.encode_query_params(parsed)
        workspace_id =
          parsed.delete(:workspace_id) do
            @client.workspace_id
          end
        @client.request(
          method: :get,
          path: ["v1/workspaces/%1$s/widgets", workspace_id],
          query: query.transform_keys(
            agent_id: "agentId",
            include_info: "includeInfo",
            sort_order: "sortOrder"
          ),
          page: Cadenya::Internal::CursorPagination,
          model: Cadenya::Widget,
          options: options
        )
      end

      # Some parameter documentations has been truncated, see
      # {Cadenya::Models::WidgetDeleteParams} for more details.
      #
      # Deletes a widget. Its hostname stops serving and all of its sessions are
      # revoked.
      #
      # @overload delete(id, workspace_id: nil, request_options: {})
      #
      # @param id [String] Widget ID. Accepts the canonical `wgt_…` form or the `external_id:<value>` form.
      #
      # @param workspace_id [String] Workspace ID.
      #
      # @param request_options [Cadenya::RequestOptions, Hash{Symbol=>Object}, nil]
      #
      # @return [nil]
      #
      # @see Cadenya::Models::WidgetDeleteParams
      def delete(id, params = {})
        parsed, options = Cadenya::WidgetDeleteParams.dump_request(params)
        workspace_id =
          parsed.delete(:workspace_id) do
            @client.workspace_id
          end
        @client.request(
          method: :delete,
          path: ["v1/workspaces/%1$s/widgets/%2$s", workspace_id, id],
          model: NilClass,
          options: options
        )
      end

      # Some parameter documentations has been truncated, see
      # {Cadenya::Models::WidgetArchiveParams} for more details.
      #
      # Transitions a widget to STATE_ARCHIVED. The hostname stops serving at the edge,
      # existing sessions are revoked, and no new sessions can be minted. Reversible via
      # :unarchive.
      #
      # @overload archive(id, workspace_id: nil, request_options: {})
      #
      # @param id [String] Widget ID. Accepts the canonical `wgt_…` form or the `external_id:<value>` form.
      #
      # @param workspace_id [String] Workspace ID.
      #
      # @param request_options [Cadenya::RequestOptions, Hash{Symbol=>Object}, nil]
      #
      # @return [Cadenya::Models::Widget]
      #
      # @see Cadenya::Models::WidgetArchiveParams
      def archive(id, params = {})
        parsed, options = Cadenya::WidgetArchiveParams.dump_request(params)
        workspace_id =
          parsed.delete(:workspace_id) do
            @client.workspace_id
          end
        @client.request(
          method: :post,
          path: ["v1/workspaces/%1$s/widgets/%2$s:archive", workspace_id, id],
          model: Cadenya::Widget,
          options: options
        )
      end

      # Some parameter documentations has been truncated, see
      # {Cadenya::Models::WidgetUnarchiveParams} for more details.
      #
      # Transitions an archived widget back to STATE_ACTIVE so its hostname serves
      # traffic again. Sessions revoked by archival stay revoked; mint new ones.
      #
      # @overload unarchive(id, workspace_id: nil, request_options: {})
      #
      # @param id [String] Widget ID. Accepts the canonical `wgt_…` form or the `external_id:<value>` form.
      #
      # @param workspace_id [String] Workspace ID.
      #
      # @param request_options [Cadenya::RequestOptions, Hash{Symbol=>Object}, nil]
      #
      # @return [Cadenya::Models::Widget]
      #
      # @see Cadenya::Models::WidgetUnarchiveParams
      def unarchive(id, params = {})
        parsed, options = Cadenya::WidgetUnarchiveParams.dump_request(params)
        workspace_id =
          parsed.delete(:workspace_id) do
            @client.workspace_id
          end
        @client.request(
          method: :post,
          path: ["v1/workspaces/%1$s/widgets/%2$s:unarchive", workspace_id, id],
          model: Cadenya::Widget,
          options: options
        )
      end

      # @api private
      #
      # @param client [Cadenya::Client]
      def initialize(client:)
        @client = client
      end
    end
  end
end
