# frozen_string_literal: true

# Code generated by redwood. DO NOT EDIT.

module Cadenya
  module Resources
    class Widgets
      def initialize(core)
        @core = core
      end

      # List widgets
      def list(workspace_id: nil, limit: nil, cursor: nil, agent_id: nil, labels: nil, sort_order: nil, include_info: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/widgets"
        _query = {
          "limit" => limit,
          "cursor" => cursor,
          "agentId" => agent_id,
          "labels" => labels,
          "sortOrder" => sort_order,
          "includeInfo" => include_info,
        }
        _data = @core.request(:get, _path, query: _query, request_options: request_options) || {}
        _items = (_data["items"] || []).map { |item| Types::Widget.from_json(item) }
        _next_cursor = (((_data)["pagination"] || {}))["nextCursor"].to_s
        Page.new(_items, _next_cursor) do |_c|
          list(workspace_id: workspace_id, limit: limit, cursor: _c, agent_id: agent_id, labels: labels, sort_order: sort_order, include_info: include_info, request_options: request_options)
        end
      end

      # Create a new widget
      def create(metadata:, spec:, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/widgets"
        _body = {
          "metadata" => metadata.nil? ? nil : (->(_v) { Types.encode_CreateResourceMetadata(_v) }).call(metadata),
          "spec" => spec.nil? ? nil : (->(_v) { Types.encode_WidgetSpec(_v) }).call(spec),
        }.reject { |_k, v| v.nil? }
        _data = @core.request(:post, _path, body: _body, request_options: request_options)
        Types::Widget.from_json(_data)
      end

      # Get a widget by ID
      def retrieve(id, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/widgets/#{Util.path_param('id', id)}"
        _data = @core.request(:get, _path, request_options: request_options)
        Types::Widget.from_json(_data)
      end

      # Delete a widget
      def delete(id, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/widgets/#{Util.path_param('id', id)}"
        @core.request(:delete, _path, expects_body: false, request_options: request_options)
        nil
      end

      # Update a widget
      def update(id, workspace_id: nil, metadata: nil, spec: nil, update_mask: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/widgets/#{Util.path_param('id', id)}"
        _body = {
          "metadata" => metadata.nil? ? nil : (->(_v) { Types.encode_UpdateResourceMetadata(_v) }).call(metadata),
          "spec" => spec.nil? ? nil : (->(_v) { Types.encode_WidgetSpec(_v) }).call(spec),
          "updateMask" => update_mask,
        }.reject { |_k, v| v.nil? }
        _data = @core.request(:patch, _path, body: _body, request_options: request_options)
        Types::Widget.from_json(_data)
      end

      # Archive a widget
      def archive(id, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/widgets/#{Util.path_param('id', id)}:archive"
        _data = @core.request(:post, _path, request_options: request_options)
        Types::Widget.from_json(_data)
      end

      # Unarchive a widget
      def unarchive(id, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/workspaces/#{Util.path_param('workspaceId', workspace_id)}/widgets/#{Util.path_param('id', id)}:unarchive"
        _data = @core.request(:post, _path, request_options: request_options)
        Types::Widget.from_json(_data)
      end
    end
  end
end
