# frozen_string_literal: true

# Code generated by redwood. DO NOT EDIT.

module Cadenya
  module Resources
    class Workspaces
      def initialize(core)
        @core = core
      end

      # List workspaces
      def list(limit: nil, cursor: nil, sort_order: nil, include_info: nil, labels: nil, request_options: nil)
        _path = "/v1/workspaces"
        _query = {
          "limit" => limit,
          "cursor" => cursor,
          "sortOrder" => sort_order,
          "includeInfo" => include_info,
          "labels" => labels,
        }
        _data = @core.request(:get, _path, query: _query, request_options: request_options) || {}
        _items = (_data["items"] || []).map { |item| Types::Workspace.from_json(item) }
        _next_cursor = (((_data)["pagination"] || {}))["nextCursor"].to_s
        Page.new(_items, _next_cursor) do |_c|
          list(limit: limit, cursor: _c, sort_order: sort_order, include_info: include_info, labels: labels, request_options: request_options)
        end
      end
    end
  end
end
