# frozen_string_literal: true

# Code generated by redwood. DO NOT EDIT.

module Cadenya
  module Resources
    class WorkspaceAdmin
      def initialize(core)
        @core = core
      end

      # Search account profiles
      def list_profiles(limit: nil, cursor: nil, query: nil, labels: nil, request_options: nil)
        _path = "/v1/account/profiles"
        _query = {
          "limit" => limit,
          "cursor" => cursor,
          "query" => query,
          "labels" => labels,
        }
        _data = @core.request(:get, _path, query: _query, request_options: request_options) || {}
        _items = (_data["items"] || []).map { |item| Types::Profile.from_json(item) }
        _next_cursor = (((_data)["pagination"] || {}))["nextCursor"].to_s
        Page.new(_items, _next_cursor) do |_c|
          list_profiles(limit: limit, cursor: _c, query: query, labels: labels, request_options: request_options)
        end
      end

      # List all workspaces in the account
      def list_account(limit: nil, cursor: nil, include_archived: nil, labels: nil, request_options: nil)
        _path = "/v1/account/workspaces"
        _query = {
          "limit" => limit,
          "cursor" => cursor,
          "includeArchived" => include_archived,
          "labels" => labels,
        }
        _data = @core.request(:get, _path, query: _query, request_options: request_options) || {}
        _items = (_data["items"] || []).map { |item| Types::Workspace.from_json(item) }
        _next_cursor = (((_data)["pagination"] || {}))["nextCursor"].to_s
        Page.new(_items, _next_cursor) do |_c|
          list_account(limit: limit, cursor: _c, include_archived: include_archived, labels: labels, request_options: request_options)
        end
      end

      # Create a workspace
      def create(metadata:, spec:, request_options: nil)
        _path = "/v1/account/workspaces"
        _body = {
          "metadata" => metadata.nil? ? nil : (->(_v) { Types.encode_CreateAccountResourceMetadata(_v) }).call(metadata),
          "spec" => spec.nil? ? nil : (->(_v) { Types.encode_WorkspaceSpec(_v) }).call(spec),
        }.reject { |_k, v| v.nil? }
        _data = @core.request(:post, _path, body: _body, request_options: request_options)
        Types::Workspace.from_json(_data)
      end

      # Get a workspace by ID
      def retrieve(workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/account/workspaces/#{Util.path_param('workspaceId', workspace_id)}"
        _data = @core.request(:get, _path, request_options: request_options)
        Types::Workspace.from_json(_data)
      end

      # Archive a workspace
      def archive(workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/account/workspaces/#{Util.path_param('workspaceId', workspace_id)}"
        @core.request(:delete, _path, expects_body: false, request_options: request_options)
        nil
      end

      # Update a workspace
      def update(workspace_id: nil, metadata: nil, spec: nil, update_mask: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/account/workspaces/#{Util.path_param('workspaceId', workspace_id)}"
        _body = {
          "metadata" => metadata.nil? ? nil : (->(_v) { Types.encode_UpdateAccountResourceMetadata(_v) }).call(metadata),
          "spec" => spec.nil? ? nil : (->(_v) { Types.encode_WorkspaceSpec(_v) }).call(spec),
          "updateMask" => update_mask,
        }.reject { |_k, v| v.nil? }
        _data = @core.request(:patch, _path, body: _body, request_options: request_options)
        Types::Workspace.from_json(_data)
      end

      # List workspace members
      def list_members(workspace_id: nil, limit: nil, cursor: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/account/workspaces/#{Util.path_param('workspaceId', workspace_id)}/members"
        _query = {
          "limit" => limit,
          "cursor" => cursor,
        }
        _data = @core.request(:get, _path, query: _query, request_options: request_options) || {}
        _items = (_data["items"] || []).map { |item| Types::WorkspaceMember.from_json(item) }
        _next_cursor = (((_data)["pagination"] || {}))["nextCursor"].to_s
        Page.new(_items, _next_cursor) do |_c|
          list_members(workspace_id: workspace_id, limit: limit, cursor: _c, request_options: request_options)
        end
      end

      # Add a member to a workspace
      def add_member(workspace_id: nil, profile_id: nil, email: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/account/workspaces/#{Util.path_param('workspaceId', workspace_id)}/members"
        _body = {
          "profileId" => profile_id,
          "email" => email,
        }.reject { |_k, v| v.nil? }
        _data = @core.request(:post, _path, body: _body, request_options: request_options)
        Types::WorkspaceMember.from_json(_data)
      end

      # Remove a member from a workspace
      def remove_member(profile_id, workspace_id: nil, request_options: nil)
        workspace_id = @core.resolve_default("workspaceId", "CADENYA_WORKSPACE_ID", workspace_id)
        _path = "/v1/account/workspaces/#{Util.path_param('workspaceId', workspace_id)}/members/#{Util.path_param('profileId', profile_id)}"
        @core.request(:delete, _path, expects_body: false, request_options: request_options)
        nil
      end
    end
  end
end
