module Cadenya
  module Models
    module MemoryLayers
      type entry_create_params =
        {
          workspace_id: String,
          memory_layer_id: String,
          metadata: Cadenya::CreateResourceMetadata,
          spec: Cadenya::Models::MemoryLayers::memory_entry_create_spec
        }
        & Cadenya::Internal::Type::request_parameters

      class EntryCreateParams < Cadenya::Internal::Type::BaseModel
        extend Cadenya::Internal::Type::RequestParameters::Converter
        include Cadenya::Internal::Type::RequestParameters

        attr_reader workspace_id: String?

        def workspace_id=: (String) -> String

        attr_accessor memory_layer_id: String

        attr_accessor metadata: Cadenya::CreateResourceMetadata

        attr_accessor spec: Cadenya::Models::MemoryLayers::memory_entry_create_spec

        def initialize: (
          memory_layer_id: String,
          metadata: Cadenya::CreateResourceMetadata,
          spec: Cadenya::Models::MemoryLayers::memory_entry_create_spec,
          ?workspace_id: String,
          ?request_options: Cadenya::request_opts
        ) -> void

        def to_hash: -> {
          workspace_id: String,
          memory_layer_id: String,
          metadata: Cadenya::CreateResourceMetadata,
          spec: Cadenya::Models::MemoryLayers::memory_entry_create_spec,
          request_options: Cadenya::RequestOptions
        }
      end
    end
  end
end
