module Cadenya
  module Models
    module MemoryLayers
      type memory_entry =
        {
          metadata: Cadenya::ResourceMetadata,
          spec: Cadenya::MemoryLayers::MemoryEntrySpec,
          info: Cadenya::MemoryLayers::MemoryEntryInfo
        }

      class MemoryEntry < Cadenya::Internal::Type::BaseModel
        attr_accessor metadata: Cadenya::ResourceMetadata

        attr_accessor spec: Cadenya::MemoryLayers::MemoryEntrySpec

        attr_reader info: Cadenya::MemoryLayers::MemoryEntryInfo?

        def info=: (
          Cadenya::MemoryLayers::MemoryEntryInfo
        ) -> Cadenya::MemoryLayers::MemoryEntryInfo

        def initialize: (
          metadata: Cadenya::ResourceMetadata,
          spec: Cadenya::MemoryLayers::MemoryEntrySpec,
          ?info: Cadenya::MemoryLayers::MemoryEntryInfo
        ) -> void

        def to_hash: -> {
          metadata: Cadenya::ResourceMetadata,
          spec: Cadenya::MemoryLayers::MemoryEntrySpec,
          info: Cadenya::MemoryLayers::MemoryEntryInfo
        }
      end
    end
  end
end
