module Cadenya
  module Models
    module MemoryLayers
      type memory_entry_create_spec_upload_id =
        {
          type: Cadenya::Models::MemoryLayers::MemoryEntryCreateSpecUploadID::type_,
          upload_id: String,
          description: String,
          key: String
        }

      class MemoryEntryCreateSpecUploadID < Cadenya::Internal::Type::BaseModel
        attr_accessor type: Cadenya::Models::MemoryLayers::MemoryEntryCreateSpecUploadID::type_

        attr_accessor upload_id: String

        attr_reader description: String?

        def description=: (String) -> String

        attr_accessor key: String

        def initialize: (
          type: Cadenya::Models::MemoryLayers::MemoryEntryCreateSpecUploadID::type_,
          upload_id: String,
          key: String,
          ?description: String
        ) -> void

        def to_hash: -> {
          type: Cadenya::Models::MemoryLayers::MemoryEntryCreateSpecUploadID::type_,
          upload_id: String,
          description: String,
          key: String
        }

        type type_ = :uploadId

        module Type
          extend Cadenya::Internal::Type::Enum

          UPLOAD_ID: :uploadId

          def self?.values: -> ::Array[Cadenya::Models::MemoryLayers::MemoryEntryCreateSpecUploadID::type_]
        end
      end
    end
  end
end
