module Cadenya
  module Models
    module MemoryLayers
      type memory_entry_spec = { key: String, description: String }

      class MemoryEntrySpec < Cadenya::Internal::Type::BaseModel
        attr_accessor key: String

        attr_reader description: String?

        def description=: (String) -> String

        def initialize: (key: String, ?description: String) -> void

        def to_hash: -> { key: String, description: String }
      end
    end
  end
end
