module Cadenya
  module Models
    module MemoryLayers
      type memory_entry_create_spec =
        Cadenya::MemoryLayers::MemoryEntryCreateSpecContent
        | Cadenya::MemoryLayers::MemoryEntryCreateSpecUploadID

      module MemoryEntryCreateSpec
        extend Cadenya::Internal::Type::Union

        def self?.variants: -> ::Array[Cadenya::Models::MemoryLayers::memory_entry_create_spec]
      end
    end
  end
end
