module Cadenya
  module Models
    module MemoryLayers
      type memory_entry_info =
        {
          created_by: Cadenya::Profile,
          memory_layer: Cadenya::ResourceMetadata
        }

      class MemoryEntryInfo < Cadenya::Internal::Type::BaseModel
        attr_reader created_by: Cadenya::Profile?

        def created_by=: (Cadenya::Profile) -> Cadenya::Profile

        attr_reader memory_layer: Cadenya::ResourceMetadata?

        def memory_layer=: (
          Cadenya::ResourceMetadata
        ) -> Cadenya::ResourceMetadata

        def initialize: (
          ?created_by: Cadenya::Profile,
          ?memory_layer: Cadenya::ResourceMetadata
        ) -> void

        def to_hash: -> {
          created_by: Cadenya::Profile,
          memory_layer: Cadenya::ResourceMetadata
        }
      end
    end
  end
end
