module Cadenya
  module Models
    module MemoryLayers
      type memory_entry_create_spec_content =
        {
          content: String,
          type: Cadenya::Models::MemoryLayers::MemoryEntryCreateSpecContent::type_,
          description: String,
          key: String
        }

      class MemoryEntryCreateSpecContent < Cadenya::Internal::Type::BaseModel
        attr_accessor content: String

        attr_accessor type: Cadenya::Models::MemoryLayers::MemoryEntryCreateSpecContent::type_

        attr_reader description: String?

        def description=: (String) -> String

        attr_reader key: String?

        def key=: (String) -> String

        def initialize: (
          content: String,
          type: Cadenya::Models::MemoryLayers::MemoryEntryCreateSpecContent::type_,
          ?description: String,
          ?key: String
        ) -> void

        def to_hash: -> {
          content: String,
          type: Cadenya::Models::MemoryLayers::MemoryEntryCreateSpecContent::type_,
          description: String,
          key: String
        }

        type type_ = :content

        module Type
          extend Cadenya::Internal::Type::Enum

          CONTENT: :content

          def self?.values: -> ::Array[Cadenya::Models::MemoryLayers::MemoryEntryCreateSpecContent::type_]
        end
      end
    end
  end
end
