# frozen_string_literal: true

# Code generated by redwood. DO NOT EDIT.

require "json"

module Cadenya
  # The Cadenya API client. Resource groups are readers; unset options are
  # read from the environment.
  class Client
    attr_reader :accounts, :api_keys, :workspace_admin, :profiles, :workspaces, :agents, :ai_provider_keys, :memory_layers, :models, :objectives, :tool_search, :tenants, :tool_sets, :uploads, :widget_sessions, :widgets, :workspace_secrets

    def initialize(api_key: nil, base_url: nil, webhook_secret: nil, max_retries: 0, connection: nil, stream_transport: nil, workspace_id: nil)
      if !api_key.nil? && api_key.to_s.strip.empty?
        raise ArgumentError, "api_key must not be blank"
      end
      if !base_url.nil? && base_url.to_s.strip.empty?
        raise ArgumentError, "base_url must not be blank"
      end
      if !webhook_secret.nil? && webhook_secret.to_s.strip.empty?
        raise ArgumentError, "webhook_secret must not be blank"
      end
      if !workspace_id.nil? && workspace_id.to_s.strip.empty?
        raise ArgumentError, "workspace_id must not be blank"
      end
      api_key = (api_key || ENV.fetch("CADENYA_API_KEY", "")).to_s.strip
      if api_key.empty?
        raise ArgumentError, "missing API key: pass api_key: or set CADENYA_API_KEY"
      end
      base_url = (base_url || ENV.fetch("CADENYA_BASE_URL", "")).to_s.strip
      base_url = "https://api.cadenya.com" if base_url.empty?
      @webhook_secret = (webhook_secret || ENV.fetch("CADENYA_WEBHOOK_SECRET", "")).to_s.strip
      defaults = {}
      defaults["workspaceId"] = (workspace_id || ENV.fetch("CADENYA_WORKSPACE_ID", "")).to_s.strip
      core = Core.new(
        base_url: base_url,
        auth_header: ["Authorization", "Bearer #{api_key}"],
        max_retries: max_retries,
        defaults: defaults,
        user_agent: "cadenya-ruby/1.0.0 (api 1.0)",
        connection: connection,
        stream_transport: stream_transport
      )
      @accounts = Resources::Accounts.new(core)
      @api_keys = Resources::ApiKeys.new(core)
      @workspace_admin = Resources::WorkspaceAdmin.new(core)
      @profiles = Resources::Profiles.new(core)
      @workspaces = Resources::Workspaces.new(core)
      @agents = Resources::Agents.new(core)
      @ai_provider_keys = Resources::AiProviderKeys.new(core)
      @memory_layers = Resources::MemoryLayers.new(core)
      @models = Resources::Models.new(core)
      @objectives = Resources::Objectives.new(core)
      @tool_search = Resources::ToolSearch.new(core)
      @tenants = Resources::Tenants.new(core)
      @tool_sets = Resources::ToolSets.new(core)
      @uploads = Resources::Uploads.new(core)
      @widget_sessions = Resources::WidgetSessions.new(core)
      @widgets = Resources::Widgets.new(core)
      @workspace_secrets = Resources::WorkspaceSecrets.new(core)
    end

    # Verify a Standard Webhooks delivery and return the typed payload.
    def unwrap_webhook(payload, headers)
      if @webhook_secret.to_s.empty?
        raise ArgumentError, "missing webhook secret: pass webhook_secret: or set CADENYA_WEBHOOK_SECRET"
      end
      Webhooks.verify(@webhook_secret, payload, headers)
      Types::ObjectiveEventWebhookData.from_json(JSON.parse(payload))
    end
  end
end
