# typed: strong

module Cadenya
  module Resources
    # Manage embeddable chat widgets. A widget binds an agent to a globally unique
    # hostname with a per-widget origin allowlist; browsers reach it with session
    # tokens minted via WidgetSessionService.
    class Widgets
      # Creates a widget bound to an agent. The widget's DNS label and hostname are
      # generated by the server and returned in `info`. The hostname may take up to a
      # minute to become reachable while the edge propagates.
      sig do
        params(
          metadata: Cadenya::CreateResourceMetadata::OrHash,
          spec: Cadenya::WidgetSpec::OrHash,
          workspace_id: String,
          request_options: Cadenya::RequestOptions::OrHash
        ).returns(Cadenya::Widget)
      end
      def create(
        # Body param: CreateResourceMetadata contains the user-provided fields for
        # creating a workspace-scoped resource. Read-only fields (id, account_id,
        # workspace_id, profile_id, created_at) are excluded since they are set by the
        # server.
        metadata:,
        # Body param: WidgetSpec is the user-provided configuration for a widget.
        spec:,
        # Path param: Workspace ID.
        workspace_id: nil,
        request_options: {}
      )
      end

      # Retrieves a widget by ID
      sig do
        params(
          id: String,
          workspace_id: String,
          request_options: Cadenya::RequestOptions::OrHash
        ).returns(Cadenya::Widget)
      end
      def retrieve(
        # Widget ID. Accepts the canonical `wgt_…` form or the `external_id:<value>` form.
        id,
        # Workspace ID.
        workspace_id: nil,
        request_options: {}
      )
      end

      # Updates a widget's metadata or spec. The DNS label is immutable and cannot be
      # updated. Re-pointing the agent affects new sessions only; in-flight
      # conversations finish against the agent they started with.
      sig do
        params(
          id: String,
          workspace_id: String,
          metadata: Cadenya::UpdateResourceMetadata::OrHash,
          spec: Cadenya::WidgetSpec::OrHash,
          update_mask: String,
          request_options: Cadenya::RequestOptions::OrHash
        ).returns(Cadenya::Widget)
      end
      def update(
        # Path param: Widget ID. Accepts the canonical `wgt_…` form or the
        # `external_id:<value>` form.
        id,
        # Path param: Workspace ID.
        workspace_id: nil,
        # Body param: UpdateResourceMetadata contains the user-provided fields for
        # updating a workspace-scoped resource. Read-only fields (id, account_id,
        # workspace_id, profile_id, created_at) are excluded since they are set by the
        # server.
        metadata: nil,
        # Body param: WidgetSpec is the user-provided configuration for a widget.
        spec: nil,
        # Body param: Fields to update.
        update_mask: nil,
        request_options: {}
      )
      end

      # Lists all widgets in a workspace
      sig do
        params(
          workspace_id: String,
          agent_id: String,
          cursor: String,
          include_info: T::Boolean,
          labels: String,
          limit: Integer,
          sort_order: String,
          request_options: Cadenya::RequestOptions::OrHash
        ).returns(Cadenya::Internal::CursorPagination[Cadenya::Widget])
      end
      def list(
        # Path param: Workspace ID.
        workspace_id: nil,
        # Query param: Filter to widgets bound to a specific agent. Accepts the canonical
        # `agent_…` form or the `external_id:<value>` form.
        agent_id: nil,
        # Query param: Pagination cursor from previous response.
        cursor: nil,
        # Query param: When true, the `info` field on each returned widget is populated.
        # Requests with this flag count more against your rate limit.
        include_info: nil,
        # Query param: Filters by metadata labels. Comma-separated key=value pairs, e.g.
        # "env=prod,team=ai". A resource matches only if every pair matches exactly (AND
        # semantics).
        labels: nil,
        # Query param: Maximum number of results to return.
        limit: nil,
        # Query param: Sort order for results (asc or desc by creation time).
        sort_order: nil,
        request_options: {}
      )
      end

      # Deletes a widget. Its hostname stops serving and all of its sessions are
      # revoked.
      sig do
        params(
          id: String,
          workspace_id: String,
          request_options: Cadenya::RequestOptions::OrHash
        ).void
      end
      def delete(
        # Widget ID. Accepts the canonical `wgt_…` form or the `external_id:<value>` form.
        id,
        # Workspace ID.
        workspace_id: nil,
        request_options: {}
      )
      end

      # Transitions a widget to STATE_ARCHIVED. The hostname stops serving at the edge,
      # existing sessions are revoked, and no new sessions can be minted. Reversible via
      # :unarchive.
      sig do
        params(
          id: String,
          workspace_id: String,
          request_options: Cadenya::RequestOptions::OrHash
        ).returns(Cadenya::Widget)
      end
      def archive(
        # Widget ID. Accepts the canonical `wgt_…` form or the `external_id:<value>` form.
        id,
        # Workspace ID.
        workspace_id: nil,
        request_options: {}
      )
      end

      # Transitions an archived widget back to STATE_ACTIVE so its hostname serves
      # traffic again. Sessions revoked by archival stay revoked; mint new ones.
      sig do
        params(
          id: String,
          workspace_id: String,
          request_options: Cadenya::RequestOptions::OrHash
        ).returns(Cadenya::Widget)
      end
      def unarchive(
        # Widget ID. Accepts the canonical `wgt_…` form or the `external_id:<value>` form.
        id,
        # Workspace ID.
        workspace_id: nil,
        request_options: {}
      )
      end

      # @api private
      sig { params(client: Cadenya::Client).returns(T.attached_class) }
      def self.new(client:)
      end
    end
  end
end
