module Cadenya
  module Resources
    class MemoryLayers
      class Entries
        def create: (
          String memory_layer_id,
          metadata: Cadenya::CreateResourceMetadata,
          spec: Cadenya::MemoryLayers::MemoryEntryCreateSpec,
          ?workspace_id: String,
          ?request_options: Cadenya::request_opts
        ) -> Cadenya::MemoryLayers::MemoryEntryDetail

        def retrieve: (
          String memory_layer_id,
          String id,
          ?workspace_id: String,
          ?request_options: Cadenya::request_opts
        ) -> Cadenya::MemoryLayers::MemoryEntryDetail

        def update: (
          String memory_layer_id,
          String id,
          ?workspace_id: String,
          ?metadata: Cadenya::UpdateResourceMetadata,
          ?spec: Cadenya::MemoryLayers::MemoryEntryUpdateSpec,
          ?update_mask: String,
          ?request_options: Cadenya::request_opts
        ) -> Cadenya::MemoryLayers::MemoryEntryDetail

        def list: (
          String memory_layer_id,
          ?workspace_id: String,
          ?cursor: String,
          ?include_info: bool,
          ?labels: String,
          ?limit: Integer,
          ?prefix: String,
          ?query: String,
          ?sort_order: String,
          ?request_options: Cadenya::request_opts
        ) -> Cadenya::Internal::CursorPagination[Cadenya::MemoryLayers::MemoryEntry]

        def delete: (
          String memory_layer_id,
          String id,
          ?workspace_id: String,
          ?request_options: Cadenya::request_opts
        ) -> nil

        def initialize: (client: Cadenya::Client) -> void
      end
    end
  end
end
