# frozen_string_literal: true

# Code generated by redwood. DO NOT EDIT.
# Cross-cutting runtime contracts, anchored on operations chosen by shape.

RSpec.describe "client construction" do
  context "when the base URL carries a query" do
    it "is rejected before any request" do
      expect { build_client(base_url: "https://host.example?x=1") }.to raise_error(ArgumentError)
    end
  end
  context "when the base URL carries a fragment" do
    it "is rejected before any request" do
      expect { build_client(base_url: "https://host.example#frag") }.to raise_error(ArgumentError)
    end
  end
  context "when the base URL carries userinfo" do
    it "is rejected before any request" do
      expect { build_client(base_url: "https://user:pw@host.example") }.to raise_error(ArgumentError)
    end
  end
  context "when the base URL carries a bare query delimiter" do
    it "is rejected before any request" do
      expect { build_client(base_url: "https://host.example?") }.to raise_error(ArgumentError)
    end
  end
  context "when the base URL carries a bare fragment delimiter" do
    it "is rejected before any request" do
      expect { build_client(base_url: "https://host.example#") }.to raise_error(ArgumentError)
    end
  end
  context "when the base URL carries a non-http scheme" do
    it "is rejected before any request" do
      expect { build_client(base_url: "ftp://host.example") }.to raise_error(ArgumentError)
    end
  end
  context "when the base URL carries no host" do
    it "is rejected before any request" do
      expect { build_client(base_url: "https://") }.to raise_error(ArgumentError)
    end
  end
end

RSpec.describe "authentication" do
  let(:client) { build_client }
  it "sends the bearer credential on every request" do
    stub = stub_request(:get, "#{SPEC_BASE_URL}/v1/account").to_return(status: 200, body: "{\"info\":{\"challengeToken\":\"sample\",\"webhookEventsHmacSecret\":\"sample\"},\"metadata\":{\"accountId\":\"sample\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\"},\"spec\":{\"billingEmail\":\"sample\",\"description\":\"sample\",\"domain\":\"sample\",\"workspaces\":[{\"metadata\":{\"accountId\":\"sample\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\"},\"spec\":{},\"status\":\"STATUS_ENABLED\"}]}}", headers: { "Content-Type" => "application/json" })
    client.accounts.retrieve
    expect(stub).to have_been_requested
    expect(WebMock).to(have_requested(:get, %r{.*}).with { |req| req.headers["Authorization"] == "Bearer test-key" })
  end
end

RSpec.describe "error mapping" do
  let(:client) { build_client }

  context "when the API answers with an rpc status" do
    it "raises APIError carrying status, code, and message" do
      stub_request(:get, "#{SPEC_BASE_URL}/v1/account").to_return(status: 404, body: '{"code":5,"message":"missing","details":[]}', headers: { "Content-Type" => "application/json" })
      expect { client.accounts.retrieve }.to raise_error(Cadenya::APIError) do |e|
        expect(e.status_code).to eq(404)
        expect(e.code).to eq(5)
        expect(e.message).to eq("missing")
      end
    end
  end

  context "when the success body is empty where JSON is promised" do
    it "raises the stable protocol error" do
      stub_request(:get, "#{SPEC_BASE_URL}/v1/account").to_return(status: 200, body: "")
      expect { client.accounts.retrieve }.to raise_error(Cadenya::APIResponseError)
    end
  end

  context "when the success body is a JSON null" do
    it "raises the stable protocol error" do
      stub_request(:get, "#{SPEC_BASE_URL}/v1/account").to_return(status: 200, body: "null", headers: { "Content-Type" => "application/json" })
      expect { client.accounts.retrieve }.to raise_error(Cadenya::APIResponseError)
    end
  end

  context "when the success body is not JSON" do
    it "raises the stable protocol error" do
      stub_request(:get, "#{SPEC_BASE_URL}/v1/account").to_return(status: 200, body: "<html>", headers: { "Content-Type" => "text/html" })
      expect { client.accounts.retrieve }.to raise_error(Cadenya::APIResponseError)
    end
  end

  context "when an unfollowed redirect arrives" do
    it "raises the stable protocol error" do
      stub_request(:get, "#{SPEC_BASE_URL}/v1/account").to_return(status: 302, body: "", headers: { "Location" => "https://elsewhere.example" })
      expect { client.accounts.retrieve }.to raise_error(Cadenya::APIResponseError)
    end
  end
end

RSpec.describe "retries" do
  before { allow_any_instance_of(Cadenya::Core).to receive(:sleep) }

  context "when an idempotent request hits a retryable status" do
    it "retries up to the client budget and then succeeds" do
      client = build_client(max_retries: 2)
      stub = stub_request(:get, "#{SPEC_BASE_URL}/v1/account")
        .to_return({ status: 503, body: "" }, { status: 200, body: "{\"info\":{\"challengeToken\":\"sample\",\"webhookEventsHmacSecret\":\"sample\"},\"metadata\":{\"accountId\":\"sample\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\"},\"spec\":{\"billingEmail\":\"sample\",\"description\":\"sample\",\"domain\":\"sample\",\"workspaces\":[{\"metadata\":{\"accountId\":\"sample\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\"},\"spec\":{},\"status\":\"STATUS_ENABLED\"}]}}", headers: { "Content-Type" => "application/json" } })
      client.accounts.retrieve
      expect(stub).to have_been_requested.times(2)
    end
  end

  context "when a mutation hits a retryable status" do
    it "does NOT retry by default" do
      client = build_client(max_retries: 2)
      stub = stub_request(:post, "#{SPEC_BASE_URL}/v1/workspaces/sample/api_keys").to_return(status: 503, body: "")
      expect { client.api_keys.create(workspace_id: "sample", metadata: {"name" => "sample"}, spec: {}) }.to raise_error(Cadenya::APIError)
      expect(stub).to have_been_requested.times(1)
    end

    it "retries when the CALLER opts this call in via request_options" do
      client = build_client
      stub = stub_request(:post, "#{SPEC_BASE_URL}/v1/workspaces/sample/api_keys")
        .to_return({ status: 503, body: "" }, { status: 200, body: "{\"metadata\":{\"accountId\":\"sample\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\"},\"spec\":{\"system\":true,\"token\":\"sample\"},\"state\":\"STATE_UNSPECIFIED\"}", headers: { "Content-Type" => "application/json" } })
      client.api_keys.create(workspace_id: "sample", metadata: {"name" => "sample"}, spec: {}, request_options: { max_retries: 2 })
      expect(stub).to have_been_requested.times(2)
    end
  end
end

RSpec.describe "request options" do
  let(:client) { build_client }

  context "when an unknown option key is supplied" do
    it "is rejected loudly before any request" do
      expect { client.accounts.retrieve(request_options: { timout: 5 }) }.to raise_error(ArgumentError, /unknown request_options key/)
      expect(WebMock).not_to have_requested(:get, %r{.*})
    end
  end

  context "when per-request headers are supplied" do
    it "sends them, replacing defaults case-insensitively" do
      stub_request(:get, "#{SPEC_BASE_URL}/v1/account").to_return(status: 200, body: "{\"info\":{\"challengeToken\":\"sample\",\"webhookEventsHmacSecret\":\"sample\"},\"metadata\":{\"accountId\":\"sample\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\"},\"spec\":{\"billingEmail\":\"sample\",\"description\":\"sample\",\"domain\":\"sample\",\"workspaces\":[{\"metadata\":{\"accountId\":\"sample\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\"},\"spec\":{},\"status\":\"STATUS_ENABLED\"}]}}", headers: { "Content-Type" => "application/json" })
      client.accounts.retrieve(request_options: { headers: { "X-Request-ID" => "rid-1", "user-agent" => "custom-ua" } })
      expect(WebMock).to(have_requested(:get, %r{.*}).with { |req| req.headers["X-Request-Id"] == "rid-1" && req.headers["User-Agent"] == "custom-ua" })
    end
  end

  context "when a negative timeout is supplied" do
    it "is rejected" do
      expect { client.accounts.retrieve(request_options: { timeout: -1 }) }.to raise_error(ArgumentError)
    end
  end

  context "when a non-numeric timeout is supplied" do
    it "is rejected" do
      expect { client.accounts.retrieve(request_options: { timeout: "soon" }) }.to raise_error(ArgumentError)
    end
  end

  context "when a fractional retry count is supplied" do
    it "is rejected" do
      expect { client.accounts.retrieve(request_options: { max_retries: 1.5 }) }.to raise_error(ArgumentError)
    end
  end
end

RSpec.describe "request encoding" do
  let(:client) { build_client }
  it "translates snake_case keys to the exact golden wire body" do
    stub_request(:post, "#{SPEC_BASE_URL}/v1/workspaces/sample/api_keys").to_return(status: 200, body: "{\"metadata\":{\"accountId\":\"sample\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\"},\"spec\":{\"system\":true,\"token\":\"sample\"},\"state\":\"STATE_UNSPECIFIED\"}", headers: { "Content-Type" => "application/json" })
    client.api_keys.create(workspace_id: "sample", metadata: {"name" => "sample"}, spec: {})
    expect(WebMock).to(have_requested(:post, %r{.*}).with { |req| JSON.parse(req.body) == JSON.parse("{\"metadata\":{\"name\":\"sample\"},\"spec\":{}}") })
  end

  context "when a fetched value still carries server-owned fields" do
    it "drops readOnly keys instead of echoing server state" do
      stub_request(:post, "#{SPEC_BASE_URL}/v1/workspaces/sample/api_keys").to_return(status: 200, body: "{\"metadata\":{\"accountId\":\"sample\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\"},\"spec\":{\"system\":true,\"token\":\"sample\"},\"state\":\"STATE_UNSPECIFIED\"}", headers: { "Content-Type" => "application/json" })
      client.api_keys.create(workspace_id: "sample", metadata: {"name" => "sample"}, spec: {"system" => "server-owned", "token" => "server-owned"})
      expect(WebMock).to(have_requested(:post, %r{.*}).with do |req|
        sent = JSON.parse(req.body).fetch("spec", {})
        !sent.key?("token") &&
        !sent.key?("system") &&
          true
      end)
    end
  end
end
