# frozen_string_literal: true

# Code generated by redwood. DO NOT EDIT.
$LOAD_PATH.unshift File.expand_path("../lib", __dir__)

require "cadenya"
require "json"
require "webmock/rspec"
require "vcr"

SPEC_BASE_URL = "https://api.test.example"

VCR.configure do |c|
  c.cassette_library_dir = File.expand_path("cassettes", __dir__)
  c.hook_into :webmock
  # Cassettes are the GOLDEN FILES for every operation's request shape,
  # generated deterministically by redwood — refresh them by REGENERATING,
  # never by recording against a live server (recording would persist real
  # credentials and secret bodies into durable files).
  c.default_cassette_options = {
    record: :none,
    match_requests_on: %i[method path query json_body],
    allow_unused_http_interactions: false,
  }
  # Golden request bodies compare as PARSED JSON: serialization key order is
  # not part of the contract, but every key and value is.
  c.register_request_matcher :json_body do |real, recorded|
    real_body = real.body.to_s
    recorded_body = recorded.body.to_s
    if real_body.empty? || recorded_body.empty?
      real_body.empty? == recorded_body.empty?
    else
      JSON.parse(real_body) == JSON.parse(recorded_body)
    end
  end
end

def build_client(**overrides)
  Cadenya::Client.new(**{ api_key: "test-key", workspace_id: "default_workspace_id", base_url: SPEC_BASE_URL }.merge(overrides))
end

RSpec.configure do |config|
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end
  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end
  config.order = :random
  Kernel.srand config.seed
end
