# frozen_string_literal: true

# Code generated by redwood. DO NOT EDIT.

require "base64"
require "openssl"

RSpec.describe "webhook verification" do
  let(:secret_key) { "0123456789abcdef0123456789abcdef" }
  let(:secret) { "whsec_#{Base64.strict_encode64(secret_key)}" }
  let(:payload) { "{\"data\":{\"agent\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"agentVariation\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"objective\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"objectiveEvent\":{\"contextWindowId\":\"sample\",\"data\":{\"type\":\"userMessage\",\"userMessage\":{\"content\":\"sample\"}},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"profileId\":\"sample\",\"workspaceId\":\"sample\"}}},\"timestamp\":\"2026-01-01T00:00:00Z\",\"type\":\"sample\"}" }

  def signed_headers(payload, at: Time.now.to_i, key: secret_key, msg_id: "msg_1")
    signature = Base64.strict_encode64(OpenSSL::HMAC.digest("SHA256", key, "#{msg_id}.#{at}.#{payload}"))
    {
      "webhook-id" => msg_id,
      "webhook-timestamp" => at.to_s,
      "webhook-signature" => "v1,#{signature}",
    }
  end

  context "with an authentic signature" do
    it "verifies" do
      expect { Cadenya::Webhooks.verify(secret, payload, signed_headers(payload)) }.not_to raise_error
    end
  end

  context "when the payload was tampered with" do
    it "rejects" do
      headers = signed_headers(payload)
      expect { Cadenya::Webhooks.verify(secret, payload + " ", headers) }
        .to raise_error(Cadenya::WebhookVerificationError)
    end
  end

  context "with the wrong secret" do
    it "rejects" do
      other = "whsec_#{Base64.strict_encode64("fedcba9876543210fedcba9876543210")}"
      expect { Cadenya::Webhooks.verify(other, payload, signed_headers(payload)) }
        .to raise_error(Cadenya::WebhookVerificationError)
    end
  end

  context "when the timestamp is outside the tolerance" do
    it "rejects the replay" do
      headers = signed_headers(payload, at: Time.now.to_i - 3600)
      expect { Cadenya::Webhooks.verify(secret, payload, headers) }
        .to raise_error(Cadenya::WebhookVerificationError, /tolerance/)
    end
  end

  context "when a signature header is missing" do
    it "rejects" do
      headers = signed_headers(payload).reject { |k, _| k == "webhook-signature" }
      expect { Cadenya::Webhooks.verify(secret, payload, headers) }
        .to raise_error(Cadenya::WebhookVerificationError)
    end
  end
end
