module Cadenya
  module Models
    type account_spec =
      {
        billing_email: String,
        description: String,
        domain: String,
        workspaces: ::Array[Cadenya::Workspace]
      }

    class AccountSpec < Cadenya::Internal::Type::BaseModel
      attr_accessor billing_email: String

      attr_accessor description: String

      attr_accessor domain: String

      attr_accessor workspaces: ::Array[Cadenya::Workspace]

      def initialize: (
        billing_email: String,
        description: String,
        domain: String,
        workspaces: ::Array[Cadenya::Workspace]
      ) -> void

      def to_hash: -> {
        billing_email: String,
        description: String,
        domain: String,
        workspaces: ::Array[Cadenya::Workspace]
      }
    end
  end
end
