module Cadenya
  module Models
    type account_resource_metadata =
      {
        id: String,
        account_id: String,
        name: String,
        profile_id: String,
        created_at: Time,
        external_id: String,
        labels: ::Hash[Symbol, String]
      }

    class AccountResourceMetadata < Cadenya::Internal::Type::BaseModel
      attr_accessor name: String

      attr_accessor external_id: String

      attr_accessor labels: ::Hash[Symbol, String]

      attr_accessor id: String

      attr_accessor account_id: String

      attr_accessor profile_id: String

      attr_reader created_at: Time?

      def created_at=: (Time) -> Time

      def initialize: (
        id: String,
        account_id: String,
        name: String,
        profile_id: String,
        external_id: String,
        labels: ::Hash[Symbol, String],
        ?created_at: Time
      ) -> void

      def to_hash: -> {
        id: String,
        account_id: String,
        name: String,
        profile_id: String,
        created_at: Time,
        external_id: String,
        labels: ::Hash[Symbol, String]
      }
    end
  end
end
