module Cadenya
  module Models
    type account_info =
      { challenge_token: String, webhook_events_hmac_secret: String }

    class AccountInfo < Cadenya::Internal::Type::BaseModel
      attr_accessor challenge_token: String

      attr_accessor webhook_events_hmac_secret: String

      def initialize: (
        challenge_token: String,
        webhook_events_hmac_secret: String
      ) -> void

      def to_hash: -> {
        challenge_token: String,
        webhook_events_hmac_secret: String
      }
    end
  end
end
