module Cadenya
  module Models
    type agent_info = { created_by: Cadenya::Profile, variation_count: Integer }

    class AgentInfo < Cadenya::Internal::Type::BaseModel
      attr_reader created_by: Cadenya::Profile?

      def created_by=: (Cadenya::Profile) -> Cadenya::Profile

      attr_reader variation_count: Integer?

      def variation_count=: (Integer) -> Integer

      def initialize: (
        ?created_by: Cadenya::Profile,
        ?variation_count: Integer
      ) -> void

      def to_hash: -> { created_by: Cadenya::Profile, variation_count: Integer }
    end
  end
end
