module Cadenya
  module Models
    type agent_list_params =
      {
        workspace_id: String,
        cursor: String,
        include_info: bool,
        labels: String,
        limit: Integer,
        prefix: String,
        query: String,
        sort_order: String,
        state: Cadenya::Models::AgentListParams::state,
        variation_selection_mode: Cadenya::Models::AgentListParams::variation_selection_mode
      }
      & Cadenya::Internal::Type::request_parameters

    class AgentListParams < Cadenya::Internal::Type::BaseModel
      extend Cadenya::Internal::Type::RequestParameters::Converter
      include Cadenya::Internal::Type::RequestParameters

      attr_reader workspace_id: String?

      def workspace_id=: (String) -> String

      attr_reader cursor: String?

      def cursor=: (String) -> String

      attr_reader include_info: bool?

      def include_info=: (bool) -> bool

      attr_reader labels: String?

      def labels=: (String) -> String

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_reader prefix: String?

      def prefix=: (String) -> String

      attr_reader query: String?

      def query=: (String) -> String

      attr_reader sort_order: String?

      def sort_order=: (String) -> String

      attr_reader state: Cadenya::Models::AgentListParams::state?

      def state=: (
        Cadenya::Models::AgentListParams::state
      ) -> Cadenya::Models::AgentListParams::state

      attr_reader variation_selection_mode: Cadenya::Models::AgentListParams::variation_selection_mode?

      def variation_selection_mode=: (
        Cadenya::Models::AgentListParams::variation_selection_mode
      ) -> Cadenya::Models::AgentListParams::variation_selection_mode

      def initialize: (
        ?workspace_id: String,
        ?cursor: String,
        ?include_info: bool,
        ?labels: String,
        ?limit: Integer,
        ?prefix: String,
        ?query: String,
        ?sort_order: String,
        ?state: Cadenya::Models::AgentListParams::state,
        ?variation_selection_mode: Cadenya::Models::AgentListParams::variation_selection_mode,
        ?request_options: Cadenya::request_opts
      ) -> void

      def to_hash: -> {
        workspace_id: String,
        cursor: String,
        include_info: bool,
        labels: String,
        limit: Integer,
        prefix: String,
        query: String,
        sort_order: String,
        state: Cadenya::Models::AgentListParams::state,
        variation_selection_mode: Cadenya::Models::AgentListParams::variation_selection_mode,
        request_options: Cadenya::RequestOptions
      }

      type state =
        :STATE_UNSPECIFIED | :STATE_DRAFT | :STATE_PUBLISHED | :STATE_ARCHIVED

      module State
        extend Cadenya::Internal::Type::Enum

        STATE_UNSPECIFIED: :STATE_UNSPECIFIED
        STATE_DRAFT: :STATE_DRAFT
        STATE_PUBLISHED: :STATE_PUBLISHED
        STATE_ARCHIVED: :STATE_ARCHIVED

        def self?.values: -> ::Array[Cadenya::Models::AgentListParams::state]
      end

      type variation_selection_mode =
        :VARIATION_SELECTION_MODE_UNSPECIFIED
        | :VARIATION_SELECTION_MODE_RANDOM
        | :VARIATION_SELECTION_MODE_WEIGHTED

      module VariationSelectionMode
        extend Cadenya::Internal::Type::Enum

        VARIATION_SELECTION_MODE_UNSPECIFIED: :VARIATION_SELECTION_MODE_UNSPECIFIED
        VARIATION_SELECTION_MODE_RANDOM: :VARIATION_SELECTION_MODE_RANDOM
        VARIATION_SELECTION_MODE_WEIGHTED: :VARIATION_SELECTION_MODE_WEIGHTED

        def self?.values: -> ::Array[Cadenya::Models::AgentListParams::variation_selection_mode]
      end
    end
  end
end
