module Cadenya
  module Models
    type agent_create_params =
      {
        workspace_id: String,
        metadata: Cadenya::CreateResourceMetadata,
        spec: Cadenya::AgentSpec,
        default_variation: Cadenya::AgentCreateParams::DefaultVariation
      }
      & Cadenya::Internal::Type::request_parameters

    class AgentCreateParams < Cadenya::Internal::Type::BaseModel
      extend Cadenya::Internal::Type::RequestParameters::Converter
      include Cadenya::Internal::Type::RequestParameters

      attr_reader workspace_id: String?

      def workspace_id=: (String) -> String

      attr_accessor metadata: Cadenya::CreateResourceMetadata

      attr_accessor spec: Cadenya::AgentSpec

      attr_reader default_variation: Cadenya::AgentCreateParams::DefaultVariation?

      def default_variation=: (
        Cadenya::AgentCreateParams::DefaultVariation
      ) -> Cadenya::AgentCreateParams::DefaultVariation

      def initialize: (
        metadata: Cadenya::CreateResourceMetadata,
        spec: Cadenya::AgentSpec,
        ?workspace_id: String,
        ?default_variation: Cadenya::AgentCreateParams::DefaultVariation,
        ?request_options: Cadenya::request_opts
      ) -> void

      def to_hash: -> {
        workspace_id: String,
        metadata: Cadenya::CreateResourceMetadata,
        spec: Cadenya::AgentSpec,
        default_variation: Cadenya::AgentCreateParams::DefaultVariation,
        request_options: Cadenya::RequestOptions
      }

      type default_variation =
        {
          metadata: Cadenya::CreateResourceMetadata,
          spec: Cadenya::Agents::AgentVariationSpec,
          agent_id: String,
          workspace_id: String
        }

      class DefaultVariation < Cadenya::Internal::Type::BaseModel
        attr_accessor metadata: Cadenya::CreateResourceMetadata

        attr_accessor spec: Cadenya::Agents::AgentVariationSpec

        def initialize: (
          metadata: Cadenya::CreateResourceMetadata,
          spec: Cadenya::Agents::AgentVariationSpec
        ) -> void

        def to_hash: -> {
          metadata: Cadenya::CreateResourceMetadata,
          spec: Cadenya::Agents::AgentVariationSpec,
          agent_id: String,
          workspace_id: String
        }
      end
    end
  end
end
