module Cadenya
  module Models
    type agent_spec =
      {
        variation_selection_mode: Cadenya::Models::AgentSpec::variation_selection_mode,
        description: String,
        enable_episodic_memory: bool,
        episodic_memory_ttl: Integer,
        input_data_schema: ::Hash[Symbol, top],
        output_definition: ::Hash[Symbol, top],
        webhook_events_url: String
      }

    class AgentSpec < Cadenya::Internal::Type::BaseModel
      attr_accessor variation_selection_mode: Cadenya::Models::AgentSpec::variation_selection_mode

      attr_reader description: String?

      def description=: (String) -> String

      attr_reader enable_episodic_memory: bool?

      def enable_episodic_memory=: (bool) -> bool

      attr_reader episodic_memory_ttl: Integer?

      def episodic_memory_ttl=: (Integer) -> Integer

      attr_reader input_data_schema: ::Hash[Symbol, top]?

      def input_data_schema=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

      attr_reader output_definition: ::Hash[Symbol, top]?

      def output_definition=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

      attr_reader webhook_events_url: String?

      def webhook_events_url=: (String) -> String

      def initialize: (
        variation_selection_mode: Cadenya::Models::AgentSpec::variation_selection_mode,
        ?description: String,
        ?enable_episodic_memory: bool,
        ?episodic_memory_ttl: Integer,
        ?input_data_schema: ::Hash[Symbol, top],
        ?output_definition: ::Hash[Symbol, top],
        ?webhook_events_url: String
      ) -> void

      def to_hash: -> {
        variation_selection_mode: Cadenya::Models::AgentSpec::variation_selection_mode,
        description: String,
        enable_episodic_memory: bool,
        episodic_memory_ttl: Integer,
        input_data_schema: ::Hash[Symbol, top],
        output_definition: ::Hash[Symbol, top],
        webhook_events_url: String
      }

      type variation_selection_mode =
        :VARIATION_SELECTION_MODE_UNSPECIFIED
        | :VARIATION_SELECTION_MODE_RANDOM
        | :VARIATION_SELECTION_MODE_WEIGHTED

      module VariationSelectionMode
        extend Cadenya::Internal::Type::Enum

        VARIATION_SELECTION_MODE_UNSPECIFIED: :VARIATION_SELECTION_MODE_UNSPECIFIED
        VARIATION_SELECTION_MODE_RANDOM: :VARIATION_SELECTION_MODE_RANDOM
        VARIATION_SELECTION_MODE_WEIGHTED: :VARIATION_SELECTION_MODE_WEIGHTED

        def self?.values: -> ::Array[Cadenya::Models::AgentSpec::variation_selection_mode]
      end
    end
  end
end
