module Cadenya
  module Models
    type agent_info = { created_by: Cadenya::Profile, variation_count: Integer }

    class AgentInfo < Cadenya::Internal::Type::BaseModel
      attr_reader created_by: Cadenya::Profile?

      def created_by=: (Cadenya::Profile) -> Cadenya::Profile

      attr_accessor variation_count: Integer

      def initialize: (
        variation_count: Integer,
        ?created_by: Cadenya::Profile
      ) -> void

      def to_hash: -> { created_by: Cadenya::Profile, variation_count: Integer }
    end
  end
end
