module Cadenya
  module Models
    type agent =
      {
        metadata: Cadenya::ResourceMetadata,
        spec: Cadenya::AgentSpec,
        state: Cadenya::Models::Agent::state,
        info: Cadenya::AgentInfo
      }

    class Agent < Cadenya::Internal::Type::BaseModel
      attr_accessor metadata: Cadenya::ResourceMetadata

      attr_accessor spec: Cadenya::AgentSpec

      attr_accessor state: Cadenya::Models::Agent::state

      attr_reader info: Cadenya::AgentInfo?

      def info=: (Cadenya::AgentInfo) -> Cadenya::AgentInfo

      def initialize: (
        metadata: Cadenya::ResourceMetadata,
        spec: Cadenya::AgentSpec,
        state: Cadenya::Models::Agent::state,
        ?info: Cadenya::AgentInfo
      ) -> void

      def to_hash: -> {
        metadata: Cadenya::ResourceMetadata,
        spec: Cadenya::AgentSpec,
        state: Cadenya::Models::Agent::state,
        info: Cadenya::AgentInfo
      }

      type state =
        :STATE_UNSPECIFIED | :STATE_DRAFT | :STATE_PUBLISHED | :STATE_ARCHIVED

      module State
        extend Cadenya::Internal::Type::Enum

        STATE_UNSPECIFIED: :STATE_UNSPECIFIED
        STATE_DRAFT: :STATE_DRAFT
        STATE_PUBLISHED: :STATE_PUBLISHED
        STATE_ARCHIVED: :STATE_ARCHIVED

        def self?.values: -> ::Array[Cadenya::Models::Agent::state]
      end
    end
  end
end
