module Cadenya
  module Models
    type agent_entry =
      {
        name: String,
        spec: Cadenya::AgentSpec,
        labels: ::Hash[Symbol, String],
        schedules: ::Hash[Symbol, Cadenya::AgentScheduleEntry],
        state: Cadenya::Models::AgentEntry::state,
        variations: ::Hash[Symbol, Cadenya::AgentVariationEntry]
      }

    class AgentEntry < Cadenya::Internal::Type::BaseModel
      attr_accessor name: String

      attr_accessor spec: Cadenya::AgentSpec

      attr_reader labels: ::Hash[Symbol, String]?

      def labels=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      attr_reader schedules: ::Hash[Symbol, Cadenya::AgentScheduleEntry]?

      def schedules=: (
        ::Hash[Symbol, Cadenya::AgentScheduleEntry]
      ) -> ::Hash[Symbol, Cadenya::AgentScheduleEntry]

      attr_reader state: Cadenya::Models::AgentEntry::state?

      def state=: (
        Cadenya::Models::AgentEntry::state
      ) -> Cadenya::Models::AgentEntry::state

      attr_reader variations: ::Hash[Symbol, Cadenya::AgentVariationEntry]?

      def variations=: (
        ::Hash[Symbol, Cadenya::AgentVariationEntry]
      ) -> ::Hash[Symbol, Cadenya::AgentVariationEntry]

      def initialize: (
        name: String,
        spec: Cadenya::AgentSpec,
        ?labels: ::Hash[Symbol, String],
        ?schedules: ::Hash[Symbol, Cadenya::AgentScheduleEntry],
        ?state: Cadenya::Models::AgentEntry::state,
        ?variations: ::Hash[Symbol, Cadenya::AgentVariationEntry]
      ) -> void

      def to_hash: -> {
        name: String,
        spec: Cadenya::AgentSpec,
        labels: ::Hash[Symbol, String],
        schedules: ::Hash[Symbol, Cadenya::AgentScheduleEntry],
        state: Cadenya::Models::AgentEntry::state,
        variations: ::Hash[Symbol, Cadenya::AgentVariationEntry]
      }

      type state =
        :STATE_UNSPECIFIED | :STATE_DRAFT | :STATE_PUBLISHED | :STATE_ARCHIVED

      module State
        extend Cadenya::Internal::Type::Enum

        STATE_UNSPECIFIED: :STATE_UNSPECIFIED
        STATE_DRAFT: :STATE_DRAFT
        STATE_PUBLISHED: :STATE_PUBLISHED
        STATE_ARCHIVED: :STATE_ARCHIVED

        def self?.values: -> ::Array[Cadenya::Models::AgentEntry::state]
      end
    end
  end
end
