module Cadenya
  module Models
    type ai_provider_credential_api_key =
      {
        api_key: Cadenya::AIProviderCredentialAPIKey::APIKey,
        type: Cadenya::Models::AIProviderCredentialAPIKey::type_
      }

    class AIProviderCredentialAPIKey < Cadenya::Internal::Type::BaseModel
      attr_accessor api_key: Cadenya::AIProviderCredentialAPIKey::APIKey

      attr_accessor type: Cadenya::Models::AIProviderCredentialAPIKey::type_

      def initialize: (
        api_key: Cadenya::AIProviderCredentialAPIKey::APIKey,
        type: Cadenya::Models::AIProviderCredentialAPIKey::type_
      ) -> void

      def to_hash: -> {
        api_key: Cadenya::AIProviderCredentialAPIKey::APIKey,
        type: Cadenya::Models::AIProviderCredentialAPIKey::type_
      }

      type api_key = { api_key: String }

      class APIKey < Cadenya::Internal::Type::BaseModel
        attr_reader api_key: String?

        def api_key=: (String) -> String

        def initialize: (?api_key: String) -> void

        def to_hash: -> { api_key: String }
      end

      type type_ = :apiKey

      module Type
        extend Cadenya::Internal::Type::Enum

        API_KEY: :apiKey

        def self?.values: -> ::Array[Cadenya::Models::AIProviderCredentialAPIKey::type_]
      end
    end
  end
end
