module Cadenya
  module Models
    type ai_provider_key_spec =
      {
        config: Cadenya::Models::AIProviderKeySpec::config,
        credentials: Cadenya::Models::AIProviderKeySpec::credentials,
        provider: Cadenya::Models::AIProviderKeySpec::provider
      }

    class AIProviderKeySpec < Cadenya::Internal::Type::BaseModel
      attr_reader config: Cadenya::Models::AIProviderKeySpec::config?

      def config=: (
        Cadenya::Models::AIProviderKeySpec::config
      ) -> Cadenya::Models::AIProviderKeySpec::config

      attr_reader credentials: Cadenya::Models::AIProviderKeySpec::credentials?

      def credentials=: (
        Cadenya::Models::AIProviderKeySpec::credentials
      ) -> Cadenya::Models::AIProviderKeySpec::credentials

      attr_reader provider: Cadenya::Models::AIProviderKeySpec::provider?

      def provider=: (
        Cadenya::Models::AIProviderKeySpec::provider
      ) -> Cadenya::Models::AIProviderKeySpec::provider

      def initialize: (
        ?config: Cadenya::Models::AIProviderKeySpec::config,
        ?credentials: Cadenya::Models::AIProviderKeySpec::credentials,
        ?provider: Cadenya::Models::AIProviderKeySpec::provider
      ) -> void

      def to_hash: -> {
        config: Cadenya::Models::AIProviderKeySpec::config,
        credentials: Cadenya::Models::AIProviderKeySpec::credentials,
        provider: Cadenya::Models::AIProviderKeySpec::provider
      }

      type config =
        Cadenya::AIProviderConfigOpenrouter
        | Cadenya::AIProviderConfigOpenAI
        | Cadenya::AIProviderConfigOpenAICompatible

      module Config
        extend Cadenya::Internal::Type::Union

        def self?.variants: -> ::Array[Cadenya::Models::AIProviderKeySpec::config]
      end

      type credentials =
        Cadenya::AIProviderCredentialAPIKey
        | Cadenya::AIProviderCredentialHeaders

      module Credentials
        extend Cadenya::Internal::Type::Union

        def self?.variants: -> ::Array[Cadenya::Models::AIProviderKeySpec::credentials]
      end

      type provider =
        :AI_PROVIDER_UNSPECIFIED
        | :AI_PROVIDER_OPENROUTER
        | :AI_PROVIDER_OPENAI
        | :AI_PROVIDER_ANTHROPIC
        | :AI_PROVIDER_GEMINI
        | :AI_PROVIDER_OPENAI_COMPATIBLE

      module Provider
        extend Cadenya::Internal::Type::Enum

        AI_PROVIDER_UNSPECIFIED: :AI_PROVIDER_UNSPECIFIED
        AI_PROVIDER_OPENROUTER: :AI_PROVIDER_OPENROUTER
        AI_PROVIDER_OPENAI: :AI_PROVIDER_OPENAI
        AI_PROVIDER_ANTHROPIC: :AI_PROVIDER_ANTHROPIC
        AI_PROVIDER_GEMINI: :AI_PROVIDER_GEMINI
        AI_PROVIDER_OPENAI_COMPATIBLE: :AI_PROVIDER_OPENAI_COMPATIBLE

        def self?.values: -> ::Array[Cadenya::Models::AIProviderKeySpec::provider]
      end
    end
  end
end
