module Cadenya
  module Models
    type ai_provider_credential_headers =
      {
        headers: Cadenya::AIProviderCredentialHeaders::Headers,
        type: Cadenya::Models::AIProviderCredentialHeaders::type_
      }

    class AIProviderCredentialHeaders < Cadenya::Internal::Type::BaseModel
      attr_accessor headers: Cadenya::AIProviderCredentialHeaders::Headers

      attr_accessor type: Cadenya::Models::AIProviderCredentialHeaders::type_

      def initialize: (
        headers: Cadenya::AIProviderCredentialHeaders::Headers,
        type: Cadenya::Models::AIProviderCredentialHeaders::type_
      ) -> void

      def to_hash: -> {
        headers: Cadenya::AIProviderCredentialHeaders::Headers,
        type: Cadenya::Models::AIProviderCredentialHeaders::type_
      }

      type headers = { headers: ::Hash[Symbol, String] }

      class Headers < Cadenya::Internal::Type::BaseModel
        attr_reader headers: ::Hash[Symbol, String]?

        def headers=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

        def initialize: (?headers: ::Hash[Symbol, String]) -> void

        def to_hash: -> { headers: ::Hash[Symbol, String] }
      end

      type type_ = :headers

      module Type
        extend Cadenya::Internal::Type::Enum

        HEADERS: :headers

        def self?.values: -> ::Array[Cadenya::Models::AIProviderCredentialHeaders::type_]
      end
    end
  end
end
