module Cadenya
  module Models
    type ai_provider_config_openrouter =
      {
        openrouter: Cadenya::AIProviderConfigOpenrouter::Openrouter,
        type: Cadenya::Models::AIProviderConfigOpenrouter::type_
      }

    class AIProviderConfigOpenrouter < Cadenya::Internal::Type::BaseModel
      attr_accessor openrouter: Cadenya::AIProviderConfigOpenrouter::Openrouter

      attr_accessor type: Cadenya::Models::AIProviderConfigOpenrouter::type_

      def initialize: (
        openrouter: Cadenya::AIProviderConfigOpenrouter::Openrouter,
        type: Cadenya::Models::AIProviderConfigOpenrouter::type_
      ) -> void

      def to_hash: -> {
        openrouter: Cadenya::AIProviderConfigOpenrouter::Openrouter,
        type: Cadenya::Models::AIProviderConfigOpenrouter::type_
      }

      type openrouter = { region: String }

      class Openrouter < Cadenya::Internal::Type::BaseModel
        attr_reader region: String?

        def region=: (String) -> String

        def initialize: (?region: String) -> void

        def to_hash: -> { region: String }
      end

      type type_ = :openrouter

      module Type
        extend Cadenya::Internal::Type::Enum

        OPENROUTER: :openrouter

        def self?.values: -> ::Array[Cadenya::Models::AIProviderConfigOpenrouter::type_]
      end
    end
  end
end
