module Cadenya
  module Models
    type api_key =
      {
        metadata: Cadenya::AccountResourceMetadata,
        spec: Cadenya::APIKeySpec,
        info: Cadenya::APIKeyInfo
      }

    class APIKey < Cadenya::Internal::Type::BaseModel
      attr_accessor metadata: Cadenya::AccountResourceMetadata

      attr_accessor spec: Cadenya::APIKeySpec

      attr_reader info: Cadenya::APIKeyInfo?

      def info=: (Cadenya::APIKeyInfo) -> Cadenya::APIKeyInfo

      def initialize: (
        metadata: Cadenya::AccountResourceMetadata,
        spec: Cadenya::APIKeySpec,
        ?info: Cadenya::APIKeyInfo
      ) -> void

      def to_hash: -> {
        metadata: Cadenya::AccountResourceMetadata,
        spec: Cadenya::APIKeySpec,
        info: Cadenya::APIKeyInfo
      }
    end
  end
end
