module Cadenya
  module Models
    type api_key_spec =
      {
        token: String,
        description: String,
        permissions: ::Array[String],
        system_: bool
      }

    class APIKeySpec < Cadenya::Internal::Type::BaseModel
      attr_reader description: String?

      def description=: (String) -> String

      attr_reader permissions: ::Array[String]?

      def permissions=: (::Array[String]) -> ::Array[String]

      attr_accessor token: String

      attr_accessor system_: bool

      def initialize: (
        token: String,
        system_: bool,
        ?description: String,
        ?permissions: ::Array[String]
      ) -> void

      def to_hash: -> {
        token: String,
        description: String,
        permissions: ::Array[String],
        system_: bool
      }
    end
  end
end
