module Cadenya
  module Models
    type approval_requirement_filter_only =
      {
        only: Cadenya::ToolFilter,
        type: Cadenya::Models::ApprovalRequirementFilterOnly::type_
      }

    class ApprovalRequirementFilterOnly < Cadenya::Internal::Type::BaseModel
      attr_accessor only: Cadenya::ToolFilter

      attr_accessor type: Cadenya::Models::ApprovalRequirementFilterOnly::type_

      def initialize: (
        only: Cadenya::ToolFilter,
        type: Cadenya::Models::ApprovalRequirementFilterOnly::type_
      ) -> void

      def to_hash: -> {
        only: Cadenya::ToolFilter,
        type: Cadenya::Models::ApprovalRequirementFilterOnly::type_
      }

      type type_ = :only

      module Type
        extend Cadenya::Internal::Type::Enum

        ONLY: :only

        def self?.values: -> ::Array[Cadenya::Models::ApprovalRequirementFilterOnly::type_]
      end
    end
  end
end
