module Cadenya
  module Models
    type approval_requirement_filter =
      Cadenya::ApprovalRequirementFilterAlways
      | Cadenya::ApprovalRequirementFilterOnly

    module ApprovalRequirementFilter
      extend Cadenya::Internal::Type::Union

      def self?.variants: -> ::Array[Cadenya::Models::approval_requirement_filter]
    end
  end
end
