module Cadenya
  module Models
    type approval_requirement_filter =
      { always: bool, only: Cadenya::ToolFilter, type: String }

    class ApprovalRequirementFilter < Cadenya::Internal::Type::BaseModel
      attr_reader always: bool?

      def always=: (bool) -> bool

      attr_reader only: Cadenya::ToolFilter?

      def only=: (Cadenya::ToolFilter) -> Cadenya::ToolFilter

      attr_reader type: String?

      def type=: (String) -> String

      def initialize: (
        ?always: bool,
        ?only: Cadenya::ToolFilter,
        ?type: String
      ) -> void

      def to_hash: -> { always: bool, only: Cadenya::ToolFilter, type: String }
    end
  end
end
