module Cadenya
  module Models
    type assistant_tool_call =
      {
        arguments: String,
        function_name: String,
        tool: Cadenya::Models::callable_tool
      }

    class AssistantToolCall < Cadenya::Internal::Type::BaseModel
      attr_reader arguments: String?

      def arguments=: (String) -> String

      attr_reader function_name: String?

      def function_name=: (String) -> String

      attr_reader tool: Cadenya::Models::callable_tool?

      def tool=: (
        Cadenya::Models::callable_tool
      ) -> Cadenya::Models::callable_tool

      def initialize: (
        ?arguments: String,
        ?function_name: String,
        ?tool: Cadenya::Models::callable_tool
      ) -> void

      def to_hash: -> {
        arguments: String,
        function_name: String,
        tool: Cadenya::Models::callable_tool
      }
    end
  end
end
