module Cadenya
  module Models
    type attribute_filter =
      {
        attribute: Cadenya::Models::AttributeFilter::attribute,
        matcher: Cadenya::StringMatcher
      }

    class AttributeFilter < Cadenya::Internal::Type::BaseModel
      attr_accessor attribute: Cadenya::Models::AttributeFilter::attribute

      attr_reader matcher: Cadenya::StringMatcher?

      def matcher=: (Cadenya::StringMatcher) -> Cadenya::StringMatcher

      def initialize: (
        attribute: Cadenya::Models::AttributeFilter::attribute,
        ?matcher: Cadenya::StringMatcher
      ) -> void

      def to_hash: -> {
        attribute: Cadenya::Models::AttributeFilter::attribute,
        matcher: Cadenya::StringMatcher
      }

      type attribute =
        :ATTRIBUTE_UNSPECIFIED
        | :ATTRIBUTE_NAME
        | :ATTRIBUTE_TITLE
        | :ATTRIBUTE_DESCRIPTION

      module Attribute
        extend Cadenya::Internal::Type::Enum

        ATTRIBUTE_UNSPECIFIED: :ATTRIBUTE_UNSPECIFIED
        ATTRIBUTE_NAME: :ATTRIBUTE_NAME
        ATTRIBUTE_TITLE: :ATTRIBUTE_TITLE
        ATTRIBUTE_DESCRIPTION: :ATTRIBUTE_DESCRIPTION

        def self?.values: -> ::Array[Cadenya::Models::AttributeFilter::attribute]
      end
    end
  end
end
