module Cadenya
  module Models
    type bulk_workspace_apply_info =
      {
        completed_at: Time,
        created_by: Cadenya::Profile,
        created_count: Integer,
        deleted_count: Integer,
        failed_count: Integer,
        started_at: Time,
        total_count: Integer,
        unchanged_count: Integer,
        updated_count: Integer
      }

    class BulkWorkspaceApplyInfo < Cadenya::Internal::Type::BaseModel
      attr_reader created_by: Cadenya::Profile?

      def created_by=: (Cadenya::Profile) -> Cadenya::Profile

      attr_reader completed_at: Time?

      def completed_at=: (Time) -> Time

      attr_reader created_count: Integer?

      def created_count=: (Integer) -> Integer

      attr_reader deleted_count: Integer?

      def deleted_count=: (Integer) -> Integer

      attr_reader failed_count: Integer?

      def failed_count=: (Integer) -> Integer

      attr_reader started_at: Time?

      def started_at=: (Time) -> Time

      attr_reader total_count: Integer?

      def total_count=: (Integer) -> Integer

      attr_reader unchanged_count: Integer?

      def unchanged_count=: (Integer) -> Integer

      attr_reader updated_count: Integer?

      def updated_count=: (Integer) -> Integer

      def initialize: (
        ?completed_at: Time,
        ?created_by: Cadenya::Profile,
        ?created_count: Integer,
        ?deleted_count: Integer,
        ?failed_count: Integer,
        ?started_at: Time,
        ?total_count: Integer,
        ?unchanged_count: Integer,
        ?updated_count: Integer
      ) -> void

      def to_hash: -> {
        completed_at: Time,
        created_by: Cadenya::Profile,
        created_count: Integer,
        deleted_count: Integer,
        failed_count: Integer,
        started_at: Time,
        total_count: Integer,
        unchanged_count: Integer,
        updated_count: Integer
      }
    end
  end
end
