module Cadenya
  module Models
    type callable_tool =
      Cadenya::CallableToolTool
      | Cadenya::CallableToolAgent
      | Cadenya::CallableToolCadenyaProvidedTool

    module CallableTool
      extend Cadenya::Internal::Type::Union

      def self?.variants: -> ::Array[Cadenya::Models::callable_tool]
    end
  end
end
