module Cadenya
  module Models
    type callable_tool_cadenya_provided_tool =
      {
        cadenya_provided_tool: Cadenya::ResourceMetadata,
        type: Cadenya::Models::CallableToolCadenyaProvidedTool::type_
      }

    class CallableToolCadenyaProvidedTool < Cadenya::Internal::Type::BaseModel
      attr_accessor cadenya_provided_tool: Cadenya::ResourceMetadata

      attr_accessor type: Cadenya::Models::CallableToolCadenyaProvidedTool::type_

      def initialize: (
        cadenya_provided_tool: Cadenya::ResourceMetadata,
        type: Cadenya::Models::CallableToolCadenyaProvidedTool::type_
      ) -> void

      def to_hash: -> {
        cadenya_provided_tool: Cadenya::ResourceMetadata,
        type: Cadenya::Models::CallableToolCadenyaProvidedTool::type_
      }

      type type_ = :cadenyaProvidedTool

      module Type
        extend Cadenya::Internal::Type::Enum

        CADENYA_PROVIDED_TOOL: :cadenyaProvidedTool

        def self?.values: -> ::Array[Cadenya::Models::CallableToolCadenyaProvidedTool::type_]
      end
    end
  end
end
