module Cadenya
  module Models
    type callable_tool =
      {
        agent: Cadenya::ResourceMetadata,
        cadenya_provided_tool: Cadenya::ResourceMetadata,
        tool: Cadenya::ResourceMetadata,
        type: String
      }

    class CallableTool < Cadenya::Internal::Type::BaseModel
      attr_reader agent: Cadenya::ResourceMetadata?

      def agent=: (Cadenya::ResourceMetadata) -> Cadenya::ResourceMetadata

      attr_reader cadenya_provided_tool: Cadenya::ResourceMetadata?

      def cadenya_provided_tool=: (
        Cadenya::ResourceMetadata
      ) -> Cadenya::ResourceMetadata

      attr_reader tool: Cadenya::ResourceMetadata?

      def tool=: (Cadenya::ResourceMetadata) -> Cadenya::ResourceMetadata

      attr_reader type: String?

      def type=: (String) -> String

      def initialize: (
        ?agent: Cadenya::ResourceMetadata,
        ?cadenya_provided_tool: Cadenya::ResourceMetadata,
        ?tool: Cadenya::ResourceMetadata,
        ?type: String
      ) -> void

      def to_hash: -> {
        agent: Cadenya::ResourceMetadata,
        cadenya_provided_tool: Cadenya::ResourceMetadata,
        tool: Cadenya::ResourceMetadata,
        type: String
      }
    end
  end
end
