module Cadenya
  module Models
    type context_window_compacted =
      {
        messages_compacted: Integer,
        new_context_window: Cadenya::ObjectiveContextWindowData,
        strategies: ::Array[String],
        summary: String
      }

    class ContextWindowCompacted < Cadenya::Internal::Type::BaseModel
      attr_accessor messages_compacted: Integer

      attr_accessor new_context_window: Cadenya::ObjectiveContextWindowData

      attr_accessor strategies: ::Array[String]

      attr_reader summary: String?

      def summary=: (String) -> String

      def initialize: (
        messages_compacted: Integer,
        new_context_window: Cadenya::ObjectiveContextWindowData,
        strategies: ::Array[String],
        ?summary: String
      ) -> void

      def to_hash: -> {
        messages_compacted: Integer,
        new_context_window: Cadenya::ObjectiveContextWindowData,
        strategies: ::Array[String],
        summary: String
      }
    end
  end
end
