module Cadenya
  module Models
    type global_api_key_retrieve_params =
      {  } & Cadenya::Internal::Type::request_parameters

    class GlobalAPIKeyRetrieveParams < Cadenya::Internal::Type::BaseModel
      extend Cadenya::Internal::Type::RequestParameters::Converter
      include Cadenya::Internal::Type::RequestParameters

      def initialize: (?request_options: Cadenya::request_opts) -> void

      def to_hash: -> { request_options: Cadenya::RequestOptions }
    end
  end
end
