module Cadenya
  module Models
    type memory_reference = { memory_entry_id: String, memory_layer_id: String }

    class MemoryReference < Cadenya::Internal::Type::BaseModel
      attr_reader memory_entry_id: String?

      def memory_entry_id=: (String) -> String

      attr_reader memory_layer_id: String?

      def memory_layer_id=: (String) -> String

      def initialize: (
        ?memory_entry_id: String,
        ?memory_layer_id: String
      ) -> void

      def to_hash: -> { memory_entry_id: String, memory_layer_id: String }
    end
  end
end
