module Cadenya
  module Models
    type memory_read =
      { memory_entry_id: String, memory_layer_id: String, message: String }

    class MemoryRead < Cadenya::Internal::Type::BaseModel
      attr_accessor memory_entry_id: String

      attr_accessor memory_layer_id: String

      attr_accessor message: String

      def initialize: (
        memory_entry_id: String,
        memory_layer_id: String,
        message: String
      ) -> void

      def to_hash: -> {
        memory_entry_id: String,
        memory_layer_id: String,
        message: String
      }
    end
  end
end
