module Cadenya
  module Models
    type memory_layer_entry =
      {
        name: String,
        spec: Cadenya::MemoryLayerSpec,
        entries: ::Hash[Symbol, Cadenya::MemoryEntryItem],
        labels: ::Hash[Symbol, String]
      }

    class MemoryLayerEntry < Cadenya::Internal::Type::BaseModel
      attr_accessor name: String

      attr_accessor spec: Cadenya::MemoryLayerSpec

      attr_reader entries: ::Hash[Symbol, Cadenya::MemoryEntryItem]?

      def entries=: (
        ::Hash[Symbol, Cadenya::MemoryEntryItem]
      ) -> ::Hash[Symbol, Cadenya::MemoryEntryItem]

      attr_reader labels: ::Hash[Symbol, String]?

      def labels=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      def initialize: (
        name: String,
        spec: Cadenya::MemoryLayerSpec,
        ?entries: ::Hash[Symbol, Cadenya::MemoryEntryItem],
        ?labels: ::Hash[Symbol, String]
      ) -> void

      def to_hash: -> {
        name: String,
        spec: Cadenya::MemoryLayerSpec,
        entries: ::Hash[Symbol, Cadenya::MemoryEntryItem],
        labels: ::Hash[Symbol, String]
      }
    end
  end
end
