module Cadenya
  module Models
    type memory_reference = { memory_layer_id: String, memory_entry_id: String }

    class MemoryReference < Cadenya::Internal::Type::BaseModel
      attr_accessor memory_layer_id: String

      attr_reader memory_entry_id: String?

      def memory_entry_id=: (String) -> String

      def initialize: (
        memory_layer_id: String,
        ?memory_entry_id: String
      ) -> void

      def to_hash: -> { memory_layer_id: String, memory_entry_id: String }
    end
  end
end
