module Cadenya
  module Models
    type memory_layer =
      {
        metadata: Cadenya::ResourceMetadata,
        spec: Cadenya::MemoryLayerSpec,
        info: Cadenya::MemoryLayerInfo
      }

    class MemoryLayer < Cadenya::Internal::Type::BaseModel
      attr_accessor metadata: Cadenya::ResourceMetadata

      attr_accessor spec: Cadenya::MemoryLayerSpec

      attr_reader info: Cadenya::MemoryLayerInfo?

      def info=: (Cadenya::MemoryLayerInfo) -> Cadenya::MemoryLayerInfo

      def initialize: (
        metadata: Cadenya::ResourceMetadata,
        spec: Cadenya::MemoryLayerSpec,
        ?info: Cadenya::MemoryLayerInfo
      ) -> void

      def to_hash: -> {
        metadata: Cadenya::ResourceMetadata,
        spec: Cadenya::MemoryLayerSpec,
        info: Cadenya::MemoryLayerInfo
      }
    end
  end
end
