module Cadenya
  module Models
    type memory_layer_info =
      {
        agent: Cadenya::ResourceMetadata,
        created_by: Cadenya::Profile,
        entry_count: Integer,
        last_used_at: Time
      }

    class MemoryLayerInfo < Cadenya::Internal::Type::BaseModel
      attr_reader created_by: Cadenya::Profile?

      def created_by=: (Cadenya::Profile) -> Cadenya::Profile

      attr_reader agent: Cadenya::ResourceMetadata?

      def agent=: (Cadenya::ResourceMetadata) -> Cadenya::ResourceMetadata

      attr_accessor entry_count: Integer

      attr_reader last_used_at: Time?

      def last_used_at=: (Time) -> Time

      def initialize: (
        entry_count: Integer,
        ?agent: Cadenya::ResourceMetadata,
        ?created_by: Cadenya::Profile,
        ?last_used_at: Time
      ) -> void

      def to_hash: -> {
        agent: Cadenya::ResourceMetadata,
        created_by: Cadenya::Profile,
        entry_count: Integer,
        last_used_at: Time
      }
    end
  end
end
