module Cadenya
  module Models
    type model_spec =
      {
        family: String,
        provider: String,
        input_price_per_million_tokens: String,
        max_input_tokens: Integer,
        max_output_tokens: Integer,
        output_price_per_million_tokens: String,
        reasoning: Cadenya::Models::ModelSpec::reasoning
      }

    class ModelSpec < Cadenya::Internal::Type::BaseModel
      attr_accessor family: String

      attr_accessor provider: String

      attr_reader input_price_per_million_tokens: String?

      def input_price_per_million_tokens=: (String) -> String

      attr_reader max_input_tokens: Integer?

      def max_input_tokens=: (Integer) -> Integer

      attr_reader max_output_tokens: Integer?

      def max_output_tokens=: (Integer) -> Integer

      attr_reader output_price_per_million_tokens: String?

      def output_price_per_million_tokens=: (String) -> String

      attr_reader reasoning: Cadenya::Models::ModelSpec::reasoning?

      def reasoning=: (
        Cadenya::Models::ModelSpec::reasoning
      ) -> Cadenya::Models::ModelSpec::reasoning

      def initialize: (
        family: String,
        provider: String,
        ?input_price_per_million_tokens: String,
        ?max_input_tokens: Integer,
        ?max_output_tokens: Integer,
        ?output_price_per_million_tokens: String,
        ?reasoning: Cadenya::Models::ModelSpec::reasoning
      ) -> void

      def to_hash: -> {
        family: String,
        provider: String,
        input_price_per_million_tokens: String,
        max_input_tokens: Integer,
        max_output_tokens: Integer,
        output_price_per_million_tokens: String,
        reasoning: Cadenya::Models::ModelSpec::reasoning
      }

      type reasoning =
        :REASONING_UNSPECIFIED
        | :REASONING_NONE
        | :REASONING_ADAPTIVE
        | :REASONING_BUDGET

      module Reasoning
        extend Cadenya::Internal::Type::Enum

        REASONING_UNSPECIFIED: :REASONING_UNSPECIFIED
        REASONING_NONE: :REASONING_NONE
        REASONING_ADAPTIVE: :REASONING_ADAPTIVE
        REASONING_BUDGET: :REASONING_BUDGET

        def self?.values: -> ::Array[Cadenya::Models::ModelSpec::reasoning]
      end
    end
  end
end
