module Cadenya
  module Models
    type model_spec_capability_top_p =
      { top_p: top, type: Cadenya::Models::ModelSpecCapabilityTopP::type_ }

    class ModelSpecCapabilityTopP < Cadenya::Internal::Type::BaseModel
      attr_accessor top_p: top

      attr_accessor type: Cadenya::Models::ModelSpecCapabilityTopP::type_

      def initialize: (
        top_p: top,
        type: Cadenya::Models::ModelSpecCapabilityTopP::type_
      ) -> void

      def to_hash: -> {
        top_p: top,
        type: Cadenya::Models::ModelSpecCapabilityTopP::type_
      }

      type type_ = :topP

      module Type
        extend Cadenya::Internal::Type::Enum

        TOP_P: :topP

        def self?.values: -> ::Array[Cadenya::Models::ModelSpecCapabilityTopP::type_]
      end
    end
  end
end
