module Cadenya
  module Models
    type model =
      {
        metadata: Cadenya::ResourceMetadata,
        spec: Cadenya::ModelSpec,
        state: Cadenya::Models::Model::state,
        info: Cadenya::Model::Info
      }

    class Model < Cadenya::Internal::Type::BaseModel
      attr_accessor metadata: Cadenya::ResourceMetadata

      attr_accessor spec: Cadenya::ModelSpec

      attr_accessor state: Cadenya::Models::Model::state

      attr_reader info: Cadenya::Model::Info?

      def info=: (Cadenya::Model::Info) -> Cadenya::Model::Info

      def initialize: (
        metadata: Cadenya::ResourceMetadata,
        spec: Cadenya::ModelSpec,
        state: Cadenya::Models::Model::state,
        ?info: Cadenya::Model::Info
      ) -> void

      def to_hash: -> {
        metadata: Cadenya::ResourceMetadata,
        spec: Cadenya::ModelSpec,
        state: Cadenya::Models::Model::state,
        info: Cadenya::Model::Info
      }

      type state = :STATE_UNSPECIFIED | :STATE_ENABLED | :STATE_DISABLED

      module State
        extend Cadenya::Internal::Type::Enum

        STATE_UNSPECIFIED: :STATE_UNSPECIFIED
        STATE_ENABLED: :STATE_ENABLED
        STATE_DISABLED: :STATE_DISABLED

        def self?.values: -> ::Array[Cadenya::Models::Model::state]
      end

      type info =
        {
          agent_variation_count: Integer,
          ai_provider_key: Cadenya::AIProviderKey,
          last_used_at: Time
        }

      class Info < Cadenya::Internal::Type::BaseModel
        attr_reader agent_variation_count: Integer?

        def agent_variation_count=: (Integer) -> Integer

        attr_reader ai_provider_key: Cadenya::AIProviderKey?

        def ai_provider_key=: (Cadenya::AIProviderKey) -> Cadenya::AIProviderKey

        attr_reader last_used_at: Time?

        def last_used_at=: (Time) -> Time

        def initialize: (
          ?agent_variation_count: Integer,
          ?ai_provider_key: Cadenya::AIProviderKey,
          ?last_used_at: Time
        ) -> void

        def to_hash: -> {
          agent_variation_count: Integer,
          ai_provider_key: Cadenya::AIProviderKey,
          last_used_at: Time
        }
      end
    end
  end
end
