module Cadenya
  module Models
    type model_spec_capability =
      Cadenya::ModelSpecCapabilityTemperature
      | Cadenya::ModelSpecCapabilityTopP
      | Cadenya::ModelSpecCapabilityTopK
      | Cadenya::ModelSpecCapabilityStopSequences
      | Cadenya::ModelSpecCapabilityMaxOutputTokens
      | Cadenya::ModelSpecCapabilityReasoning

    module ModelSpecCapability
      extend Cadenya::Internal::Type::Union

      def self?.variants: -> ::Array[Cadenya::Models::model_spec_capability]
    end
  end
end
