module Cadenya
  module Models
    type model_spec =
      {
        family: String,
        provider: String,
        capabilities: ::Array[Cadenya::Models::model_spec_capability],
        input_price_per_million_tokens: String,
        max_input_tokens: Integer,
        max_output_tokens: Integer,
        output_price_per_million_tokens: String
      }

    class ModelSpec < Cadenya::Internal::Type::BaseModel
      attr_accessor family: String

      attr_accessor provider: String

      attr_reader capabilities: ::Array[Cadenya::Models::model_spec_capability]?

      def capabilities=: (
        ::Array[Cadenya::Models::model_spec_capability]
      ) -> ::Array[Cadenya::Models::model_spec_capability]

      attr_reader input_price_per_million_tokens: String?

      def input_price_per_million_tokens=: (String) -> String

      attr_reader max_input_tokens: Integer?

      def max_input_tokens=: (Integer) -> Integer

      attr_reader max_output_tokens: Integer?

      def max_output_tokens=: (Integer) -> Integer

      attr_reader output_price_per_million_tokens: String?

      def output_price_per_million_tokens=: (String) -> String

      def initialize: (
        family: String,
        provider: String,
        ?capabilities: ::Array[Cadenya::Models::model_spec_capability],
        ?input_price_per_million_tokens: String,
        ?max_input_tokens: Integer,
        ?max_output_tokens: Integer,
        ?output_price_per_million_tokens: String
      ) -> void

      def to_hash: -> {
        family: String,
        provider: String,
        capabilities: ::Array[Cadenya::Models::model_spec_capability],
        input_price_per_million_tokens: String,
        max_input_tokens: Integer,
        max_output_tokens: Integer,
        output_price_per_million_tokens: String
      }
    end
  end
end
