module Cadenya
  module Models
    type model_spec =
      {
        family: String,
        provider: String,
        capabilities: ::Array[Cadenya::Models::model_spec_capability],
        input_price_per_million_tokens: String,
        max_input_tokens: Integer,
        max_output_tokens: Integer,
        output_price_per_million_tokens: String
      }

    class ModelSpec < Cadenya::Internal::Type::BaseModel
      attr_accessor family: String

      attr_accessor provider: String

      attr_accessor capabilities: ::Array[Cadenya::Models::model_spec_capability]

      attr_accessor input_price_per_million_tokens: String

      attr_accessor max_input_tokens: Integer

      attr_accessor max_output_tokens: Integer

      attr_accessor output_price_per_million_tokens: String

      def initialize: (
        family: String,
        provider: String,
        capabilities: ::Array[Cadenya::Models::model_spec_capability],
        input_price_per_million_tokens: String,
        max_input_tokens: Integer,
        max_output_tokens: Integer,
        output_price_per_million_tokens: String
      ) -> void

      def to_hash: -> {
        family: String,
        provider: String,
        capabilities: ::Array[Cadenya::Models::model_spec_capability],
        input_price_per_million_tokens: String,
        max_input_tokens: Integer,
        max_output_tokens: Integer,
        output_price_per_million_tokens: String
      }
    end
  end
end
