module Cadenya
  module Models
    type model_list_params =
      {
        workspace_id: String,
        ai_provider_key_id: String,
        cursor: String,
        include_info: bool,
        is_assigned: bool,
        labels: String,
        limit: Integer,
        prefix: String,
        query: String,
        sort_order: String,
        state: Cadenya::Models::ModelListParams::state
      }
      & Cadenya::Internal::Type::request_parameters

    class ModelListParams < Cadenya::Internal::Type::BaseModel
      extend Cadenya::Internal::Type::RequestParameters::Converter
      include Cadenya::Internal::Type::RequestParameters

      attr_accessor workspace_id: String

      attr_reader ai_provider_key_id: String?

      def ai_provider_key_id=: (String) -> String

      attr_reader cursor: String?

      def cursor=: (String) -> String

      attr_reader include_info: bool?

      def include_info=: (bool) -> bool

      attr_reader is_assigned: bool?

      def is_assigned=: (bool) -> bool

      attr_reader labels: String?

      def labels=: (String) -> String

      attr_reader limit: Integer?

      def limit=: (Integer) -> Integer

      attr_reader prefix: String?

      def prefix=: (String) -> String

      attr_reader query: String?

      def query=: (String) -> String

      attr_reader sort_order: String?

      def sort_order=: (String) -> String

      attr_reader state: Cadenya::Models::ModelListParams::state?

      def state=: (
        Cadenya::Models::ModelListParams::state
      ) -> Cadenya::Models::ModelListParams::state

      def initialize: (
        workspace_id: String,
        ?ai_provider_key_id: String,
        ?cursor: String,
        ?include_info: bool,
        ?is_assigned: bool,
        ?labels: String,
        ?limit: Integer,
        ?prefix: String,
        ?query: String,
        ?sort_order: String,
        ?state: Cadenya::Models::ModelListParams::state,
        ?request_options: Cadenya::request_opts
      ) -> void

      def to_hash: -> {
        workspace_id: String,
        ai_provider_key_id: String,
        cursor: String,
        include_info: bool,
        is_assigned: bool,
        labels: String,
        limit: Integer,
        prefix: String,
        query: String,
        sort_order: String,
        state: Cadenya::Models::ModelListParams::state,
        request_options: Cadenya::RequestOptions
      }

      type state = :STATE_UNSPECIFIED | :STATE_ENABLED | :STATE_DISABLED

      module State
        extend Cadenya::Internal::Type::Enum

        STATE_UNSPECIFIED: :STATE_UNSPECIFIED
        STATE_ENABLED: :STATE_ENABLED
        STATE_DISABLED: :STATE_DISABLED

        def self?.values: -> ::Array[Cadenya::Models::ModelListParams::state]
      end
    end
  end
end
