module Cadenya
  module Models
    type model_spec_capability_stop_sequences =
      {
        stop_sequences: Cadenya::CapabilityStopSequences,
        type: Cadenya::Models::ModelSpecCapabilityStopSequences::type_
      }

    class ModelSpecCapabilityStopSequences < Cadenya::Internal::Type::BaseModel
      attr_accessor stop_sequences: Cadenya::CapabilityStopSequences

      attr_accessor type: Cadenya::Models::ModelSpecCapabilityStopSequences::type_

      def initialize: (
        stop_sequences: Cadenya::CapabilityStopSequences,
        type: Cadenya::Models::ModelSpecCapabilityStopSequences::type_
      ) -> void

      def to_hash: -> {
        stop_sequences: Cadenya::CapabilityStopSequences,
        type: Cadenya::Models::ModelSpecCapabilityStopSequences::type_
      }

      type type_ = :stopSequences

      module Type
        extend Cadenya::Internal::Type::Enum

        STOP_SEQUENCES: :stopSequences

        def self?.values: -> ::Array[Cadenya::Models::ModelSpecCapabilityStopSequences::type_]
      end
    end
  end
end
