module Cadenya
  module Models
    type model_spec_capability_top_k =
      { top_k: top, type: Cadenya::Models::ModelSpecCapabilityTopK::type_ }

    class ModelSpecCapabilityTopK < Cadenya::Internal::Type::BaseModel
      attr_accessor top_k: top

      attr_accessor type: Cadenya::Models::ModelSpecCapabilityTopK::type_

      def initialize: (
        top_k: top,
        type: Cadenya::Models::ModelSpecCapabilityTopK::type_
      ) -> void

      def to_hash: -> {
        top_k: top,
        type: Cadenya::Models::ModelSpecCapabilityTopK::type_
      }

      type type_ = :topK

      module Type
        extend Cadenya::Internal::Type::Enum

        TOP_K: :topK

        def self?.values: -> ::Array[Cadenya::Models::ModelSpecCapabilityTopK::type_]
      end
    end
  end
end
