module Cadenya
  module Models
    type objective_info =
      {
        agent: Cadenya::ResourceMetadata,
        agent_variation: Cadenya::ResourceMetadata,
        created_by: Cadenya::Profile,
        current_context_window_id: String,
        effective_memory_cascade: ::Array[Cadenya::MemoryReference],
        total_context_windows: Integer,
        total_events: Integer,
        total_input_tokens: Integer,
        total_iterations: Integer,
        total_output_tokens: Integer,
        total_tool_calls: Integer,
        subject: Cadenya::SubjectReference,
        tenant: Cadenya::TenantReference,
        widget: Cadenya::BareMetadata
      }

    class ObjectiveInfo < Cadenya::Internal::Type::BaseModel
      attr_accessor created_by: Cadenya::Profile

      attr_accessor agent: Cadenya::ResourceMetadata

      attr_accessor agent_variation: Cadenya::ResourceMetadata

      attr_accessor current_context_window_id: String

      attr_accessor effective_memory_cascade: ::Array[Cadenya::MemoryReference]

      attr_accessor total_context_windows: Integer

      attr_accessor total_events: Integer

      attr_accessor total_input_tokens: Integer

      attr_accessor total_iterations: Integer

      attr_accessor total_output_tokens: Integer

      attr_accessor total_tool_calls: Integer

      attr_reader subject: Cadenya::SubjectReference?

      def subject=: (Cadenya::SubjectReference) -> Cadenya::SubjectReference

      attr_reader tenant: Cadenya::TenantReference?

      def tenant=: (Cadenya::TenantReference) -> Cadenya::TenantReference

      attr_reader widget: Cadenya::BareMetadata?

      def widget=: (Cadenya::BareMetadata) -> Cadenya::BareMetadata

      def initialize: (
        agent: Cadenya::ResourceMetadata,
        agent_variation: Cadenya::ResourceMetadata,
        created_by: Cadenya::Profile,
        current_context_window_id: String,
        effective_memory_cascade: ::Array[Cadenya::MemoryReference],
        total_context_windows: Integer,
        total_events: Integer,
        total_input_tokens: Integer,
        total_iterations: Integer,
        total_output_tokens: Integer,
        total_tool_calls: Integer,
        ?subject: Cadenya::SubjectReference,
        ?tenant: Cadenya::TenantReference,
        ?widget: Cadenya::BareMetadata
      ) -> void

      def to_hash: -> {
        agent: Cadenya::ResourceMetadata,
        agent_variation: Cadenya::ResourceMetadata,
        created_by: Cadenya::Profile,
        current_context_window_id: String,
        effective_memory_cascade: ::Array[Cadenya::MemoryReference],
        total_context_windows: Integer,
        total_events: Integer,
        total_input_tokens: Integer,
        total_iterations: Integer,
        total_output_tokens: Integer,
        total_tool_calls: Integer,
        subject: Cadenya::SubjectReference,
        tenant: Cadenya::TenantReference,
        widget: Cadenya::BareMetadata
      }
    end
  end
end
