module Cadenya
  module Models
    type objective_config_snapshot =
      {
        agent: Cadenya::Agent,
        agent_schedule: Cadenya::Agents::AgentSchedule,
        agent_variation: Cadenya::Agents::AgentVariation
      }

    class ObjectiveConfigSnapshot < Cadenya::Internal::Type::BaseModel
      attr_accessor agent: Cadenya::Agent

      attr_reader agent_schedule: Cadenya::Agents::AgentSchedule?

      def agent_schedule=: (
        Cadenya::Agents::AgentSchedule
      ) -> Cadenya::Agents::AgentSchedule

      attr_accessor agent_variation: Cadenya::Agents::AgentVariation

      def initialize: (
        agent: Cadenya::Agent,
        agent_variation: Cadenya::Agents::AgentVariation,
        ?agent_schedule: Cadenya::Agents::AgentSchedule
      ) -> void

      def to_hash: -> {
        agent: Cadenya::Agent,
        agent_schedule: Cadenya::Agents::AgentSchedule,
        agent_variation: Cadenya::Agents::AgentVariation
      }
    end
  end
end
