module Cadenya
  module Models
    type objective_event_data_reasoning =
      {
        reasoning: Cadenya::Reasoning,
        type: Cadenya::Models::ObjectiveEventDataReasoning::type_
      }

    class ObjectiveEventDataReasoning < Cadenya::Internal::Type::BaseModel
      attr_accessor reasoning: Cadenya::Reasoning

      attr_accessor type: Cadenya::Models::ObjectiveEventDataReasoning::type_

      def initialize: (
        reasoning: Cadenya::Reasoning,
        type: Cadenya::Models::ObjectiveEventDataReasoning::type_
      ) -> void

      def to_hash: -> {
        reasoning: Cadenya::Reasoning,
        type: Cadenya::Models::ObjectiveEventDataReasoning::type_
      }

      type type_ = :reasoning

      module Type
        extend Cadenya::Internal::Type::Enum

        REASONING: :reasoning

        def self?.values: -> ::Array[Cadenya::Models::ObjectiveEventDataReasoning::type_]
      end
    end
  end
end
