module Cadenya
  module Models
    type objective_continue_params =
      {
        workspace_id: String,
        objective_id: String,
        enqueue: bool,
        message: String,
        secrets: ::Array[Cadenya::ObjectiveContinueParams::Secret]
      }
      & Cadenya::Internal::Type::request_parameters

    class ObjectiveContinueParams < Cadenya::Internal::Type::BaseModel
      extend Cadenya::Internal::Type::RequestParameters::Converter
      include Cadenya::Internal::Type::RequestParameters

      attr_accessor workspace_id: String

      attr_accessor objective_id: String

      attr_reader enqueue: bool?

      def enqueue=: (bool) -> bool

      attr_reader message: String?

      def message=: (String) -> String

      attr_reader secrets: ::Array[Cadenya::ObjectiveContinueParams::Secret]?

      def secrets=: (
        ::Array[Cadenya::ObjectiveContinueParams::Secret]
      ) -> ::Array[Cadenya::ObjectiveContinueParams::Secret]

      def initialize: (
        workspace_id: String,
        objective_id: String,
        ?enqueue: bool,
        ?message: String,
        ?secrets: ::Array[Cadenya::ObjectiveContinueParams::Secret],
        ?request_options: Cadenya::request_opts
      ) -> void

      def to_hash: -> {
        workspace_id: String,
        objective_id: String,
        enqueue: bool,
        message: String,
        secrets: ::Array[Cadenya::ObjectiveContinueParams::Secret],
        request_options: Cadenya::RequestOptions
      }

      type secret = { name: String, value: String }

      class Secret < Cadenya::Internal::Type::BaseModel
        attr_reader name: String?

        def name=: (String) -> String

        attr_reader value: String?

        def value=: (String) -> String

        def initialize: (?name: String, ?value: String) -> void

        def to_hash: -> { name: String, value: String }
      end
    end
  end
end
