module Cadenya
  module Models
    type objective_event_data_finalized =
      {
        finalized: Cadenya::ObjectiveEventDataFinalized::Finalized,
        type: Cadenya::Models::ObjectiveEventDataFinalized::type_
      }

    class ObjectiveEventDataFinalized < Cadenya::Internal::Type::BaseModel
      attr_accessor finalized: Cadenya::ObjectiveEventDataFinalized::Finalized

      attr_accessor type: Cadenya::Models::ObjectiveEventDataFinalized::type_

      def initialize: (
        finalized: Cadenya::ObjectiveEventDataFinalized::Finalized,
        type: Cadenya::Models::ObjectiveEventDataFinalized::type_
      ) -> void

      def to_hash: -> {
        finalized: Cadenya::ObjectiveEventDataFinalized::Finalized,
        type: Cadenya::Models::ObjectiveEventDataFinalized::type_
      }

      type finalized = { output: top }

      class Finalized < Cadenya::Internal::Type::BaseModel
        attr_reader output: top?

        def output=: (top) -> top

        def initialize: (?output: top) -> void

        def to_hash: -> { output: top }
      end

      type type_ = :finalized

      module Type
        extend Cadenya::Internal::Type::Enum

        FINALIZED: :finalized

        def self?.values: -> ::Array[Cadenya::Models::ObjectiveEventDataFinalized::type_]
      end
    end
  end
end
