module Cadenya
  module Models
    type objective_retrieve_params =
      { workspace_id: String, id: String }
      & Cadenya::Internal::Type::request_parameters

    class ObjectiveRetrieveParams < Cadenya::Internal::Type::BaseModel
      extend Cadenya::Internal::Type::RequestParameters::Converter
      include Cadenya::Internal::Type::RequestParameters

      attr_reader workspace_id: String?

      def workspace_id=: (String) -> String

      attr_accessor id: String

      def initialize: (
        id: String,
        ?workspace_id: String,
        ?request_options: Cadenya::request_opts
      ) -> void

      def to_hash: -> {
        workspace_id: String,
        id: String,
        request_options: Cadenya::RequestOptions
      }
    end
  end
end
