module Cadenya
  module Models
    type objective_event_info =
      { created_by: Cadenya::Profile, objective: Cadenya::OperationMetadata }

    class ObjectiveEventInfo < Cadenya::Internal::Type::BaseModel
      attr_reader created_by: Cadenya::Profile?

      def created_by=: (Cadenya::Profile) -> Cadenya::Profile

      attr_reader objective: Cadenya::OperationMetadata?

      def objective=: (Cadenya::OperationMetadata) -> Cadenya::OperationMetadata

      def initialize: (
        ?created_by: Cadenya::Profile,
        ?objective: Cadenya::OperationMetadata
      ) -> void

      def to_hash: -> {
        created_by: Cadenya::Profile,
        objective: Cadenya::OperationMetadata
      }
    end
  end
end
