module Cadenya
  module Models
    type objective_create_params =
      {
        workspace_id: String,
        agent_id: String,
        system_prompt_data: ::Hash[Symbol, top],
        episodic_memory: Cadenya::ObjectiveCreateParams::EpisodicMemory,
        first_user_message: String,
        first_user_message_data: ::Hash[Symbol, top],
        memory_cascade: ::Array[Cadenya::MemoryReference],
        metadata: Cadenya::CreateOperationMetadata,
        secrets: ::Array[Cadenya::ObjectiveCreateParams::Secret],
        variation_id: String
      }
      & Cadenya::Internal::Type::request_parameters

    class ObjectiveCreateParams < Cadenya::Internal::Type::BaseModel
      extend Cadenya::Internal::Type::RequestParameters::Converter
      include Cadenya::Internal::Type::RequestParameters

      attr_accessor workspace_id: String

      attr_accessor agent_id: String

      attr_accessor system_prompt_data: ::Hash[Symbol, top]

      attr_reader episodic_memory: Cadenya::ObjectiveCreateParams::EpisodicMemory?

      def episodic_memory=: (
        Cadenya::ObjectiveCreateParams::EpisodicMemory
      ) -> Cadenya::ObjectiveCreateParams::EpisodicMemory

      attr_reader first_user_message: String?

      def first_user_message=: (String) -> String

      attr_reader first_user_message_data: ::Hash[Symbol, top]?

      def first_user_message_data=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

      attr_reader memory_cascade: ::Array[Cadenya::MemoryReference]?

      def memory_cascade=: (
        ::Array[Cadenya::MemoryReference]
      ) -> ::Array[Cadenya::MemoryReference]

      attr_reader metadata: Cadenya::CreateOperationMetadata?

      def metadata=: (
        Cadenya::CreateOperationMetadata
      ) -> Cadenya::CreateOperationMetadata

      attr_reader secrets: ::Array[Cadenya::ObjectiveCreateParams::Secret]?

      def secrets=: (
        ::Array[Cadenya::ObjectiveCreateParams::Secret]
      ) -> ::Array[Cadenya::ObjectiveCreateParams::Secret]

      attr_reader variation_id: String?

      def variation_id=: (String) -> String

      def initialize: (
        workspace_id: String,
        agent_id: String,
        system_prompt_data: ::Hash[Symbol, top],
        ?episodic_memory: Cadenya::ObjectiveCreateParams::EpisodicMemory,
        ?first_user_message: String,
        ?first_user_message_data: ::Hash[Symbol, top],
        ?memory_cascade: ::Array[Cadenya::MemoryReference],
        ?metadata: Cadenya::CreateOperationMetadata,
        ?secrets: ::Array[Cadenya::ObjectiveCreateParams::Secret],
        ?variation_id: String,
        ?request_options: Cadenya::request_opts
      ) -> void

      def to_hash: -> {
        workspace_id: String,
        agent_id: String,
        system_prompt_data: ::Hash[Symbol, top],
        episodic_memory: Cadenya::ObjectiveCreateParams::EpisodicMemory,
        first_user_message: String,
        first_user_message_data: ::Hash[Symbol, top],
        memory_cascade: ::Array[Cadenya::MemoryReference],
        metadata: Cadenya::CreateOperationMetadata,
        secrets: ::Array[Cadenya::ObjectiveCreateParams::Secret],
        variation_id: String,
        request_options: Cadenya::RequestOptions
      }

      type episodic_memory = { key: String, memory_layer_id: String }

      class EpisodicMemory < Cadenya::Internal::Type::BaseModel
        attr_reader key: String?

        def key=: (String) -> String

        def initialize: (?key: String) -> void

        def to_hash: -> { key: String, memory_layer_id: String }
      end

      type secret = { name: String, value: String }

      class Secret < Cadenya::Internal::Type::BaseModel
        attr_reader name: String?

        def name=: (String) -> String

        attr_reader value: String?

        def value=: (String) -> String

        def initialize: (?name: String, ?value: String) -> void

        def to_hash: -> { name: String, value: String }
      end
    end
  end
end
