module Cadenya
  module Models
    type objective =
      {
        config_snapshot: Cadenya::ObjectiveConfigSnapshot,
        first_user_message: String,
        metadata: Cadenya::OperationMetadata,
        state: Cadenya::Models::Objective::state,
        system_prompt: String,
        episodic_memory: Cadenya::Objective::EpisodicMemory,
        first_user_message_data: ::Hash[Symbol, top],
        info: Cadenya::ObjectiveInfo,
        memory_cascade: ::Array[Cadenya::MemoryReference],
        output: ::Hash[Symbol, top],
        parent_objective_id: String,
        secrets: ::Array[Cadenya::ObjectiveSecret],
        state_message: String,
        system_prompt_data: ::Hash[Symbol, top]
      }

    class Objective < Cadenya::Internal::Type::BaseModel
      attr_accessor first_user_message: String

      attr_accessor metadata: Cadenya::OperationMetadata

      attr_reader episodic_memory: Cadenya::Objective::EpisodicMemory?

      def episodic_memory=: (
        Cadenya::Objective::EpisodicMemory
      ) -> Cadenya::Objective::EpisodicMemory

      attr_reader memory_cascade: ::Array[Cadenya::MemoryReference]?

      def memory_cascade=: (
        ::Array[Cadenya::MemoryReference]
      ) -> ::Array[Cadenya::MemoryReference]

      attr_reader secrets: ::Array[Cadenya::ObjectiveSecret]?

      def secrets=: (
        ::Array[Cadenya::ObjectiveSecret]
      ) -> ::Array[Cadenya::ObjectiveSecret]

      attr_accessor config_snapshot: Cadenya::ObjectiveConfigSnapshot

      attr_accessor state: Cadenya::Models::Objective::state

      attr_accessor system_prompt: String

      attr_reader first_user_message_data: ::Hash[Symbol, top]?

      def first_user_message_data=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

      attr_reader info: Cadenya::ObjectiveInfo?

      def info=: (Cadenya::ObjectiveInfo) -> Cadenya::ObjectiveInfo

      attr_reader output: ::Hash[Symbol, top]?

      def output=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

      attr_reader parent_objective_id: String?

      def parent_objective_id=: (String) -> String

      attr_reader state_message: String?

      def state_message=: (String) -> String

      attr_reader system_prompt_data: ::Hash[Symbol, top]?

      def system_prompt_data=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

      def initialize: (
        config_snapshot: Cadenya::ObjectiveConfigSnapshot,
        first_user_message: String,
        metadata: Cadenya::OperationMetadata,
        state: Cadenya::Models::Objective::state,
        system_prompt: String,
        ?episodic_memory: Cadenya::Objective::EpisodicMemory,
        ?first_user_message_data: ::Hash[Symbol, top],
        ?info: Cadenya::ObjectiveInfo,
        ?memory_cascade: ::Array[Cadenya::MemoryReference],
        ?output: ::Hash[Symbol, top],
        ?parent_objective_id: String,
        ?secrets: ::Array[Cadenya::ObjectiveSecret],
        ?state_message: String,
        ?system_prompt_data: ::Hash[Symbol, top]
      ) -> void

      def to_hash: -> {
        config_snapshot: Cadenya::ObjectiveConfigSnapshot,
        first_user_message: String,
        metadata: Cadenya::OperationMetadata,
        state: Cadenya::Models::Objective::state,
        system_prompt: String,
        episodic_memory: Cadenya::Objective::EpisodicMemory,
        first_user_message_data: ::Hash[Symbol, top],
        info: Cadenya::ObjectiveInfo,
        memory_cascade: ::Array[Cadenya::MemoryReference],
        output: ::Hash[Symbol, top],
        parent_objective_id: String,
        secrets: ::Array[Cadenya::ObjectiveSecret],
        state_message: String,
        system_prompt_data: ::Hash[Symbol, top]
      }

      type state =
        :STATE_UNSPECIFIED
        | :STATE_PENDING
        | :STATE_RUNNING
        | :STATE_WAITING
        | :STATE_FAILED
        | :STATE_CANCELLED
        | :STATE_FINALIZED

      module State
        extend Cadenya::Internal::Type::Enum

        STATE_UNSPECIFIED: :STATE_UNSPECIFIED
        STATE_PENDING: :STATE_PENDING
        STATE_RUNNING: :STATE_RUNNING
        STATE_WAITING: :STATE_WAITING
        STATE_FAILED: :STATE_FAILED
        STATE_CANCELLED: :STATE_CANCELLED
        STATE_FINALIZED: :STATE_FINALIZED

        def self?.values: -> ::Array[Cadenya::Models::Objective::state]
      end

      type episodic_memory = { key: String, memory_layer_id: String }

      class EpisodicMemory < Cadenya::Internal::Type::BaseModel
        attr_reader key: String?

        def key=: (String) -> String

        attr_reader memory_layer_id: String?

        def memory_layer_id=: (String) -> String

        def initialize: (?key: String, ?memory_layer_id: String) -> void

        def to_hash: -> { key: String, memory_layer_id: String }
      end
    end
  end
end
