module Cadenya
  module Models
    type objective_context_window =
      {
        data: Cadenya::ObjectiveContextWindowData,
        metadata: Cadenya::OperationMetadata,
        info: Cadenya::ObjectiveContextWindow::Info
      }

    class ObjectiveContextWindow < Cadenya::Internal::Type::BaseModel
      attr_accessor data: Cadenya::ObjectiveContextWindowData

      attr_accessor metadata: Cadenya::OperationMetadata

      attr_reader info: Cadenya::ObjectiveContextWindow::Info?

      def info=: (
        Cadenya::ObjectiveContextWindow::Info
      ) -> Cadenya::ObjectiveContextWindow::Info

      def initialize: (
        data: Cadenya::ObjectiveContextWindowData,
        metadata: Cadenya::OperationMetadata,
        ?info: Cadenya::ObjectiveContextWindow::Info
      ) -> void

      def to_hash: -> {
        data: Cadenya::ObjectiveContextWindowData,
        metadata: Cadenya::OperationMetadata,
        info: Cadenya::ObjectiveContextWindow::Info
      }

      type info =
        { created_by: Cadenya::Profile, objective: Cadenya::OperationMetadata }

      class Info < Cadenya::Internal::Type::BaseModel
        attr_reader created_by: Cadenya::Profile?

        def created_by=: (Cadenya::Profile) -> Cadenya::Profile

        attr_reader objective: Cadenya::OperationMetadata?

        def objective=: (
          Cadenya::OperationMetadata
        ) -> Cadenya::OperationMetadata

        def initialize: (
          ?created_by: Cadenya::Profile,
          ?objective: Cadenya::OperationMetadata
        ) -> void

        def to_hash: -> {
          created_by: Cadenya::Profile,
          objective: Cadenya::OperationMetadata
        }
      end
    end
  end
end
