module Cadenya
  module Models
    type objective_context_window_data =
      {
        completion_tokens: Integer,
        objective_id: String,
        previous_window_continue_instructions: String,
        prompt_tokens: Integer,
        sequence: Integer
      }

    class ObjectiveContextWindowData < Cadenya::Internal::Type::BaseModel
      attr_accessor previous_window_continue_instructions: String

      attr_accessor completion_tokens: Integer

      attr_accessor objective_id: String

      attr_accessor prompt_tokens: Integer

      attr_accessor sequence: Integer

      def initialize: (
        completion_tokens: Integer,
        objective_id: String,
        previous_window_continue_instructions: String,
        prompt_tokens: Integer,
        sequence: Integer
      ) -> void

      def to_hash: -> {
        completion_tokens: Integer,
        objective_id: String,
        previous_window_continue_instructions: String,
        prompt_tokens: Integer,
        sequence: Integer
      }
    end
  end
end
