module Cadenya
  module Models
    type objective_event_data_tool_denied =
      {
        tool_denied: Cadenya::ToolDenied,
        type: Cadenya::Models::ObjectiveEventDataToolDenied::type_
      }

    class ObjectiveEventDataToolDenied < Cadenya::Internal::Type::BaseModel
      attr_accessor tool_denied: Cadenya::ToolDenied

      attr_accessor type: Cadenya::Models::ObjectiveEventDataToolDenied::type_

      def initialize: (
        tool_denied: Cadenya::ToolDenied,
        type: Cadenya::Models::ObjectiveEventDataToolDenied::type_
      ) -> void

      def to_hash: -> {
        tool_denied: Cadenya::ToolDenied,
        type: Cadenya::Models::ObjectiveEventDataToolDenied::type_
      }

      type type_ = :toolDenied

      module Type
        extend Cadenya::Internal::Type::Enum

        TOOL_DENIED: :toolDenied

        def self?.values: -> ::Array[Cadenya::Models::ObjectiveEventDataToolDenied::type_]
      end
    end
  end
end
