module Cadenya
  module Models
    type objective_create_params =
      {
        workspace_id: String,
        agent_id: String,
        data: ::Hash[Symbol, top],
        initial_message: String,
        memory_stack: ::Array[Cadenya::MemoryReference],
        metadata: Cadenya::CreateOperationMetadata,
        secrets: ::Array[Cadenya::ObjectiveCreateParams::Secret],
        variation_id: String
      }
      & Cadenya::Internal::Type::request_parameters

    class ObjectiveCreateParams < Cadenya::Internal::Type::BaseModel
      extend Cadenya::Internal::Type::RequestParameters::Converter
      include Cadenya::Internal::Type::RequestParameters

      attr_accessor workspace_id: String

      attr_accessor agent_id: String

      attr_accessor data: ::Hash[Symbol, top]

      attr_reader initial_message: String?

      def initial_message=: (String) -> String

      attr_reader memory_stack: ::Array[Cadenya::MemoryReference]?

      def memory_stack=: (
        ::Array[Cadenya::MemoryReference]
      ) -> ::Array[Cadenya::MemoryReference]

      attr_reader metadata: Cadenya::CreateOperationMetadata?

      def metadata=: (
        Cadenya::CreateOperationMetadata
      ) -> Cadenya::CreateOperationMetadata

      attr_reader secrets: ::Array[Cadenya::ObjectiveCreateParams::Secret]?

      def secrets=: (
        ::Array[Cadenya::ObjectiveCreateParams::Secret]
      ) -> ::Array[Cadenya::ObjectiveCreateParams::Secret]

      attr_reader variation_id: String?

      def variation_id=: (String) -> String

      def initialize: (
        workspace_id: String,
        agent_id: String,
        data: ::Hash[Symbol, top],
        ?initial_message: String,
        ?memory_stack: ::Array[Cadenya::MemoryReference],
        ?metadata: Cadenya::CreateOperationMetadata,
        ?secrets: ::Array[Cadenya::ObjectiveCreateParams::Secret],
        ?variation_id: String,
        ?request_options: Cadenya::request_opts
      ) -> void

      def to_hash: -> {
        workspace_id: String,
        agent_id: String,
        data: ::Hash[Symbol, top],
        initial_message: String,
        memory_stack: ::Array[Cadenya::MemoryReference],
        metadata: Cadenya::CreateOperationMetadata,
        secrets: ::Array[Cadenya::ObjectiveCreateParams::Secret],
        variation_id: String,
        request_options: Cadenya::RequestOptions
      }

      type secret = { name: String, value: String }

      class Secret < Cadenya::Internal::Type::BaseModel
        attr_reader name: String?

        def name=: (String) -> String

        attr_reader value: String?

        def value=: (String) -> String

        def initialize: (?name: String, ?value: String) -> void

        def to_hash: -> { name: String, value: String }
      end
    end
  end
end
