module Cadenya
  module Models
    type objective_event_data =
      Cadenya::ObjectiveEventDataUserMessage
      | Cadenya::ObjectiveEventDataToolApprovalRequested
      | Cadenya::ObjectiveEventDataToolApproved
      | Cadenya::ObjectiveEventDataToolDenied
      | Cadenya::ObjectiveEventDataToolCalled
      | Cadenya::ObjectiveEventDataError
      | Cadenya::ObjectiveEventDataAssistantMessage
      | Cadenya::ObjectiveEventDataToolResult
      | Cadenya::ObjectiveEventDataToolError
      | Cadenya::ObjectiveEventDataContextWindowCompacted
      | Cadenya::ObjectiveEventDataMemoryRead
      | Cadenya::ObjectiveEventDataCancelled
      | Cadenya::ObjectiveEventDataSubAgentSpawned
      | Cadenya::ObjectiveEventDataSubAgentUpdated
      | Cadenya::ObjectiveEventDataFinalized
      | Cadenya::ObjectiveEventDataNotice
      | Cadenya::ObjectiveEventDataTimedOut

    module ObjectiveEventData
      extend Cadenya::Internal::Type::Union

      def self?.variants: -> ::Array[Cadenya::Models::objective_event_data]
    end
  end
end
