module Cadenya
  module Models
    type objective_status =
      { state: Cadenya::Models::ObjectiveStatus::state, message: String }

    class ObjectiveStatus < Cadenya::Internal::Type::BaseModel
      attr_accessor state: Cadenya::Models::ObjectiveStatus::state

      attr_reader message: String?

      def message=: (String) -> String

      def initialize: (
        state: Cadenya::Models::ObjectiveStatus::state,
        ?message: String
      ) -> void

      def to_hash: -> {
        state: Cadenya::Models::ObjectiveStatus::state,
        message: String
      }

      type state =
        :STATE_UNSPECIFIED
        | :STATE_PENDING
        | :STATE_RUNNING
        | :STATE_COMPLETED
        | :STATE_FAILED
        | :STATE_CANCELLED

      module State
        extend Cadenya::Internal::Type::Enum

        STATE_UNSPECIFIED: :STATE_UNSPECIFIED
        STATE_PENDING: :STATE_PENDING
        STATE_RUNNING: :STATE_RUNNING
        STATE_COMPLETED: :STATE_COMPLETED
        STATE_FAILED: :STATE_FAILED
        STATE_CANCELLED: :STATE_CANCELLED

        def self?.values: -> ::Array[Cadenya::Models::ObjectiveStatus::state]
      end
    end
  end
end
