module Cadenya
  module Models
    type objective_error = { message: String, type: String }

    class ObjectiveError < Cadenya::Internal::Type::BaseModel
      attr_accessor message: String

      attr_reader type: String?

      def type=: (String) -> String

      def initialize: (message: String, ?type: String) -> void

      def to_hash: -> { message: String, type: String }
    end
  end
end
