module Cadenya
  module Models
    type objective_compact_response =
      { context_window: Cadenya::ObjectiveContextWindowData }

    class ObjectiveCompactResponse < Cadenya::Internal::Type::BaseModel
      attr_reader context_window: Cadenya::ObjectiveContextWindowData?

      def context_window=: (
        Cadenya::ObjectiveContextWindowData
      ) -> Cadenya::ObjectiveContextWindowData

      def initialize: (
        ?context_window: Cadenya::ObjectiveContextWindowData
      ) -> void

      def to_hash: -> { context_window: Cadenya::ObjectiveContextWindowData }
    end
  end
end
