module Cadenya
  module Models
    type objective_data =
      {
        agent: Cadenya::Agent,
        data: top,
        initial_message: String,
        memory_stack: ::Array[Cadenya::MemoryReference],
        output: top,
        parent_objective_id: String,
        secrets: ::Array[Cadenya::ObjectiveDataSecret],
        source_schedule_id: String,
        system_prompt: String,
        variation: Cadenya::Agents::AgentVariation
      }

    class ObjectiveData < Cadenya::Internal::Type::BaseModel
      attr_reader data: top?

      def data=: (top) -> top

      attr_reader initial_message: String?

      def initial_message=: (String) -> String

      attr_reader memory_stack: ::Array[Cadenya::MemoryReference]?

      def memory_stack=: (
        ::Array[Cadenya::MemoryReference]
      ) -> ::Array[Cadenya::MemoryReference]

      attr_reader secrets: ::Array[Cadenya::ObjectiveDataSecret]?

      def secrets=: (
        ::Array[Cadenya::ObjectiveDataSecret]
      ) -> ::Array[Cadenya::ObjectiveDataSecret]

      attr_reader agent: Cadenya::Agent?

      def agent=: (Cadenya::Agent) -> Cadenya::Agent

      attr_reader output: top?

      def output=: (top) -> top

      attr_reader parent_objective_id: String?

      def parent_objective_id=: (String) -> String

      attr_reader source_schedule_id: String?

      def source_schedule_id=: (String) -> String

      attr_reader system_prompt: String?

      def system_prompt=: (String) -> String

      attr_reader variation: Cadenya::Agents::AgentVariation?

      def variation=: (
        Cadenya::Agents::AgentVariation
      ) -> Cadenya::Agents::AgentVariation

      def initialize: (
        ?agent: Cadenya::Agent,
        ?data: top,
        ?initial_message: String,
        ?memory_stack: ::Array[Cadenya::MemoryReference],
        ?output: top,
        ?parent_objective_id: String,
        ?secrets: ::Array[Cadenya::ObjectiveDataSecret],
        ?source_schedule_id: String,
        ?system_prompt: String,
        ?variation: Cadenya::Agents::AgentVariation
      ) -> void

      def to_hash: -> {
        agent: Cadenya::Agent,
        data: top,
        initial_message: String,
        memory_stack: ::Array[Cadenya::MemoryReference],
        output: top,
        parent_objective_id: String,
        secrets: ::Array[Cadenya::ObjectiveDataSecret],
        source_schedule_id: String,
        system_prompt: String,
        variation: Cadenya::Agents::AgentVariation
      }
    end
  end
end
