module Cadenya
  module Models
    type objective_data_secret = { name: String, value: String }

    class ObjectiveDataSecret < Cadenya::Internal::Type::BaseModel
      attr_reader name: String?

      def name=: (String) -> String

      attr_reader value: String?

      def value=: (String) -> String

      def initialize: (?name: String, ?value: String) -> void

      def to_hash: -> { name: String, value: String }
    end
  end
end
