module Cadenya
  module Models
    type operation_metadata =
      {
        id: String,
        account_id: String,
        created_at: Time,
        profile_id: String,
        workspace_id: String,
        external_id: String,
        labels: ::Hash[Symbol, String]
      }

    class OperationMetadata < Cadenya::Internal::Type::BaseModel
      attr_accessor external_id: String

      attr_accessor labels: ::Hash[Symbol, String]

      attr_accessor id: String

      attr_accessor account_id: String

      attr_accessor created_at: Time

      attr_accessor profile_id: String

      attr_accessor workspace_id: String

      def initialize: (
        id: String,
        account_id: String,
        created_at: Time,
        profile_id: String,
        workspace_id: String,
        external_id: String,
        labels: ::Hash[Symbol, String]
      ) -> void

      def to_hash: -> {
        id: String,
        account_id: String,
        created_at: Time,
        profile_id: String,
        workspace_id: String,
        external_id: String,
        labels: ::Hash[Symbol, String]
      }
    end
  end
end
