module Cadenya
  module Models
    type profile_spec =
      { type: Cadenya::Models::ProfileSpec::type_, email: String, name: String }

    class ProfileSpec < Cadenya::Internal::Type::BaseModel
      attr_accessor type: Cadenya::Models::ProfileSpec::type_

      attr_accessor email: String

      attr_accessor name: String

      def initialize: (
        type: Cadenya::Models::ProfileSpec::type_,
        email: String,
        name: String
      ) -> void

      def to_hash: -> {
        type: Cadenya::Models::ProfileSpec::type_,
        email: String,
        name: String
      }

      type type_ =
        :PROFILE_TYPE_UNSPECIFIED
        | :PROFILE_TYPE_USER
        | :PROFILE_TYPE_API_KEY
        | :PROFILE_TYPE_SYSTEM

      module Type
        extend Cadenya::Internal::Type::Enum

        PROFILE_TYPE_UNSPECIFIED: :PROFILE_TYPE_UNSPECIFIED
        PROFILE_TYPE_USER: :PROFILE_TYPE_USER
        PROFILE_TYPE_API_KEY: :PROFILE_TYPE_API_KEY
        PROFILE_TYPE_SYSTEM: :PROFILE_TYPE_SYSTEM

        def self?.values: -> ::Array[Cadenya::Models::ProfileSpec::type_]
      end
    end
  end
end
