module Cadenya
  module Models
    type profile =
      { metadata: Cadenya::AccountResourceMetadata, spec: Cadenya::ProfileSpec }

    class Profile < Cadenya::Internal::Type::BaseModel
      attr_accessor metadata: Cadenya::AccountResourceMetadata

      attr_accessor spec: Cadenya::ProfileSpec

      def initialize: (
        metadata: Cadenya::AccountResourceMetadata,
        spec: Cadenya::ProfileSpec
      ) -> void

      def to_hash: -> {
        metadata: Cadenya::AccountResourceMetadata,
        spec: Cadenya::ProfileSpec
      }
    end
  end
end
