module Cadenya
  module Models
    type reasoning = { content: String }

    class Reasoning < Cadenya::Internal::Type::BaseModel
      attr_accessor content: String

      def initialize: (content: String) -> void

      def to_hash: -> { content: String }
    end
  end
end
