module Cadenya
  module Models
    type rotate_webhook_signing_key_response =
      { webhook_events_hmac_secret: String }

    class RotateWebhookSigningKeyResponse < Cadenya::Internal::Type::BaseModel
      attr_accessor webhook_events_hmac_secret: String

      def initialize: (webhook_events_hmac_secret: String) -> void

      def to_hash: -> { webhook_events_hmac_secret: String }
    end
  end
end
