module Cadenya
  module Models
    type search_search_tools_or_tool_sets_response =
      {
        agents: ::Array[Cadenya::Agent],
        tools: ::Array[Cadenya::ToolSets::Tool],
        tool_sets: ::Array[Cadenya::ToolSet]
      }

    class SearchSearchToolsOrToolSetsResponse < Cadenya::Internal::Type::BaseModel
      attr_accessor agents: ::Array[Cadenya::Agent]

      attr_accessor tools: ::Array[Cadenya::ToolSets::Tool]

      attr_accessor tool_sets: ::Array[Cadenya::ToolSet]

      def initialize: (
        agents: ::Array[Cadenya::Agent],
        tools: ::Array[Cadenya::ToolSets::Tool],
        tool_sets: ::Array[Cadenya::ToolSet]
      ) -> void

      def to_hash: -> {
        agents: ::Array[Cadenya::Agent],
        tools: ::Array[Cadenya::ToolSets::Tool],
        tool_sets: ::Array[Cadenya::ToolSet]
      }
    end
  end
end
