module Cadenya
  module Models
    type string_matcher_exact =
      {
        exact: String,
        type: Cadenya::Models::StringMatcherExact::type_,
        case_sensitive: bool
      }

    class StringMatcherExact < Cadenya::Internal::Type::BaseModel
      attr_accessor exact: String

      attr_accessor type: Cadenya::Models::StringMatcherExact::type_

      attr_reader case_sensitive: bool?

      def case_sensitive=: (bool) -> bool

      def initialize: (
        exact: String,
        type: Cadenya::Models::StringMatcherExact::type_,
        ?case_sensitive: bool
      ) -> void

      def to_hash: -> {
        exact: String,
        type: Cadenya::Models::StringMatcherExact::type_,
        case_sensitive: bool
      }

      type type_ = :exact

      module Type
        extend Cadenya::Internal::Type::Enum

        EXACT: :exact

        def self?.values: -> ::Array[Cadenya::Models::StringMatcherExact::type_]
      end
    end
  end
end
