module Cadenya
  module Models
    type string_matcher_starts_with =
      {
        starts_with: String,
        type: Cadenya::Models::StringMatcherStartsWith::type_,
        case_sensitive: bool
      }

    class StringMatcherStartsWith < Cadenya::Internal::Type::BaseModel
      attr_accessor starts_with: String

      attr_accessor type: Cadenya::Models::StringMatcherStartsWith::type_

      attr_reader case_sensitive: bool?

      def case_sensitive=: (bool) -> bool

      def initialize: (
        starts_with: String,
        type: Cadenya::Models::StringMatcherStartsWith::type_,
        ?case_sensitive: bool
      ) -> void

      def to_hash: -> {
        starts_with: String,
        type: Cadenya::Models::StringMatcherStartsWith::type_,
        case_sensitive: bool
      }

      type type_ = :startsWith

      module Type
        extend Cadenya::Internal::Type::Enum

        STARTS_WITH: :startsWith

        def self?.values: -> ::Array[Cadenya::Models::StringMatcherStartsWith::type_]
      end
    end
  end
end
