module Cadenya
  module Models
    type string_matcher_regex =
      {
        regex: String,
        type: Cadenya::Models::StringMatcherRegex::type_,
        case_sensitive: bool
      }

    class StringMatcherRegex < Cadenya::Internal::Type::BaseModel
      attr_accessor regex: String

      attr_accessor type: Cadenya::Models::StringMatcherRegex::type_

      attr_reader case_sensitive: bool?

      def case_sensitive=: (bool) -> bool

      def initialize: (
        regex: String,
        type: Cadenya::Models::StringMatcherRegex::type_,
        ?case_sensitive: bool
      ) -> void

      def to_hash: -> {
        regex: String,
        type: Cadenya::Models::StringMatcherRegex::type_,
        case_sensitive: bool
      }

      type type_ = :regex

      module Type
        extend Cadenya::Internal::Type::Enum

        REGEX: :regex

        def self?.values: -> ::Array[Cadenya::Models::StringMatcherRegex::type_]
      end
    end
  end
end
