module Cadenya
  module Models
    type string_matcher =
      Cadenya::StringMatcherExact
      | Cadenya::StringMatcherStartsWith
      | Cadenya::StringMatcherEndsWith
      | Cadenya::StringMatcherContains
      | Cadenya::StringMatcherRegex

    module StringMatcher
      extend Cadenya::Internal::Type::Union

      def self?.variants: -> ::Array[Cadenya::Models::string_matcher]
    end
  end
end
