module Cadenya
  module Models
    type sub_agent_spawned =
      {
        agent: Cadenya::ResourceMetadata,
        objective: Cadenya::OperationMetadata,
        task: String
      }

    class SubAgentSpawned < Cadenya::Internal::Type::BaseModel
      attr_accessor agent: Cadenya::ResourceMetadata

      attr_accessor objective: Cadenya::OperationMetadata

      attr_accessor task: String

      def initialize: (
        agent: Cadenya::ResourceMetadata,
        objective: Cadenya::OperationMetadata,
        task: String
      ) -> void

      def to_hash: -> {
        agent: Cadenya::ResourceMetadata,
        objective: Cadenya::OperationMetadata,
        task: String
      }
    end
  end
end
