module Cadenya
  module Models
    type sub_agent_spawned =
      {
        agent: Cadenya::ResourceMetadata,
        objective: Cadenya::OperationMetadata,
        task: String
      }

    class SubAgentSpawned < Cadenya::Internal::Type::BaseModel
      attr_reader agent: Cadenya::ResourceMetadata?

      def agent=: (Cadenya::ResourceMetadata) -> Cadenya::ResourceMetadata

      attr_reader objective: Cadenya::OperationMetadata?

      def objective=: (Cadenya::OperationMetadata) -> Cadenya::OperationMetadata

      attr_reader task: String?

      def task=: (String) -> String

      def initialize: (
        ?agent: Cadenya::ResourceMetadata,
        ?objective: Cadenya::OperationMetadata,
        ?task: String
      ) -> void

      def to_hash: -> {
        agent: Cadenya::ResourceMetadata,
        objective: Cadenya::OperationMetadata,
        task: String
      }
    end
  end
end
