module Cadenya
  module Models
    type sub_agent_updated =
      {
        agent: Cadenya::BareMetadata,
        message: String,
        objective: Cadenya::BareMetadata,
        status: Cadenya::Models::SubAgentUpdated::status
      }

    class SubAgentUpdated < Cadenya::Internal::Type::BaseModel
      attr_reader agent: Cadenya::BareMetadata?

      def agent=: (Cadenya::BareMetadata) -> Cadenya::BareMetadata

      attr_reader message: String?

      def message=: (String) -> String

      attr_reader objective: Cadenya::BareMetadata?

      def objective=: (Cadenya::BareMetadata) -> Cadenya::BareMetadata

      attr_accessor status: Cadenya::Models::SubAgentUpdated::status

      def initialize: (
        status: Cadenya::Models::SubAgentUpdated::status,
        ?agent: Cadenya::BareMetadata,
        ?message: String,
        ?objective: Cadenya::BareMetadata
      ) -> void

      def to_hash: -> {
        agent: Cadenya::BareMetadata,
        message: String,
        objective: Cadenya::BareMetadata,
        status: Cadenya::Models::SubAgentUpdated::status
      }

      type status =
        :STATUS_UNSPECIFIED
        | :STATUS_PENDING
        | :STATUS_RUNNING
        | :STATUS_COMPLETED
        | :STATUS_FAILED
        | :STATUS_CANCELLED

      module Status
        extend Cadenya::Internal::Type::Enum

        STATUS_UNSPECIFIED: :STATUS_UNSPECIFIED
        STATUS_PENDING: :STATUS_PENDING
        STATUS_RUNNING: :STATUS_RUNNING
        STATUS_COMPLETED: :STATUS_COMPLETED
        STATUS_FAILED: :STATUS_FAILED
        STATUS_CANCELLED: :STATUS_CANCELLED

        def self?.values: -> ::Array[Cadenya::Models::SubAgentUpdated::status]
      end
    end
  end
end
