module Cadenya
  module Models
    type subject_reference = { id: String, external_id: String, name: String }

    class SubjectReference < Cadenya::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor external_id: String

      attr_reader name: String?

      def name=: (String) -> String

      def initialize: (id: String, external_id: String, ?name: String) -> void

      def to_hash: -> { id: String, external_id: String, name: String }
    end
  end
end
