module Cadenya
  module Models
    type sync_completed = { message: String, tools_synced: Integer }

    class SyncCompleted < Cadenya::Internal::Type::BaseModel
      attr_accessor message: String

      attr_accessor tools_synced: Integer

      def initialize: (message: String, tools_synced: Integer) -> void

      def to_hash: -> { message: String, tools_synced: Integer }
    end
  end
end
