module Cadenya
  module Models
    type sync_started = { message: String }

    class SyncStarted < Cadenya::Internal::Type::BaseModel
      attr_accessor message: String

      def initialize: (message: String) -> void

      def to_hash: -> { message: String }
    end
  end
end
