module Cadenya
  module Models
    type sync_failed = { error: bool, error_type: String, message: String }

    class SyncFailed < Cadenya::Internal::Type::BaseModel
      attr_accessor error: bool

      attr_accessor error_type: String

      attr_accessor message: String

      def initialize: (error: bool, error_type: String, message: String) -> void

      def to_hash: -> { error: bool, error_type: String, message: String }
    end
  end
end
