module Cadenya
  module Models
    type tenant_assertion = { id: String, name: String }

    class TenantAssertion < Cadenya::Internal::Type::BaseModel
      attr_accessor id: String

      attr_reader name: String?

      def name=: (String) -> String

      def initialize: (id: String, ?name: String) -> void

      def to_hash: -> { id: String, name: String }
    end
  end
end
