module Cadenya
  module Models
    type tenant_info =
      {
        objective_count: Integer,
        subject_count: Integer,
        widget_session_count: Integer
      }

    class TenantInfo < Cadenya::Internal::Type::BaseModel
      attr_accessor objective_count: Integer

      attr_accessor subject_count: Integer

      attr_accessor widget_session_count: Integer

      def initialize: (
        objective_count: Integer,
        subject_count: Integer,
        widget_session_count: Integer
      ) -> void

      def to_hash: -> {
        objective_count: Integer,
        subject_count: Integer,
        widget_session_count: Integer
      }
    end
  end
end
