module Cadenya
  module Models
    type tool_set_adapter_openapi_variant =
      {
        openapi: Cadenya::Models::tool_set_adapter_openapi,
        type: Cadenya::Models::ToolSetAdapterOpenAPIVariant::type_
      }

    class ToolSetAdapterOpenAPIVariant < Cadenya::Internal::Type::BaseModel
      attr_accessor openapi: Cadenya::Models::tool_set_adapter_openapi

      attr_accessor type: Cadenya::Models::ToolSetAdapterOpenAPIVariant::type_

      def initialize: (
        openapi: Cadenya::Models::tool_set_adapter_openapi,
        type: Cadenya::Models::ToolSetAdapterOpenAPIVariant::type_
      ) -> void

      def to_hash: -> {
        openapi: Cadenya::Models::tool_set_adapter_openapi,
        type: Cadenya::Models::ToolSetAdapterOpenAPIVariant::type_
      }

      type type_ = :openapi

      module Type
        extend Cadenya::Internal::Type::Enum

        OPENAPI: :openapi

        def self?.values: -> ::Array[Cadenya::Models::ToolSetAdapterOpenAPIVariant::type_]
      end
    end
  end
end
