module Cadenya
  module Models
    type tool_set_event_data_sync_failed =
      {
        sync_failed: Cadenya::SyncFailed,
        type: Cadenya::Models::ToolSetEventDataSyncFailed::type_
      }

    class ToolSetEventDataSyncFailed < Cadenya::Internal::Type::BaseModel
      attr_accessor sync_failed: Cadenya::SyncFailed

      attr_accessor type: Cadenya::Models::ToolSetEventDataSyncFailed::type_

      def initialize: (
        sync_failed: Cadenya::SyncFailed,
        type: Cadenya::Models::ToolSetEventDataSyncFailed::type_
      ) -> void

      def to_hash: -> {
        sync_failed: Cadenya::SyncFailed,
        type: Cadenya::Models::ToolSetEventDataSyncFailed::type_
      }

      type type_ = :syncFailed

      module Type
        extend Cadenya::Internal::Type::Enum

        SYNC_FAILED: :syncFailed

        def self?.values: -> ::Array[Cadenya::Models::ToolSetEventDataSyncFailed::type_]
      end
    end
  end
end
