module Cadenya
  module Models
    type tool_filter =
      {
        operator: Cadenya::Models::ToolFilter::operator,
        filters: ::Array[Cadenya::AttributeFilter]
      }

    class ToolFilter < Cadenya::Internal::Type::BaseModel
      attr_accessor operator: Cadenya::Models::ToolFilter::operator

      attr_reader filters: ::Array[Cadenya::AttributeFilter]?

      def filters=: (
        ::Array[Cadenya::AttributeFilter]
      ) -> ::Array[Cadenya::AttributeFilter]

      def initialize: (
        operator: Cadenya::Models::ToolFilter::operator,
        ?filters: ::Array[Cadenya::AttributeFilter]
      ) -> void

      def to_hash: -> {
        operator: Cadenya::Models::ToolFilter::operator,
        filters: ::Array[Cadenya::AttributeFilter]
      }

      type operator = :OPERATOR_UNSPECIFIED | :OPERATOR_AND | :OPERATOR_OR

      module Operator
        extend Cadenya::Internal::Type::Enum

        OPERATOR_UNSPECIFIED: :OPERATOR_UNSPECIFIED
        OPERATOR_AND: :OPERATOR_AND
        OPERATOR_OR: :OPERATOR_OR

        def self?.values: -> ::Array[Cadenya::Models::ToolFilter::operator]
      end
    end
  end
end
