module Cadenya
  module Models
    type tool_set_adapter =
      Cadenya::ToolSetAdapterMCPVariant
      | Cadenya::ToolSetAdapterHTTPVariant
      | Cadenya::ToolSetAdapterOpenAPIVariant
      | Cadenya::ToolSetAdapterBareVariant

    module ToolSetAdapter
      extend Cadenya::Internal::Type::Union

      def self?.variants: -> ::Array[Cadenya::Models::tool_set_adapter]
    end
  end
end
