module Cadenya
  module Models
    type tool_entry =
      {
        name: String,
        spec: Cadenya::ToolSets::ToolSpec,
        labels: ::Hash[Symbol, String],
        state: Cadenya::Models::ToolEntry::state
      }

    class ToolEntry < Cadenya::Internal::Type::BaseModel
      attr_accessor name: String

      attr_accessor spec: Cadenya::ToolSets::ToolSpec

      attr_reader labels: ::Hash[Symbol, String]?

      def labels=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      attr_reader state: Cadenya::Models::ToolEntry::state?

      def state=: (
        Cadenya::Models::ToolEntry::state
      ) -> Cadenya::Models::ToolEntry::state

      def initialize: (
        name: String,
        spec: Cadenya::ToolSets::ToolSpec,
        ?labels: ::Hash[Symbol, String],
        ?state: Cadenya::Models::ToolEntry::state
      ) -> void

      def to_hash: -> {
        name: String,
        spec: Cadenya::ToolSets::ToolSpec,
        labels: ::Hash[Symbol, String],
        state: Cadenya::Models::ToolEntry::state
      }

      type state =
        :STATE_UNSPECIFIED | :STATE_AVAILABLE | :STATE_OMITTED | :STATE_ARCHIVED

      module State
        extend Cadenya::Internal::Type::Enum

        STATE_UNSPECIFIED: :STATE_UNSPECIFIED
        STATE_AVAILABLE: :STATE_AVAILABLE
        STATE_OMITTED: :STATE_OMITTED
        STATE_ARCHIVED: :STATE_ARCHIVED

        def self?.values: -> ::Array[Cadenya::Models::ToolEntry::state]
      end
    end
  end
end
