module Cadenya
  module Models
    type tool_set_spec =
      { adapter: Cadenya::Models::tool_set_adapter, description: String }

    class ToolSetSpec < Cadenya::Internal::Type::BaseModel
      attr_accessor adapter: Cadenya::Models::tool_set_adapter

      attr_reader description: String?

      def description=: (String) -> String

      def initialize: (
        adapter: Cadenya::Models::tool_set_adapter,
        ?description: String
      ) -> void

      def to_hash: -> {
        adapter: Cadenya::Models::tool_set_adapter,
        description: String
      }
    end
  end
end
