module Cadenya
  module Models
    type tool_set_spec =
      { adapter: Cadenya::ToolSetAdapter, description: String }

    class ToolSetSpec < Cadenya::Internal::Type::BaseModel
      attr_reader adapter: Cadenya::ToolSetAdapter?

      def adapter=: (Cadenya::ToolSetAdapter) -> Cadenya::ToolSetAdapter

      attr_reader description: String?

      def description=: (String) -> String

      def initialize: (
        ?adapter: Cadenya::ToolSetAdapter,
        ?description: String
      ) -> void

      def to_hash: -> { adapter: Cadenya::ToolSetAdapter, description: String }
    end
  end
end
