module Cadenya
  module Models
    type tool_set =
      {
        metadata: Cadenya::ResourceMetadata,
        spec: Cadenya::ToolSetSpec,
        state: Cadenya::Models::ToolSet::state,
        info: Cadenya::ToolSetInfo
      }

    class ToolSet < Cadenya::Internal::Type::BaseModel
      attr_accessor metadata: Cadenya::ResourceMetadata

      attr_accessor spec: Cadenya::ToolSetSpec

      attr_accessor state: Cadenya::Models::ToolSet::state

      attr_reader info: Cadenya::ToolSetInfo?

      def info=: (Cadenya::ToolSetInfo) -> Cadenya::ToolSetInfo

      def initialize: (
        metadata: Cadenya::ResourceMetadata,
        spec: Cadenya::ToolSetSpec,
        state: Cadenya::Models::ToolSet::state,
        ?info: Cadenya::ToolSetInfo
      ) -> void

      def to_hash: -> {
        metadata: Cadenya::ResourceMetadata,
        spec: Cadenya::ToolSetSpec,
        state: Cadenya::Models::ToolSet::state,
        info: Cadenya::ToolSetInfo
      }

      type state = :STATE_UNSPECIFIED | :STATE_ACTIVE | :STATE_ARCHIVED

      module State
        extend Cadenya::Internal::Type::Enum

        STATE_UNSPECIFIED: :STATE_UNSPECIFIED
        STATE_ACTIVE: :STATE_ACTIVE
        STATE_ARCHIVED: :STATE_ARCHIVED

        def self?.values: -> ::Array[Cadenya::Models::ToolSet::state]
      end
    end
  end
end
