module Cadenya
  module Models
    type tool_set_adapter_openapi =
      Cadenya::ToolSetAdapterOpenAPIURL | Cadenya::ToolSetAdapterOpenAPIUploadID

    module ToolSetAdapterOpenAPI
      extend Cadenya::Internal::Type::Union

      def self?.variants: -> ::Array[Cadenya::Models::tool_set_adapter_openapi]
    end
  end
end
