module Cadenya
  module Models
    type tool_set_adapter_bare_variant =
      {
        bare: Cadenya::ToolSetAdapterBare,
        type: Cadenya::Models::ToolSetAdapterBareVariant::type_
      }

    class ToolSetAdapterBareVariant < Cadenya::Internal::Type::BaseModel
      attr_accessor bare: Cadenya::ToolSetAdapterBare

      attr_accessor type: Cadenya::Models::ToolSetAdapterBareVariant::type_

      def initialize: (
        bare: Cadenya::ToolSetAdapterBare,
        type: Cadenya::Models::ToolSetAdapterBareVariant::type_
      ) -> void

      def to_hash: -> {
        bare: Cadenya::ToolSetAdapterBare,
        type: Cadenya::Models::ToolSetAdapterBareVariant::type_
      }

      type type_ = :bare

      module Type
        extend Cadenya::Internal::Type::Enum

        BARE: :bare

        def self?.values: -> ::Array[Cadenya::Models::ToolSetAdapterBareVariant::type_]
      end
    end
  end
end
