module Cadenya
  module Models
    type tool_set_event_data_sync_started =
      {
        sync_started: Cadenya::SyncStarted,
        type: Cadenya::Models::ToolSetEventDataSyncStarted::type_
      }

    class ToolSetEventDataSyncStarted < Cadenya::Internal::Type::BaseModel
      attr_accessor sync_started: Cadenya::SyncStarted

      attr_accessor type: Cadenya::Models::ToolSetEventDataSyncStarted::type_

      def initialize: (
        sync_started: Cadenya::SyncStarted,
        type: Cadenya::Models::ToolSetEventDataSyncStarted::type_
      ) -> void

      def to_hash: -> {
        sync_started: Cadenya::SyncStarted,
        type: Cadenya::Models::ToolSetEventDataSyncStarted::type_
      }

      type type_ = :syncStarted

      module Type
        extend Cadenya::Internal::Type::Enum

        SYNC_STARTED: :syncStarted

        def self?.values: -> ::Array[Cadenya::Models::ToolSetEventDataSyncStarted::type_]
      end
    end
  end
end
