module Cadenya
  module Models
    type tool_set_event_data_sync_completed =
      {
        sync_completed: Cadenya::SyncCompleted,
        type: Cadenya::Models::ToolSetEventDataSyncCompleted::type_
      }

    class ToolSetEventDataSyncCompleted < Cadenya::Internal::Type::BaseModel
      attr_accessor sync_completed: Cadenya::SyncCompleted

      attr_accessor type: Cadenya::Models::ToolSetEventDataSyncCompleted::type_

      def initialize: (
        sync_completed: Cadenya::SyncCompleted,
        type: Cadenya::Models::ToolSetEventDataSyncCompleted::type_
      ) -> void

      def to_hash: -> {
        sync_completed: Cadenya::SyncCompleted,
        type: Cadenya::Models::ToolSetEventDataSyncCompleted::type_
      }

      type type_ = :syncCompleted

      module Type
        extend Cadenya::Internal::Type::Enum

        SYNC_COMPLETED: :syncCompleted

        def self?.values: -> ::Array[Cadenya::Models::ToolSetEventDataSyncCompleted::type_]
      end
    end
  end
end
