module Cadenya
  module Models
    type tool_set_adapter_mcp =
      {
        exclude_tools: Cadenya::ToolFilter,
        headers: ::Hash[Symbol, String],
        include_tools: Cadenya::ToolFilter,
        just_in_time: Cadenya::ToolSetAdapterMCP::JustInTime,
        tool_approvals: Cadenya::ApprovalRequirementFilter,
        url: String
      }

    class ToolSetAdapterMCP < Cadenya::Internal::Type::BaseModel
      attr_reader exclude_tools: Cadenya::ToolFilter?

      def exclude_tools=: (Cadenya::ToolFilter) -> Cadenya::ToolFilter

      attr_reader headers: ::Hash[Symbol, String]?

      def headers=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      attr_reader include_tools: Cadenya::ToolFilter?

      def include_tools=: (Cadenya::ToolFilter) -> Cadenya::ToolFilter

      attr_reader just_in_time: Cadenya::ToolSetAdapterMCP::JustInTime?

      def just_in_time=: (
        Cadenya::ToolSetAdapterMCP::JustInTime
      ) -> Cadenya::ToolSetAdapterMCP::JustInTime

      attr_reader tool_approvals: Cadenya::ApprovalRequirementFilter?

      def tool_approvals=: (
        Cadenya::ApprovalRequirementFilter
      ) -> Cadenya::ApprovalRequirementFilter

      attr_reader url: String?

      def url=: (String) -> String

      def initialize: (
        ?exclude_tools: Cadenya::ToolFilter,
        ?headers: ::Hash[Symbol, String],
        ?include_tools: Cadenya::ToolFilter,
        ?just_in_time: Cadenya::ToolSetAdapterMCP::JustInTime,
        ?tool_approvals: Cadenya::ApprovalRequirementFilter,
        ?url: String
      ) -> void

      def to_hash: -> {
        exclude_tools: Cadenya::ToolFilter,
        headers: ::Hash[Symbol, String],
        include_tools: Cadenya::ToolFilter,
        just_in_time: Cadenya::ToolSetAdapterMCP::JustInTime,
        tool_approvals: Cadenya::ApprovalRequirementFilter,
        url: String
      }

      type just_in_time =
        { enabled: bool, fail_objective_on_tool_list_error: bool }

      class JustInTime < Cadenya::Internal::Type::BaseModel
        attr_reader enabled: bool?

        def enabled=: (bool) -> bool

        attr_reader fail_objective_on_tool_list_error: bool?

        def fail_objective_on_tool_list_error=: (bool) -> bool

        def initialize: (
          ?enabled: bool,
          ?fail_objective_on_tool_list_error: bool
        ) -> void

        def to_hash: -> {
          enabled: bool,
          fail_objective_on_tool_list_error: bool
        }
      end
    end
  end
end
