module Cadenya
  module Models
    type tool_set_usage =
      {
        assigned_at: Time,
        agent: Cadenya::ResourceMetadata,
        agent_variation: Cadenya::ResourceMetadata,
        model: Cadenya::ResourceMetadata
      }

    class ToolSetUsage < Cadenya::Internal::Type::BaseModel
      attr_accessor assigned_at: Time

      attr_accessor agent: Cadenya::ResourceMetadata

      attr_accessor agent_variation: Cadenya::ResourceMetadata

      attr_accessor model: Cadenya::ResourceMetadata

      def initialize: (
        assigned_at: Time,
        agent: Cadenya::ResourceMetadata,
        agent_variation: Cadenya::ResourceMetadata,
        model: Cadenya::ResourceMetadata
      ) -> void

      def to_hash: -> {
        assigned_at: Time,
        agent: Cadenya::ResourceMetadata,
        agent_variation: Cadenya::ResourceMetadata,
        model: Cadenya::ResourceMetadata
      }
    end
  end
end
