module Cadenya
  module Models
    type tool_called =
      {
        arguments: ::Hash[Symbol, top],
        config: Cadenya::ToolSets::ToolSpecConfig,
        tool: Cadenya::CallableTool,
        tool_call_id: String
      }

    class ToolCalled < Cadenya::Internal::Type::BaseModel
      attr_reader arguments: ::Hash[Symbol, top]?

      def arguments=: (::Hash[Symbol, top]) -> ::Hash[Symbol, top]

      attr_reader config: Cadenya::ToolSets::ToolSpecConfig?

      def config=: (
        Cadenya::ToolSets::ToolSpecConfig
      ) -> Cadenya::ToolSets::ToolSpecConfig

      attr_reader tool: Cadenya::CallableTool?

      def tool=: (Cadenya::CallableTool) -> Cadenya::CallableTool

      attr_reader tool_call_id: String?

      def tool_call_id=: (String) -> String

      def initialize: (
        ?arguments: ::Hash[Symbol, top],
        ?config: Cadenya::ToolSets::ToolSpecConfig,
        ?tool: Cadenya::CallableTool,
        ?tool_call_id: String
      ) -> void

      def to_hash: -> {
        arguments: ::Hash[Symbol, top],
        config: Cadenya::ToolSets::ToolSpecConfig,
        tool: Cadenya::CallableTool,
        tool_call_id: String
      }
    end
  end
end
