module Cadenya
  module Models
    type tool_set_info =
      {
        agent_count: Integer,
        available_tools: Integer,
        created_by: Cadenya::Profile,
        last_sync: Time,
        omitted_tools: Integer,
        tool_count: Integer
      }

    class ToolSetInfo < Cadenya::Internal::Type::BaseModel
      attr_accessor available_tools: Integer

      attr_reader created_by: Cadenya::Profile?

      def created_by=: (Cadenya::Profile) -> Cadenya::Profile

      attr_accessor omitted_tools: Integer

      attr_accessor agent_count: Integer

      attr_reader last_sync: Time?

      def last_sync=: (Time) -> Time

      attr_accessor tool_count: Integer

      def initialize: (
        agent_count: Integer,
        available_tools: Integer,
        omitted_tools: Integer,
        tool_count: Integer,
        ?created_by: Cadenya::Profile,
        ?last_sync: Time
      ) -> void

      def to_hash: -> {
        agent_count: Integer,
        available_tools: Integer,
        created_by: Cadenya::Profile,
        last_sync: Time,
        omitted_tools: Integer,
        tool_count: Integer
      }
    end
  end
end
