module Cadenya
  module Models
    type tool_set_event_data =
      Cadenya::ToolSetEventDataSyncStarted
      | Cadenya::ToolSetEventDataSyncCompleted
      | Cadenya::ToolSetEventDataSyncFailed

    module ToolSetEventData
      extend Cadenya::Internal::Type::Union

      def self?.variants: -> ::Array[Cadenya::Models::tool_set_event_data]
    end
  end
end
