module Cadenya
  module Models
    type unsafe_unwrap_webhook_event =
      {
        data: Cadenya::UnsafeUnwrapWebhookEvent::Data,
        timestamp: Time,
        type: String
      }

    class UnsafeUnwrapWebhookEvent < Cadenya::Internal::Type::BaseModel
      attr_accessor data: Cadenya::UnsafeUnwrapWebhookEvent::Data

      attr_accessor timestamp: Time

      attr_accessor type: String

      def initialize: (
        data: Cadenya::UnsafeUnwrapWebhookEvent::Data,
        timestamp: Time,
        type: String
      ) -> void

      def to_hash: -> {
        data: Cadenya::UnsafeUnwrapWebhookEvent::Data,
        timestamp: Time,
        type: String
      }

      type data =
        {
          agent: Cadenya::ResourceMetadata,
          agent_variation: Cadenya::ResourceMetadata,
          objective: Cadenya::OperationMetadata,
          objective_event: Cadenya::ObjectiveEvent
        }

      class Data < Cadenya::Internal::Type::BaseModel
        attr_accessor agent: Cadenya::ResourceMetadata

        attr_accessor agent_variation: Cadenya::ResourceMetadata

        attr_accessor objective: Cadenya::OperationMetadata

        attr_accessor objective_event: Cadenya::ObjectiveEvent

        def initialize: (
          agent: Cadenya::ResourceMetadata,
          agent_variation: Cadenya::ResourceMetadata,
          objective: Cadenya::OperationMetadata,
          objective_event: Cadenya::ObjectiveEvent
        ) -> void

        def to_hash: -> {
          agent: Cadenya::ResourceMetadata,
          agent_variation: Cadenya::ResourceMetadata,
          objective: Cadenya::OperationMetadata,
          objective_event: Cadenya::ObjectiveEvent
        }
      end
    end
  end
end
