module Cadenya
  module Models
    type upload_info =
      {
        created_by: Cadenya::Profile,
        status: Cadenya::Models::UploadInfo::status,
        upload_url: String,
        upload_url_expires_at: Time
      }

    class UploadInfo < Cadenya::Internal::Type::BaseModel
      attr_reader created_by: Cadenya::Profile?

      def created_by=: (Cadenya::Profile) -> Cadenya::Profile

      attr_accessor status: Cadenya::Models::UploadInfo::status

      attr_accessor upload_url: String

      attr_reader upload_url_expires_at: Time?

      def upload_url_expires_at=: (Time) -> Time

      def initialize: (
        status: Cadenya::Models::UploadInfo::status,
        upload_url: String,
        ?created_by: Cadenya::Profile,
        ?upload_url_expires_at: Time
      ) -> void

      def to_hash: -> {
        created_by: Cadenya::Profile,
        status: Cadenya::Models::UploadInfo::status,
        upload_url: String,
        upload_url_expires_at: Time
      }

      type status =
        :UPLOAD_STATUS_UNSPECIFIED
        | :UPLOAD_STATUS_PENDING
        | :UPLOAD_STATUS_COMPLETE
        | :UPLOAD_STATUS_CONSUMED
        | :UPLOAD_STATUS_EXPIRED

      module Status
        extend Cadenya::Internal::Type::Enum

        UPLOAD_STATUS_UNSPECIFIED: :UPLOAD_STATUS_UNSPECIFIED
        UPLOAD_STATUS_PENDING: :UPLOAD_STATUS_PENDING
        UPLOAD_STATUS_COMPLETE: :UPLOAD_STATUS_COMPLETE
        UPLOAD_STATUS_CONSUMED: :UPLOAD_STATUS_CONSUMED
        UPLOAD_STATUS_EXPIRED: :UPLOAD_STATUS_EXPIRED

        def self?.values: -> ::Array[Cadenya::Models::UploadInfo::status]
      end
    end
  end
end
