module Cadenya
  module Models
    type upload_create_params =
      {
        workspace_id: String,
        metadata: Cadenya::CreateResourceMetadata,
        spec: Cadenya::UploadSpec
      }
      & Cadenya::Internal::Type::request_parameters

    class UploadCreateParams < Cadenya::Internal::Type::BaseModel
      extend Cadenya::Internal::Type::RequestParameters::Converter
      include Cadenya::Internal::Type::RequestParameters

      attr_reader workspace_id: String?

      def workspace_id=: (String) -> String

      attr_accessor metadata: Cadenya::CreateResourceMetadata

      attr_accessor spec: Cadenya::UploadSpec

      def initialize: (
        metadata: Cadenya::CreateResourceMetadata,
        spec: Cadenya::UploadSpec,
        ?workspace_id: String,
        ?request_options: Cadenya::request_opts
      ) -> void

      def to_hash: -> {
        workspace_id: String,
        metadata: Cadenya::CreateResourceMetadata,
        spec: Cadenya::UploadSpec,
        request_options: Cadenya::RequestOptions
      }
    end
  end
end
