module Cadenya
  module Models
    type variation_assignment_entry =
      { sub_agent_id: String, tool_id: String, tool_set_id: String }

    class VariationAssignmentEntry < Cadenya::Internal::Type::BaseModel
      attr_reader sub_agent_id: String?

      def sub_agent_id=: (String) -> String

      attr_reader tool_id: String?

      def tool_id=: (String) -> String

      attr_reader tool_set_id: String?

      def tool_set_id=: (String) -> String

      def initialize: (
        ?sub_agent_id: String,
        ?tool_id: String,
        ?tool_set_id: String
      ) -> void

      def to_hash: -> {
        sub_agent_id: String,
        tool_id: String,
        tool_set_id: String
      }
    end
  end
end
