module Cadenya
  module Models
    type variation_memory_layer_entry =
      { memory_layer_id: String, position: Integer }

    class VariationMemoryLayerEntry < Cadenya::Internal::Type::BaseModel
      attr_reader memory_layer_id: String?

      def memory_layer_id=: (String) -> String

      attr_reader position: Integer?

      def position=: (Integer) -> Integer

      def initialize: (?memory_layer_id: String, ?position: Integer) -> void

      def to_hash: -> { memory_layer_id: String, position: Integer }
    end
  end
end
