module Cadenya
  module Models
    type webhook_unwrap_params =
      {  } & Cadenya::Internal::Type::request_parameters

    class WebhookUnwrapParams < Cadenya::Internal::Type::BaseModel
      extend Cadenya::Internal::Type::RequestParameters::Converter
      include Cadenya::Internal::Type::RequestParameters

      def initialize: (?request_options: Cadenya::request_opts) -> void

      def to_hash: -> { request_options: Cadenya::RequestOptions }
    end
  end
end
