module Cadenya
  module Models
    type widget_info =
      {
        agent: Cadenya::BareMetadata,
        created_by: Cadenya::Profile,
        dns_label: String,
        host: String
      }

    class WidgetInfo < Cadenya::Internal::Type::BaseModel
      attr_reader created_by: Cadenya::Profile?

      def created_by=: (Cadenya::Profile) -> Cadenya::Profile

      attr_accessor agent: Cadenya::BareMetadata

      attr_accessor dns_label: String

      attr_accessor host: String

      def initialize: (
        agent: Cadenya::BareMetadata,
        dns_label: String,
        host: String,
        ?created_by: Cadenya::Profile
      ) -> void

      def to_hash: -> {
        agent: Cadenya::BareMetadata,
        created_by: Cadenya::Profile,
        dns_label: String,
        host: String
      }
    end
  end
end
