module Cadenya
  module Models
    type widget_session_delete_tenant_response =
      { objectives_deleted: Integer, sessions_deleted: Integer }

    class WidgetSessionDeleteTenantResponse < Cadenya::Internal::Type::BaseModel
      attr_accessor objectives_deleted: Integer

      attr_accessor sessions_deleted: Integer

      def initialize: (
        objectives_deleted: Integer,
        sessions_deleted: Integer
      ) -> void

      def to_hash: -> { objectives_deleted: Integer, sessions_deleted: Integer }
    end
  end
end
