module Cadenya
  module Models
    type widget_session_spec =
      {
        widget_id: String,
        token: String,
        expires_at: Time,
        pinned_parameters: ::Hash[Symbol, String],
        subject: Cadenya::SubjectAssertion,
        tenant: Cadenya::TenantAssertion,
        token_expires_at: Time
      }

    class WidgetSessionSpec < Cadenya::Internal::Type::BaseModel
      attr_accessor widget_id: String

      attr_reader expires_at: Time?

      def expires_at=: (Time) -> Time

      attr_reader pinned_parameters: ::Hash[Symbol, String]?

      def pinned_parameters=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

      attr_reader subject: Cadenya::SubjectAssertion?

      def subject=: (Cadenya::SubjectAssertion) -> Cadenya::SubjectAssertion

      attr_reader tenant: Cadenya::TenantAssertion?

      def tenant=: (Cadenya::TenantAssertion) -> Cadenya::TenantAssertion

      attr_accessor token: String

      attr_reader token_expires_at: Time?

      def token_expires_at=: (Time) -> Time

      def initialize: (
        widget_id: String,
        token: String,
        ?expires_at: Time,
        ?pinned_parameters: ::Hash[Symbol, String],
        ?subject: Cadenya::SubjectAssertion,
        ?tenant: Cadenya::TenantAssertion,
        ?token_expires_at: Time
      ) -> void

      def to_hash: -> {
        widget_id: String,
        token: String,
        expires_at: Time,
        pinned_parameters: ::Hash[Symbol, String],
        subject: Cadenya::SubjectAssertion,
        tenant: Cadenya::TenantAssertion,
        token_expires_at: Time
      }
    end
  end
end
