module Cadenya
  module Models
    type widget_session_info =
      {
        agent: Cadenya::BareMetadata,
        host: String,
        last_active_at: Time,
        message_count: Integer,
        subject: Cadenya::SubjectReference,
        tenant: Cadenya::TenantReference,
        widget: Cadenya::BareMetadata
      }

    class WidgetSessionInfo < Cadenya::Internal::Type::BaseModel
      attr_accessor agent: Cadenya::BareMetadata

      attr_accessor host: String

      attr_reader last_active_at: Time?

      def last_active_at=: (Time) -> Time

      attr_accessor message_count: Integer

      attr_reader subject: Cadenya::SubjectReference?

      def subject=: (Cadenya::SubjectReference) -> Cadenya::SubjectReference

      attr_reader tenant: Cadenya::TenantReference?

      def tenant=: (Cadenya::TenantReference) -> Cadenya::TenantReference

      attr_accessor widget: Cadenya::BareMetadata

      def initialize: (
        agent: Cadenya::BareMetadata,
        host: String,
        message_count: Integer,
        widget: Cadenya::BareMetadata,
        ?last_active_at: Time,
        ?subject: Cadenya::SubjectReference,
        ?tenant: Cadenya::TenantReference
      ) -> void

      def to_hash: -> {
        agent: Cadenya::BareMetadata,
        host: String,
        last_active_at: Time,
        message_count: Integer,
        subject: Cadenya::SubjectReference,
        tenant: Cadenya::TenantReference,
        widget: Cadenya::BareMetadata
      }
    end
  end
end
