module Cadenya
  module Models
    type widget_session =
      {
        metadata: Cadenya::OperationMetadata,
        spec: Cadenya::WidgetSessionSpec,
        state: Cadenya::Models::WidgetSession::state,
        info: Cadenya::WidgetSessionInfo,
        secrets: ::Array[Cadenya::WidgetSession::Secret]
      }

    class WidgetSession < Cadenya::Internal::Type::BaseModel
      attr_accessor metadata: Cadenya::OperationMetadata

      attr_accessor spec: Cadenya::WidgetSessionSpec

      attr_reader info: Cadenya::WidgetSessionInfo?

      def info=: (Cadenya::WidgetSessionInfo) -> Cadenya::WidgetSessionInfo

      attr_accessor state: Cadenya::Models::WidgetSession::state

      attr_accessor secrets: ::Array[Cadenya::WidgetSession::Secret]

      def initialize: (
        metadata: Cadenya::OperationMetadata,
        spec: Cadenya::WidgetSessionSpec,
        state: Cadenya::Models::WidgetSession::state,
        secrets: ::Array[Cadenya::WidgetSession::Secret],
        ?info: Cadenya::WidgetSessionInfo
      ) -> void

      def to_hash: -> {
        metadata: Cadenya::OperationMetadata,
        spec: Cadenya::WidgetSessionSpec,
        state: Cadenya::Models::WidgetSession::state,
        info: Cadenya::WidgetSessionInfo,
        secrets: ::Array[Cadenya::WidgetSession::Secret]
      }

      type state =
        :STATE_UNSPECIFIED
        | :STATE_ACTIVE
        | :STATE_EXPIRED
        | :STATE_REVOKED
        | :STATE_EXHAUSTED

      module State
        extend Cadenya::Internal::Type::Enum

        STATE_UNSPECIFIED: :STATE_UNSPECIFIED
        STATE_ACTIVE: :STATE_ACTIVE
        STATE_EXPIRED: :STATE_EXPIRED
        STATE_REVOKED: :STATE_REVOKED
        STATE_EXHAUSTED: :STATE_EXHAUSTED

        def self?.values: -> ::Array[Cadenya::Models::WidgetSession::state]
      end

      type secret = { name: String }

      class Secret < Cadenya::Internal::Type::BaseModel
        attr_reader name: String?

        def name=: (String) -> String

        def initialize: (?name: String) -> void

        def to_hash: -> { name: String }
      end
    end
  end
end
