module Cadenya
  module Models
    type workspace_secret =
      {
        metadata: Cadenya::ResourceMetadata,
        spec: Cadenya::WorkspaceSecretSpec,
        info: Cadenya::WorkspaceSecretInfo
      }

    class WorkspaceSecret < Cadenya::Internal::Type::BaseModel
      attr_accessor metadata: Cadenya::ResourceMetadata

      attr_accessor spec: Cadenya::WorkspaceSecretSpec

      attr_reader info: Cadenya::WorkspaceSecretInfo?

      def info=: (Cadenya::WorkspaceSecretInfo) -> Cadenya::WorkspaceSecretInfo

      def initialize: (
        metadata: Cadenya::ResourceMetadata,
        spec: Cadenya::WorkspaceSecretSpec,
        ?info: Cadenya::WorkspaceSecretInfo
      ) -> void

      def to_hash: -> {
        metadata: Cadenya::ResourceMetadata,
        spec: Cadenya::WorkspaceSecretSpec,
        info: Cadenya::WorkspaceSecretInfo
      }
    end
  end
end
