module Cadenya
  module Models
    type workspace =
      {
        metadata: Cadenya::AccountResourceMetadata,
        spec: Cadenya::WorkspaceSpec,
        status: Cadenya::Models::Workspace::status
      }

    class Workspace < Cadenya::Internal::Type::BaseModel
      attr_accessor metadata: Cadenya::AccountResourceMetadata

      attr_accessor spec: Cadenya::WorkspaceSpec

      attr_reader status: Cadenya::Models::Workspace::status?

      def status=: (
        Cadenya::Models::Workspace::status
      ) -> Cadenya::Models::Workspace::status

      def initialize: (
        metadata: Cadenya::AccountResourceMetadata,
        spec: Cadenya::WorkspaceSpec,
        ?status: Cadenya::Models::Workspace::status
      ) -> void

      def to_hash: -> {
        metadata: Cadenya::AccountResourceMetadata,
        spec: Cadenya::WorkspaceSpec,
        status: Cadenya::Models::Workspace::status
      }

      type status = :STATUS_ENABLED | :STATUS_DISABLED | :STATUS_ARCHIVED

      module Status
        extend Cadenya::Internal::Type::Enum

        STATUS_ENABLED: :STATUS_ENABLED
        STATUS_DISABLED: :STATUS_DISABLED
        STATUS_ARCHIVED: :STATUS_ARCHIVED

        def self?.values: -> ::Array[Cadenya::Models::Workspace::status]
      end
    end
  end
end
