module Cadenya
  module Models
    type workspace_secret_info =
      { created_by: Cadenya::Profile, last_used_at: Time }

    class WorkspaceSecretInfo < Cadenya::Internal::Type::BaseModel
      attr_reader created_by: Cadenya::Profile?

      def created_by=: (Cadenya::Profile) -> Cadenya::Profile

      attr_reader last_used_at: Time?

      def last_used_at=: (Time) -> Time

      def initialize: (
        ?created_by: Cadenya::Profile,
        ?last_used_at: Time
      ) -> void

      def to_hash: -> { created_by: Cadenya::Profile, last_used_at: Time }
    end
  end
end
