module Cadenya
  module Models
    type workspace_member =
      {
        actor_id: String,
        profile_id: String,
        added_at: Time,
        email: String,
        name: String
      }

    class WorkspaceMember < Cadenya::Internal::Type::BaseModel
      attr_accessor actor_id: String

      attr_accessor profile_id: String

      attr_reader added_at: Time?

      def added_at=: (Time) -> Time

      attr_reader email: String?

      def email=: (String) -> String

      attr_reader name: String?

      def name=: (String) -> String

      def initialize: (
        actor_id: String,
        profile_id: String,
        ?added_at: Time,
        ?email: String,
        ?name: String
      ) -> void

      def to_hash: -> {
        actor_id: String,
        profile_id: String,
        added_at: Time,
        email: String,
        name: String
      }
    end
  end
end
