module Cadenya
  module Models
    type workspace_secret_spec = { value: String }

    class WorkspaceSecretSpec < Cadenya::Internal::Type::BaseModel
      attr_reader value: String?

      def value=: (String) -> String

      def initialize: (?value: String) -> void

      def to_hash: -> { value: String }
    end
  end
end
