module Cadenya
  module Resources
    class Objectives
      class Tools
        def list: (
          String objective_id,
          workspace_id: String,
          ?cursor: String,
          ?limit: Integer,
          ?request_options: Cadenya::request_opts
        ) -> Cadenya::Internal::CursorPagination[Cadenya::Objectives::ObjectiveTool]

        def initialize: (client: Cadenya::Client) -> void
      end
    end
  end
end
