module Cadenya
  module Resources
    class Objectives
      class ToolCalls
        def retrieve: (
          String objective_id,
          String tool_call_id,
          ?workspace_id: String,
          ?request_options: Cadenya::request_opts
        ) -> Cadenya::Objectives::ObjectiveToolCallWithResult

        def list: (
          String objective_id,
          ?workspace_id: String,
          ?cursor: String,
          ?execution_status: Cadenya::Models::Objectives::ToolCallListParams::execution_status,
          ?include_info: bool,
          ?labels: String,
          ?limit: Integer,
          ?status: Cadenya::Models::Objectives::ToolCallListParams::status,
          ?request_options: Cadenya::request_opts
        ) -> Cadenya::Internal::CursorPagination[Cadenya::Objectives::ObjectiveToolCall]

        def approve: (
          String objective_id,
          String tool_call_id,
          ?workspace_id: String,
          ?request_options: Cadenya::request_opts
        ) -> Cadenya::Objectives::ObjectiveToolCall

        def deny: (
          String objective_id,
          String tool_call_id,
          ?workspace_id: String,
          ?memo: String,
          ?request_options: Cadenya::request_opts
        ) -> Cadenya::Objectives::ObjectiveToolCall

        def set_content: (
          String objective_id,
          String tool_call_id,
          content: ::Array[Cadenya::Objectives::SetToolCallContentRequestContentBlock],
          ?workspace_id: String,
          ?request_options: Cadenya::request_opts
        ) -> Cadenya::Objectives::ObjectiveToolCall

        def initialize: (client: Cadenya::Client) -> void
      end
    end
  end
end
