module Cadenya
  module Models
    module APIKeys
      type access_list_params =
        { id: String, cursor: String, limit: Integer }
        & Cadenya::Internal::Type::request_parameters

      class AccessListParams < Cadenya::Internal::Type::BaseModel
        extend Cadenya::Internal::Type::RequestParameters::Converter
        include Cadenya::Internal::Type::RequestParameters

        attr_accessor id: String

        attr_reader cursor: String?

        def cursor=: (String) -> String

        attr_reader limit: Integer?

        def limit=: (Integer) -> Integer

        def initialize: (
          id: String,
          ?cursor: String,
          ?limit: Integer,
          ?request_options: Cadenya::request_opts
        ) -> void

        def to_hash: -> {
          id: String,
          cursor: String,
          limit: Integer,
          request_options: Cadenya::RequestOptions
        }
      end
    end
  end
end
