module Cadenya
  module Models
    module Agents
      type add_agent_variation_assignment_request_tool_id =
        {
          tool_id: String,
          type: Cadenya::Models::Agents::AddAgentVariationAssignmentRequestToolID::type_,
          agent_id: String,
          variation_id: String,
          workspace_id: String
        }

      class AddAgentVariationAssignmentRequestToolID < Cadenya::Internal::Type::BaseModel
        attr_accessor tool_id: String

        attr_accessor type: Cadenya::Models::Agents::AddAgentVariationAssignmentRequestToolID::type_

        def initialize: (
          tool_id: String,
          type: Cadenya::Models::Agents::AddAgentVariationAssignmentRequestToolID::type_
        ) -> void

        def to_hash: -> {
          tool_id: String,
          type: Cadenya::Models::Agents::AddAgentVariationAssignmentRequestToolID::type_,
          agent_id: String,
          variation_id: String,
          workspace_id: String
        }

        type type_ = :toolId

        module Type
          extend Cadenya::Internal::Type::Enum

          TOOL_ID: :toolId

          def self?.values: -> ::Array[Cadenya::Models::Agents::AddAgentVariationAssignmentRequestToolID::type_]
        end
      end
    end
  end
end
