module Cadenya
  module Models
    module Agents
      type add_agent_variation_assignment_request_sub_agent_id =
        {
          sub_agent_id: String,
          type: Cadenya::Models::Agents::AddAgentVariationAssignmentRequestSubAgentID::type_,
          agent_id: String,
          variation_id: String,
          workspace_id: String
        }

      class AddAgentVariationAssignmentRequestSubAgentID < Cadenya::Internal::Type::BaseModel
        attr_accessor sub_agent_id: String

        attr_accessor type: Cadenya::Models::Agents::AddAgentVariationAssignmentRequestSubAgentID::type_

        def initialize: (
          sub_agent_id: String,
          type: Cadenya::Models::Agents::AddAgentVariationAssignmentRequestSubAgentID::type_
        ) -> void

        def to_hash: -> {
          sub_agent_id: String,
          type: Cadenya::Models::Agents::AddAgentVariationAssignmentRequestSubAgentID::type_,
          agent_id: String,
          variation_id: String,
          workspace_id: String
        }

        type type_ = :subAgentId

        module Type
          extend Cadenya::Internal::Type::Enum

          SUB_AGENT_ID: :subAgentId

          def self?.values: -> ::Array[Cadenya::Models::Agents::AddAgentVariationAssignmentRequestSubAgentID::type_]
        end
      end
    end
  end
end
