module Cadenya
  module Models
    class AgentVariationInfo = Agents::AgentVariationInfo

    module Agents
      type agent_variation_info =
        {
          assignments: ::Array[Cadenya::Models::Agents::variation_assignment],
          created_by: Cadenya::Profile,
          feedback_count: Integer,
          memory_layer_assignments: ::Array[Cadenya::Agents::VariationMemoryLayerAssignment],
          memory_layer_count: Integer,
          model: Cadenya::ResourceMetadata,
          score: Float,
          sub_agent_count: Integer,
          tool_count: Integer,
          tool_set_count: Integer
        }

      class AgentVariationInfo < Cadenya::Internal::Type::BaseModel
        attr_reader created_by: Cadenya::Profile?

        def created_by=: (Cadenya::Profile) -> Cadenya::Profile

        attr_accessor feedback_count: Integer

        attr_accessor score: Float

        attr_accessor assignments: ::Array[Cadenya::Models::Agents::variation_assignment]

        attr_accessor memory_layer_assignments: ::Array[Cadenya::Agents::VariationMemoryLayerAssignment]

        attr_accessor memory_layer_count: Integer

        attr_reader model: Cadenya::ResourceMetadata?

        def model=: (Cadenya::ResourceMetadata) -> Cadenya::ResourceMetadata

        attr_accessor sub_agent_count: Integer

        attr_accessor tool_count: Integer

        attr_accessor tool_set_count: Integer

        def initialize: (
          assignments: ::Array[Cadenya::Models::Agents::variation_assignment],
          feedback_count: Integer,
          memory_layer_assignments: ::Array[Cadenya::Agents::VariationMemoryLayerAssignment],
          memory_layer_count: Integer,
          score: Float,
          sub_agent_count: Integer,
          tool_count: Integer,
          tool_set_count: Integer,
          ?created_by: Cadenya::Profile,
          ?model: Cadenya::ResourceMetadata
        ) -> void

        def to_hash: -> {
          assignments: ::Array[Cadenya::Models::Agents::variation_assignment],
          created_by: Cadenya::Profile,
          feedback_count: Integer,
          memory_layer_assignments: ::Array[Cadenya::Agents::VariationMemoryLayerAssignment],
          memory_layer_count: Integer,
          model: Cadenya::ResourceMetadata,
          score: Float,
          sub_agent_count: Integer,
          tool_count: Integer,
          tool_set_count: Integer
        }
      end
    end
  end
end
