module Cadenya
  module Models
    class AgentScheduleSpec = Agents::AgentScheduleSpec

    module Agents
      type agent_schedule_spec =
        {
          schedule: Cadenya::Agents::AgentScheduleSpecSchedule,
          data: top,
          initial_message: String,
          overlap_policy: Cadenya::Models::Agents::AgentScheduleSpec::overlap_policy,
          user_data: top,
          variation_id: String
        }

      class AgentScheduleSpec < Cadenya::Internal::Type::BaseModel
        attr_accessor schedule: Cadenya::Agents::AgentScheduleSpecSchedule

        attr_reader data: top?

        def data=: (top) -> top

        attr_reader initial_message: String?

        def initial_message=: (String) -> String

        attr_reader overlap_policy: Cadenya::Models::Agents::AgentScheduleSpec::overlap_policy?

        def overlap_policy=: (
          Cadenya::Models::Agents::AgentScheduleSpec::overlap_policy
        ) -> Cadenya::Models::Agents::AgentScheduleSpec::overlap_policy

        attr_reader user_data: top?

        def user_data=: (top) -> top

        attr_reader variation_id: String?

        def variation_id=: (String) -> String

        def initialize: (
          schedule: Cadenya::Agents::AgentScheduleSpecSchedule,
          ?data: top,
          ?initial_message: String,
          ?overlap_policy: Cadenya::Models::Agents::AgentScheduleSpec::overlap_policy,
          ?user_data: top,
          ?variation_id: String
        ) -> void

        def to_hash: -> {
          schedule: Cadenya::Agents::AgentScheduleSpecSchedule,
          data: top,
          initial_message: String,
          overlap_policy: Cadenya::Models::Agents::AgentScheduleSpec::overlap_policy,
          user_data: top,
          variation_id: String
        }

        type overlap_policy =
          :OVERLAP_POLICY_UNSPECIFIED
          | :OVERLAP_POLICY_ALLOW
          | :OVERLAP_POLICY_SKIP

        module OverlapPolicy
          extend Cadenya::Internal::Type::Enum

          OVERLAP_POLICY_UNSPECIFIED: :OVERLAP_POLICY_UNSPECIFIED
          OVERLAP_POLICY_ALLOW: :OVERLAP_POLICY_ALLOW
          OVERLAP_POLICY_SKIP: :OVERLAP_POLICY_SKIP

          def self?.values: -> ::Array[Cadenya::Models::Agents::AgentScheduleSpec::overlap_policy]
        end
      end
    end
  end
end
