module Cadenya
  module Models
    class AgentSchedule = Agents::AgentSchedule

    module Agents
      type agent_schedule =
        {
          metadata: Cadenya::ResourceMetadata,
          spec: Cadenya::Agents::AgentScheduleSpec,
          state: Cadenya::Models::Agents::AgentSchedule::state,
          info: Cadenya::Agents::AgentScheduleInfo
        }

      class AgentSchedule < Cadenya::Internal::Type::BaseModel
        attr_accessor metadata: Cadenya::ResourceMetadata

        attr_accessor spec: Cadenya::Agents::AgentScheduleSpec

        attr_accessor info: Cadenya::Agents::AgentScheduleInfo

        attr_accessor state: Cadenya::Models::Agents::AgentSchedule::state

        def initialize: (
          metadata: Cadenya::ResourceMetadata,
          spec: Cadenya::Agents::AgentScheduleSpec,
          state: Cadenya::Models::Agents::AgentSchedule::state,
          info: Cadenya::Agents::AgentScheduleInfo
        ) -> void

        def to_hash: -> {
          metadata: Cadenya::ResourceMetadata,
          spec: Cadenya::Agents::AgentScheduleSpec,
          state: Cadenya::Models::Agents::AgentSchedule::state,
          info: Cadenya::Agents::AgentScheduleInfo
        }

        type state =
          :STATE_UNSPECIFIED | :STATE_ACTIVE | :STATE_PAUSED | :STATE_ARCHIVED

        module State
          extend Cadenya::Internal::Type::Enum

          STATE_UNSPECIFIED: :STATE_UNSPECIFIED
          STATE_ACTIVE: :STATE_ACTIVE
          STATE_PAUSED: :STATE_PAUSED
          STATE_ARCHIVED: :STATE_ARCHIVED

          def self?.values: -> ::Array[Cadenya::Models::Agents::AgentSchedule::state]
        end
      end
    end
  end
end
