module Cadenya
  module Models
    class AgentVariation = Agents::AgentVariation

    module Agents
      type agent_variation =
        {
          metadata: Cadenya::ResourceMetadata,
          spec: Cadenya::Agents::AgentVariationSpec,
          info: Cadenya::Agents::AgentVariationInfo
        }

      class AgentVariation < Cadenya::Internal::Type::BaseModel
        attr_accessor metadata: Cadenya::ResourceMetadata

        attr_accessor spec: Cadenya::Agents::AgentVariationSpec

        attr_reader info: Cadenya::Agents::AgentVariationInfo?

        def info=: (
          Cadenya::Agents::AgentVariationInfo
        ) -> Cadenya::Agents::AgentVariationInfo

        def initialize: (
          metadata: Cadenya::ResourceMetadata,
          spec: Cadenya::Agents::AgentVariationSpec,
          ?info: Cadenya::Agents::AgentVariationInfo
        ) -> void

        def to_hash: -> {
          metadata: Cadenya::ResourceMetadata,
          spec: Cadenya::Agents::AgentVariationSpec,
          info: Cadenya::Agents::AgentVariationInfo
        }
      end
    end
  end
end
