module Cadenya
  module Models
    class AgentVariationSpec = Agents::AgentVariationSpec

    module Agents
      type agent_variation_spec =
        {
          compaction_config: Cadenya::Agents::AgentVariationSpecCompactionConfig,
          constraints: Cadenya::Agents::AgentVariationSpecConstraints,
          description: String,
          first_user_message_template: String,
          model_config: Cadenya::Agents::AgentVariationSpecModelConfig,
          progressive_discovery: Cadenya::Agents::AgentVariationSpecProgressiveDiscovery,
          system_prompt_template: String
        }

      class AgentVariationSpec < Cadenya::Internal::Type::BaseModel
        attr_reader compaction_config: Cadenya::Agents::AgentVariationSpecCompactionConfig?

        def compaction_config=: (
          Cadenya::Agents::AgentVariationSpecCompactionConfig
        ) -> Cadenya::Agents::AgentVariationSpecCompactionConfig

        attr_reader constraints: Cadenya::Agents::AgentVariationSpecConstraints?

        def constraints=: (
          Cadenya::Agents::AgentVariationSpecConstraints
        ) -> Cadenya::Agents::AgentVariationSpecConstraints

        attr_reader description: String?

        def description=: (String) -> String

        attr_reader first_user_message_template: String?

        def first_user_message_template=: (String) -> String

        attr_reader model_config: Cadenya::Agents::AgentVariationSpecModelConfig?

        def model_config=: (
          Cadenya::Agents::AgentVariationSpecModelConfig
        ) -> Cadenya::Agents::AgentVariationSpecModelConfig

        attr_reader progressive_discovery: Cadenya::Agents::AgentVariationSpecProgressiveDiscovery?

        def progressive_discovery=: (
          Cadenya::Agents::AgentVariationSpecProgressiveDiscovery
        ) -> Cadenya::Agents::AgentVariationSpecProgressiveDiscovery

        attr_reader system_prompt_template: String?

        def system_prompt_template=: (String) -> String

        def initialize: (
          ?compaction_config: Cadenya::Agents::AgentVariationSpecCompactionConfig,
          ?constraints: Cadenya::Agents::AgentVariationSpecConstraints,
          ?description: String,
          ?first_user_message_template: String,
          ?model_config: Cadenya::Agents::AgentVariationSpecModelConfig,
          ?progressive_discovery: Cadenya::Agents::AgentVariationSpecProgressiveDiscovery,
          ?system_prompt_template: String
        ) -> void

        def to_hash: -> {
          compaction_config: Cadenya::Agents::AgentVariationSpecCompactionConfig,
          constraints: Cadenya::Agents::AgentVariationSpecConstraints,
          description: String,
          first_user_message_template: String,
          model_config: Cadenya::Agents::AgentVariationSpecModelConfig,
          progressive_discovery: Cadenya::Agents::AgentVariationSpecProgressiveDiscovery,
          system_prompt_template: String
        }
      end
    end
  end
end
