module Cadenya
  module Models
    module Agents
      type feedback_list_params =
        {
          workspace_id: String,
          agent_id: String,
          agent_variation_id: String,
          created_after: Time,
          created_before: Time,
          cursor: String,
          include_info: bool,
          labels: String,
          limit: Integer,
          query: String,
          sentiment: Cadenya::Models::Agents::FeedbackListParams::sentiment
        }
        & Cadenya::Internal::Type::request_parameters

      class FeedbackListParams < Cadenya::Internal::Type::BaseModel
        extend Cadenya::Internal::Type::RequestParameters::Converter
        include Cadenya::Internal::Type::RequestParameters

        attr_reader workspace_id: String?

        def workspace_id=: (String) -> String

        attr_accessor agent_id: String

        attr_reader agent_variation_id: String?

        def agent_variation_id=: (String) -> String

        attr_reader created_after: Time?

        def created_after=: (Time) -> Time

        attr_reader created_before: Time?

        def created_before=: (Time) -> Time

        attr_reader cursor: String?

        def cursor=: (String) -> String

        attr_reader include_info: bool?

        def include_info=: (bool) -> bool

        attr_reader labels: String?

        def labels=: (String) -> String

        attr_reader limit: Integer?

        def limit=: (Integer) -> Integer

        attr_reader query: String?

        def query=: (String) -> String

        attr_reader sentiment: Cadenya::Models::Agents::FeedbackListParams::sentiment?

        def sentiment=: (
          Cadenya::Models::Agents::FeedbackListParams::sentiment
        ) -> Cadenya::Models::Agents::FeedbackListParams::sentiment

        def initialize: (
          agent_id: String,
          ?workspace_id: String,
          ?agent_variation_id: String,
          ?created_after: Time,
          ?created_before: Time,
          ?cursor: String,
          ?include_info: bool,
          ?labels: String,
          ?limit: Integer,
          ?query: String,
          ?sentiment: Cadenya::Models::Agents::FeedbackListParams::sentiment,
          ?request_options: Cadenya::request_opts
        ) -> void

        def to_hash: -> {
          workspace_id: String,
          agent_id: String,
          agent_variation_id: String,
          created_after: Time,
          created_before: Time,
          cursor: String,
          include_info: bool,
          labels: String,
          limit: Integer,
          query: String,
          sentiment: Cadenya::Models::Agents::FeedbackListParams::sentiment,
          request_options: Cadenya::RequestOptions
        }

        type sentiment =
          :FEEDBACK_SENTIMENT_UNSPECIFIED
          | :FEEDBACK_SENTIMENT_POSITIVE
          | :FEEDBACK_SENTIMENT_NEGATIVE

        module Sentiment
          extend Cadenya::Internal::Type::Enum

          FEEDBACK_SENTIMENT_UNSPECIFIED: :FEEDBACK_SENTIMENT_UNSPECIFIED
          FEEDBACK_SENTIMENT_POSITIVE: :FEEDBACK_SENTIMENT_POSITIVE
          FEEDBACK_SENTIMENT_NEGATIVE: :FEEDBACK_SENTIMENT_NEGATIVE

          def self?.values: -> ::Array[Cadenya::Models::Agents::FeedbackListParams::sentiment]
        end
      end
    end
  end
end
