module Cadenya
  module Models
    module Agents
      type schedule_interval = { every: String, offset: String }

      class ScheduleInterval < Cadenya::Internal::Type::BaseModel
        attr_reader every: String?

        def every=: (String) -> String

        attr_reader offset: String?

        def offset=: (String) -> String

        def initialize: (?every: String, ?offset: String) -> void

        def to_hash: -> { every: String, offset: String }
      end
    end
  end
end
