module Cadenya
  module Models
    module Agents
      type schedule_calendar =
        {
          comment: String,
          day_of_month: ::Array[Cadenya::Agents::ScheduleRange],
          day_of_week: ::Array[Cadenya::Agents::ScheduleRange],
          hour: ::Array[Cadenya::Agents::ScheduleRange],
          minute: ::Array[Cadenya::Agents::ScheduleRange],
          month: ::Array[Cadenya::Agents::ScheduleRange],
          second: ::Array[Cadenya::Agents::ScheduleRange]
        }

      class ScheduleCalendar < Cadenya::Internal::Type::BaseModel
        attr_reader comment: String?

        def comment=: (String) -> String

        attr_reader day_of_month: ::Array[Cadenya::Agents::ScheduleRange]?

        def day_of_month=: (
          ::Array[Cadenya::Agents::ScheduleRange]
        ) -> ::Array[Cadenya::Agents::ScheduleRange]

        attr_reader day_of_week: ::Array[Cadenya::Agents::ScheduleRange]?

        def day_of_week=: (
          ::Array[Cadenya::Agents::ScheduleRange]
        ) -> ::Array[Cadenya::Agents::ScheduleRange]

        attr_reader hour: ::Array[Cadenya::Agents::ScheduleRange]?

        def hour=: (
          ::Array[Cadenya::Agents::ScheduleRange]
        ) -> ::Array[Cadenya::Agents::ScheduleRange]

        attr_reader minute: ::Array[Cadenya::Agents::ScheduleRange]?

        def minute=: (
          ::Array[Cadenya::Agents::ScheduleRange]
        ) -> ::Array[Cadenya::Agents::ScheduleRange]

        attr_reader month: ::Array[Cadenya::Agents::ScheduleRange]?

        def month=: (
          ::Array[Cadenya::Agents::ScheduleRange]
        ) -> ::Array[Cadenya::Agents::ScheduleRange]

        attr_reader second: ::Array[Cadenya::Agents::ScheduleRange]?

        def second=: (
          ::Array[Cadenya::Agents::ScheduleRange]
        ) -> ::Array[Cadenya::Agents::ScheduleRange]

        def initialize: (
          ?comment: String,
          ?day_of_month: ::Array[Cadenya::Agents::ScheduleRange],
          ?day_of_week: ::Array[Cadenya::Agents::ScheduleRange],
          ?hour: ::Array[Cadenya::Agents::ScheduleRange],
          ?minute: ::Array[Cadenya::Agents::ScheduleRange],
          ?month: ::Array[Cadenya::Agents::ScheduleRange],
          ?second: ::Array[Cadenya::Agents::ScheduleRange]
        ) -> void

        def to_hash: -> {
          comment: String,
          day_of_month: ::Array[Cadenya::Agents::ScheduleRange],
          day_of_week: ::Array[Cadenya::Agents::ScheduleRange],
          hour: ::Array[Cadenya::Agents::ScheduleRange],
          minute: ::Array[Cadenya::Agents::ScheduleRange],
          month: ::Array[Cadenya::Agents::ScheduleRange],
          second: ::Array[Cadenya::Agents::ScheduleRange]
        }
      end
    end
  end
end
