module Cadenya
  module Models
    module Agents
      type schedule_create_params =
        {
          workspace_id: String,
          agent_id: String,
          metadata: Cadenya::CreateResourceMetadata,
          spec: Cadenya::Agents::AgentScheduleSpec
        }
        & Cadenya::Internal::Type::request_parameters

      class ScheduleCreateParams < Cadenya::Internal::Type::BaseModel
        extend Cadenya::Internal::Type::RequestParameters::Converter
        include Cadenya::Internal::Type::RequestParameters

        attr_reader workspace_id: String?

        def workspace_id=: (String) -> String

        attr_accessor agent_id: String

        attr_accessor metadata: Cadenya::CreateResourceMetadata

        attr_accessor spec: Cadenya::Agents::AgentScheduleSpec

        def initialize: (
          agent_id: String,
          metadata: Cadenya::CreateResourceMetadata,
          spec: Cadenya::Agents::AgentScheduleSpec,
          ?workspace_id: String,
          ?request_options: Cadenya::request_opts
        ) -> void

        def to_hash: -> {
          workspace_id: String,
          agent_id: String,
          metadata: Cadenya::CreateResourceMetadata,
          spec: Cadenya::Agents::AgentScheduleSpec,
          request_options: Cadenya::RequestOptions
        }
      end
    end
  end
end
