module Cadenya
  module Models
    module Agents
      type variation_create_params =
        {
          workspace_id: String,
          agent_id: String,
          metadata: Cadenya::CreateResourceMetadata,
          spec: Cadenya::Agents::AgentVariationSpec
        }
        & Cadenya::Internal::Type::request_parameters

      class VariationCreateParams < Cadenya::Internal::Type::BaseModel
        extend Cadenya::Internal::Type::RequestParameters::Converter
        include Cadenya::Internal::Type::RequestParameters

        attr_accessor workspace_id: String

        attr_accessor agent_id: String

        attr_accessor metadata: Cadenya::CreateResourceMetadata

        attr_accessor spec: Cadenya::Agents::AgentVariationSpec

        def initialize: (
          workspace_id: String,
          agent_id: String,
          metadata: Cadenya::CreateResourceMetadata,
          spec: Cadenya::Agents::AgentVariationSpec,
          ?request_options: Cadenya::request_opts
        ) -> void

        def to_hash: -> {
          workspace_id: String,
          agent_id: String,
          metadata: Cadenya::CreateResourceMetadata,
          spec: Cadenya::Agents::AgentVariationSpec,
          request_options: Cadenya::RequestOptions
        }
      end
    end
  end
end
