module Cadenya
  module Models
    class VariationAssignmentAgent = Agents::VariationAssignmentAgent

    module Agents
      type variation_assignment_agent =
        {
          agent: Cadenya::BareMetadata,
          type: Cadenya::Models::Agents::VariationAssignmentAgent::type_,
          id: String
        }

      class VariationAssignmentAgent < Cadenya::Internal::Type::BaseModel
        attr_accessor agent: Cadenya::BareMetadata

        attr_accessor type: Cadenya::Models::Agents::VariationAssignmentAgent::type_

        attr_reader id: String?

        def id=: (String) -> String

        def initialize: (
          agent: Cadenya::BareMetadata,
          type: Cadenya::Models::Agents::VariationAssignmentAgent::type_,
          ?id: String
        ) -> void

        def to_hash: -> {
          agent: Cadenya::BareMetadata,
          type: Cadenya::Models::Agents::VariationAssignmentAgent::type_,
          id: String
        }

        type type_ = :agent

        module Type
          extend Cadenya::Internal::Type::Enum

          AGENT: :agent

          def self?.values: -> ::Array[Cadenya::Models::Agents::VariationAssignmentAgent::type_]
        end
      end
    end
  end
end
