module Cadenya
  module Models
    module Agents
      type variation_assignment =
        {
          id: String,
          agent: Cadenya::BareMetadata,
          tool: Cadenya::BareMetadata,
          tool_set: Cadenya::BareMetadata,
          type: String
        }

      class VariationAssignment < Cadenya::Internal::Type::BaseModel
        attr_reader agent: Cadenya::BareMetadata?

        def agent=: (Cadenya::BareMetadata) -> Cadenya::BareMetadata

        attr_reader tool: Cadenya::BareMetadata?

        def tool=: (Cadenya::BareMetadata) -> Cadenya::BareMetadata

        attr_reader tool_set: Cadenya::BareMetadata?

        def tool_set=: (Cadenya::BareMetadata) -> Cadenya::BareMetadata

        attr_reader type: String?

        def type=: (String) -> String

        attr_reader id: String?

        def id=: (String) -> String

        def initialize: (
          ?id: String,
          ?agent: Cadenya::BareMetadata,
          ?tool: Cadenya::BareMetadata,
          ?tool_set: Cadenya::BareMetadata,
          ?type: String
        ) -> void

        def to_hash: -> {
          id: String,
          agent: Cadenya::BareMetadata,
          tool: Cadenya::BareMetadata,
          tool_set: Cadenya::BareMetadata,
          type: String
        }
      end
    end
  end
end
