module Cadenya
  module Models
    module Agents
      type variation_memory_layer_assignment =
        { id: String, memory_layer: Cadenya::BareMetadata, position: Integer }

      class VariationMemoryLayerAssignment < Cadenya::Internal::Type::BaseModel
        attr_accessor memory_layer: Cadenya::BareMetadata

        attr_accessor position: Integer

        attr_accessor id: String

        def initialize: (
          id: String,
          memory_layer: Cadenya::BareMetadata,
          position: Integer
        ) -> void

        def to_hash: -> {
          id: String,
          memory_layer: Cadenya::BareMetadata,
          position: Integer
        }
      end
    end
  end
end
