module Cadenya
  module Models
    module Agents
      type variation_assignment_tool_set =
        {
          tool_set: Cadenya::BareMetadata,
          type: Cadenya::Models::Agents::VariationAssignmentToolSet::type_,
          id: String
        }

      class VariationAssignmentToolSet < Cadenya::Internal::Type::BaseModel
        attr_accessor tool_set: Cadenya::BareMetadata

        attr_accessor type: Cadenya::Models::Agents::VariationAssignmentToolSet::type_

        attr_reader id: String?

        def id=: (String) -> String

        def initialize: (
          tool_set: Cadenya::BareMetadata,
          type: Cadenya::Models::Agents::VariationAssignmentToolSet::type_,
          ?id: String
        ) -> void

        def to_hash: -> {
          tool_set: Cadenya::BareMetadata,
          type: Cadenya::Models::Agents::VariationAssignmentToolSet::type_,
          id: String
        }

        type type_ = :toolSet

        module Type
          extend Cadenya::Internal::Type::Enum

          TOOL_SET: :toolSet

          def self?.values: -> ::Array[Cadenya::Models::Agents::VariationAssignmentToolSet::type_]
        end
      end
    end
  end
end
