module Cadenya
  module Models
    module Agents
      type variation_add_assignment_params =
        {
          workspace_id: String,
          agent_id: String,
          variation_id: String,
          sub_agent_id: String,
          tool_id: String,
          tool_set_id: String
        }
        & Cadenya::Internal::Type::request_parameters

      class VariationAddAssignmentParams < Cadenya::Internal::Type::BaseModel
        extend Cadenya::Internal::Type::RequestParameters::Converter
        include Cadenya::Internal::Type::RequestParameters

        attr_accessor workspace_id: String

        attr_accessor agent_id: String

        attr_accessor variation_id: String

        attr_reader sub_agent_id: String?

        def sub_agent_id=: (String) -> String

        attr_reader tool_id: String?

        def tool_id=: (String) -> String

        attr_reader tool_set_id: String?

        def tool_set_id=: (String) -> String

        def initialize: (
          workspace_id: String,
          agent_id: String,
          variation_id: String,
          ?sub_agent_id: String,
          ?tool_id: String,
          ?tool_set_id: String,
          ?request_options: Cadenya::request_opts
        ) -> void

        def to_hash: -> {
          workspace_id: String,
          agent_id: String,
          variation_id: String,
          sub_agent_id: String,
          tool_id: String,
          tool_set_id: String,
          request_options: Cadenya::RequestOptions
        }
      end
    end
  end
end
