module Cadenya
  module Models
    module Agents
      type variation_assignment =
        Cadenya::Agents::VariationAssignmentTool
        | Cadenya::Agents::VariationAssignmentToolSet
        | Cadenya::Agents::VariationAssignmentAgent

      module VariationAssignment
        extend Cadenya::Internal::Type::Union

        def self?.variants: -> ::Array[Cadenya::Models::Agents::variation_assignment]
      end
    end
  end
end
