module Cadenya
  module Models
    module Agents
      type variation_assignment_tool =
        {
          tool: Cadenya::BareMetadata,
          type: Cadenya::Models::Agents::VariationAssignmentTool::type_,
          id: String
        }

      class VariationAssignmentTool < Cadenya::Internal::Type::BaseModel
        attr_accessor tool: Cadenya::BareMetadata

        attr_accessor type: Cadenya::Models::Agents::VariationAssignmentTool::type_

        attr_reader id: String?

        def id=: (String) -> String

        def initialize: (
          tool: Cadenya::BareMetadata,
          type: Cadenya::Models::Agents::VariationAssignmentTool::type_,
          ?id: String
        ) -> void

        def to_hash: -> {
          tool: Cadenya::BareMetadata,
          type: Cadenya::Models::Agents::VariationAssignmentTool::type_,
          id: String
        }

        type type_ = :tool

        module Type
          extend Cadenya::Internal::Type::Enum

          TOOL: :tool

          def self?.values: -> ::Array[Cadenya::Models::Agents::VariationAssignmentTool::type_]
        end
      end
    end
  end
end
