module Cadenya
  module Models
    module Agents
      type variation_add_memory_layer_params =
        {
          workspace_id: String,
          agent_id: String,
          variation_id: String,
          memory_layer_id: String,
          position: Integer
        }
        & Cadenya::Internal::Type::request_parameters

      class VariationAddMemoryLayerParams < Cadenya::Internal::Type::BaseModel
        extend Cadenya::Internal::Type::RequestParameters::Converter
        include Cadenya::Internal::Type::RequestParameters

        attr_accessor workspace_id: String

        attr_accessor agent_id: String

        attr_accessor variation_id: String

        attr_reader memory_layer_id: String?

        def memory_layer_id=: (String) -> String

        attr_reader position: Integer?

        def position=: (Integer) -> Integer

        def initialize: (
          workspace_id: String,
          agent_id: String,
          variation_id: String,
          ?memory_layer_id: String,
          ?position: Integer,
          ?request_options: Cadenya::request_opts
        ) -> void

        def to_hash: -> {
          workspace_id: String,
          agent_id: String,
          variation_id: String,
          memory_layer_id: String,
          position: Integer,
          request_options: Cadenya::RequestOptions
        }
      end
    end
  end
end
