module Cadenya
  module Models
    module Agents
      type webhook_delivery =
        {
          data: Cadenya::Agents::WebhookDeliveryData,
          metadata: Cadenya::OperationMetadata
        }

      class WebhookDelivery < Cadenya::Internal::Type::BaseModel
        attr_accessor data: Cadenya::Agents::WebhookDeliveryData

        attr_accessor metadata: Cadenya::OperationMetadata

        def initialize: (
          data: Cadenya::Agents::WebhookDeliveryData,
          metadata: Cadenya::OperationMetadata
        ) -> void

        def to_hash: -> {
          data: Cadenya::Agents::WebhookDeliveryData,
          metadata: Cadenya::OperationMetadata
        }
      end
    end
  end
end
