module Cadenya
  module Resources
    class WorkspaceAdmin
      class Profiles
        def list: (
          ?cursor: String,
          ?labels: String,
          ?limit: Integer,
          ?query: String,
          ?request_options: Cadenya::request_opts
        ) -> Cadenya::Internal::CursorPagination[Cadenya::Profile]

        def initialize: (client: Cadenya::Client) -> void
      end
    end
  end
end
