module Cadenya
  module Models
    module WorkspaceAdmin
      type profile_list_params =
        { cursor: String, labels: String, limit: Integer, query: String }
        & Cadenya::Internal::Type::request_parameters

      class ProfileListParams < Cadenya::Internal::Type::BaseModel
        extend Cadenya::Internal::Type::RequestParameters::Converter
        include Cadenya::Internal::Type::RequestParameters

        attr_reader cursor: String?

        def cursor=: (String) -> String

        attr_reader labels: String?

        def labels=: (String) -> String

        attr_reader limit: Integer?

        def limit=: (Integer) -> Integer

        attr_reader query: String?

        def query=: (String) -> String

        def initialize: (
          ?cursor: String,
          ?labels: String,
          ?limit: Integer,
          ?query: String,
          ?request_options: Cadenya::request_opts
        ) -> void

        def to_hash: -> {
          cursor: String,
          labels: String,
          limit: Integer,
          query: String,
          request_options: Cadenya::RequestOptions
        }
      end
    end
  end
end
