# frozen_string_literal: true

# Code generated by redwood. DO NOT EDIT.

RSpec.describe "client.accounts" do
  let(:client) { build_client }

  describe "#retrieve" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("AccountService_GetAccount") do
        result = client.accounts.retrieve
        expect(result).to be_a(Cadenya::Types::Account)
      end
    end
  end

  describe "#rotate_challenge_token" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("AccountService_RotateChallengeToken") do
        result = client.accounts.rotate_challenge_token
        expect(result).to be_a(Cadenya::Types::RotateChallengeTokenResponse)
      end
    end
  end

  describe "#rotate_webhook_signing_key" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("AccountService_RotateWebhookSigningKey") do
        result = client.accounts.rotate_webhook_signing_key
        expect(result).to be_a(Cadenya::Types::RotateWebhookEventsHmacSecretResponse)
      end
    end
  end
end
