# frozen_string_literal: true

# Code generated by redwood. DO NOT EDIT.

RSpec.describe "client.agents" do
  let(:client) { build_client }

  describe "#list" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("AgentService_ListAgents") do
        result = client.agents.list(workspace_id: "sample", limit: 1, cursor: "sample", prefix: "sample", query: "sample", state: "STATE_UNSPECIFIED", variation_selection_mode: "VARIATION_SELECTION_MODE_UNSPECIFIED", labels: "sample", sort_order: "sample", include_info: true)
        items = result.to_a
        expect(items.length).to eq(2)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:get, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/agents")
          .with(query: hash_including({}))
          .to_return(status: 200, body: "{\"items\":[{\"info\":{\"variationCount\":1},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"variationSelectionMode\":\"VARIATION_SELECTION_MODE_UNSPECIFIED\"},\"state\":\"STATE_UNSPECIFIED\"}],\"pagination\":{\"nextCursor\":\"\"}}", headers: { "Content-Type" => "application/json" })
        client.agents.list(limit: 1, cursor: "sample", prefix: "sample", query: "sample", state: "STATE_UNSPECIFIED", variation_selection_mode: "VARIATION_SELECTION_MODE_UNSPECIFIED", labels: "sample", sort_order: "sample", include_info: true)
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#create" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("AgentService_CreateAgent") do
        result = client.agents.create(workspace_id: "sample", metadata: {"name" => "sample"}, spec: {"variation_selection_mode" => "VARIATION_SELECTION_MODE_UNSPECIFIED"}, default_variation: {"metadata" => {"name" => "sample"}, "spec" => {}})
        expect(result).to be_a(Cadenya::Types::Agent)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:post, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/agents")
          .to_return(status: 200, body: "{\"info\":{\"variationCount\":1},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"variationSelectionMode\":\"VARIATION_SELECTION_MODE_UNSPECIFIED\"},\"state\":\"STATE_UNSPECIFIED\"}", headers: { "Content-Type" => "application/json" })
        client.agents.create(metadata: {"name" => "sample"}, spec: {"variation_selection_mode" => "VARIATION_SELECTION_MODE_UNSPECIFIED"}, default_variation: {"metadata" => {"name" => "sample"}, "spec" => {}})
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#list_feedback" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("AgentService_ListAgentFeedback") do
        result = client.agents.list_feedback("sample", workspace_id: "sample", limit: 1, cursor: "sample", query: "sample", sentiment: "FEEDBACK_SENTIMENT_UNSPECIFIED", agent_variation_id: "sample", created_after: "2026-01-01T00:00:00Z", created_before: "2026-01-01T00:00:00Z", labels: "sample", include_info: true)
        items = result.to_a
        expect(items.length).to eq(2)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:get, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/agents/sample/feedback")
          .with(query: hash_including({}))
          .to_return(status: 200, body: "{\"items\":[{\"data\":{},\"info\":{\"submittedBy\":{\"metadata\":{\"accountId\":\"sample\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\"},\"spec\":{\"email\":\"sample\",\"name\":\"sample\",\"type\":\"PROFILE_TYPE_UNSPECIFIED\"}}},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"profileId\":\"sample\",\"workspaceId\":\"sample\"}}],\"pagination\":{\"nextCursor\":\"\"}}", headers: { "Content-Type" => "application/json" })
        client.agents.list_feedback("sample", limit: 1, cursor: "sample", query: "sample", sentiment: "FEEDBACK_SENTIMENT_UNSPECIFIED", agent_variation_id: "sample", created_after: "2026-01-01T00:00:00Z", created_before: "2026-01-01T00:00:00Z", labels: "sample", include_info: true)
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#list_webhook_deliveries" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("AgentService_ListAgentWebhookDeliveries") do
        result = client.agents.list_webhook_deliveries("sample", workspace_id: "sample", cursor: "sample", limit: 1, objective_id: "sample", event_type: "OBJECTIVE_EVENT_TYPE_UNSPECIFIED", labels: "sample")
        items = result.to_a
        expect(items.length).to eq(2)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:get, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/agents/sample/webhook_deliveries")
          .with(query: hash_including({}))
          .to_return(status: 200, body: "{\"items\":[{\"data\":{\"agentId\":\"sample\",\"attemptCount\":1,\"errorMessage\":\"sample\",\"eventType\":\"OBJECTIVE_EVENT_TYPE_UNSPECIFIED\",\"httpStatusCode\":1,\"lastAttemptAt\":\"2026-01-01T00:00:00Z\",\"latencyMs\":1,\"objectiveEventId\":\"sample\",\"objectiveId\":\"sample\",\"responseContentLength\":\"sample\",\"responseHeaders\":{},\"status\":\"WEBHOOK_DELIVERY_STATUS_UNSPECIFIED\",\"webhookId\":\"sample\",\"webhookUrl\":\"sample\"},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"profileId\":\"sample\",\"workspaceId\":\"sample\"}}],\"pagination\":{\"nextCursor\":\"\"}}", headers: { "Content-Type" => "application/json" })
        client.agents.list_webhook_deliveries("sample", cursor: "sample", limit: 1, objective_id: "sample", event_type: "OBJECTIVE_EVENT_TYPE_UNSPECIFIED", labels: "sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#retrieve" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("AgentService_GetAgent") do
        result = client.agents.retrieve("sample", workspace_id: "sample")
        expect(result).to be_a(Cadenya::Types::Agent)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:get, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/agents/sample")
          .to_return(status: 200, body: "{\"info\":{\"variationCount\":1},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"variationSelectionMode\":\"VARIATION_SELECTION_MODE_UNSPECIFIED\"},\"state\":\"STATE_UNSPECIFIED\"}", headers: { "Content-Type" => "application/json" })
        client.agents.retrieve("sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#delete" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("AgentService_DeleteAgent") do
        result = client.agents.delete("sample", workspace_id: "sample")
        expect(result).to be_nil
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:delete, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/agents/sample")
          .to_return(status: 204, body: "")
        client.agents.delete("sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#update" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("AgentService_UpdateAgent") do
        result = client.agents.update("sample", workspace_id: "sample", metadata: {"name" => "sample"}, spec: {"variation_selection_mode" => "VARIATION_SELECTION_MODE_UNSPECIFIED"}, update_mask: "sample")
        expect(result).to be_a(Cadenya::Types::Agent)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:patch, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/agents/sample")
          .to_return(status: 200, body: "{\"info\":{\"variationCount\":1},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"variationSelectionMode\":\"VARIATION_SELECTION_MODE_UNSPECIFIED\"},\"state\":\"STATE_UNSPECIFIED\"}", headers: { "Content-Type" => "application/json" })
        client.agents.update("sample", metadata: {"name" => "sample"}, spec: {"variation_selection_mode" => "VARIATION_SELECTION_MODE_UNSPECIFIED"}, update_mask: "sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#archive" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("AgentService_ArchiveAgent") do
        result = client.agents.archive("sample", workspace_id: "sample")
        expect(result).to be_a(Cadenya::Types::Agent)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:post, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/agents/sample:archive")
          .to_return(status: 200, body: "{\"info\":{\"variationCount\":1},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"variationSelectionMode\":\"VARIATION_SELECTION_MODE_UNSPECIFIED\"},\"state\":\"STATE_UNSPECIFIED\"}", headers: { "Content-Type" => "application/json" })
        client.agents.archive("sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#publish" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("AgentService_PublishAgent") do
        result = client.agents.publish("sample", workspace_id: "sample")
        expect(result).to be_a(Cadenya::Types::Agent)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:post, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/agents/sample:publish")
          .to_return(status: 200, body: "{\"info\":{\"variationCount\":1},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"variationSelectionMode\":\"VARIATION_SELECTION_MODE_UNSPECIFIED\"},\"state\":\"STATE_UNSPECIFIED\"}", headers: { "Content-Type" => "application/json" })
        client.agents.publish("sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#unarchive" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("AgentService_UnarchiveAgent") do
        result = client.agents.unarchive("sample", workspace_id: "sample")
        expect(result).to be_a(Cadenya::Types::Agent)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:post, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/agents/sample:unarchive")
          .to_return(status: 200, body: "{\"info\":{\"variationCount\":1},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"variationSelectionMode\":\"VARIATION_SELECTION_MODE_UNSPECIFIED\"},\"state\":\"STATE_UNSPECIFIED\"}", headers: { "Content-Type" => "application/json" })
        client.agents.unarchive("sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#unpublish" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("AgentService_UnpublishAgent") do
        result = client.agents.unpublish("sample", workspace_id: "sample")
        expect(result).to be_a(Cadenya::Types::Agent)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:post, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/agents/sample:unpublish")
          .to_return(status: 200, body: "{\"info\":{\"variationCount\":1},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"variationSelectionMode\":\"VARIATION_SELECTION_MODE_UNSPECIFIED\"},\"state\":\"STATE_UNSPECIFIED\"}", headers: { "Content-Type" => "application/json" })
        client.agents.unpublish("sample")
        expect(stub).to have_been_requested
      end
    end
  end
end
