# frozen_string_literal: true

# Code generated by redwood. DO NOT EDIT.

RSpec.describe "client.agents.schedules" do
  let(:client) { build_client }

  describe "#list" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("AgentScheduleService_ListAgentSchedules") do
        result = client.agents.schedules.list("sample", workspace_id: "sample", limit: 1, cursor: "sample", prefix: "sample", query: "sample", labels: "sample", sort_order: "sample", include_info: true)
        items = result.to_a
        expect(items.length).to eq(2)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:get, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/agents/sample/schedules")
          .with(query: hash_including({}))
          .to_return(status: 200, body: "{\"items\":[{\"info\":{\"totalFires\":1},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"schedule\":{}},\"state\":\"STATE_UNSPECIFIED\"}],\"pagination\":{\"nextCursor\":\"\"}}", headers: { "Content-Type" => "application/json" })
        client.agents.schedules.list("sample", limit: 1, cursor: "sample", prefix: "sample", query: "sample", labels: "sample", sort_order: "sample", include_info: true)
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#create" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("AgentScheduleService_CreateAgentSchedule") do
        result = client.agents.schedules.create("sample", workspace_id: "sample", metadata: {"name" => "sample"}, spec: {"schedule" => {}})
        expect(result).to be_a(Cadenya::Types::AgentSchedule)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:post, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/agents/sample/schedules")
          .to_return(status: 200, body: "{\"info\":{\"totalFires\":1},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"schedule\":{}},\"state\":\"STATE_UNSPECIFIED\"}", headers: { "Content-Type" => "application/json" })
        client.agents.schedules.create("sample", metadata: {"name" => "sample"}, spec: {"schedule" => {}})
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#retrieve" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("AgentScheduleService_GetAgentSchedule") do
        result = client.agents.schedules.retrieve("sample", "sample", workspace_id: "sample")
        expect(result).to be_a(Cadenya::Types::AgentSchedule)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:get, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/agents/sample/schedules/sample")
          .to_return(status: 200, body: "{\"info\":{\"totalFires\":1},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"schedule\":{}},\"state\":\"STATE_UNSPECIFIED\"}", headers: { "Content-Type" => "application/json" })
        client.agents.schedules.retrieve("sample", "sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#delete" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("AgentScheduleService_DeleteAgentSchedule") do
        result = client.agents.schedules.delete("sample", "sample", workspace_id: "sample")
        expect(result).to be_nil
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:delete, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/agents/sample/schedules/sample")
          .to_return(status: 204, body: "")
        client.agents.schedules.delete("sample", "sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#update" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("AgentScheduleService_UpdateAgentSchedule") do
        result = client.agents.schedules.update("sample", "sample", workspace_id: "sample", metadata: {"name" => "sample"}, spec: {"schedule" => {}}, update_mask: "sample")
        expect(result).to be_a(Cadenya::Types::AgentSchedule)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:patch, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/agents/sample/schedules/sample")
          .to_return(status: 200, body: "{\"info\":{\"totalFires\":1},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"schedule\":{}},\"state\":\"STATE_UNSPECIFIED\"}", headers: { "Content-Type" => "application/json" })
        client.agents.schedules.update("sample", "sample", metadata: {"name" => "sample"}, spec: {"schedule" => {}}, update_mask: "sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#archive" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("AgentScheduleService_ArchiveAgentSchedule") do
        result = client.agents.schedules.archive("sample", "sample", workspace_id: "sample")
        expect(result).to be_a(Cadenya::Types::AgentSchedule)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:post, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/agents/sample/schedules/sample:archive")
          .to_return(status: 200, body: "{\"info\":{\"totalFires\":1},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"schedule\":{}},\"state\":\"STATE_UNSPECIFIED\"}", headers: { "Content-Type" => "application/json" })
        client.agents.schedules.archive("sample", "sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#pause" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("AgentScheduleService_PauseAgentSchedule") do
        result = client.agents.schedules.pause("sample", "sample", workspace_id: "sample")
        expect(result).to be_a(Cadenya::Types::AgentSchedule)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:post, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/agents/sample/schedules/sample:pause")
          .to_return(status: 200, body: "{\"info\":{\"totalFires\":1},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"schedule\":{}},\"state\":\"STATE_UNSPECIFIED\"}", headers: { "Content-Type" => "application/json" })
        client.agents.schedules.pause("sample", "sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#resume" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("AgentScheduleService_ResumeAgentSchedule") do
        result = client.agents.schedules.resume("sample", "sample", workspace_id: "sample")
        expect(result).to be_a(Cadenya::Types::AgentSchedule)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:post, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/agents/sample/schedules/sample:resume")
          .to_return(status: 200, body: "{\"info\":{\"totalFires\":1},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"schedule\":{}},\"state\":\"STATE_UNSPECIFIED\"}", headers: { "Content-Type" => "application/json" })
        client.agents.schedules.resume("sample", "sample")
        expect(stub).to have_been_requested
      end
    end
  end
end
