# frozen_string_literal: true

# Code generated by redwood. DO NOT EDIT.

RSpec.describe "client.agent_pools" do
  let(:client) { build_client }

  describe "#list" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("AgentPoolService_ListAgentPools") do
        result = client.agent_pools.list(workspace_id: "sample", limit: 1, cursor: "sample", prefix: "sample", query: "sample", state: "AGENT_POOL_STATE_ACTIVE", labels: "sample", sort_order: "sample", include_info: true)
        items = result.to_a
        expect(items.length).to eq(2)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:get, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/agent_pools")
          .with(query: hash_including({}))
          .to_return(status: 200, body: "{\"items\":[{\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"assignments\":[{\"agentId\":\"sample\"}],\"description\":\"sample\"},\"state\":\"AGENT_POOL_STATE_ACTIVE\"}],\"pagination\":{\"nextCursor\":\"\"}}", headers: { "Content-Type" => "application/json" })
        client.agent_pools.list(limit: 1, cursor: "sample", prefix: "sample", query: "sample", state: "AGENT_POOL_STATE_ACTIVE", labels: "sample", sort_order: "sample", include_info: true)
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#create" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("AgentPoolService_CreateAgentPool") do
        result = client.agent_pools.create(workspace_id: "sample", metadata: {"name" => "sample"}, spec: {"assignments" => [{"agent_id" => "sample"}], "description" => "sample"})
        expect(result).to be_a(Cadenya::Types::AgentPool)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:post, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/agent_pools")
          .to_return(status: 200, body: "{\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"assignments\":[{\"agentId\":\"sample\"}],\"description\":\"sample\"},\"state\":\"AGENT_POOL_STATE_ACTIVE\"}", headers: { "Content-Type" => "application/json" })
        client.agent_pools.create(metadata: {"name" => "sample"}, spec: {"assignments" => [{"agent_id" => "sample"}], "description" => "sample"})
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#retrieve" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("AgentPoolService_GetAgentPool") do
        result = client.agent_pools.retrieve("sample", workspace_id: "sample")
        expect(result).to be_a(Cadenya::Types::AgentPool)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:get, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/agent_pools/sample")
          .to_return(status: 200, body: "{\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"assignments\":[{\"agentId\":\"sample\"}],\"description\":\"sample\"},\"state\":\"AGENT_POOL_STATE_ACTIVE\"}", headers: { "Content-Type" => "application/json" })
        client.agent_pools.retrieve("sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#delete" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("AgentPoolService_DeleteAgentPool") do
        result = client.agent_pools.delete("sample", workspace_id: "sample")
        expect(result).to be_nil
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:delete, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/agent_pools/sample")
          .to_return(status: 204, body: "")
        client.agent_pools.delete("sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#update" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("AgentPoolService_UpdateAgentPool") do
        result = client.agent_pools.update("sample", workspace_id: "sample", metadata: {"name" => "sample"}, spec: {}, update_mask: "sample")
        expect(result).to be_a(Cadenya::Types::AgentPool)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:patch, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/agent_pools/sample")
          .to_return(status: 200, body: "{\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"assignments\":[{\"agentId\":\"sample\"}],\"description\":\"sample\"},\"state\":\"AGENT_POOL_STATE_ACTIVE\"}", headers: { "Content-Type" => "application/json" })
        client.agent_pools.update("sample", metadata: {"name" => "sample"}, spec: {}, update_mask: "sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#activate" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("AgentPoolService_ActivateAgentPool") do
        result = client.agent_pools.activate("sample", workspace_id: "sample")
        expect(result).to be_a(Cadenya::Types::AgentPool)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:post, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/agent_pools/sample:activate")
          .to_return(status: 200, body: "{\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"assignments\":[{\"agentId\":\"sample\"}],\"description\":\"sample\"},\"state\":\"AGENT_POOL_STATE_ACTIVE\"}", headers: { "Content-Type" => "application/json" })
        client.agent_pools.activate("sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#archive" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("AgentPoolService_ArchiveAgentPool") do
        result = client.agent_pools.archive("sample", workspace_id: "sample")
        expect(result).to be_a(Cadenya::Types::AgentPool)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:post, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/agent_pools/sample:archive")
          .to_return(status: 200, body: "{\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"assignments\":[{\"agentId\":\"sample\"}],\"description\":\"sample\"},\"state\":\"AGENT_POOL_STATE_ACTIVE\"}", headers: { "Content-Type" => "application/json" })
        client.agent_pools.archive("sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#deactivate" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("AgentPoolService_DeactivateAgentPool") do
        result = client.agent_pools.deactivate("sample", workspace_id: "sample")
        expect(result).to be_a(Cadenya::Types::AgentPool)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:post, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/agent_pools/sample:deactivate")
          .to_return(status: 200, body: "{\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"assignments\":[{\"agentId\":\"sample\"}],\"description\":\"sample\"},\"state\":\"AGENT_POOL_STATE_ACTIVE\"}", headers: { "Content-Type" => "application/json" })
        client.agent_pools.deactivate("sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#unarchive" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("AgentPoolService_UnarchiveAgentPool") do
        result = client.agent_pools.unarchive("sample", workspace_id: "sample")
        expect(result).to be_a(Cadenya::Types::AgentPool)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:post, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/agent_pools/sample:unarchive")
          .to_return(status: 200, body: "{\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"assignments\":[{\"agentId\":\"sample\"}],\"description\":\"sample\"},\"state\":\"AGENT_POOL_STATE_ACTIVE\"}", headers: { "Content-Type" => "application/json" })
        client.agent_pools.unarchive("sample")
        expect(stub).to have_been_requested
      end
    end
  end
end
