# frozen_string_literal: true

# Code generated by redwood. DO NOT EDIT.

RSpec.describe "client.api_keys" do
  let(:client) { build_client }

  describe "#retrieve_global" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("GlobalAPIKeyService_GetGlobalAPIKey") do
        result = client.api_keys.retrieve_global
        expect(result).to be_a(Cadenya::Types::APIKey)
      end
    end
  end

  describe "#disable_global" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("GlobalAPIKeyService_DisableGlobalAPIKey") do
        result = client.api_keys.disable_global
        expect(result).to be_a(Cadenya::Types::APIKey)
      end
    end
  end

  describe "#enable_global" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("GlobalAPIKeyService_EnableGlobalAPIKey") do
        result = client.api_keys.enable_global
        expect(result).to be_a(Cadenya::Types::APIKey)
      end
    end
  end

  describe "#rotate_global" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("GlobalAPIKeyService_RotateGlobalAPIKey") do
        result = client.api_keys.rotate_global
        expect(result).to be_a(Cadenya::Types::APIKey)
      end
    end
  end

  describe "#list" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("APIKeyService_ListAPIKeys") do
        result = client.api_keys.list(workspace_id: "sample", limit: 1, cursor: "sample", prefix: "sample", query: "sample", labels: "sample", sort_order: "sample", include_info: true)
        items = result.to_a
        expect(items.length).to eq(2)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:get, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/api_keys")
          .with(query: hash_including({}))
          .to_return(status: 200, body: "{\"items\":[{\"metadata\":{\"accountId\":\"sample\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\"},\"spec\":{\"system\":true,\"token\":\"sample\"},\"state\":\"STATE_UNSPECIFIED\"}],\"pagination\":{\"nextCursor\":\"\"}}", headers: { "Content-Type" => "application/json" })
        client.api_keys.list(limit: 1, cursor: "sample", prefix: "sample", query: "sample", labels: "sample", sort_order: "sample", include_info: true)
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#create" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("APIKeyService_CreateAPIKey") do
        result = client.api_keys.create(workspace_id: "sample", metadata: {"name" => "sample"}, spec: {})
        expect(result).to be_a(Cadenya::Types::APIKey)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:post, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/api_keys")
          .to_return(status: 200, body: "{\"metadata\":{\"accountId\":\"sample\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\"},\"spec\":{\"system\":true,\"token\":\"sample\"},\"state\":\"STATE_UNSPECIFIED\"}", headers: { "Content-Type" => "application/json" })
        client.api_keys.create(metadata: {"name" => "sample"}, spec: {})
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#retrieve" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("APIKeyService_GetAPIKey") do
        result = client.api_keys.retrieve("sample", workspace_id: "sample")
        expect(result).to be_a(Cadenya::Types::APIKey)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:get, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/api_keys/sample")
          .to_return(status: 200, body: "{\"metadata\":{\"accountId\":\"sample\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\"},\"spec\":{\"system\":true,\"token\":\"sample\"},\"state\":\"STATE_UNSPECIFIED\"}", headers: { "Content-Type" => "application/json" })
        client.api_keys.retrieve("sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#delete" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("APIKeyService_DeleteAPIKey") do
        result = client.api_keys.delete("sample", workspace_id: "sample")
        expect(result).to be_nil
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:delete, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/api_keys/sample")
          .to_return(status: 204, body: "")
        client.api_keys.delete("sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#update" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("APIKeyService_UpdateAPIKey") do
        result = client.api_keys.update("sample", workspace_id: "sample", metadata: {"name" => "sample"}, spec: {}, update_mask: "sample")
        expect(result).to be_a(Cadenya::Types::APIKey)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:patch, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/api_keys/sample")
          .to_return(status: 200, body: "{\"metadata\":{\"accountId\":\"sample\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\"},\"spec\":{\"system\":true,\"token\":\"sample\"},\"state\":\"STATE_UNSPECIFIED\"}", headers: { "Content-Type" => "application/json" })
        client.api_keys.update("sample", metadata: {"name" => "sample"}, spec: {}, update_mask: "sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#disable" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("APIKeyService_DisableAPIKey") do
        result = client.api_keys.disable("sample", workspace_id: "sample")
        expect(result).to be_a(Cadenya::Types::APIKey)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:post, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/api_keys/sample:disable")
          .to_return(status: 200, body: "{\"metadata\":{\"accountId\":\"sample\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\"},\"spec\":{\"system\":true,\"token\":\"sample\"},\"state\":\"STATE_UNSPECIFIED\"}", headers: { "Content-Type" => "application/json" })
        client.api_keys.disable("sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#enable" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("APIKeyService_EnableAPIKey") do
        result = client.api_keys.enable("sample", workspace_id: "sample")
        expect(result).to be_a(Cadenya::Types::APIKey)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:post, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/api_keys/sample:enable")
          .to_return(status: 200, body: "{\"metadata\":{\"accountId\":\"sample\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\"},\"spec\":{\"system\":true,\"token\":\"sample\"},\"state\":\"STATE_UNSPECIFIED\"}", headers: { "Content-Type" => "application/json" })
        client.api_keys.enable("sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#rotate" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("APIKeyService_RotateAPIKey") do
        result = client.api_keys.rotate("sample", workspace_id: "sample")
        expect(result).to be_a(Cadenya::Types::APIKey)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:post, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/api_keys/sample:rotate")
          .to_return(status: 200, body: "{\"metadata\":{\"accountId\":\"sample\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\"},\"spec\":{\"system\":true,\"token\":\"sample\"},\"state\":\"STATE_UNSPECIFIED\"}", headers: { "Content-Type" => "application/json" })
        client.api_keys.rotate("sample")
        expect(stub).to have_been_requested
      end
    end
  end
end
