# frozen_string_literal: true

# Code generated by redwood. DO NOT EDIT.

RSpec.describe "client.memory_layers.entries" do
  let(:client) { build_client }

  describe "#list" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("MemoryService_ListMemoryEntries") do
        result = client.memory_layers.entries.list("sample", workspace_id: "sample", limit: 1, cursor: "sample", prefix: "sample", query: "sample", labels: "sample", sort_order: "sample", include_info: true)
        items = result.to_a
        expect(items.length).to eq(2)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:get, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/memory_layers/sample/entries")
          .with(query: hash_including({}))
          .to_return(status: 200, body: "{\"items\":[{\"info\":{},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"description\":\"sample\",\"key\":\"sample\"}}],\"pagination\":{\"nextCursor\":\"\"}}", headers: { "Content-Type" => "application/json" })
        client.memory_layers.entries.list("sample", limit: 1, cursor: "sample", prefix: "sample", query: "sample", labels: "sample", sort_order: "sample", include_info: true)
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#create" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("MemoryService_CreateMemoryEntry") do
        result = client.memory_layers.entries.create("sample", workspace_id: "sample", metadata: {"name" => "sample"}, spec: {"content" => "sample", "key" => "sample", "type" => "content"})
        expect(result).to be_a(Cadenya::Types::MemoryEntryDetail)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:post, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/memory_layers/sample/entries")
          .to_return(status: 200, body: "{\"content\":\"sample\",\"info\":{},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"description\":\"sample\",\"key\":\"sample\"}}", headers: { "Content-Type" => "application/json" })
        client.memory_layers.entries.create("sample", metadata: {"name" => "sample"}, spec: {"content" => "sample", "key" => "sample", "type" => "content"})
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#retrieve" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("MemoryService_GetMemoryEntry") do
        result = client.memory_layers.entries.retrieve("sample", "sample", workspace_id: "sample")
        expect(result).to be_a(Cadenya::Types::MemoryEntryDetail)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:get, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/memory_layers/sample/entries/sample")
          .to_return(status: 200, body: "{\"content\":\"sample\",\"info\":{},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"description\":\"sample\",\"key\":\"sample\"}}", headers: { "Content-Type" => "application/json" })
        client.memory_layers.entries.retrieve("sample", "sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#delete" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("MemoryService_DeleteMemoryEntry") do
        result = client.memory_layers.entries.delete("sample", "sample", workspace_id: "sample")
        expect(result).to be_nil
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:delete, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/memory_layers/sample/entries/sample")
          .to_return(status: 204, body: "")
        client.memory_layers.entries.delete("sample", "sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#update" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("MemoryService_UpdateMemoryEntry") do
        result = client.memory_layers.entries.update("sample", "sample", workspace_id: "sample", metadata: {"name" => "sample"}, spec: {}, update_mask: "sample")
        expect(result).to be_a(Cadenya::Types::MemoryEntryDetail)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:patch, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/memory_layers/sample/entries/sample")
          .to_return(status: 200, body: "{\"content\":\"sample\",\"info\":{},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"description\":\"sample\",\"key\":\"sample\"}}", headers: { "Content-Type" => "application/json" })
        client.memory_layers.entries.update("sample", "sample", metadata: {"name" => "sample"}, spec: {}, update_mask: "sample")
        expect(stub).to have_been_requested
      end
    end
  end
end
