# frozen_string_literal: true

# Code generated by redwood. DO NOT EDIT.

RSpec.describe "client.memory_layers" do
  let(:client) { build_client }

  describe "#list" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("MemoryService_ListMemoryLayers") do
        result = client.memory_layers.list(workspace_id: "sample", limit: 1, cursor: "sample", prefix: "sample", query: "sample", type: "MEMORY_LAYER_TYPE_UNSPECIFIED", agent_id: "sample", episodic_key_prefix: "sample", labels: "sample", sort_order: "sample", include_info: true)
        items = result.to_a
        expect(items.length).to eq(2)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:get, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/memory_layers")
          .with(query: hash_including({}))
          .to_return(status: 200, body: "{\"items\":[{\"info\":{\"entryCount\":1},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"agentId\":\"sample\",\"episodicKey\":\"sample\",\"systemManaged\":true,\"type\":\"MEMORY_LAYER_TYPE_UNSPECIFIED\"}}],\"pagination\":{\"nextCursor\":\"\"}}", headers: { "Content-Type" => "application/json" })
        client.memory_layers.list(limit: 1, cursor: "sample", prefix: "sample", query: "sample", type: "MEMORY_LAYER_TYPE_UNSPECIFIED", agent_id: "sample", episodic_key_prefix: "sample", labels: "sample", sort_order: "sample", include_info: true)
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#create" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("MemoryService_CreateMemoryLayer") do
        result = client.memory_layers.create(workspace_id: "sample", metadata: {"name" => "sample"}, spec: {"type" => "MEMORY_LAYER_TYPE_UNSPECIFIED"})
        expect(result).to be_a(Cadenya::Types::MemoryLayer)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:post, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/memory_layers")
          .to_return(status: 200, body: "{\"info\":{\"entryCount\":1},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"agentId\":\"sample\",\"episodicKey\":\"sample\",\"systemManaged\":true,\"type\":\"MEMORY_LAYER_TYPE_UNSPECIFIED\"}}", headers: { "Content-Type" => "application/json" })
        client.memory_layers.create(metadata: {"name" => "sample"}, spec: {"type" => "MEMORY_LAYER_TYPE_UNSPECIFIED"})
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#retrieve" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("MemoryService_GetMemoryLayer") do
        result = client.memory_layers.retrieve("sample", workspace_id: "sample")
        expect(result).to be_a(Cadenya::Types::MemoryLayer)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:get, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/memory_layers/sample")
          .to_return(status: 200, body: "{\"info\":{\"entryCount\":1},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"agentId\":\"sample\",\"episodicKey\":\"sample\",\"systemManaged\":true,\"type\":\"MEMORY_LAYER_TYPE_UNSPECIFIED\"}}", headers: { "Content-Type" => "application/json" })
        client.memory_layers.retrieve("sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#delete" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("MemoryService_DeleteMemoryLayer") do
        result = client.memory_layers.delete("sample", workspace_id: "sample")
        expect(result).to be_nil
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:delete, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/memory_layers/sample")
          .to_return(status: 204, body: "")
        client.memory_layers.delete("sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#update" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("MemoryService_UpdateMemoryLayer") do
        result = client.memory_layers.update("sample", workspace_id: "sample", metadata: {"name" => "sample"}, spec: {"type" => "MEMORY_LAYER_TYPE_UNSPECIFIED"}, update_mask: "sample")
        expect(result).to be_a(Cadenya::Types::MemoryLayer)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:patch, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/memory_layers/sample")
          .to_return(status: 200, body: "{\"info\":{\"entryCount\":1},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"agentId\":\"sample\",\"episodicKey\":\"sample\",\"systemManaged\":true,\"type\":\"MEMORY_LAYER_TYPE_UNSPECIFIED\"}}", headers: { "Content-Type" => "application/json" })
        client.memory_layers.update("sample", metadata: {"name" => "sample"}, spec: {"type" => "MEMORY_LAYER_TYPE_UNSPECIFIED"}, update_mask: "sample")
        expect(stub).to have_been_requested
      end
    end
  end
end
