# frozen_string_literal: true

# Code generated by redwood. DO NOT EDIT.

RSpec.describe "client.objectives" do
  let(:client) { build_client }

  describe "#list" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("ObjectiveService_ListObjectives") do
        result = client.objectives.list(workspace_id: "sample", limit: 1, cursor: "sample", agent_id: "sample", parent_objective_id: "sample", state: "STATE_UNSPECIFIED", profile_id: "sample", sort_order: "sample", include_info: true, agent_schedule_id: "sample", labels: "sample", tenant_id: "sample", subject_id: "sample", widget_id: "sample", widget_session_id: "sample")
        items = result.to_a
        expect(items.length).to eq(2)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:get, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/objectives")
          .with(query: hash_including({}))
          .to_return(status: 200, body: "{\"items\":[{\"configSnapshot\":{\"agent\":{\"info\":{\"variationCount\":1},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"variationSelectionMode\":\"VARIATION_SELECTION_MODE_UNSPECIFIED\"},\"state\":\"STATE_UNSPECIFIED\"},\"agentVariation\":{\"info\":{\"assignments\":[{\"id\":\"sample\",\"tool\":{\"id\":\"sample\"},\"type\":\"tool\"}],\"feedbackCount\":1,\"memoryLayerAssignments\":[{\"id\":\"sample\",\"memoryLayer\":{\"id\":\"sample\"},\"position\":1}],\"memoryLayerCount\":1,\"score\":1.5,\"subAgentCount\":1,\"toolCount\":1,\"toolSetCount\":1},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{}}},\"firstUserMessage\":\"sample\",\"memoryCascade\":[{\"memoryLayerId\":\"sample\"}],\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"parentObjectiveId\":\"sample\",\"pinnedParameters\":{},\"secrets\":[{\"name\":\"sample\"}],\"state\":\"STATE_UNSPECIFIED\",\"stateMessage\":\"sample\",\"systemPrompt\":\"sample\"}],\"pagination\":{\"nextCursor\":\"\"}}", headers: { "Content-Type" => "application/json" })
        client.objectives.list(limit: 1, cursor: "sample", agent_id: "sample", parent_objective_id: "sample", state: "STATE_UNSPECIFIED", profile_id: "sample", sort_order: "sample", include_info: true, agent_schedule_id: "sample", labels: "sample", tenant_id: "sample", subject_id: "sample", widget_id: "sample", widget_session_id: "sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#create" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("ObjectiveService_CreateObjective") do
        result = client.objectives.create(workspace_id: "sample", agent_id: "sample", variation_id: "sample", metadata: {}, system_prompt_data: {}, first_user_message: "sample", secrets: [{}], memory_cascade: [{"memory_layer_id" => "sample"}], first_user_message_data: {}, episodic_memory: {"key" => "sample"}, tenant: {"id" => "sample"}, subject: {"id" => "sample"}, pinned_parameters: {})
        expect(result).to be_a(Cadenya::Types::Objective)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:post, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/objectives")
          .to_return(status: 200, body: "{\"configSnapshot\":{\"agent\":{\"info\":{\"variationCount\":1},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"variationSelectionMode\":\"VARIATION_SELECTION_MODE_UNSPECIFIED\"},\"state\":\"STATE_UNSPECIFIED\"},\"agentVariation\":{\"info\":{\"assignments\":[{\"id\":\"sample\",\"tool\":{\"id\":\"sample\"},\"type\":\"tool\"}],\"feedbackCount\":1,\"memoryLayerAssignments\":[{\"id\":\"sample\",\"memoryLayer\":{\"id\":\"sample\"},\"position\":1}],\"memoryLayerCount\":1,\"score\":1.5,\"subAgentCount\":1,\"toolCount\":1,\"toolSetCount\":1},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{}}},\"firstUserMessage\":\"sample\",\"memoryCascade\":[{\"memoryLayerId\":\"sample\"}],\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"parentObjectiveId\":\"sample\",\"pinnedParameters\":{},\"secrets\":[{\"name\":\"sample\"}],\"state\":\"STATE_UNSPECIFIED\",\"stateMessage\":\"sample\",\"systemPrompt\":\"sample\"}", headers: { "Content-Type" => "application/json" })
        client.objectives.create(agent_id: "sample", variation_id: "sample", metadata: {}, system_prompt_data: {}, first_user_message: "sample", secrets: [{}], memory_cascade: [{"memory_layer_id" => "sample"}], first_user_message_data: {}, episodic_memory: {"key" => "sample"}, tenant: {"id" => "sample"}, subject: {"id" => "sample"}, pinned_parameters: {})
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#retrieve" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("ObjectiveService_GetObjective") do
        result = client.objectives.retrieve("sample", workspace_id: "sample")
        expect(result).to be_a(Cadenya::Types::Objective)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:get, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/objectives/sample")
          .to_return(status: 200, body: "{\"configSnapshot\":{\"agent\":{\"info\":{\"variationCount\":1},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"variationSelectionMode\":\"VARIATION_SELECTION_MODE_UNSPECIFIED\"},\"state\":\"STATE_UNSPECIFIED\"},\"agentVariation\":{\"info\":{\"assignments\":[{\"id\":\"sample\",\"tool\":{\"id\":\"sample\"},\"type\":\"tool\"}],\"feedbackCount\":1,\"memoryLayerAssignments\":[{\"id\":\"sample\",\"memoryLayer\":{\"id\":\"sample\"},\"position\":1}],\"memoryLayerCount\":1,\"score\":1.5,\"subAgentCount\":1,\"toolCount\":1,\"toolSetCount\":1},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{}}},\"firstUserMessage\":\"sample\",\"memoryCascade\":[{\"memoryLayerId\":\"sample\"}],\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"parentObjectiveId\":\"sample\",\"pinnedParameters\":{},\"secrets\":[{\"name\":\"sample\"}],\"state\":\"STATE_UNSPECIFIED\",\"stateMessage\":\"sample\",\"systemPrompt\":\"sample\"}", headers: { "Content-Type" => "application/json" })
        client.objectives.retrieve("sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#list_context_windows" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("ObjectiveService_ListObjectiveContextWindows") do
        result = client.objectives.list_context_windows("sample", workspace_id: "sample", limit: 1, cursor: "sample", include_info: true, labels: "sample")
        items = result.to_a
        expect(items.length).to eq(2)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:get, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/objectives/sample/context_windows")
          .with(query: hash_including({}))
          .to_return(status: 200, body: "{\"items\":[{\"data\":{\"completionTokens\":1,\"objectiveId\":\"sample\",\"previousWindowContinueInstructions\":\"sample\",\"promptTokens\":1,\"sequence\":1},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"profileId\":\"sample\",\"workspaceId\":\"sample\"}}],\"pagination\":{\"nextCursor\":\"\"}}", headers: { "Content-Type" => "application/json" })
        client.objectives.list_context_windows("sample", limit: 1, cursor: "sample", include_info: true, labels: "sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#retrieve_diagnostics" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("ObjectiveService_GetObjectiveDiagnostics") do
        result = client.objectives.retrieve_diagnostics("sample", workspace_id: "sample")
        expect(result).to be_a(Cadenya::Types::GetObjectiveDiagnosticsResponse)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:get, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/objectives/sample/diagnostics")
          .to_return(status: 200, body: "{\"diagnostics\":{\"cachedInputTokens\":1,\"contextLengths\":{\"assistantMessages\":1,\"availableTools\":1,\"episodicMemory\":1,\"skillsMemory\":1,\"systemPrompt\":1,\"toolDefinitions\":1,\"toolResults\":1,\"userMessages\":1},\"inputTokens\":1}}", headers: { "Content-Type" => "application/json" })
        client.objectives.retrieve_diagnostics("sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#list_events" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("ObjectiveService_ListObjectiveEvents") do
        result = client.objectives.list_events("sample", workspace_id: "sample", limit: 1, cursor: "sample", sort_order: "sample", include_info: true, window_id: "sample", since_event_id: "sample", labels: "sample")
        items = result.to_a
        expect(items.length).to eq(2)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:get, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/objectives/sample/events")
          .with(query: hash_including({}))
          .to_return(status: 200, body: "{\"items\":[{\"contextWindowId\":\"sample\",\"data\":{\"type\":\"userMessage\",\"userMessage\":{\"content\":\"sample\"}},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"profileId\":\"sample\",\"workspaceId\":\"sample\"}}],\"pagination\":{\"nextCursor\":\"\"}}", headers: { "Content-Type" => "application/json" })
        client.objectives.list_events("sample", limit: 1, cursor: "sample", sort_order: "sample", include_info: true, window_id: "sample", since_event_id: "sample", labels: "sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#stream_events" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("ObjectiveEventStreamsService_StreamObjectiveEvents") do
        result = client.objectives.stream_events("sample", workspace_id: "sample")
        events = result.to_a
        expect(events.length).to eq(2)
        expect(result.last_event_id).to eq("e2")
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:get, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/objectives/sample/events:stream")
          .to_return(status: 200, body: "id: e1\ndata: {\"contextWindowId\":\"sample\",\"data\":{\"type\":\"userMessage\",\"userMessage\":{\"content\":\"sample\"}},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"profileId\":\"sample\",\"workspaceId\":\"sample\"}}\n\nevent: ping\ndata: not-json-housekeeping\n\nid: e2\ndata: {\"contextWindowId\":\"sample\",\"data\":{\"type\":\"userMessage\",\"userMessage\":{\"content\":\"sample\"}},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"profileId\":\"sample\",\"workspaceId\":\"sample\"}}\n\n", headers: { "Content-Type" => "text/event-stream" })
        (client.objectives.stream_events("sample")).to_a
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#list_feedback" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("ObjectiveService_ListObjectiveFeedback") do
        result = client.objectives.list_feedback("sample", workspace_id: "sample", limit: 1, cursor: "sample", labels: "sample")
        items = result.to_a
        expect(items.length).to eq(2)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:get, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/objectives/sample/feedback")
          .with(query: hash_including({}))
          .to_return(status: 200, body: "{\"items\":[{\"data\":{},\"info\":{\"submittedBy\":{\"metadata\":{\"accountId\":\"sample\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\"},\"spec\":{\"email\":\"sample\",\"name\":\"sample\",\"type\":\"PROFILE_TYPE_UNSPECIFIED\"}}},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"profileId\":\"sample\",\"workspaceId\":\"sample\"}}],\"pagination\":{\"nextCursor\":\"\"}}", headers: { "Content-Type" => "application/json" })
        client.objectives.list_feedback("sample", limit: 1, cursor: "sample", labels: "sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#create_feedback" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("ObjectiveService_CreateObjectiveFeedback") do
        result = client.objectives.create_feedback("sample", workspace_id: "sample", metadata: {}, data: {})
        expect(result).to be_a(Cadenya::Types::ObjectiveFeedback)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:post, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/objectives/sample/feedback")
          .to_return(status: 200, body: "{\"data\":{},\"info\":{\"submittedBy\":{\"metadata\":{\"accountId\":\"sample\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\"},\"spec\":{\"email\":\"sample\",\"name\":\"sample\",\"type\":\"PROFILE_TYPE_UNSPECIFIED\"}}},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"profileId\":\"sample\",\"workspaceId\":\"sample\"}}", headers: { "Content-Type" => "application/json" })
        client.objectives.create_feedback("sample", metadata: {}, data: {})
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#list_tasks" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("ObjectiveService_ListObjectiveTasks") do
        result = client.objectives.list_tasks("sample", workspace_id: "sample", limit: 1, cursor: "sample", sort_order: "sample")
        items = result.to_a
        expect(items.length).to eq(2)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:get, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/objectives/sample/tasks")
          .with(query: hash_including({}))
          .to_return(status: 200, body: "{\"items\":[{\"data\":{\"completed\":true,\"number\":1,\"task\":\"sample\"},\"metadata\":{\"id\":\"sample\"}}],\"pagination\":{\"nextCursor\":\"\"}}", headers: { "Content-Type" => "application/json" })
        client.objectives.list_tasks("sample", limit: 1, cursor: "sample", sort_order: "sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#retrieve_task" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("ObjectiveService_GetObjectiveTask") do
        result = client.objectives.retrieve_task("sample", "sample", workspace_id: "sample")
        expect(result).to be_a(Cadenya::Types::ObjectiveTask)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:get, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/objectives/sample/tasks/sample")
          .to_return(status: 200, body: "{\"data\":{\"completed\":true,\"number\":1,\"task\":\"sample\"},\"metadata\":{\"id\":\"sample\"}}", headers: { "Content-Type" => "application/json" })
        client.objectives.retrieve_task("sample", "sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#list_tool_calls" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("ObjectiveService_ListObjectiveToolCalls") do
        result = client.objectives.list_tool_calls("sample", workspace_id: "sample", limit: 1, cursor: "sample", status: "TOOL_CALL_STATUS_UNSPECIFIED", include_info: true, execution_status: "TOOL_CALL_EXECUTION_STATUS_UNSPECIFIED", labels: "sample")
        items = result.to_a
        expect(items.length).to eq(2)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:get, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/objectives/sample/tool_calls")
          .with(query: hash_including({}))
          .to_return(status: 200, body: "{\"items\":[{\"data\":{\"arguments\":{},\"callable\":{\"tool\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"type\":\"tool\"},\"resolvedSecrets\":[{\"key\":\"sample\",\"source\":\"RESOLVED_SECRET_SOURCE_UNSPECIFIED\"}]},\"executionStatus\":\"TOOL_CALL_EXECUTION_STATUS_UNSPECIFIED\",\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"status\":\"TOOL_CALL_STATUS_UNSPECIFIED\"}],\"pagination\":{\"nextCursor\":\"\"}}", headers: { "Content-Type" => "application/json" })
        client.objectives.list_tool_calls("sample", limit: 1, cursor: "sample", status: "TOOL_CALL_STATUS_UNSPECIFIED", include_info: true, execution_status: "TOOL_CALL_EXECUTION_STATUS_UNSPECIFIED", labels: "sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#retrieve_tool_call" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("ObjectiveService_GetObjectiveToolCall") do
        result = client.objectives.retrieve_tool_call("sample", "sample", workspace_id: "sample")
        expect(result).to be_a(Cadenya::Types::ObjectiveToolCallWithResult)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:get, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/objectives/sample/tool_calls/sample")
          .to_return(status: 200, body: "{\"data\":{\"arguments\":{},\"callable\":{\"tool\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"type\":\"tool\"},\"resolvedSecrets\":[{\"key\":\"sample\",\"source\":\"RESOLVED_SECRET_SOURCE_UNSPECIFIED\"}]},\"executionStatus\":\"TOOL_CALL_EXECUTION_STATUS_UNSPECIFIED\",\"info\":{\"objective\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"profileId\":\"sample\",\"workspaceId\":\"sample\"}},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"resolvedSecrets\":[{\"key\":\"sample\",\"source\":\"RESOLVED_SECRET_SOURCE_UNSPECIFIED\"}],\"status\":\"TOOL_CALL_STATUS_UNSPECIFIED\"}", headers: { "Content-Type" => "application/json" })
        client.objectives.retrieve_tool_call("sample", "sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#approve_tool_call" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("ObjectiveService_ApproveToolCall") do
        result = client.objectives.approve_tool_call("sample", "sample", workspace_id: "sample")
        expect(result).to be_a(Cadenya::Types::ObjectiveToolCall)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:post, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/objectives/sample/tool_calls/sample:approve")
          .to_return(status: 200, body: "{\"data\":{\"arguments\":{},\"callable\":{\"tool\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"type\":\"tool\"},\"resolvedSecrets\":[{\"key\":\"sample\",\"source\":\"RESOLVED_SECRET_SOURCE_UNSPECIFIED\"}]},\"executionStatus\":\"TOOL_CALL_EXECUTION_STATUS_UNSPECIFIED\",\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"status\":\"TOOL_CALL_STATUS_UNSPECIFIED\"}", headers: { "Content-Type" => "application/json" })
        client.objectives.approve_tool_call("sample", "sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#deny_tool_call" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("ObjectiveService_DenyToolCall") do
        result = client.objectives.deny_tool_call("sample", "sample", workspace_id: "sample", memo: "sample")
        expect(result).to be_a(Cadenya::Types::ObjectiveToolCall)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:post, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/objectives/sample/tool_calls/sample:deny")
          .to_return(status: 200, body: "{\"data\":{\"arguments\":{},\"callable\":{\"tool\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"type\":\"tool\"},\"resolvedSecrets\":[{\"key\":\"sample\",\"source\":\"RESOLVED_SECRET_SOURCE_UNSPECIFIED\"}]},\"executionStatus\":\"TOOL_CALL_EXECUTION_STATUS_UNSPECIFIED\",\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"status\":\"TOOL_CALL_STATUS_UNSPECIFIED\"}", headers: { "Content-Type" => "application/json" })
        client.objectives.deny_tool_call("sample", "sample", memo: "sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#set_tool_call_content" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("ObjectiveService_SetToolCallContent") do
        result = client.objectives.set_tool_call_content("sample", "sample", workspace_id: "sample", content: [{"text" => {"text" => "sample"}, "type" => "text"}])
        expect(result).to be_a(Cadenya::Types::ObjectiveToolCall)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:post, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/objectives/sample/tool_calls/sample:setContent")
          .to_return(status: 200, body: "{\"data\":{\"arguments\":{},\"callable\":{\"tool\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"type\":\"tool\"},\"resolvedSecrets\":[{\"key\":\"sample\",\"source\":\"RESOLVED_SECRET_SOURCE_UNSPECIFIED\"}]},\"executionStatus\":\"TOOL_CALL_EXECUTION_STATUS_UNSPECIFIED\",\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"status\":\"TOOL_CALL_STATUS_UNSPECIFIED\"}", headers: { "Content-Type" => "application/json" })
        client.objectives.set_tool_call_content("sample", "sample", content: [{"text" => {"text" => "sample"}, "type" => "text"}])
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#list_tools" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("ObjectiveService_ListObjectiveTools") do
        result = client.objectives.list_tools("sample", workspace_id: "sample", limit: 1, cursor: "sample")
        items = result.to_a
        expect(items.length).to eq(2)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:get, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/objectives/sample/tools")
          .with(query: hash_including({}))
          .to_return(status: 200, body: "{\"items\":[{\"metadata\":{\"id\":\"sample\"},\"snapshot\":{\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"config\":{\"http\":{\"requestMethod\":\"HTTP_METHOD_UNSPECIFIED\"},\"type\":\"http\"},\"description\":\"sample\",\"parameters\":{},\"requiresApproval\":true},\"state\":\"STATE_UNSPECIFIED\"}}],\"pagination\":{\"nextCursor\":\"\"}}", headers: { "Content-Type" => "application/json" })
        client.objectives.list_tools("sample", limit: 1, cursor: "sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#cancel" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("ObjectiveService_CancelObjective") do
        result = client.objectives.cancel("sample", workspace_id: "sample", reason: "sample")
        expect(result).to be_a(Cadenya::Types::Objective)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:post, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/objectives/sample:cancel")
          .to_return(status: 200, body: "{\"configSnapshot\":{\"agent\":{\"info\":{\"variationCount\":1},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"variationSelectionMode\":\"VARIATION_SELECTION_MODE_UNSPECIFIED\"},\"state\":\"STATE_UNSPECIFIED\"},\"agentVariation\":{\"info\":{\"assignments\":[{\"id\":\"sample\",\"tool\":{\"id\":\"sample\"},\"type\":\"tool\"}],\"feedbackCount\":1,\"memoryLayerAssignments\":[{\"id\":\"sample\",\"memoryLayer\":{\"id\":\"sample\"},\"position\":1}],\"memoryLayerCount\":1,\"score\":1.5,\"subAgentCount\":1,\"toolCount\":1,\"toolSetCount\":1},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{}}},\"firstUserMessage\":\"sample\",\"memoryCascade\":[{\"memoryLayerId\":\"sample\"}],\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"parentObjectiveId\":\"sample\",\"pinnedParameters\":{},\"secrets\":[{\"name\":\"sample\"}],\"state\":\"STATE_UNSPECIFIED\",\"stateMessage\":\"sample\",\"systemPrompt\":\"sample\"}", headers: { "Content-Type" => "application/json" })
        client.objectives.cancel("sample", reason: "sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#compact" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("ObjectiveService_CompactObjective") do
        result = client.objectives.compact("sample", workspace_id: "sample", compaction_config: {})
        expect(result).to be_a(Cadenya::Types::CompactObjectiveResponse)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:post, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/objectives/sample:compact")
          .to_return(status: 200, body: "{}", headers: { "Content-Type" => "application/json" })
        client.objectives.compact("sample", compaction_config: {})
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#continue" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("ObjectiveService_ContinueObjective") do
        result = client.objectives.continue("sample", workspace_id: "sample", message: "sample", enqueue: true)
        expect(result).to be_a(Cadenya::Types::ObjectiveEvent)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:post, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/objectives/sample:continue")
          .to_return(status: 200, body: "{\"contextWindowId\":\"sample\",\"data\":{\"type\":\"userMessage\",\"userMessage\":{\"content\":\"sample\"}},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"profileId\":\"sample\",\"workspaceId\":\"sample\"}}", headers: { "Content-Type" => "application/json" })
        client.objectives.continue("sample", message: "sample", enqueue: true)
        expect(stub).to have_been_requested
      end
    end
  end
end
