# frozen_string_literal: true

# Code generated by redwood. DO NOT EDIT.

RSpec.describe "client.profiles" do
  let(:client) { build_client }

  describe "#whoami" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("ProfilesService_Whoami") do
        result = client.profiles.whoami
        expect(result).to be_a(Cadenya::Types::Profile)
      end
    end
  end
end
