# frozen_string_literal: true

# Code generated by redwood. DO NOT EDIT.

RSpec.describe "client.tool_sets.secrets" do
  let(:client) { build_client }

  describe "#list" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("ToolService_ListToolSetSecrets") do
        result = client.tool_sets.secrets.list("sample", workspace_id: "sample", limit: 1, cursor: "sample", prefix: "sample", query: "sample", sort_order: "sample", include_info: true)
        items = result.to_a
        expect(items.length).to eq(2)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:get, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/tool_sets/sample/secrets")
          .with(query: hash_including({}))
          .to_return(status: 200, body: "{\"items\":[{\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{}}],\"pagination\":{\"nextCursor\":\"\"}}", headers: { "Content-Type" => "application/json" })
        client.tool_sets.secrets.list("sample", limit: 1, cursor: "sample", prefix: "sample", query: "sample", sort_order: "sample", include_info: true)
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#create" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("ToolService_CreateToolSetSecret") do
        result = client.tool_sets.secrets.create("sample", workspace_id: "sample", metadata: {"name" => "sample"}, spec: {})
        expect(result).to be_a(Cadenya::Types::ToolSetSecret)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:post, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/tool_sets/sample/secrets")
          .to_return(status: 200, body: "{\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{}}", headers: { "Content-Type" => "application/json" })
        client.tool_sets.secrets.create("sample", metadata: {"name" => "sample"}, spec: {})
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#retrieve" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("ToolService_GetToolSetSecret") do
        result = client.tool_sets.secrets.retrieve("sample", "sample", workspace_id: "sample")
        expect(result).to be_a(Cadenya::Types::ToolSetSecret)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:get, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/tool_sets/sample/secrets/sample")
          .to_return(status: 200, body: "{\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{}}", headers: { "Content-Type" => "application/json" })
        client.tool_sets.secrets.retrieve("sample", "sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#delete" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("ToolService_DeleteToolSetSecret") do
        result = client.tool_sets.secrets.delete("sample", "sample", workspace_id: "sample")
        expect(result).to be_nil
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:delete, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/tool_sets/sample/secrets/sample")
          .to_return(status: 204, body: "")
        client.tool_sets.secrets.delete("sample", "sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#update" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("ToolService_UpdateToolSetSecret") do
        result = client.tool_sets.secrets.update("sample", "sample", workspace_id: "sample", metadata: {"name" => "sample"}, spec: {}, update_mask: "sample")
        expect(result).to be_a(Cadenya::Types::ToolSetSecret)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:patch, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/tool_sets/sample/secrets/sample")
          .to_return(status: 200, body: "{\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{}}", headers: { "Content-Type" => "application/json" })
        client.tool_sets.secrets.update("sample", "sample", metadata: {"name" => "sample"}, spec: {}, update_mask: "sample")
        expect(stub).to have_been_requested
      end
    end
  end
end
