# frozen_string_literal: true

# Code generated by redwood. DO NOT EDIT.

RSpec.describe "client.tool_search" do
  let(:client) { build_client }

  describe "#search_or_sets" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("SearchService_SearchToolsOrToolSets") do
        result = client.tool_search.search_or_sets(workspace_id: "sample", query: "sample")
        expect(result).to be_a(Cadenya::Types::SearchToolsOrToolSetsResponse)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:get, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/search/tools_or_tool_sets")
          .with(query: hash_including({}))
          .to_return(status: 200, body: "{\"agents\":[{\"info\":{\"variationCount\":1},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{},\"state\":\"STATE_DRAFT\"}],\"toolSets\":[{\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"adapter\":{\"mcp\":{},\"type\":\"mcp\"}},\"state\":\"STATE_ACTIVE\"}],\"tools\":[{\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"config\":{\"http\":{\"requestMethod\":\"GET\"},\"type\":\"http\"},\"description\":\"sample\",\"parameters\":{},\"requiresApproval\":true},\"state\":\"STATE_AVAILABLE\"}]}", headers: { "Content-Type" => "application/json" })
        client.tool_search.search_or_sets(query: "sample")
        expect(stub).to have_been_requested
      end
    end
  end
end
