# frozen_string_literal: true

# Code generated by redwood. DO NOT EDIT.

RSpec.describe "client.tool_sets" do
  let(:client) { build_client }

  describe "#list" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("ToolService_ListToolSets") do
        result = client.tool_sets.list(workspace_id: "sample", limit: 1, cursor: "sample", prefix: "sample", query: "sample", state: "STATE_UNSPECIFIED", labels: "sample", sort_order: "sample", include_info: true)
        items = result.to_a
        expect(items.length).to eq(2)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:get, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/tool_sets")
          .with(query: hash_including({}))
          .to_return(status: 200, body: "{\"items\":[{\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"adapter\":{\"mcp\":{},\"type\":\"mcp\"}},\"state\":\"STATE_UNSPECIFIED\"}],\"pagination\":{\"nextCursor\":\"\"}}", headers: { "Content-Type" => "application/json" })
        client.tool_sets.list(limit: 1, cursor: "sample", prefix: "sample", query: "sample", state: "STATE_UNSPECIFIED", labels: "sample", sort_order: "sample", include_info: true)
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#create" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("ToolService_CreateToolSet") do
        result = client.tool_sets.create(workspace_id: "sample", metadata: {"name" => "sample"}, spec: {"adapter" => {"mcp" => {}, "type" => "mcp"}})
        expect(result).to be_a(Cadenya::Types::ToolSet)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:post, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/tool_sets")
          .to_return(status: 200, body: "{\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"adapter\":{\"mcp\":{},\"type\":\"mcp\"}},\"state\":\"STATE_UNSPECIFIED\"}", headers: { "Content-Type" => "application/json" })
        client.tool_sets.create(metadata: {"name" => "sample"}, spec: {"adapter" => {"mcp" => {}, "type" => "mcp"}})
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#retrieve" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("ToolService_GetToolSet") do
        result = client.tool_sets.retrieve("sample", workspace_id: "sample")
        expect(result).to be_a(Cadenya::Types::ToolSet)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:get, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/tool_sets/sample")
          .to_return(status: 200, body: "{\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"adapter\":{\"mcp\":{},\"type\":\"mcp\"}},\"state\":\"STATE_UNSPECIFIED\"}", headers: { "Content-Type" => "application/json" })
        client.tool_sets.retrieve("sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#delete" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("ToolService_DeleteToolSet") do
        result = client.tool_sets.delete("sample", workspace_id: "sample")
        expect(result).to be_nil
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:delete, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/tool_sets/sample")
          .to_return(status: 204, body: "")
        client.tool_sets.delete("sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#update" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("ToolService_UpdateToolSet") do
        result = client.tool_sets.update("sample", workspace_id: "sample", metadata: {"name" => "sample"}, spec: {"adapter" => {"mcp" => {}, "type" => "mcp"}}, update_mask: "sample")
        expect(result).to be_a(Cadenya::Types::ToolSet)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:patch, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/tool_sets/sample")
          .to_return(status: 200, body: "{\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"adapter\":{\"mcp\":{},\"type\":\"mcp\"}},\"state\":\"STATE_UNSPECIFIED\"}", headers: { "Content-Type" => "application/json" })
        client.tool_sets.update("sample", metadata: {"name" => "sample"}, spec: {"adapter" => {"mcp" => {}, "type" => "mcp"}}, update_mask: "sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#archive" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("ToolService_ArchiveToolSet") do
        result = client.tool_sets.archive("sample", workspace_id: "sample")
        expect(result).to be_a(Cadenya::Types::ToolSet)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:post, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/tool_sets/sample:archive")
          .to_return(status: 200, body: "{\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"adapter\":{\"mcp\":{},\"type\":\"mcp\"}},\"state\":\"STATE_UNSPECIFIED\"}", headers: { "Content-Type" => "application/json" })
        client.tool_sets.archive("sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#unarchive" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("ToolService_UnarchiveToolSet") do
        result = client.tool_sets.unarchive("sample", workspace_id: "sample")
        expect(result).to be_a(Cadenya::Types::ToolSet)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:post, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/tool_sets/sample:unarchive")
          .to_return(status: 200, body: "{\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"adapter\":{\"mcp\":{},\"type\":\"mcp\"}},\"state\":\"STATE_UNSPECIFIED\"}", headers: { "Content-Type" => "application/json" })
        client.tool_sets.unarchive("sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#list_events" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("ToolService_ListToolSetEvents") do
        result = client.tool_sets.list_events("sample", workspace_id: "sample", limit: 1, cursor: "sample", sort_order: "sample", include_info: true, labels: "sample")
        items = result.to_a
        expect(items.length).to eq(2)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:get, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/tool_sets/sample/events")
          .with(query: hash_including({}))
          .to_return(status: 200, body: "{\"items\":[{\"event\":{\"syncStarted\":{\"message\":\"sample\"},\"type\":\"syncStarted\"},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"toolSetId\":\"sample\"}],\"pagination\":{\"nextCursor\":\"\"}}", headers: { "Content-Type" => "application/json" })
        client.tool_sets.list_events("sample", limit: 1, cursor: "sample", sort_order: "sample", include_info: true, labels: "sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#retrieve_open_api_spec" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("ToolService_GetToolSetOpenAPISpec") do
        result = client.tool_sets.retrieve_open_api_spec("sample", workspace_id: "sample")
        expect(result).to be_a(Cadenya::Types::GetToolSetOpenAPISpecResponse)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:get, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/tool_sets/sample/openapi_spec")
          .to_return(status: 200, body: "{\"spec\":\"sample\"}", headers: { "Content-Type" => "application/json" })
        client.tool_sets.retrieve_open_api_spec("sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#list_usage" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("ToolService_ListToolSetUsage") do
        result = client.tool_sets.list_usage("sample", workspace_id: "sample", tool_id: "sample", limit: 1, cursor: "sample", sort_order: "sample")
        items = result.to_a
        expect(items.length).to eq(2)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:get, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/tool_sets/sample/usage")
          .with(query: hash_including({}))
          .to_return(status: 200, body: "{\"items\":[{\"agent\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"agentVariation\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"assignedAt\":\"2026-01-01T00:00:00Z\",\"model\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"}}],\"pagination\":{\"nextCursor\":\"\"}}", headers: { "Content-Type" => "application/json" })
        client.tool_sets.list_usage("sample", tool_id: "sample", limit: 1, cursor: "sample", sort_order: "sample")
        expect(stub).to have_been_requested
      end
    end
  end
end
