# frozen_string_literal: true

# Code generated by redwood. DO NOT EDIT.

RSpec.describe "client.tool_sets.tools" do
  let(:client) { build_client }

  describe "#list" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("ToolService_ListTools") do
        result = client.tool_sets.tools.list("sample", workspace_id: "sample", limit: 1, cursor: "sample", prefix: "sample", query: "sample", names: ["sample"], states: ["STATE_UNSPECIFIED"], requires_approval: true, overlays: ["sample"], labels: "sample", sort_order: "sample", include_info: true)
        items = result.to_a
        expect(items.length).to eq(2)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:get, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/tool_sets/sample/tools")
          .with(query: hash_including({}))
          .to_return(status: 200, body: "{\"items\":[{\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"config\":{\"http\":{\"requestMethod\":\"HTTP_METHOD_UNSPECIFIED\"},\"type\":\"http\"},\"description\":\"sample\",\"parameters\":{},\"requiresApproval\":true},\"state\":\"STATE_UNSPECIFIED\"}],\"pagination\":{\"nextCursor\":\"\"}}", headers: { "Content-Type" => "application/json" })
        client.tool_sets.tools.list("sample", limit: 1, cursor: "sample", prefix: "sample", query: "sample", names: ["sample"], states: ["STATE_UNSPECIFIED"], requires_approval: true, overlays: ["sample"], labels: "sample", sort_order: "sample", include_info: true)
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#create" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("ToolService_CreateTool") do
        result = client.tool_sets.tools.create("sample", workspace_id: "sample", metadata: {"name" => "sample"}, spec: {"config" => {"http" => {"request_method" => "HTTP_METHOD_UNSPECIFIED"}, "type" => "http"}, "description" => "sample", "parameters" => {}, "requires_approval" => true})
        expect(result).to be_a(Cadenya::Types::Tool)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:post, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/tool_sets/sample/tools")
          .to_return(status: 200, body: "{\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"config\":{\"http\":{\"requestMethod\":\"HTTP_METHOD_UNSPECIFIED\"},\"type\":\"http\"},\"description\":\"sample\",\"parameters\":{},\"requiresApproval\":true},\"state\":\"STATE_UNSPECIFIED\"}", headers: { "Content-Type" => "application/json" })
        client.tool_sets.tools.create("sample", metadata: {"name" => "sample"}, spec: {"config" => {"http" => {"request_method" => "HTTP_METHOD_UNSPECIFIED"}, "type" => "http"}, "description" => "sample", "parameters" => {}, "requires_approval" => true})
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#retrieve" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("ToolService_GetTool") do
        result = client.tool_sets.tools.retrieve("sample", "sample", workspace_id: "sample")
        expect(result).to be_a(Cadenya::Types::Tool)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:get, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/tool_sets/sample/tools/sample")
          .to_return(status: 200, body: "{\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"config\":{\"http\":{\"requestMethod\":\"HTTP_METHOD_UNSPECIFIED\"},\"type\":\"http\"},\"description\":\"sample\",\"parameters\":{},\"requiresApproval\":true},\"state\":\"STATE_UNSPECIFIED\"}", headers: { "Content-Type" => "application/json" })
        client.tool_sets.tools.retrieve("sample", "sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#delete" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("ToolService_DeleteTool") do
        result = client.tool_sets.tools.delete("sample", "sample", workspace_id: "sample")
        expect(result).to be_nil
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:delete, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/tool_sets/sample/tools/sample")
          .to_return(status: 204, body: "")
        client.tool_sets.tools.delete("sample", "sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#update" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("ToolService_UpdateTool") do
        result = client.tool_sets.tools.update("sample", "sample", workspace_id: "sample", metadata: {"name" => "sample"}, spec: {"config" => {"http" => {"request_method" => "HTTP_METHOD_UNSPECIFIED"}, "type" => "http"}, "description" => "sample", "parameters" => {}, "requires_approval" => true}, update_mask: "sample")
        expect(result).to be_a(Cadenya::Types::Tool)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:patch, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/tool_sets/sample/tools/sample")
          .to_return(status: 200, body: "{\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"config\":{\"http\":{\"requestMethod\":\"HTTP_METHOD_UNSPECIFIED\"},\"type\":\"http\"},\"description\":\"sample\",\"parameters\":{},\"requiresApproval\":true},\"state\":\"STATE_UNSPECIFIED\"}", headers: { "Content-Type" => "application/json" })
        client.tool_sets.tools.update("sample", "sample", metadata: {"name" => "sample"}, spec: {"config" => {"http" => {"request_method" => "HTTP_METHOD_UNSPECIFIED"}, "type" => "http"}, "description" => "sample", "parameters" => {}, "requires_approval" => true}, update_mask: "sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#omit" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("ToolService_OmitTool") do
        result = client.tool_sets.tools.omit("sample", "sample", workspace_id: "sample")
        expect(result).to be_a(Cadenya::Types::Tool)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:post, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/tool_sets/sample/tools/sample:omit")
          .to_return(status: 200, body: "{\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"config\":{\"http\":{\"requestMethod\":\"HTTP_METHOD_UNSPECIFIED\"},\"type\":\"http\"},\"description\":\"sample\",\"parameters\":{},\"requiresApproval\":true},\"state\":\"STATE_UNSPECIFIED\"}", headers: { "Content-Type" => "application/json" })
        client.tool_sets.tools.omit("sample", "sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#restore" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("ToolService_RestoreTool") do
        result = client.tool_sets.tools.restore("sample", "sample", workspace_id: "sample")
        expect(result).to be_a(Cadenya::Types::Tool)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:post, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/tool_sets/sample/tools/sample:restore")
          .to_return(status: 200, body: "{\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"config\":{\"http\":{\"requestMethod\":\"HTTP_METHOD_UNSPECIFIED\"},\"type\":\"http\"},\"description\":\"sample\",\"parameters\":{},\"requiresApproval\":true},\"state\":\"STATE_UNSPECIFIED\"}", headers: { "Content-Type" => "application/json" })
        client.tool_sets.tools.restore("sample", "sample")
        expect(stub).to have_been_requested
      end
    end
  end
end
