# frozen_string_literal: true

# Code generated by redwood. DO NOT EDIT.

RSpec.describe "client.uploads" do
  let(:client) { build_client }

  describe "#create" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("UploadService_CreateUpload") do
        result = client.uploads.create(workspace_id: "sample", metadata: {"name" => "sample"}, spec: {"content_type" => "sample", "filename" => "sample", "size_bytes" => "sample"})
        expect(result).to be_a(Cadenya::Types::Upload)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:post, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/uploads")
          .to_return(status: 200, body: "{\"info\":{\"status\":\"UPLOAD_STATUS_UNSPECIFIED\",\"uploadUrl\":\"sample\"},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"contentType\":\"sample\",\"filename\":\"sample\",\"sizeBytes\":\"sample\"}}", headers: { "Content-Type" => "application/json" })
        client.uploads.create(metadata: {"name" => "sample"}, spec: {"content_type" => "sample", "filename" => "sample", "size_bytes" => "sample"})
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#retrieve" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("UploadService_GetUpload") do
        result = client.uploads.retrieve("sample", workspace_id: "sample")
        expect(result).to be_a(Cadenya::Types::Upload)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:get, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/uploads/sample")
          .to_return(status: 200, body: "{\"info\":{\"status\":\"UPLOAD_STATUS_UNSPECIFIED\",\"uploadUrl\":\"sample\"},\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"spec\":{\"contentType\":\"sample\",\"filename\":\"sample\",\"sizeBytes\":\"sample\"}}", headers: { "Content-Type" => "application/json" })
        client.uploads.retrieve("sample")
        expect(stub).to have_been_requested
      end
    end
  end
end
