# frozen_string_literal: true

# Code generated by redwood. DO NOT EDIT.

RSpec.describe "client.widget_sessions" do
  let(:client) { build_client }

  describe "#list" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("WidgetSessionService_ListWidgetSessions") do
        result = client.widget_sessions.list(workspace_id: "sample", limit: 1, cursor: "sample", widget_id: "sample", tenant_id: "sample", subject_id: "sample", state: "STATE_UNSPECIFIED", labels: "sample", sort_order: "sample", include_info: true)
        items = result.to_a
        expect(items.length).to eq(2)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:get, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/widget_sessions")
          .with(query: hash_including({}))
          .to_return(status: 200, body: "{\"items\":[{\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"secrets\":[{\"name\":\"sample\"}],\"spec\":{\"token\":\"sample\",\"widgetId\":\"sample\"},\"state\":\"STATE_UNSPECIFIED\"}],\"pagination\":{\"nextCursor\":\"\"}}", headers: { "Content-Type" => "application/json" })
        client.widget_sessions.list(limit: 1, cursor: "sample", widget_id: "sample", tenant_id: "sample", subject_id: "sample", state: "STATE_UNSPECIFIED", labels: "sample", sort_order: "sample", include_info: true)
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#create" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("WidgetSessionService_CreateWidgetSession") do
        result = client.widget_sessions.create(workspace_id: "sample", metadata: {}, spec: {"widget_id" => "sample"}, secrets: [{}])
        expect(result).to be_a(Cadenya::Types::WidgetSession)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:post, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/widget_sessions")
          .to_return(status: 200, body: "{\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"secrets\":[{\"name\":\"sample\"}],\"spec\":{\"token\":\"sample\",\"widgetId\":\"sample\"},\"state\":\"STATE_UNSPECIFIED\"}", headers: { "Content-Type" => "application/json" })
        client.widget_sessions.create(metadata: {}, spec: {"widget_id" => "sample"}, secrets: [{}])
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#delete_tenant" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("WidgetSessionService_DeleteTenantWidgetSessions") do
        result = client.widget_sessions.delete_tenant(workspace_id: "sample", tenant_id: "sample")
        expect(result).to be_a(Cadenya::Types::DeleteTenantWidgetSessionsResponse)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:delete, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/widget_sessions")
          .with(query: hash_including({}))
          .to_return(status: 200, body: "{\"objectivesDeleted\":1,\"sessionsDeleted\":1}", headers: { "Content-Type" => "application/json" })
        client.widget_sessions.delete_tenant(tenant_id: "sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#retrieve" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("WidgetSessionService_GetWidgetSession") do
        result = client.widget_sessions.retrieve("sample", workspace_id: "sample")
        expect(result).to be_a(Cadenya::Types::WidgetSession)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:get, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/widget_sessions/sample")
          .to_return(status: 200, body: "{\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"secrets\":[{\"name\":\"sample\"}],\"spec\":{\"token\":\"sample\",\"widgetId\":\"sample\"},\"state\":\"STATE_UNSPECIFIED\"}", headers: { "Content-Type" => "application/json" })
        client.widget_sessions.retrieve("sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#delete" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("WidgetSessionService_DeleteWidgetSession") do
        result = client.widget_sessions.delete("sample", workspace_id: "sample")
        expect(result).to be_nil
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:delete, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/widget_sessions/sample")
          .to_return(status: 204, body: "")
        client.widget_sessions.delete("sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#revoke" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("WidgetSessionService_RevokeWidgetSession") do
        result = client.widget_sessions.revoke("sample", workspace_id: "sample")
        expect(result).to be_a(Cadenya::Types::WidgetSession)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:post, "#{SPEC_BASE_URL}/v1/workspaces/default_workspace_id/widget_sessions/sample:revoke")
          .to_return(status: 200, body: "{\"metadata\":{\"accountId\":\"sample\",\"createdAt\":\"2026-01-01T00:00:00Z\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"profileId\":\"sample\",\"workspaceId\":\"sample\"},\"secrets\":[{\"name\":\"sample\"}],\"spec\":{\"token\":\"sample\",\"widgetId\":\"sample\"},\"state\":\"STATE_UNSPECIFIED\"}", headers: { "Content-Type" => "application/json" })
        client.widget_sessions.revoke("sample")
        expect(stub).to have_been_requested
      end
    end
  end
end
