# frozen_string_literal: true

# Code generated by redwood. DO NOT EDIT.

RSpec.describe "client.workspaces" do
  let(:client) { build_client }

  describe "#list" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("WorkspaceService_ListWorkspaces") do
        result = client.workspaces.list(limit: 1, cursor: "sample", sort_order: "sample", include_info: true, labels: "sample")
        items = result.to_a
        expect(items.length).to eq(2)
      end
    end
  end
end
