# frozen_string_literal: true

# Code generated by redwood. DO NOT EDIT.

RSpec.describe "client.workspace_admin" do
  let(:client) { build_client }

  describe "#list_profiles" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("WorkspaceAdminService_ListProfiles") do
        result = client.workspace_admin.list_profiles(limit: 1, cursor: "sample", query: "sample", labels: "sample")
        items = result.to_a
        expect(items.length).to eq(2)
      end
    end
  end

  describe "#list_account" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("WorkspaceAdminService_ListAccountWorkspaces") do
        result = client.workspace_admin.list_account(limit: 1, cursor: "sample", include_archived: true, labels: "sample")
        items = result.to_a
        expect(items.length).to eq(2)
      end
    end
  end

  describe "#create" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("WorkspaceAdminService_CreateWorkspace") do
        result = client.workspace_admin.create(metadata: {"name" => "sample"}, spec: {})
        expect(result).to be_a(Cadenya::Types::Workspace)
      end
    end
  end

  describe "#retrieve" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("WorkspaceAdminService_GetWorkspace") do
        result = client.workspace_admin.retrieve(workspace_id: "sample")
        expect(result).to be_a(Cadenya::Types::Workspace)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:get, "#{SPEC_BASE_URL}/v1/account/workspaces/default_workspace_id")
          .to_return(status: 200, body: "{\"metadata\":{\"accountId\":\"sample\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\"},\"spec\":{},\"status\":\"STATUS_ENABLED\"}", headers: { "Content-Type" => "application/json" })
        client.workspace_admin.retrieve
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#archive" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("WorkspaceAdminService_ArchiveWorkspace") do
        result = client.workspace_admin.archive(workspace_id: "sample")
        expect(result).to be_nil
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:delete, "#{SPEC_BASE_URL}/v1/account/workspaces/default_workspace_id")
          .to_return(status: 204, body: "")
        client.workspace_admin.archive
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#update" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("WorkspaceAdminService_UpdateWorkspace") do
        result = client.workspace_admin.update(workspace_id: "sample", metadata: {"name" => "sample"}, spec: {}, update_mask: "sample")
        expect(result).to be_a(Cadenya::Types::Workspace)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:patch, "#{SPEC_BASE_URL}/v1/account/workspaces/default_workspace_id")
          .to_return(status: 200, body: "{\"metadata\":{\"accountId\":\"sample\",\"externalId\":\"sample\",\"id\":\"sample\",\"labels\":{},\"name\":\"sample\",\"profileId\":\"sample\"},\"spec\":{},\"status\":\"STATUS_ENABLED\"}", headers: { "Content-Type" => "application/json" })
        client.workspace_admin.update(metadata: {"name" => "sample"}, spec: {}, update_mask: "sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#list_members" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("WorkspaceAdminService_ListWorkspaceMembers") do
        result = client.workspace_admin.list_members(workspace_id: "sample", limit: 1, cursor: "sample")
        items = result.to_a
        expect(items.length).to eq(2)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:get, "#{SPEC_BASE_URL}/v1/account/workspaces/default_workspace_id/members")
          .with(query: hash_including({}))
          .to_return(status: 200, body: "{\"items\":[{\"actorId\":\"sample\",\"email\":\"sample\",\"name\":\"sample\",\"profileId\":\"sample\"}],\"pagination\":{\"nextCursor\":\"\"}}", headers: { "Content-Type" => "application/json" })
        client.workspace_admin.list_members(limit: 1, cursor: "sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#add_member" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("WorkspaceAdminService_AddWorkspaceMember") do
        result = client.workspace_admin.add_member(workspace_id: "sample", profile_id: "sample", email: "sample")
        expect(result).to be_a(Cadenya::Types::WorkspaceMember)
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:post, "#{SPEC_BASE_URL}/v1/account/workspaces/default_workspace_id/members")
          .to_return(status: 200, body: "{\"actorId\":\"sample\",\"email\":\"sample\",\"name\":\"sample\",\"profileId\":\"sample\"}", headers: { "Content-Type" => "application/json" })
        client.workspace_admin.add_member(profile_id: "sample", email: "sample")
        expect(stub).to have_been_requested
      end
    end
  end

  describe "#remove_member" do
    it "sends the golden request and decodes the response" do
      VCR.use_cassette("WorkspaceAdminService_RemoveWorkspaceMember") do
        result = client.workspace_admin.remove_member("sample", workspace_id: "sample")
        expect(result).to be_nil
      end
    end

    context "when workspace_id falls back to the client default" do
      it "resolves the client-level value" do
        stub = stub_request(:delete, "#{SPEC_BASE_URL}/v1/account/workspaces/default_workspace_id/members/sample")
          .to_return(status: 204, body: "")
        client.workspace_admin.remove_member("sample")
        expect(stub).to have_been_requested
      end
    end
  end
end
