name: Publish Gem
on:
  workflow_dispatch:
  release:
    types: [published]
permissions:
  contents: read
  id-token: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - uses: rubygems/release-gem@v1
        with:
          await-release: false
