name: Publish Gem
on:
  workflow_dispatch:
  release:
    types: [published]
permissions:
  contents: read
  id-token: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0'
      - name: Configure RubyGems credentials
        uses: rubygems/configure-rubygems-credentials@dc5a8d8553e6ee01fc26761a49e99e733d17954a # v2.1.0
      - name: Build gem
        run: gem build cadenya.gemspec
      - name: Publish to RubyGems.org
        run: gem push cadenya-*.gem
