name: Publish Gem
on:
  workflow_dispatch:
  release:
    types: [published]
permissions:
  contents: read
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0'
      - name: Build gem
        run: gem build cadenya.gemspec
      - name: Publish to RubyGems.org
        run: gem push cadenya-*.gem
        env:
          GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
